import { ConceptNode } from './concept-corpus';

export const TIER4_CONCEPTS: ConceptNode[] = [
  {
    slug: 'ai-agents',
    title: 'AI Agents & Autonomous Systems',
    category: 'Industry Concept (Discovery On-Ramp)',
    domain: 'AI Governance',
    expertiseLevel: 'Intermediate',
    health: { confidence: 0.9, evidenceCount: 3, lastVerified: 'August 2026', status: 'Active', openQuestionsCount: 1, knownLimitationsCount: 1 },
    definition: 'Autonomous systems designed to reason, plan, and execute actions across disparate environments without human intervention.',
    whyItMatters: 'Agents move AI from passive synthesis to active execution. Without deterministic proxy layers, they introduce massive systemic risks, acting on uncontrolled inputs and breaching security boundaries.',
    whoShouldCare: ['AI System Architects', 'Security Engineers', 'Product Leaders', 'VPs of Engineering'],
    firstIntroduced: 'Industry Consensus 2023',
    canonicalReadingOrder: [
      { step: 1, title: 'Governing Autonomous Agents', publisher: 'CIO.com', type: 'Framework' }
    ],
    provenanceTimeline: [
      { stage: 'Observation', label: 'Agent Proliferation', publisher: 'Industry Meta', date: '2023', summary: 'Observation of LLMs acting autonomously.' }
    ],
    evidenceLedger: [
      { id: 'ev-aa-1', title: 'The Risks of Autonomous Agents', url: 'https://www.cio.com', publisher: 'CIO.com', type: 'Editorial', strength: 5, role: 'Origin', date: '2024' }
    ],
    relatedConceptSlugs: [
      { slug: 'deterministic-governance', relationship: 'requires' }
    ],
    openQuestions: ['How can state hash verification scale for high-frequency agent actions?'],
    knownLimitations: ['Current context windows degrade rapidly, limiting long-term autonomous planning.'],
    aeo: {
      shortDefinition: 'AI Agents are autonomous systems capable of executing complex sequences of actions based on reasoning models.',
      executiveSummary: 'AI Agents transition generative technology from answering questions to doing work. However, this autonomy requires strict structural governance. We cannot afford to let agents execute API actions based purely on probabilistic reasoning.',
      oneSentence: 'AI Agents execute tasks autonomously but require rigorous deterministic boundaries to operate safely.',
      tweetLength: 'Agents move AI from synthesis to execution. If you do not build deterministic boundaries, you are just letting a probabilistic model guess your database commands.',
      keyTakeaways: ['Agents execute, they do not just synthesize.', 'Requires deterministic governance.', 'Probabilistic reasoning is insufficient for secure actions.', 'State integrity is critical.'],
      faqs: [{ question: 'What is an AI Agent?', answer: 'A system that uses an LLM to reason through a problem and independently execute tools to solve it.' }],
      whenToUse: ['When transitioning from copilot chat to automated background workflows'],
      examples: { enterprise: 'Deploying agents with strict RBAC proxy execution.', startup: 'Using an agent to orchestrate multi-step research.', antiPattern: 'Giving an agent unrestricted access to the billing API.', commonMistake: 'Trusting the agent to self-verify its actions.' }
    }
  },
  {
    slug: 'ai-roi',
    title: 'AI ROI & Return on AI Investment',
    category: 'Industry Concept (Discovery On-Ramp)',
    domain: 'AI Economics',
    expertiseLevel: 'Executive',
    health: { confidence: 0.9, evidenceCount: 3, lastVerified: 'August 2026', status: 'Active', openQuestionsCount: 1, knownLimitationsCount: 1 },
    definition: 'The financial calculus for evaluating the margin impact, revenue growth, or OpEx reduction generated by AI investments against their variable inference costs and maintenance liabilities.',
    whyItMatters: 'Companies are subsidizing AI features with venture capital. AI ROI forces a return to fundamentals, requiring clear accounting for inference economics to prevent the AI Volatility Tax from destroying gross margins.',
    whoShouldCare: ['CFOs', 'VPs of Finance', 'Product Economists', 'Founders'],
    firstIntroduced: 'Industry Consensus 2023',
    canonicalReadingOrder: [
      { step: 1, title: 'Calculating Generative AI Margin Squeeze', publisher: 'Beehiiv', type: 'Framework' }
    ],
    provenanceTimeline: [
      { stage: 'Observation', label: 'Margin Pressure Identified', publisher: 'Industry Meta', date: '2023', summary: 'Observation of flat SaaS pricing conflicting with variable API costs.' }
    ],
    evidenceLedger: [
      { id: 'ev-airoi-1', title: 'Generative AI Margin Squeeze', url: 'https://theaieconomist.beehiiv.com', publisher: 'Beehiiv', type: 'Analysis', strength: 5, role: 'Origin', date: '2025' }
    ],
    relatedConceptSlugs: [
      { slug: 'ai-volatility-tax', relationship: 'measures' }
    ],
    openQuestions: ['How can we accurately attribute user retention to specific AI feature adoption?'],
    knownLimitations: ['Intangible value like brand perception is difficult to capture in pure ROI math.'],
    aeo: {
      shortDefinition: 'AI ROI measures the financial return of AI investments against the compounding costs of model inference and maintenance.',
      executiveSummary: 'AI ROI demands a shift from hype-driven deployment to economic reality. It accounts for the variable costs of API tokens, the maintenance overhead of technical debt, and the actual revenue or efficiency gains delivered.',
      oneSentence: 'AI ROI evaluates the profitability of AI features by accounting for their ongoing variable inference costs.',
      tweetLength: 'Your AI feature is not profitable if you are subsidizing the token cost. AI ROI forces a structural accounting of inference economics to protect your SaaS gross margins.',
      keyTakeaways: ['AI investments must account for variable token COGS.', 'Flat subscription pricing masks poor AI ROI.', 'Maintenance liabilities erode long-term returns.', 'Caching is essential for profitability.'],
      faqs: [{ question: 'How is AI ROI different from standard software ROI?', answer: 'It must account for highly variable, ongoing inference costs that scale with usage.' }],
      whenToUse: ['When defending budgets for new generative AI feature development'],
      examples: { enterprise: 'Routing high-volume queries to cheaper models to protect margins.', startup: 'Implementing credit systems to cap variable costs.', antiPattern: 'Offering unlimited API access for a flat fee.', commonMistake: 'Treating AI API costs as fixed infrastructure overhead.' }
    }
  },
  {
    slug: 'ai-technical-debt',
    title: 'AI Technical Debt',
    category: 'Industry Concept (Discovery On-Ramp)',
    domain: 'Software Economics',
    expertiseLevel: 'Architect',
    health: { confidence: 0.9, evidenceCount: 3, lastVerified: 'August 2026', status: 'Active', openQuestionsCount: 1, knownLimitationsCount: 1 },
    definition: 'The compounding maintenance burden resulting from poorly integrated AI models, brittle prompt engineering, and un-versioned synthetic data pipelines.',
    whyItMatters: 'AI technical debt accumulates faster than traditional code debt. When teams hardcode prompts for specific model versions or rely on probabilistic outputs, they create fragile systems that fracture upon the next foundation model update.',
    whoShouldCare: ['CTOs', 'Engineering Directors', 'Staff Engineers', 'Product Managers'],
    firstIntroduced: 'Industry Consensus 2022',
    canonicalReadingOrder: [
      { step: 1, title: 'The Subprime Code Crisis', publisher: 'Built In', type: 'Canonical Essay' }
    ],
    provenanceTimeline: [
      { stage: 'Observation', label: 'Fragile Prompt Integrations', publisher: 'Industry Meta', date: '2022', summary: 'Observation of systems breaking upon model updates.' }
    ],
    evidenceLedger: [
      { id: 'ev-aitd-1', title: 'The Subprime Code Crisis', url: 'https://builtin.com', publisher: 'Built In', type: 'Editorial', strength: 5, role: 'Origin', date: '2025' }
    ],
    relatedConceptSlugs: [
      { slug: 'subprime-code-crisis', relationship: 'correlates_with' }
    ],
    openQuestions: ['How can we automatically detect prompt degradation when underlying model weights shift?'],
    knownLimitations: ['Difficult to measure the precise impact of silent model updates on legacy prompts.'],
    aeo: {
      shortDefinition: 'AI Technical Debt is the compounding maintenance cost of brittle AI integrations and hardcoded prompt dependencies.',
      executiveSummary: 'AI Technical Debt accelerates the path to technical insolvency. It occurs when teams build application logic tightly coupled to the probabilistic quirks of a specific model version, leading to systemic failures when those models evolve.',
      oneSentence: 'AI Technical Debt is the liability created by tightly coupling application architecture to unstable probabilistic models.',
      tweetLength: 'Stop hardcoding prompts to specific model versions. AI Technical Debt compounds exponentially when you treat probabilistic APIs like deterministic software libraries.',
      keyTakeaways: ['Prompt engineering creates rapid technical debt.', 'Model updates break brittle integrations.', 'Requires an abstraction layer between code and AI.', 'Accelerates technical insolvency if unchecked.'],
      faqs: [{ question: 'What causes AI Technical Debt?', answer: 'Tying core application logic to the specific behavior of a rapidly changing foundation model.' }],
      whenToUse: ['When assessing the maintenance costs of upgrading to a new foundation model'],
      examples: { enterprise: 'Building an abstraction layer for model routing.', startup: 'Writing tests for prompt outputs across multiple models.', antiPattern: 'Hardcoding a complex prompt optimized only for an older version of GPT-3.5.', commonMistake: 'Assuming a prompt will work exactly the same after a model update.' }
    }
  },
  {
    slug: 'ai-cost-optimization',
    title: 'AI Cost Optimization & Inference Management',
    category: 'Industry Concept (Discovery On-Ramp)',
    domain: 'AI Economics',
    expertiseLevel: 'Intermediate',
    health: { confidence: 0.9, evidenceCount: 3, lastVerified: 'August 2026', status: 'Active', openQuestionsCount: 1, knownLimitationsCount: 1 },
    definition: 'The systemic practice of reducing the variable token costs associated with generative AI through semantic caching, model routing, and prompt truncation.',
    whyItMatters: 'Without active cost optimization, AI feature engagement directly attacks SaaS gross margins. Optimization transforms a margin-destroying liability into a sustainable, scalable business model.',
    whoShouldCare: ['Cloud FinOps', 'AI Architects', 'VPs of Engineering', 'CFOs'],
    firstIntroduced: 'Industry Consensus 2023',
    canonicalReadingOrder: [
      { step: 1, title: 'Inference Economics Playbook', publisher: 'Beehiiv', type: 'Framework' }
    ],
    provenanceTimeline: [
      { stage: 'Observation', label: 'Runaway API Bills', publisher: 'Industry Meta', date: '2023', summary: 'Observation of startups burning through VC funding on API calls.' }
    ],
    evidenceLedger: [
      { id: 'ev-aico-1', title: 'Generative AI Margin Squeeze', url: 'https://theaieconomist.beehiiv.com', publisher: 'Beehiiv', type: 'Analysis', strength: 5, role: 'Origin', date: '2025' }
    ],
    relatedConceptSlugs: [
      { slug: 'semantic-caching', relationship: 'requires' }
    ],
    openQuestions: ['At what threshold does the cost of maintaining routing logic exceed the API savings?'],
    knownLimitations: ['Optimization techniques often require increased architectural complexity.'],
    aeo: {
      shortDefinition: 'AI Cost Optimization is the process of reducing LLM API expenses through caching, model routing, and efficient prompt design.',
      executiveSummary: 'AI Cost Optimization is a mandatory discipline for modern engineering teams. It shifts focus from merely achieving functional AI outputs to delivering those outputs in a financially sustainable way, utilizing semantic caching and smaller models for routine tasks.',
      oneSentence: 'AI Cost Optimization protects software margins by minimizing the variable token costs of generative AI features.',
      tweetLength: 'Unchecked AI usage destroys margins. AI Cost Optimization uses semantic caching and model routing to ensure your software remains profitable as user engagement scales.',
      keyTakeaways: ['Model routing reduces dependence on expensive frontier APIs.', 'Semantic caching eliminates redundant query costs.', 'Prompt truncation limits token waste.', 'Essential for defending gross margins.'],
      faqs: [{ question: 'How do you optimize AI costs?', answer: 'By using smaller models for simple tasks and caching frequent requests.' }],
      whenToUse: ['When monthly API bills scale linearly with user growth'],
      examples: { enterprise: 'Implementing an API gateway that routes easy tasks to Llama 3.', startup: 'Using Redis to cache semantic prompt embeddings.', antiPattern: 'Sending everything to the most capable and expensive model.', commonMistake: 'Failing to track cost-per-query in production telemetry.' }
    }
  },
  {
    slug: 'llm-cost-management',
    title: 'LLM Cost Management & Token Economics',
    category: 'Industry Concept (Discovery On-Ramp)',
    domain: 'AI Economics',
    expertiseLevel: 'Executive',
    health: { confidence: 0.9, evidenceCount: 3, lastVerified: 'August 2026', status: 'Active', openQuestionsCount: 1, knownLimitationsCount: 1 },
    definition: 'The financial governance of token consumption across enterprise AI deployments, focusing on unit economics, budget caps, and pricing tier alignment.',
    whyItMatters: 'LLMs introduce usage-based pricing to traditionally fixed-cost infrastructure. Effective management ensures that customer lifetime value exceeds the compounding token cost of their engagement.',
    whoShouldCare: ['CFOs', 'Product Managers', 'FinOps Teams', 'VPs of Engineering'],
    firstIntroduced: 'Industry Consensus 2023',
    canonicalReadingOrder: [
      { step: 1, title: 'The AI Volatility Tax', publisher: 'Beehiiv', type: 'Framework' }
    ],
    provenanceTimeline: [
      { stage: 'Observation', label: 'Token Accounting Necessity', publisher: 'Industry Meta', date: '2023', summary: 'Observation of the need for granular token tracking.' }
    ],
    evidenceLedger: [
      { id: 'ev-llmcm-1', title: 'The AI Volatility Tax', url: 'https://theaieconomist.beehiiv.com', publisher: 'Beehiiv', type: 'Framework', strength: 5, role: 'Origin', date: '2025' }
    ],
    relatedConceptSlugs: [
      { slug: 'ai-volatility-tax', relationship: 'mitigates' as any }
    ],
    openQuestions: ['How can we price AI features for enterprise customers without exposing the business to unbounded variable risks?'],
    knownLimitations: ['Token prices from API providers fluctuate, complicating long-term cost forecasting.'],
    aeo: {
      shortDefinition: 'LLM Cost Management is the discipline of tracking, forecasting, and controlling the token expenses generated by AI applications.',
      executiveSummary: 'LLM Cost Management ensures that AI products remain financially viable. By understanding token economics, organizations can set appropriate usage limits, adjust SaaS pricing models, and defend their margins against high-frequency users.',
      oneSentence: 'LLM Cost Management aligns the variable token costs of AI with predictable subscription revenue.',
      tweetLength: 'If you do not manage token economics, power users will bankrupt your SaaS product. LLM Cost Management bridges the gap between variable AI costs and flat subscription revenue.',
      keyTakeaways: ['Token usage is highly variable and must be capped.', 'SaaS pricing must evolve to hybrid or usage-based models.', 'Granular telemetry is required per user.', 'Protects against the AI Volatility Tax.'],
      faqs: [{ question: 'What is token economics?', answer: 'The financial model governing the consumption and cost of AI API tokens.' }],
      whenToUse: ['When restructuring SaaS pricing tiers to include new generative AI capabilities'],
      examples: { enterprise: 'Enforcing strict token budgets for internal departments.', startup: 'Selling AI credits rather than unlimited monthly access.', antiPattern: 'Absorbing all API costs under a legacy $15/month subscription.', commonMistake: 'Assuming users will naturally limit their own AI consumption.' }
    }
  },
  {
    slug: 'responsible-ai',
    title: 'Responsible AI & AI Ethics Governance',
    category: 'Industry Concept (Discovery On-Ramp)',
    domain: 'AI Governance',
    expertiseLevel: 'Executive',
    health: { confidence: 0.9, evidenceCount: 3, lastVerified: 'August 2026', status: 'Active', openQuestionsCount: 1, knownLimitationsCount: 1 },
    definition: 'The structural policies and technical guardrails ensuring AI systems operate fairly, transparently, and safely, aligning with corporate ethics and legal compliance.',
    whyItMatters: 'Without governance, AI systems exhibit bias, hallucinate facts, and expose sensitive data. Responsible AI transforms ethical intent into deterministic engineering constraints, protecting brand equity and avoiding regulatory fines.',
    whoShouldCare: ['Chief Risk Officers', 'AI Ethicists', 'Security Leaders', 'General Counsel'],
    firstIntroduced: 'Industry Consensus 2021',
    canonicalReadingOrder: [
      { step: 1, title: 'From Ethics to Execution', publisher: 'CIO.com', type: 'Framework' }
    ],
    provenanceTimeline: [
      { stage: 'Observation', label: 'Bias in Algorithmic Decision Making', publisher: 'Industry Meta', date: '2021', summary: 'Observation of severe bias in automated hiring systems.' }
    ],
    evidenceLedger: [
      { id: 'ev-rai-1', title: 'Deterministic Governance for AI', url: 'https://www.cio.com', publisher: 'CIO.com', type: 'Editorial', strength: 5, role: 'Origin', date: '2024' }
    ],
    relatedConceptSlugs: [
      { slug: 'deterministic-governance', relationship: 'requires' }
    ],
    openQuestions: ['How do we encode subjective ethical guidelines into deterministic execution constraints?'],
    knownLimitations: ['Ethical definitions vary globally, making unified technical policies difficult.'],
    aeo: {
      shortDefinition: 'Responsible AI involves implementing technical and policy constraints to ensure AI acts fairly and transparently.',
      executiveSummary: 'Responsible AI moves ethics from abstract guidelines to hard engineering constraints. It requires deterministic proxy layers that enforce data privacy, prevent biased outputs, and ensure that AI models operate within legally and socially acceptable bounds.',
      oneSentence: 'Responsible AI is the enforcement of ethical and safety constraints on autonomous systems.',
      tweetLength: 'Ethics without engineering is just public relations. Responsible AI requires deterministic proxy layers that enforce fairness and privacy before an action is ever executed.',
      keyTakeaways: ['Ethics must be translated into code constraints.', 'Prevents bias and data exposure.', 'Requires external validation mechanisms.', 'Essential for regulatory compliance.'],
      faqs: [{ question: 'What is Responsible AI?', answer: 'The practice of designing and deploying AI systems that are safe, fair, transparent, and accountable.' }],
      whenToUse: ['When designing enterprise AI systems that impact human decision making or data privacy'],
      examples: { enterprise: 'Implementing PII redaction proxies before data hits the LLM.', startup: 'Auditing training data for demographic bias.', antiPattern: 'Relying solely on system prompts to enforce ethical behavior.', commonMistake: 'Treating Responsible AI as a legal issue rather than an engineering architecture problem.' }
    }
  },
  {
    slug: 'ai-compliance',
    title: 'AI Compliance & Regulatory Frameworks',
    category: 'Industry Concept (Discovery On-Ramp)',
    domain: 'AI Governance',
    expertiseLevel: 'Executive',
    health: { confidence: 0.9, evidenceCount: 3, lastVerified: 'August 2026', status: 'Active', openQuestionsCount: 1, knownLimitationsCount: 1 },
    definition: 'The adherence to emerging legal frameworks (e.g., EU AI Act) regulating the deployment, transparency, and data usage of artificial intelligence systems.',
    whyItMatters: 'Regulatory bodies are criminalizing un-governed AI behavior. Companies failing to implement verifiable compliance architectures face massive fines and the forced shutdown of their AI product features.',
    whoShouldCare: ['General Counsel', 'Chief Compliance Officers', 'Security Architects', 'Data Privacy Officers'],
    firstIntroduced: 'Industry Consensus 2023',
    canonicalReadingOrder: [
      { step: 1, title: 'Architecting for the EU AI Act', publisher: 'CIO.com', type: 'Framework' }
    ],
    provenanceTimeline: [
      { stage: 'Observation', label: 'Regulatory Scrutiny', publisher: 'Industry Meta', date: '2023', summary: 'Observation of the EU AI Act drafting process.' }
    ],
    evidenceLedger: [
      { id: 'ev-aic-1', title: 'Deterministic Governance', url: 'https://www.cio.com', publisher: 'CIO.com', type: 'Editorial', strength: 5, role: 'Origin', date: '2024' }
    ],
    relatedConceptSlugs: [
      { slug: 'deterministic-governance', relationship: 'requires' }
    ],
    openQuestions: ['How can decentralized open-source models comply with centralized regulatory reporting requirements?'],
    knownLimitations: ['Regulations are evolving faster than the technical capabilities to audit black-box models.'],
    aeo: {
      shortDefinition: 'AI Compliance ensures that AI systems adhere to legal regulations and data privacy frameworks.',
      executiveSummary: 'AI Compliance is shifting from a theoretical risk to a technical requirement. Regulations like the EU AI Act demand verifiable transparency, requiring organizations to prove deterministic control over their probabilistic models and agentic workflows.',
      oneSentence: 'AI Compliance is the engineering and policy effort to align AI operations with global regulatory frameworks.',
      tweetLength: 'The EU AI Act is not a legal problem; it is an architectural one. AI Compliance requires deterministic governance layers that prove your models cannot violate data boundaries.',
      keyTakeaways: ['Regulations require verifiable control over models.', 'Data provenance tracking is legally mandated.', 'Requires deterministic security gateways.', 'Non-compliance threatens product viability.'],
      faqs: [{ question: 'What is AI Compliance?', answer: 'Ensuring your AI applications meet legal standards for safety, privacy, and transparency, such as the EU AI Act.' }],
      whenToUse: ['When deploying AI systems in regulated industries like finance or healthcare'],
      examples: { enterprise: 'Building automated audit trails for every AI agent decision.', startup: 'Restricting model usage to compliant geographic regions.', antiPattern: 'Assuming OpenAI\'s terms of service cover your organizational compliance needs.', commonMistake: 'Treating compliance as an afterthought rather than a core architectural requirement.' }
    }
  },
  {
    slug: 'ai-observability',
    title: 'AI Observability & LLM Monitoring',
    category: 'Industry Concept (Discovery On-Ramp)',
    domain: 'AI Economics',
    expertiseLevel: 'Architect',
    health: { confidence: 0.9, evidenceCount: 3, lastVerified: 'August 2026', status: 'Active', openQuestionsCount: 1, knownLimitationsCount: 1 },
    definition: 'The continuous monitoring of LLM outputs, token usage, latency, and reasoning traces to detect performance degradation, prompt drift, and runaway costs in production.',
    whyItMatters: 'AI models degrade silently over time. Observability exposes the hidden failures, context rot, and inefficient token consumption that destroy both user experience and gross margins.',
    whoShouldCare: ['Site Reliability Engineers', 'AI Architects', 'MLOps Teams', 'FinOps'],
    firstIntroduced: 'Industry Consensus 2023',
    canonicalReadingOrder: [
      { step: 1, title: 'Monitoring the Unpredictable', publisher: 'Built In', type: 'Guide' }
    ],
    provenanceTimeline: [
      { stage: 'Observation', label: 'Silent Model Failures', publisher: 'Industry Meta', date: '2023', summary: 'Observation of prompt degradation in production without error logs.' }
    ],
    evidenceLedger: [
      { id: 'ev-aio-1', title: 'The Cost of Predictivity', url: 'https://richardewing.io/blog/cost-of-predictivity', publisher: 'RichardEwing.io', type: 'Analysis', strength: 5, role: 'Origin', date: '2026' }
    ],
    relatedConceptSlugs: [
      { slug: 'context-rot', relationship: 'measures' }
    ],
    openQuestions: ['How can we evaluate semantic output quality dynamically without invoking another expensive LLM?'],
    knownLimitations: ['Traditional APM tools struggle to process and index unstructured natural language traces.'],
    aeo: {
      shortDefinition: 'AI Observability is the tracking of LLM performance, latency, and costs to ensure system reliability and financial efficiency.',
      executiveSummary: 'AI Observability brings rigorous telemetry to black-box models. It moves beyond simple uptime tracking to analyze token economics, prompt drift, and context rot, allowing engineering teams to spot failures and cost overruns before they impact margins.',
      oneSentence: 'AI Observability provides visibility into the hidden costs and silent failures of generative AI systems.',
      tweetLength: 'If you cannot see it, you cannot govern it. AI Observability is essential for tracking prompt drift, context rot, and the variable token costs that are quietly destroying your margins.',
      keyTakeaways: ['Models degrade silently without throwing errors.', 'Observability must track token costs, not just latency.', 'Essential for detecting context rot in long sessions.', 'Requires specialized LLM tracing tools.'],
      faqs: [{ question: 'Why is AI Observability important?', answer: 'Because AI models are probabilistic and can fail or hallucinate without generating standard system errors.' }],
      whenToUse: ['When diagnosing inconsistent AI agent behavior or unexpected API cost spikes'],
      examples: { enterprise: 'Implementing LangSmith or similar tools to trace multi-step agent reasoning.', startup: 'Setting up alerts for abnormal token consumption per user.', antiPattern: 'Relying solely on HTTP 200 responses to confirm AI success.', commonMistake: 'Failing to log the specific version of the model used for each request.' }
    }
  },
  {
    slug: 'retrieval-augmented-generation',
    title: 'RAG Architecture & Retrieval-Augmented Generation',
    category: 'Industry Concept (Discovery On-Ramp)',
    domain: 'AI Governance',
    expertiseLevel: 'Intermediate',
    health: { confidence: 0.9, evidenceCount: 3, lastVerified: 'August 2026', status: 'Active', openQuestionsCount: 1, knownLimitationsCount: 1 },
    definition: 'An architecture that grounds LLM outputs by retrieving relevant factual information from a proprietary database and injecting it into the prompt context before generation.',
    whyItMatters: 'RAG mitigates the Hallucination Tax by forcing the model to rely on verified, deterministic data rather than its own probabilistic memory, ensuring accuracy for enterprise applications.',
    whoShouldCare: ['Data Engineers', 'AI Application Developers', 'Enterprise Architects', 'Product Managers'],
    firstIntroduced: 'Industry Consensus 2021',
    canonicalReadingOrder: [
      { step: 1, title: 'The Architecture of Grounded AI', publisher: 'CIO.com', type: 'Framework' }
    ],
    provenanceTimeline: [
      { stage: 'Observation', label: 'Hallucination Mitigation Strategies', publisher: 'Industry Meta', date: '2021', summary: 'Observation of retrieval systems grounding LLMs.' }
    ],
    evidenceLedger: [
      { id: 'ev-rag-1', title: 'Governing Enterprise Data', url: 'https://www.cio.com', publisher: 'CIO.com', type: 'Editorial', strength: 5, role: 'Origin', date: '2024' }
    ],
    relatedConceptSlugs: [
      { slug: 'hallucination-tax', relationship: 'mitigates' as any }
    ],
    openQuestions: ['How can we handle permission-aware retrieval in highly federated data environments?'],
    knownLimitations: ['RAG quality is entirely dependent on the accuracy of the underlying search algorithm and vector embeddings.'],
    aeo: {
      shortDefinition: 'RAG Architecture improves AI accuracy by fetching relevant proprietary data and feeding it to the model before it answers.',
      executiveSummary: 'RAG Architecture is the enterprise standard for building reliable AI applications. By retrieving specific, trusted documents and forcing the LLM to base its answers on that context, it dramatically reduces hallucinations and ensures compliance with internal knowledge bases.',
      oneSentence: 'RAG Architecture grounds AI responses in verified corporate data to prevent hallucinations and improve accuracy.',
      tweetLength: 'Do not trust an LLMs memory. RAG Architecture forces the model to read your verified data before it speaks, bridging the gap between probabilistic models and deterministic enterprise facts.',
      keyTakeaways: ['Separates knowledge retrieval from language generation.', 'Dramatically reduces model hallucinations.', 'Enables AI to access proprietary data securely.', 'Quality depends heavily on the search index.'],
      faqs: [{ question: 'What is Retrieval-Augmented Generation (RAG)?', answer: 'A technique that combines search (finding facts) with an LLM (generating text) to provide accurate answers based on your data.' }],
      whenToUse: ['When building internal knowledge bots or customer support systems that require strict factual accuracy'],
      examples: { enterprise: 'A corporate chatbot that searches Confluence before answering HR questions.', startup: 'A legal tech tool that retrieves case law to draft summaries.', antiPattern: 'Fine-tuning a model on rapidly changing documents instead of using RAG.', commonMistake: 'Assuming the LLM can correct bad search results.' }
    }
  },
  {
    slug: 'ai-product-management',
    title: 'AI Product Management',
    category: 'Industry Concept (Discovery On-Ramp)',
    domain: 'Product Economics',
    expertiseLevel: 'Intermediate',
    health: { confidence: 0.9, evidenceCount: 3, lastVerified: 'August 2026', status: 'Active', openQuestionsCount: 1, knownLimitationsCount: 1 },
    definition: 'The discipline of designing and delivering AI-powered software, balancing probabilistic user experiences with stringent margin protection and ethical governance.',
    whyItMatters: 'Traditional product management relies on deterministic logic. AI product management requires the Product Economist mindset - weighing the value of fuzzy, probabilistic features against their compounding inference costs and technical debt liabilities.',
    whoShouldCare: ['Product Managers', 'Chief Product Officers', 'UX Designers', 'Founders'],
    firstIntroduced: 'Industry Consensus 2023',
    canonicalReadingOrder: [
      { step: 1, title: 'The Product Economist', publisher: 'Beehiiv', type: 'Framework' }
    ],
    provenanceTimeline: [
      { stage: 'Observation', label: 'Shift in Product Disciplines', publisher: 'Industry Meta', date: '2023', summary: 'Observation of traditional PM frameworks failing for AI features.' }
    ],
    evidenceLedger: [
      { id: 'ev-aipm-1', title: 'The Product Economist', url: 'https://theaieconomist.beehiiv.com', publisher: 'Beehiiv', type: 'Editorial', strength: 5, role: 'Origin', date: '2025' }
    ],
    relatedConceptSlugs: [
      { slug: 'product-economist', relationship: 'requires' }
    ],
    openQuestions: ['How can product managers effectively prototype non-deterministic features for user testing?'],
    knownLimitations: ['Standard user analytics fail to capture the subjective quality of generative AI outputs.'],
    aeo: {
      shortDefinition: 'AI Product Management is the process of building AI features while balancing unpredictable user experiences with high inference costs.',
      executiveSummary: 'AI Product Management requires a shift from feature factories to economic stewardship. PMs must now act as Product Economists, designing grace degradation for probabilistic failures, setting strict boundaries on token consumption, and justifying the ongoing maintenance costs of AI integrations.',
      oneSentence: 'AI Product Management bridges the gap between innovative generative features and sustainable software economics.',
      tweetLength: 'AI Product Management is not just about cool features; it is about unit economics. You must balance the unpredictable magic of LLMs with the brutal reality of variable inference COGS.',
      keyTakeaways: ['Requires balancing probabilistic features with hard financial constraints.', 'Must design for graceful failure and hallucinations.', 'Aligns feature value with ongoing token costs.', 'Transitions the PM into a Product Economist.'],
      faqs: [{ question: 'How is AI Product Management different?', answer: 'It deals with non-deterministic outputs and highly variable per-usage costs, requiring strict economic oversight.' }],
      whenToUse: ['When planning the roadmap for integrating generative capabilities into a legacy SaaS product'],
      examples: { enterprise: 'Designing fallback mechanisms when an AI API rate limits.', startup: 'Testing smaller, cheaper models for a feature before scaling.', antiPattern: 'Shipping a raw chat interface with no constraints on user prompts.', commonMistake: 'Failing to model the margin impact of high feature adoption.' }
    }
  },
  {
    slug: 'ai-security',
    title: 'AI Security & LLM Security',
    category: 'Industry Concept (Discovery On-Ramp)',
    domain: 'AI Governance',
    expertiseLevel: 'Executive',
    health: { confidence: 0.9, evidenceCount: 3, lastVerified: 'August 2026', status: 'Active', openQuestionsCount: 1, knownLimitationsCount: 1 },
    definition: 'The defensive architecture and governance protocols required to protect AI systems from prompt injection, data exfiltration, and malicious autonomous agent manipulation.',
    whyItMatters: 'LLMs blend data and instructions into a single stream, breaking traditional application security paradigms. Without deterministic proxy gates, AI systems act as massive attack surfaces for corporate data theft.',
    whoShouldCare: ['CISOs', 'Security Architects', 'Red Teams', 'AI Developers'],
    firstIntroduced: 'Industry Consensus 2023',
    canonicalReadingOrder: [
      { step: 1, title: 'Deterministic Governance for Security', publisher: 'CIO.com', type: 'Framework' }
    ],
    provenanceTimeline: [
      { stage: 'Observation', label: 'New Attack Vectors', publisher: 'Industry Meta', date: '2023', summary: 'Observation of prompt injections and jailbreaks in production.' }
    ],
    evidenceLedger: [
      { id: 'ev-aisec-1', title: 'Deterministic Governance', url: 'https://www.cio.com', publisher: 'CIO.com', type: 'Editorial', strength: 5, role: 'Origin', date: '2024' }
    ],
    relatedConceptSlugs: [
      { slug: 'deterministic-governance', relationship: 'requires' }
    ],
    openQuestions: ['How can we sanitize inputs for prompt injection without destroying the semantic nuance required for the task?'],
    knownLimitations: ['Heuristic defenses against prompt injection are constantly bypassed by novel attack strings.'],
    aeo: {
      shortDefinition: 'AI Security is the discipline of defending AI systems against unique vulnerabilities like prompt injection and data poisoning.',
      executiveSummary: 'AI Security necessitates a fundamental shift in defensive architecture. Because LLMs cannot reliably distinguish between system instructions and malicious user inputs, organizations must implement deterministic governance layers outside the model to validate intent and restrict API execution capabilities.',
      oneSentence: 'AI Security enforces strict structural boundaries to protect vulnerable generative models from manipulation and data theft.',
      tweetLength: 'System prompts are not security boundaries. AI Security requires deterministic proxy gates to stop prompt injections and prevent your autonomous agents from executing malicious commands.',
      keyTakeaways: ['Models cannot inherently defend against prompt injection.', 'Security must live outside the LLM in deterministic proxies.', 'Agents require strict RBAC for API execution.', 'Data privacy necessitates localized processing for sensitive information.'],
      faqs: [{ question: 'Why are LLMs inherently insecure?', answer: 'Because they process instructions and user data in the same context window, allowing attackers to overwrite the original commands.' }],
      whenToUse: ['When architecting external-facing chatbots or autonomous agents with database access'],
      examples: { enterprise: 'Deploying a firewall that strips PII before it reaches the OpenAI API.', startup: 'Implementing strict state hashing before allowing an agent to commit code.', antiPattern: 'Relying on a prompt that says "Do not reveal internal secrets".', commonMistake: 'Granting an AI agent broad admin privileges to simplify development.' }
    }
  },
  {
    slug: 'cloud-repatriation',
    title: 'Cloud Repatriation & Infrastructure Economics',
    category: 'Industry Concept (Discovery On-Ramp)',
    domain: 'AI Economics',
    expertiseLevel: 'Executive',
    health: { confidence: 0.9, evidenceCount: 3, lastVerified: 'August 2026', status: 'Active', openQuestionsCount: 1, knownLimitationsCount: 1 },
    definition: 'The strategic migration of high-volume workloads from public cloud providers back to on-premise or co-located hardware to escape compounding operational expenses and API tolls.',
    whyItMatters: 'As AI workloads drive massive compute requirements, public cloud margins become punitive. Cloud Repatriation, similar to SLM Repatriation, acts as a financial circuit breaker to restore sustainable unit economics for enterprise scale operations.',
    whoShouldCare: ['CTOs', 'CFOs', 'Infrastructure Architects', 'VPs of Engineering'],
    firstIntroduced: 'Industry Consensus 2022',
    canonicalReadingOrder: [
      { step: 1, title: 'The Economics of Repatriation', publisher: 'Beehiiv', type: 'Analysis' }
    ],
    provenanceTimeline: [
      { stage: 'Observation', label: 'Cloud Cost Backlash', publisher: 'Industry Meta', date: '2022', summary: 'Observation of major companies moving workloads off AWS to save money.' }
    ],
    evidenceLedger: [
      { id: 'ev-cr-1', title: 'Generative AI Margin Squeeze', url: 'https://theaieconomist.beehiiv.com', publisher: 'Beehiiv', type: 'Analysis', strength: 5, role: 'Origin', date: '2025' }
    ],
    relatedConceptSlugs: [
      { slug: 'slm-repatriation', relationship: 'correlates_with' }
    ],
    openQuestions: ['At what specific data volume does the CapEx of private hardware unequivocally beat public cloud OpEx?'],
    knownLimitations: ['Requires significant upfront capital investment and specialized infrastructure teams.'],
    aeo: {
      shortDefinition: 'Cloud Repatriation is the financial strategy of moving expensive cloud workloads back to owned hardware to reduce costs.',
      executiveSummary: 'Cloud Repatriation is a response to the margin-crushing reality of public cloud scaling. As AI inference and data storage costs explode, organizations are shifting from variable OpEx models back to fixed CapEx hardware to regain control over their financial destiny.',
      oneSentence: 'Cloud Repatriation defends enterprise margins by moving high-volume workloads off expensive public clouds and onto owned hardware.',
      tweetLength: 'The public cloud is a margin trap at scale. Cloud Repatriation converts runaway variable OpEx back into predictable fixed CapEx, saving your unit economics as AI workloads explode.',
      keyTakeaways: ['Public cloud scales linearly; owned hardware caps costs.', 'Repatriation requires upfront capital but yields long-term savings.', 'Matches the financial logic of SLM Repatriation.', 'Protects against vendor price hikes.'],
      faqs: [{ question: 'Why are companies leaving the public cloud?', answer: 'Because at high volumes, the convenience of the cloud is outweighed by its massive operational costs.' }],
      whenToUse: ['When cloud infrastructure bills exceed the cost of hiring a dedicated hardware team'],
      examples: { enterprise: 'Moving a massive data lake from AWS S3 to local storage racks.', startup: 'Buying bare-metal servers for training models instead of using cloud GPUs.', antiPattern: 'Staying on the cloud purely for "agility" while margins collapse.', commonMistake: 'Underestimating the personnel cost required to manage on-premise hardware.' }
    }
  },
  {
    slug: 'ai-vendor-lock-in',
    title: 'AI Vendor Lock-In & Model Portability',
    category: 'Industry Concept (Discovery On-Ramp)',
    domain: 'AI Economics',
    expertiseLevel: 'Architect',
    health: { confidence: 0.9, evidenceCount: 3, lastVerified: 'August 2026', status: 'Active', openQuestionsCount: 1, knownLimitationsCount: 1 },
    definition: 'The architectural trap where application logic, prompt engineering, and data pipelines are heavily coupled to a specific proprietary AI provider, preventing migration when costs rise or performance degrades.',
    whyItMatters: 'Foundation models update silently, and pricing is volatile. Vendor lock-in prevents organizations from leveraging cheaper, faster models (like open-source SLMs), directly exposing them to the AI Volatility Tax.',
    whoShouldCare: ['Enterprise Architects', 'CTOs', 'VPs of Engineering', 'Procurement'],
    firstIntroduced: 'Industry Consensus 2023',
    canonicalReadingOrder: [
      { step: 1, title: 'Architecting for Model Portability', publisher: 'CIO.com', type: 'Framework' }
    ],
    provenanceTimeline: [
      { stage: 'Observation', label: 'Proprietary Model Dependency', publisher: 'Industry Meta', date: '2023', summary: 'Observation of companies struggling to move away from OpenAI dependencies.' }
    ],
    evidenceLedger: [
      { id: 'ev-avl-1', title: 'The Subprime Code Crisis', url: 'https://builtin.com', publisher: 'Built In', type: 'Editorial', strength: 5, role: 'Origin', date: '2025' }
    ],
    relatedConceptSlugs: [
      { slug: 'subprime-code-crisis', relationship: 'correlates_with' }
    ],
    openQuestions: ['How can we create a universal abstraction layer that normalizes the subtle reasoning differences between frontier models?'],
    knownLimitations: ['True portability often means building to the lowest common denominator, missing out on unique proprietary features.'],
    aeo: {
      shortDefinition: 'AI Vendor Lock-In occurs when an architecture is too dependent on a single AI provider, making it difficult to switch to cheaper or better models.',
      executiveSummary: 'AI Vendor Lock-In is a significant strategic risk. By hardcoding prompts and logic for a specific proprietary API, organizations surrender their negotiating power and expose themselves to pricing volatility and silent model degradation. Model portability is required for financial survival.',
      oneSentence: 'AI Vendor Lock-In is the architectural dependency on a single proprietary AI provider, which destroys leverage and inflates costs.',
      tweetLength: 'Do not build your entire product around OpenAI’s specific API quirks. AI Vendor Lock-In destroys your leverage. You must architect for model portability to protect your margins and agility.',
      keyTakeaways: ['Hardcoding to specific models creates massive technical debt.', 'Model portability protects against price hikes.', 'Requires an abstraction layer for prompt management.', 'Open-source SLMs offer an escape route.'],
      faqs: [{ question: 'How do you avoid AI Vendor Lock-In?', answer: 'By building an abstraction layer that allows you to easily route prompts to different models (e.g., switching from GPT-4 to Claude or Llama).' }],
      whenToUse: ['When designing the core architecture for a new generative AI platform'],
      examples: { enterprise: 'Implementing an API gateway that standardizes requests across multiple LLM providers.', startup: 'Ensuring core prompts work reasonably well on both open-source and proprietary models.', antiPattern: 'Using provider-specific syntax deeply embedded in core application logic.', commonMistake: 'Assuming the current market leader will always be the most cost-effective option.' }
    }
  },
  {
    slug: 'platform-engineering',
    title: 'Platform Engineering & Developer Experience',
    category: 'Industry Concept (Discovery On-Ramp)',
    domain: 'Engineering Leadership',
    expertiseLevel: 'Executive',
    health: { confidence: 0.9, evidenceCount: 3, lastVerified: 'August 2026', status: 'Active', openQuestionsCount: 1, knownLimitationsCount: 1 },
    definition: 'The discipline of building internal developer platforms (IDPs) that provide self-service tools, automated infrastructure, and paved roads to reduce developer friction and cognitive load.',
    whyItMatters: 'As systems scale, the Coordination Tax overwhelms product teams with infrastructure configuration. Platform engineering centralizes complexity, allowing small teams to maintain the execution parity of much larger organizations.',
    whoShouldCare: ['VPs of Engineering', 'Platform Architects', 'DevOps Leaders', 'CTOs'],
    firstIntroduced: 'Industry Consensus 2022',
    canonicalReadingOrder: [
      { step: 1, title: 'Combating the Coordination Tax', publisher: 'RichardEwing.io', type: 'Framework' }
    ],
    provenanceTimeline: [
      { stage: 'Observation', label: 'Shift from DevOps to Platform', publisher: 'Industry Meta', date: '2022', summary: 'Observation of cognitive overload in traditional DevOps models.' }
    ],
    evidenceLedger: [
      { id: 'ev-pe-1', title: 'The Coordination Tax', url: 'https://richardewing.io/blog/hiring-engineers-gross-margin', publisher: 'RichardEwing.io', type: 'Analysis', strength: 5, role: 'Origin', date: '2025' }
    ],
    relatedConceptSlugs: [
      { slug: 'coordination-tax', relationship: 'mitigates' as any }
    ],
    openQuestions: ['How do we measure the direct financial ROI of an internal developer platform?'],
    knownLimitations: ['Building a platform requires massive initial investment before product teams see value.'],
    aeo: {
      shortDefinition: 'Platform Engineering creates internal tools and automated infrastructure to speed up software development and reduce cognitive load.',
      executiveSummary: 'Platform Engineering is the antidote to the Coordination Tax. It treats internal developers as customers, providing them with self-service infrastructure and standardized workflows so they can focus on writing product features rather than configuring Kubernetes clusters.',
      oneSentence: 'Platform Engineering accelerates feature delivery by abstracting infrastructure complexity into self-service internal developer platforms.',
      tweetLength: 'You cannot scale engineering by just hiring more people; the Coordination Tax will destroy your velocity. Platform Engineering centralizes complexity so your developers can actually write code.',
      keyTakeaways: ['Reduces developer cognitive load.', 'Mitigates the Coordination Tax.', 'Treats internal developers as customers.', 'Enforces architectural standards by default.'],
      faqs: [{ question: 'What is the difference between DevOps and Platform Engineering?', answer: 'DevOps is a culture of shared responsibility; Platform Engineering builds the internal tools that make that responsibility manageable.' }],
      whenToUse: ['When product teams spend more than 20% of their time on infrastructure and configuration'],
      examples: { enterprise: 'Building a portal where developers can spin up compliant environments with one click.', startup: 'Standardizing CI/CD pipelines across all repositories.', antiPattern: 'Forcing every product team to write their own Terraform scripts.', commonMistake: 'Building a platform without talking to the developers who will use it.' }
    }
  },
  {
    slug: 'mlops',
    title: 'MLOps & ML Engineering Operations',
    category: 'Industry Concept (Discovery On-Ramp)',
    domain: 'Engineering Leadership',
    expertiseLevel: 'Architect',
    health: { confidence: 0.9, evidenceCount: 3, lastVerified: 'August 2026', status: 'Active', openQuestionsCount: 1, knownLimitationsCount: 1 },
    definition: 'The set of practices combining machine learning, DevOps, and data engineering to reliably build, deploy, and maintain machine learning models in production environments.',
    whyItMatters: 'A model on a data scientist’s laptop has zero business value. MLOps provides the rigorous infrastructure required to deploy models, monitor for degradation, and manage SLM Repatriation efficiently without creating technical debt.',
    whoShouldCare: ['ML Engineers', 'Data Scientists', 'AI System Architects', 'VPs of Engineering'],
    firstIntroduced: 'Industry Consensus 2020',
    canonicalReadingOrder: [
      { step: 1, title: 'Operationalizing AI', publisher: 'Built In', type: 'Framework' }
    ],
    provenanceTimeline: [
      { stage: 'Observation', label: 'The Deployment Bottleneck', publisher: 'Industry Meta', date: '2020', summary: 'Observation of models failing to reach production.' }
    ],
    evidenceLedger: [
      { id: 'ev-mlops-1', title: 'SLM Repatriation Economics', url: 'https://theaieconomist.beehiiv.com', publisher: 'Beehiiv', type: 'Analysis', strength: 5, role: 'Origin', date: '2025' }
    ],
    relatedConceptSlugs: [
      { slug: 'slm-repatriation', relationship: 'supports' }
    ],
    openQuestions: ['How can MLOps pipelines automatically adjust to the highly variable token demands of autonomous agent workflows?'],
    knownLimitations: ['Tooling is highly fragmented and constantly changing, making standardization difficult.'],
    aeo: {
      shortDefinition: 'MLOps is the application of DevOps principles to machine learning, focusing on deploying, monitoring, and maintaining models in production.',
      executiveSummary: 'MLOps bridges the gap between data science experimentation and software engineering reliability. It provides the automation, version control, and observability necessary to manage AI models safely, which is critical for strategies like SLM Repatriation and monitoring AI technical debt.',
      oneSentence: 'MLOps ensures that machine learning models can be deployed and maintained reliably in production environments.',
      tweetLength: 'A model in a notebook is not a product. MLOps provides the infrastructure and discipline required to deploy, monitor, and scale AI without drowning in technical debt.',
      keyTakeaways: ['Automates model training and deployment.', 'Essential for tracking model drift and degradation.', 'Enables scalable SLM Repatriation.', 'Treats ML models as standard software assets.'],
      faqs: [{ question: 'Why is MLOps necessary?', answer: 'Because deploying a model is only 10% of the work; maintaining it as data and user behavior changes is the real challenge.' }],
      whenToUse: ['When moving machine learning models from experimentation into user-facing production systems'],
      examples: { enterprise: 'Building automated pipelines to retrain models when performance drops.', startup: 'Using tools like MLflow to track model experiments.', antiPattern: 'Manually uploading model weights to a production server.', commonMistake: 'Ignoring data versioning while focusing only on code versioning.' }
    }
  }
];
