import { CurriculumModule, l, d, m } from './curriculum-data';

export const tracks18Modules: Record<string, CurriculumModule> = {};
const t18 = 'Track 18 — The Fullstack Career';

tracks18Modules['fullstack-career/18-1'] = m('18-1', 'Frontend State Economics', 'Cost of uncontrolled state, re-rendering waste, and React optimization ROI.', t18, 
    ['Identify re-rendering waste', 'Optimize state economics', 'Measure frontend performance ROI'], [
        l('The Financial Cost of the React Render Tax', 
            [
                'Frontend state management is universally treated strictly as a technical puzzle by junior developers. In reality, it is a direct margin-erosion vector. Uncontrolled, recursive re-renders aggressively burn client battery life, drastically increase Time to Interactive (TTI), and drop e-commerce conversion rates by upwards of 2-5%.', 
                'When developers place global context providers at the root of an application without rigorous memoization, every minor state fluctuation forces the entire DOM tree to recalculate. This hidden compute tax shifts the financial burden of poor engineering directly onto the user’s device.',
                'React optimization is never "premature" if it actively touches the revenue path. A 100ms improvement in browser execution time directly correlates to millions of dollars in sustained enterprise ARR.'
            ],
            [
                d('Client Render Latency', 'The absolute microsecond lag between user input and DOM confirmation.', '< 50ms Executive Benchmark'),
                d('E-Commerce Conversion Drop', 'The statistical sales penalty per 100ms of UI thread locking.', '-1% per 100ms lag')
            ], 
            'Execute a rigorous React Profiler audit on your primary application checkout or dashboard route.', 
            ['Enable "Highlight updates when components render" in React DevTools.', 'Click through the primary user path and isolate full-page flashes.', 'Determine the exact component boundary failing to memoize.'], 
            {
                question: 'Why is uncontrolled React state management considered a "margin-erosion vector"?',
                options: ['It causes AWS Lambda bills to skyrocket', 'It burns client device battery and increases Time to Interactive, which mathematically lowers sales conversions', 'It requires an enterprise license from Meta to execute', 'It forces developers to use Redux instead of native Context'],
                correctIndex: 1,
                explanation: 'Users abandon slow UI. A frontend that locks the main thread to recalculate unaffected DOM elements actively destroys user trust and financial conversions.'
            }
        )
    ], '/vault/curriculum/tracks/fullstack-career/18-2', undefined, 'live'
);

tracks18Modules['fullstack-career/18-2'] = m('18-2', 'Backend API Design ROI', 'REST vs GraphQL caching, payload size optimization.', t18, 
    ['Reduce payload dimensions', 'Master REST cache control'], [
        l('Maximum Payload Economics', 
            [
                'Over-fetching data is not just an anti-pattern; it is a financial liability. Fetching 100kb of JSON when the UI only requires 12kb actively costs mobile users their cellular data caps, but more importantly, it costs your servers massive, compounding egress fees.', 
                'Shrinking an API payload by merely 20kb on an endpoint that receives 1 Billion monthly requests saves extreme transit costs and slashes the requisite container scaling thresholds.',
                'Enterprise fullstack engineers do not blindly dump entire database models into REST responses. They architect rigorous Data Transfer Objects (DTOs) that surgically expose only the exact bytes required for the UI to render.'
            ],
            [
                d('Cloud Egress Tax', 'The literal invoice cost of moving data off the cloud provider perimeter.', 'Target: <$50/TB'),
                d('Payload Reduction ROI', 'The monthly cloud savings generated by stripping unused JSON keys.', 'Massive compounding rate')
            ], 
            'Audit your highest-traffic endpoint payload for Data Transfer Object efficiency.', 
            ['Intercept the JSON payload in the browser network tab.', 'Count how many JSON keys are transmitted but never actually rendered or utilized in the UI.', 'Draft a DTO rewrite that strips the dormant fields.'], 
            {
                question: 'What is the primary financial impact of API over-fetching?',
                options: ['It prevents GraphQL from compiling properly', 'It destroys HTTP caching mechanisms', 'It drastically inflates compounded cloud egress bandwidth bills at scale', 'It causes the browser to run out of memory'],
                correctIndex: 2,
                explanation: 'Cloud providers charge by the gigabyte for data leaving their servers. Sending unused data is literally throwing money across the network.'
            }
        )
    ], '/vault/curriculum/tracks/fullstack-career/18-3', undefined, 'live'
);

tracks18Modules['fullstack-career/18-3'] = m('18-3', 'Database Query Optimization', 'N+1 problems, indexing ROI, latency cost.', t18, 
    ['Eliminate N+1 queries', 'Calculate indexing cost vs read speed'], [
        l('The N+1 Query Death Spiral', 
            [
                'A single missing SQL join can create 10,000 recursive database hits in a single page load. In the modern era, an ORM (Object-Relational Mapper) is essentially a chainsaw: wildly powerful for velocity, but incredibly dangerous if you do not understand the underlying SQL it generates.', 
                'Junior engineers treat databases as magic black boxes. Senior engineers recognize that mastering the execution plan (`EXPLAIN ANALYZE`) is the absolute floor for professional competency.',
                'Adding a database index isn\'t free—it accelerates read times tremendously, but fundamentally degrades write speed because the index must be recalculated on every single insert. This is the core trade-off of database engineering.'
            ],
            [
                d('Query Execution Time', 'The raw database fetch speed, totally independent of network latency.', '< 10ms Target'),
                d('Index Write Penalty', 'The microsecond delay added to INSERT operations per active index.', 'Variable load dependent')
            ], 
            'Run an execution analysis on your application\'s top 5 slowest queries.', 
            ['Enable slow-query logging in your staging database.', 'Prefix the query with `EXPLAIN ANALYZE` to view the engine\'s mathematical routing plan.', 'Identify if the query is executing a "Sequential Scan" (table scan) rather than an "Index Scan."'], 
            {
                question: 'Why is an unnecessary database index considered dangerous at scale?',
                options: ['It takes up too much hard drive space on SSDs', 'It degrades write speed because the index tree must be recalculated on every SQL INSERT/UPDATE', 'It makes queries too complicated to read', 'It voids the database warranty from vendors like Oracle'],
                correctIndex: 1,
                explanation: 'Indexes optimize READ performance at the strict, direct expense of WRITE performance. Over-indexing a high-write transactional table will crash it.'
            }
        )
    ], '/vault/curriculum/tracks/fullstack-career/18-4', undefined, 'live'
);

tracks18Modules['fullstack-career/18-4'] = m('18-4', 'Client vs Server Rendering', 'SSR compute costs, CSR SEO impact, conversion.', t18, 
    ['Measure CDN vs Compute costs', 'Quantify SEO penalties of CSR'], [
        l('The Edge Computing Illusion', 
            [
                'Moving all logic to Server-Side Rendering (SSR) via frameworks like Next.js breaks the fundamental economics of static hosting. CDN bytes from a static bucket cost literal pennies; Edge compute serverless milliseconds cost compounding dollars.', 
                'Completely Client-Side Rendering (CSR) apps, however, destroy SEO visibility and punish users with slow hardware. The modern enterprise architect relies on Incremental Static Regeneration (ISR).',
                'By generating pages statically at build time and rebuilding them automatically in the background only when data mutates, you achieve the massive cost savings of a CDN with the dynamic fidelity of a server.'
            ],
            [
                d('Cold Start Penalty', 'The brutal latency lag induced by waiting for V8 isolates or containers to boot.', '300ms - 2s (Platform dependent)'),
                d('CDN Caching Efficacy', 'The percentage of page loads that bypass active compute completely.', '> 90% ISR Target')
            ], 
            'Convert a computationally heavy SSR route into a statically generated ISR route.', 
            ['Identify a page that fetches data which only changes hourly or daily.', 'Refactor the fetching logic to pre-build the page and assign a revalidation cache time (e.g., 3600 seconds).', 'Monitor the drop in serverless compute invocations on your cloud dashboard.'], 
            {
                question: 'What is the primary financial vulnerability of relying 100% on Server-Side Rendering (SSR) at massive scale?',
                options: ['SSR cannot use modern React hooks', 'It requires every single page visit to invoke active, billed server compute rather than serving cheap cached assets from a CDN', 'It makes the client download too much Javascript', 'It requires learning PHP'],
                correctIndex: 1,
                explanation: 'Compute is vastly more expensive than storage transit. If a page does not need personalized live data, generating it dynamically on every hit is burning capital.'
            }
        )
    ], '/vault/curriculum/tracks/fullstack-career/18-5', undefined, 'live'
);

tracks18Modules['fullstack-career/18-5'] = m('18-5', 'The Promotion Calculus', 'Business outcomes, impact translation.', t18, 
    ['Speak EBITDA', 'Align technical wins with business leverage'], [
        l('Promotions are Strict Economic Transactions', 
            [
                'You do not get promoted to Senior or Staff Engineer for writing "clean code" or resolving a high volume of minor Jira tickets. You get promoted for delivering and proving massive organizational leverage.', 
                'The singular path to immense compensation is translating your pull requests into unassailable financial wins. You must treat your engineering output as an investment portfolio.',
                'If you rewrite a core service, do not tell leadership you "upgraded the framework." Tell them you "retired $140,000 of AWS technical debt and unblocked 5 junior engineers by streamlining local environment boot times."'
            ],
            [
                d('Engineering Leverage Score', 'The total number of other engineers permanently unblocked or accelerated by your infrastructure.', '> 10 Devs Impacted'),
                d('EBITDA Translation', 'The direct correlation of an engineering task to revenue protection or generation.', 'Tracked on PRs')
            ], 
            'Rewrite your internal "Brag Document" or promo packet using strictly financial terminology.', 
            ['Delete references to specific libraries, syntax improvements, or refactoring vanity metrics.', 'Calculate the rough dollar value of the time saved by a CI/CD pipeline you optimized.', 'Present your impact exclusively as \'Risk Mitigated\' or \'Velocity Multipliers\'.'], 
            {
                question: 'How should a Staff Engineer position a massive codebase refactor during a promotion review?',
                options: ['Focusing on how much cleaner the repository looks', 'Explaining the clever algorithms utilized in the new implementation', 'Anchoring the impact entirely on how the refactor prevents SLA breaches and permanently lowers cognitive onboarding overhead for new hires', 'Saying it aligns with Google’s best practices'],
                correctIndex: 2,
                explanation: 'Executive management only signs off on promotions when the candidate proves they are driving systemic, business-level value, not just isolated technical craftsmanship.'
            }
        )
    ], '/vault/curriculum/tracks/fullstack-career/18-6', undefined, 'live'
);

tracks18Modules['fullstack-career/18-6'] = m('18-6', 'Node.js vs Go Economics', 'Concurrency, Memory Footprint, Cloud Billing ROI.', t18, 
    ['Measure Goroutine vs Event Loop', 'Compare memory allocations'], [
        l('The Massive Memory Tax of V8', 
            [
                'Node.js applications, powered by the V8 engine, require incredibly heavy base memory allocations just to idle. When scaling horizontally, deploying 100 NodeJS pods burns hundreds of gigabytes of RAM simply maintaining the runtime.', 
                'Rewriting a massive concurrent worker or queue consumer in a compiled language like Go can drop container cluster requirements by upwards of 80%. Goroutines handle millions of concurrent connections utilizing mere megabytes of memory compared to Node\'s event loop thread pools.',
                'This architectural pivot is rarely about raw execution speed; it is almost entirely an orchestrated AWS bill reduction tactic yielding pure EBITDA expansion.'
            ],
            [
                d('Base Memory Overhead', 'The raw RAM utilized by the runtime before processing a single request.', 'Node: High | Go: Microscopic'),
                d('Max Concurrent Connections', 'The ceiling of simultaneous open sockets per gigabyte of RAM.', 'Go wins exponentially')
            ], 
            'Benchmark the baseline footprint of an idling Node worker versus an idling Go binary.', 
            ['Deploy a simple HTTP server in both Node.js (Express) and Go (net/http).', 'Check the Activity Monitor or Docker Stats for baseline memory usage.', 'Execute a load test of 10,000 concurrent simple connections and measure identical crash limits.'], 
            {
                question: 'Why do high-scale infrastructure companies rewrite Node microservices into Go?',
                options: ['Go forces engineers to write better code', 'Because Node.js cannot handle asynchronous events', 'To drastically slash cloud memory costs through Go’s incredibly lightweight goroutines during high-concurrency workloads', 'Because Go integrates with MongoDB better'],
                correctIndex: 2,
                explanation: 'Node.js easily handles concurrency logically, but its runtime memory footprint is massive. At scale, container RAM is expensive. Go handles concurrency with minimal memory overhead.'
            }
        )
    ], '/vault/curriculum/tracks/fullstack-career/18-7', undefined, 'live'
);

tracks18Modules['fullstack-career/18-7'] = m('18-7', 'Caching Layer Mastery', 'Redis Eviction Policies, CDN Hit Rates.', t18, 
    ['Master TTL strategies', 'Prevent the Thundering Herd cache stampede'], [
        l('Cache Stampede Economics', 
            [
                'Caching is computationally cheap; cache invalidation is systemically dangerous. If a highly-trafficked cached key (like a viral homepage feed) expires under heavy load, the database receives the full brunt of 5,000 simultaneous generation queries at the exact same millisecond.', 
                'This phenomenon is known as the "Thundering Herd" or "Cache Stampede," and it is the leading cause of sudden, catastrophic P1 database lockouts.',
                'Enterprise engineers eliminate this by utilizing "Probabilistic Early Expiration" (Jitter). By adding a randomized 5-15% variance to TTL expiration times, cache refreshes naturally stagger themselves, protecting the primary database.'
            ],
            [
                d('Aggregate Cache Hit Rate', 'The percentage of inbound requests that never touch the primary database.', '> 90% Mandatory Target'),
                d('TTL Variance (Jitter)', 'The mathematical randomization applied to cache expiration bounds.', '5-15% variance')
            ], 
            'Implement TTL jitter into your primary Redis or Memcached configuration.', 
            ['Locate your primary cache sets (e.g., `redis.setEX("home", 3600, data)`).', 'Wrap the TTL value in a function that adds or subtracts a randomized integer.', 'Deploy and observe the flattening of database CPU spikes during expiration windows.'], 
            {
                question: 'What is a "Thundering Herd" (Cache Stampede) failure?',
                options: ['When Redis runs out of memory and deletes data', 'When a single highly accessed cache key expires, forcing thousands of concurrent requests to overwhelm the database simultaneously', 'When a CDN charges too much for bandwidth', 'When developers accidentally flush the cache in production'],
                correctIndex: 1,
                explanation: 'A cache stampede occurs when the defensive barrier drops, and all pending traffic hits the unprotected slow database at once.'
            }
        )
    ], '/vault/curriculum/tracks/fullstack-career/18-8', undefined, 'live'
);

tracks18Modules['fullstack-career/18-8'] = m('18-8', 'The Latency Budget', 'Time-to-First-Byte, Payload Splitting.', t18, 
    ['Calculate TTFB bounds', 'Implement strict budget enforcing via Lighthouse CI'], [
        l('Latency is Exact Abandonment', 
            [
                'Amazon proved mathematically over a decade ago that a mere 100ms of latency costs approximately 1% in total sales. Latency is not an engineering annoyance; it is a financial hemorrhaging event.', 
                'You must operate under a strict "Latency Budget." If the marketing team adds a 500kb tracking script, the engineering team must strip 500kb of UI bloat to maintain the exact same performance envelope.',
                'Enforcing this requires utilizing breaking CI/CD pipelines. If a junior developer commits a branch that pushes the Webpack bundle size over 250kb, the build must forcefully fail.'
            ],
            [
                d('Time To First Byte (TTFB)', 'The network round trip time from DNS resolution to the initial stream byte.', '< 200ms Target'),
                d('Strict Bundle Threshold', 'The maximum allowable chunk size over the wire.', '< 250kb compressed')
            ], 
            'Install a bundle analyzer and establish a hard CI/CD budget failure threshold.', 
            ['Integrate `webpack-bundle-analyzer` or Next.js equivalent.', 'Find the massive dependencies arbitrarily inflating your bundle (e.g., `moment.js`, `lodash`).', 'Write a GitHub Action that halts merges if the bundle limit is breached.'], 
            {
                question: 'Why must engineering teams enforce a "Latency Budget" during CI/CD?',
                options: ['Because large files won\'t upload to GitHub', 'To prevent marketing and feature bloat from silently crossing the performance threshold where user sales conversions statistically drop', 'Because AWS charges per kilobyte uploaded to S3', 'To make code reviews faster'],
                correctIndex: 1,
                explanation: 'Without a hard, automated threshold, applications slowly succumb to "death by a thousand cuts", gradually growing slower until they become financially non-viable.'
            }
        )
    ], '/vault/curriculum/tracks/fullstack-career/18-9', undefined, 'live'
);

tracks18Modules['fullstack-career/18-9'] = m('18-9', 'CI/CD Pipeline Engineering', 'GitHub Actions Pricing, Cache Steps.', t18, 
    ['Cut pipeline times in half', 'Save DevOps budget on runners'], [
        l('Maximum Pipeline Financial Engineering', 
            [
                'A deployment pipeline that takes 20 minutes to run might seem acceptable. However, multiplied by 50 developers executing it 5 times a day, the organization incurs over $100,000+ in annual lost productivity and raw runner compute fees.', 
                'Optimizing CI/CD pipelines is pure margin extraction. The primary bottleneck is universally NPM installs and Docker image layer rebuilding.',
                'By enforcing incredibly strict Docker layer caching and isolating `package.json` installs entirely separate from application source code logic, pipeline execution drops from 20 minutes to 3 minutes.'
            ],
            [
                d('Total CI Duration', 'The absolute time from git push to a green staging environment check.', 'Target: < 5 Minutes'),
                d('Runner Compute Burn', 'The actual monthly invoice cost of GitHub Actions or CircleCI minutes.', 'Must be optimized')
            ], 
            'Audit your GitHub Actions pipeline and implement aggressive layer caching.', 
            ['Review the execution time of the `npm install` phase.', 'Add `actions/cache` strictly for `node_modules`.', 'Ensure Dockerfiles copy `package.json` and install BEFORE copying the highly volatile source code.'], 
            {
                question: 'What is the most effective method for drastically reducing Docker build times in CI/CD?',
                options: ['Using a smaller Alpine linux base image', 'Copying package manifest files and running dependency installation strictly BEFORE copying the changing application source code', 'Paying GitHub for faster cloud runners', 'Removing unit tests'],
                correctIndex: 1,
                explanation: 'Docker caches layers based on file modifications. If you copy the application code before running npm install, any minor code change breaks the cache, forcing a 5-minute framework reinstall.'
            }
        )
    ], '/vault/curriculum/tracks/fullstack-career/18-10', undefined, 'live'
);

tracks18Modules['fullstack-career/18-10'] = m('18-10', 'Fullstack Capstone Economics', 'Synthesizing the End-to-End Latency Tradeoffs.', t18, 
    ['Map the entire request lifecycle cost', 'Define the final PDI score'], [
        l('The Complete Economic Picture', 
            [
                'An elite, Board-level fullstack engineer possesses an unclouded vision of the stack. They intrinsically calculate the exact downstream cost of a cursor hover in React, cascading all the way down to the B-tree index traversal in Postgres.', 
                'Architectural design is merely the mastery of trade-offs: stealing memory from the server to save latency on the client, or burning database storage space to accelerate application API reads.',
                'You now hold the framework to evaluate software not by syntactic sweetness, but by its pure, undeniable impact on the corporate P&L.'
            ],
            [
                d('End-to-End TCO', 'The holistic ownership cost spanning network transit, DB compute, and client lifecycle.', 'Always optimized for Margin'),
                d('Product Debt Index (PDI)', 'The overarching metric for forecasting when an application will financially collapse.', 'Maintained consistently')
            ], 
            'Draw a comprehensive architectural map applying explicit latency budgets and dollar costs to every node.', 
            ['Calculate the transit cost through your Cloudflare edge node.', 'List the exact millisecond budget of your API layer.', 'Determine the financial breaking point of your database under maximum load.'], 
            {
                question: 'In the context of the Fullstack Career, architecture is best defined as:',
                options: ['Knowing every single Javascript framework available', 'The ability to write a full web application entirely by yourself', 'The mastery of allocating financial and computational trade-offs dynamically across the client, network, and database layers', 'Getting 100% test coverage'],
                correctIndex: 2,
                explanation: 'Architecture is economics. It is the allocation of scarce resources (bandwidth, memory, time, capital) to achieve a business outcome.'
            }
        )
    ], undefined, undefined, 'live'
);
