export const tracks = [
    {
        title: 'Engineering Economics Foundations',
        subtitle: 'Track 1 — Foundations',
        description: 'The core curriculum for understanding engineering as an economic activity. From basic metrics to advanced budgeting and organizational design.',
        modules: [
            { id: '1-1', name: '1.1 Engineering Productivity Metrics', topics: 'DORA Metrics vs APER, Feature Velocity, Board-Ready Reporting', href: '/vault/curriculum/tracks/engineering-economics/1-1' },
            { id: '1-2', name: '1.2 Technical Debt Classification', topics: 'Code Debt, Architecture Debt, Infrastructure Debt, PDI Framework', href: '/vault/curriculum/tracks/engineering-economics/1-2' },
            { id: '1-3', name: '1.3 Cost of Delay & Prioritization', topics: 'Cost of Delay, WSJF, Debt Interest Rates, Executive Framing', href: '/vault/curriculum/tracks/engineering-economics/1-3' },
            { id: '1-4', name: '1.4 Team Topology & Conway\'s Law', topics: 'Conway\'s Law, Four Team Topologies, Cognitive Load, Coordination Tax', href: '/vault/curriculum/tracks/engineering-economics/1-4' },
            { id: '1-5', name: '1.5 Build vs Buy Economics', topics: 'TCO Analysis, Integration Debt, Vendor Lock-In, Differentiation Test', href: '/vault/curriculum/tracks/engineering-economics/1-5' },
            { id: '1-6', name: '1.6 Engineering Budget & Capex/Opex', topics: 'Budget Anatomy, Software Capitalization, R&D Tax Credits', href: '/vault/curriculum/tracks/engineering-economics/1-6' },
            { id: '1-7', name: '1.7 Platform Engineering Economics', topics: 'IDP ROI, Golden Path Economics, Developer Experience Metrics', href: '/vault/curriculum/tracks/engineering-economics/1-7' },
            { id: '1-8', name: '1.8 Engineering Hiring Economics', topics: 'Cost-per-Hire, Mis-Hire Impact, Retention ROI', href: '/vault/curriculum/tracks/engineering-economics/1-8' },
            { id: '1-9', name: '1.9 Outsourcing & Contractor Economics', topics: 'Blended Rates, Knowledge Retention, Offshore Cost Analysis', href: '/vault/curriculum/tracks/engineering-economics/1-9' },
            { id: '1-10', name: '1.10 Engineering Organization Design', topics: 'Team Sizing, Span of Control, IC vs Management Tracks', href: '/vault/curriculum/tracks/engineering-economics/1-10' },
            { id: '1-11', name: '1.11 Technical Debt Quantification', topics: 'PDI Methodology, Dollar Conversion, CFO Communication', href: '/vault/curriculum/tracks/engineering-economics/1-11' },
            { id: '1-12', name: '1.12 Engineering Benchmarking', topics: 'R&D Spend Benchmarks, Stage-Based APER, Performance Metrics', href: '/vault/curriculum/tracks/engineering-economics/1-12' },
            { id: '1-13', name: '1.13 Engineering Budget Planning', topics: 'Zero-Based Budgeting, Headcount Modeling, Contingency Planning', href: '/vault/curriculum/tracks/engineering-economics/1-13' },
            { id: '1-14', name: '1.14 M&A Engineering Integration', topics: 'Day 1-100 Playbook, Talent Retention, Tech Stack Consolidation', href: '/vault/curriculum/tracks/engineering-economics/1-14' },
            { id: '1-15', name: '1.15 Engineering Economics Synthesis', topics: 'Complete Economic Model, Dashboard Design, Quarterly Reporting', href: '/vault/curriculum/tracks/engineering-economics/1-15' },
            { id: '1-16', name: '1.16 Governing Vibe Coding & AI-Assisted Output', topics: 'Vibe Coding Debt, Copilot ROI, Validation', href: '/vault/curriculum/tracks/engineering-economics/1-16' },
        ],
        color: 'cyan',
        icon: '📊',
        glossaryTerms: ['technical-debt', 'dora-metrics', 'innovation-tax', 'technical-insolvency-date', 'maintenance-load', 'conways-law', 'cost-of-delay', 'developer-experience', 'architecture-review-board'],
        tools: [{ name: 'PDI Calculator', href: '/tools/pdi' }, { name: 'APER Calculator', href: '/tools/aper' }],
    },
    {
        title: 'AI Product Economics',
        subtitle: 'Track 2 — AI-First (Flagship)',
        description: 'Your most differentiated track. AI unit economics, inference costs, margin collapse — maps directly to CIO.com and Built In articles. AI cost management is the #1 FinOps priority in 2026.',
        modules: [
            { id: '2-1', name: '2.1 AI COGS Analysis', topics: 'AI COGS Equation, Token Economics, API Pricing Architecture', href: '/vault/curriculum/tracks/ai-product-economics/2-1' },
            { id: '2-2', name: '2.2 Model Selection & Optimization', topics: 'Model Tiers, Routing Architecture, Fine-Tuning ROI, Distillation', href: '/vault/curriculum/tracks/ai-product-economics/2-2' },
            { id: '2-3', name: '2.3 AI Feature Profitability', topics: 'Feature-Level P&L, Per-User Economics, The 10x Rule', href: '/vault/curriculum/tracks/ai-product-economics/2-3' },
            { id: '2-4', name: '2.4 RAG Architecture Economics', topics: 'Embedding Costs, Vector DB Pricing, Chunking, Caching & Reranking', href: '/vault/curriculum/tracks/ai-product-economics/2-4' },
            { id: '2-5', name: '2.5 AI Governance & Safety Costs', topics: 'Guardrail Tax, Red Teaming, Bias Testing, EU AI Act Compliance', href: '/vault/curriculum/tracks/ai-product-economics/2-5' },
            { id: '2-6', name: '2.6 AI Product Pricing Strategy', topics: 'Value-Based Pricing, AI Credits, Pricing Experiments', href: '/vault/curriculum/tracks/ai-product-economics/2-6' },
            { id: '2-7', name: '2.7 AI Build vs Buy Decisions', topics: 'API vs Custom Model, Open Source vs Proprietary, Self-Host TCO', href: '/vault/curriculum/tracks/ai-product-economics/2-7' },
            { id: '2-8', name: '2.8 RAG System Economics', topics: 'Embedding Costs, Retrieval Costs, Context Window Optimization', href: '/vault/curriculum/tracks/ai-product-economics/2-8' },
            { id: '2-9', name: '2.9 AI Feature Profitability Analysis', topics: 'Feature-Level P&L, Revenue Attribution, Sunset Decisions', href: '/vault/curriculum/tracks/ai-product-economics/2-9' },
            { id: '2-10', name: '2.10 GPU Infrastructure Economics', topics: 'GPU Pricing, Spot vs Reserved, Inference Batch Optimization', href: '/vault/curriculum/tracks/ai-product-economics/2-10' },
            { id: '2-11', name: '2.11 AI Compliance & Risk Costs', topics: 'EU AI Act, Model Auditing, Bias Testing Budgets', href: '/vault/curriculum/tracks/ai-product-economics/2-11' },
            { id: '2-12', name: '2.12 AI Team Composition', topics: 'ML Engineer Costs, Data Scientists, Prompt Engineers, AI PMs', href: '/vault/curriculum/tracks/ai-product-economics/2-12' },
            { id: '2-13', name: '2.13 AI Product Lifecycle', topics: 'Prototype to Production 10x Cost, Scaling Patterns', href: '/vault/curriculum/tracks/ai-product-economics/2-13' },
            { id: '2-14', name: '2.14 AI Marketplace Strategy', topics: 'API Monetization, Model-as-a-Service, Developer Ecosystems', href: '/vault/curriculum/tracks/ai-product-economics/2-14' },
            { id: '2-15', name: '2.15 AI Economics Synthesis', topics: 'Complete AI Economic Model, Portfolio Analysis, Board Reporting', href: '/vault/curriculum/tracks/ai-product-economics/2-15' },
            { id: '2-16', name: '2.16 ROAI and AI Unit Economics', topics: 'Cost of Predictivity, ROAI Calculation, AUEB Ratio', href: '/vault/curriculum/tracks/ai-product-economics/2-16' },
            { id: '2-17', name: '2.17 Shadow AI & Data Extrusion', topics: 'Unauthorized LLM Usage, IP Loss, Shadow AI Defensibility', href: '/vault/curriculum/tracks/ai-product-economics/2-17' },
        ],
        color: 'violet',
        icon: '🤖',
        glossaryTerms: ['ai-cogs', 'cost-of-predictivity', 'orchestration-debt', 'ai-inference', 'rag', 'token-ai', 'guardrails', 'large-language-model', 'small-language-models', 'open-weights', 'agentic-workflow', 'ai-assisted-development'],
        tools: [{ name: 'AUEB Calculator', href: '/tools/aueb' }, { name: 'AI Scoring', href: '/tools/scoring' }, { name: 'Shadow AI Scanner', href: '/tools/shadow-ai' }],
    },
    {
        title: 'R&D Capital Management',
        subtitle: 'Track 3 — Executive',
        description: 'The executive track: managing engineering investment as a financial asset. For CTOs, PE partners, and board members. Includes engineering leadership, executive alignment, and board governance.',
        modules: [
            { id: '3-1', name: '3.1 R&D Capital Audit Methodology', topics: 'Discovery Phase, Technical Assessment, Economic Modeling', href: '/vault/curriculum/tracks/rd-capital-management/3-1' },
            { id: '3-2', name: '3.2 PE Due Diligence for Technology', topics: 'Technology Asset Valuation, Team Assessment, Debt as Deal Currency', href: '/vault/curriculum/tracks/rd-capital-management/3-2' },
            { id: '3-3', name: '3.3 Board Reporting & Executive Communication', topics: '4-Quadrant Board Slide, KPI Dashboards, Investment Proposals', href: '/vault/curriculum/tracks/rd-capital-management/3-3' },
            { id: '3-4', name: '3.4 M&A Technical Assessment', topics: 'Pre-Close Assessment, Integration Costs, Technology Synergies', href: '/vault/curriculum/tracks/rd-capital-management/3-4' },
            { id: '3-5', name: '3.5 Vendor & Platform Risk Assessment', topics: 'Criticality Scoring, Concentration Risk, Exit Strategy Planning', href: '/vault/curriculum/tracks/rd-capital-management/3-5' },
            { id: '3-6', name: '3.6 Remediation Roadmap & Execution', topics: 'ICE Prioritization, Wave Planning, Stakeholder Management', href: '/vault/curriculum/tracks/rd-capital-management/3-6' },
            { id: '3-7', name: '3.7 Architecture Assessment', topics: 'Coupling Analysis, Scalability Modeling, Architecture Debt', href: '/vault/curriculum/tracks/rd-capital-management/3-7' },
            { id: '3-8', name: '3.8 Testing & Quality Economics', topics: 'Bug Cost by Stage, Test Automation ROI, Quality Gates', href: '/vault/curriculum/tracks/rd-capital-management/3-8' },
            { id: '3-9', name: '3.9 Dependency & Vendor Risk', topics: 'Dependency Auditing, License Compliance, Vendor Concentration', href: '/vault/curriculum/tracks/rd-capital-management/3-9' },
            { id: '3-10', name: '3.10 Cloud Infrastructure Audit', topics: 'Cloud Cost Audit, Right-Sizing, Commitment Optimization', href: '/vault/curriculum/tracks/rd-capital-management/3-10' },
            { id: '3-11', name: '3.11 Security Debt Assessment', topics: 'Vulnerability Exposure, Compliance Gaps, Remediation Economics', href: '/vault/curriculum/tracks/rd-capital-management/3-11' },
            { id: '3-12', name: '3.12 Data Quality & Governance', topics: 'Data Quality Costs, Five Dimensions, Governance Frameworks', href: '/vault/curriculum/tracks/rd-capital-management/3-12' },
            { id: '3-13', name: '3.13 DevOps Maturity Assessment', topics: 'CI/CD Pipeline ROI, Observability Investment, Incident Costs', href: '/vault/curriculum/tracks/rd-capital-management/3-13' },
            { id: '3-14', name: '3.14 Technical Debt Communication', topics: 'CFO Translation, Board Presentations, Investor Due Diligence', href: '/vault/curriculum/tracks/rd-capital-management/3-14' },
            { id: '3-15', name: '3.15 R&D Capital Synthesis', topics: 'Complete Framework, Quarterly Cadence, Investment Culture', href: '/vault/curriculum/tracks/rd-capital-management/3-15' },
            { id: '3-16', name: '3.16 The Innovation Tax Audit', topics: 'Zombie Assets, Sunset Committees, Rule of Two', href: '/vault/curriculum/tracks/rd-capital-management/3-16' },
            { id: '3-17', name: '3.17 Managing Shadow AI Risk', topics: 'Data Extrusion, Corporate GenAI Walls, Shadow AI Economics', href: '/vault/curriculum/tracks/rd-capital-management/3-17' },
            { id: '3-18', name: '3.18 Technical Debt vs Technical Insolvency', topics: 'Gradual Decay vs Terminal Collapse, Board Communication', href: '/vault/curriculum/tracks/rd-capital-management/3-18' },
        ],
        color: 'emerald',
        icon: '💎',
        glossaryTerms: ['product-debt-index', 'ev-se', 'vc-due-diligence', 'architecture-review-board', 'vendor-lock-in', 'capex-vs-opex', 'technical-insolvency-date'],
        tools: [{ name: 'EV-SE Calculator', href: '/tools/ev-se' }, { name: 'Audit Interview', href: '/tools/audit-interview' }, { name: 'Innovation Tax Calculator', href: '/tools/innovation-tax-calculator' }],
    },
    {
        title: 'Capstone & Applied Practice',
        subtitle: 'Track 4 — Capstone',
        description: 'Applied practice modules: startup economics scenarios, platform engineering, org scaling, cloud FinOps, SaaS metrics, and the full R&D Capital Audit capstone project.',
        modules: [
            { id: '4-1', name: '4.1 Startup Engineering Economics', topics: 'Runway-Aware Engineering, MVP Economics, Series A Positioning', href: '/vault/curriculum/tracks/capstone/4-1' },
            { id: '4-2', name: '4.2 Enterprise Platform Economics', topics: 'Platform Tax, Developer Experience ROI, Platform Team Economics', href: '/vault/curriculum/tracks/capstone/4-2' },
            { id: '4-3', name: '4.3 Engineering Org Scaling', topics: 'Scaling Laws, Hiring Economics, Span of Control, Conway\'s Law', href: '/vault/curriculum/tracks/capstone/4-3' },
            { id: '4-4', name: '4.4 Cloud FinOps & Infrastructure', topics: 'Cloud Cost Anatomy, Reservation Strategy, FinOps Culture', href: '/vault/curriculum/tracks/capstone/4-4' },
            { id: '4-5', name: '4.5 SaaS Metrics Deep Dive', topics: 'NRR, CAC:LTV, Unit Economics, Rule of 40, Engineering Efficiency', href: '/vault/curriculum/tracks/capstone/4-5' },
            { id: '4-6', name: '4.6 Capstone: Full R&D Capital Audit', topics: 'Complete Audit Project, Board-Ready Document, Investment Roadmap', href: '/vault/curriculum/tracks/capstone/4-6' },
            { id: '4-7', name: '4.7 Case Study: SaaS Scale-Up', topics: 'Series B Audit, Scaling Challenges, Technical Debt Hotspots', href: '/vault/curriculum/tracks/capstone/4-7' },
            { id: '4-8', name: '4.8 Case Study: PE Portfolio', topics: 'Post-Acquisition Audit, Platform Consolidation, Team Restructuring', href: '/vault/curriculum/tracks/capstone/4-8' },
            { id: '4-9', name: '4.9 Case Study: AI Startup', topics: 'Burn Rate Optimization, Model Economics, Commercialization', href: '/vault/curriculum/tracks/capstone/4-9' },
            { id: '4-10', name: '4.10 Case Study: Enterprise Modernization', topics: 'Legacy Migration, Dual-Speed IT, Strangler Fig Pattern', href: '/vault/curriculum/tracks/capstone/4-10' },
            { id: '4-11', name: '4.11 Building Your Practice', topics: 'Engagement Design, Pricing, Deliverables, Client Management', href: '/vault/curriculum/tracks/capstone/4-11' },
            { id: '4-12', name: '4.12 Tools Deep Dive', topics: 'Professional Tool Workflow, Cross-Referencing, Assessment Timing', href: '/vault/curriculum/tracks/capstone/4-12' },
            { id: '4-13', name: '4.13 Presentation & Storytelling', topics: 'SCR Framework, Data Visualization, Executive Communication', href: '/vault/curriculum/tracks/capstone/4-13' },
            { id: '4-14', name: '4.14 Continuous Improvement', topics: 'Engineering OKRs, Monthly Reviews, Automated Dashboards', href: '/vault/curriculum/tracks/capstone/4-14' },
            { id: '4-15', name: '4.15 Final Capstone Assessment', topics: 'End-to-End Audit, Peer Review, Professional Presentation', href: '/vault/curriculum/tracks/capstone/4-15' },
        ],
        color: 'amber',
        icon: '🏆',
        glossaryTerms: ['burn-rate', 'cac', 'arr', 'finops', 'developer-experience', 'cost-per-hire', 'dpi', 'down-round', 'saas-valuation'],
        tools: [{ name: 'PDI Calculator', href: '/tools/pdi' }, { name: 'APER Calculator', href: '/tools/aper' }, { name: 'AUEB Calculator', href: '/tools/aueb' }, { name: 'EV-SE Calculator', href: '/tools/ev-se' }],
    },
    {
        title: 'Product Management Economics',
        subtitle: 'Track 5 — Product',
        description: 'Product economics for PMs and CPOs: feature prioritization using economic models, pricing strategy, churn economics, and the bridge between product and finance. Nobody else teaches PM through the P&L lens.',
        modules: [
            { id: '6-1', name: '5.1 Feature Prioritization Economics', topics: 'RICE vs WSJF, Opportunity Cost, Stack Ranking by Dollar Value', href: '/vault/curriculum/tracks/product-economics/6-1' },
            { id: '6-2', name: '5.2 Pricing & Packaging Strategy', topics: 'Value-Based Pricing, Tiering, Usage Pricing, Price Elasticity', href: '/vault/curriculum/tracks/product-economics/6-2' },
            { id: '6-3', name: '5.3 Churn & Retention Economics', topics: 'Churn Waterfall, LTV Modeling, Retention ROI, Cohort Analysis', href: '/vault/curriculum/tracks/product-economics/6-3' },
            { id: '6-4', name: '5.4 Feature Bloat Calculus', topics: 'Feature Cost Decay, Maintenance Drag, Sunset Economics', href: '/vault/curriculum/tracks/product-economics/6-4' },
            { id: '6-5', name: '5.5 Product-Led Growth Economics', topics: 'PLG Funnel Costs, Free Tier Economics, Conversion Optimization', href: '/vault/curriculum/tracks/product-economics/6-5' },
            { id: '6-6', name: '5.6 Competitive Moat Analysis', topics: 'Switching Cost Quantification, Network Effects, Data Moats', href: '/vault/curriculum/tracks/product-economics/6-6' },
            { id: '6-7', name: '5.7 A/B Testing Economics', topics: 'Experimentation ROI, Test Duration Costs, Statistical Significance', href: '/vault/curriculum/tracks/product-economics/6-7' },
            { id: '6-8', name: '5.8 Product Operations', topics: 'ProductOps ROI, Tool Costs, Process Automation', href: '/vault/curriculum/tracks/product-economics/6-8' },
            { id: '6-9', name: '5.9 Customer Acquisition Economics', topics: 'CAC Payback, Channel Economics, Blended CAC', href: '/vault/curriculum/tracks/product-economics/6-9' },
            { id: '6-10', name: '5.10 Marketplace Economics', topics: 'Platform Take Rate, Network Economics, Liquidity Metrics', href: '/vault/curriculum/tracks/product-economics/6-10' },
            { id: '6-11', name: '5.11 Product Analytics ROI', topics: 'Analytics Stack Costs, Insight-to-Action, Data Warehouse ROI', href: '/vault/curriculum/tracks/product-economics/6-11' },
            { id: '6-12', name: '5.12 Technical Product Management', topics: 'TPM Economics, API Monetization, Dev Tool Pricing', href: '/vault/curriculum/tracks/product-economics/6-12' },
            { id: '6-13', name: '5.13 Product Roadmap Economics', topics: 'Opportunity Cost of Roadmaps, Pivot Costs, Feature Debt', href: '/vault/curriculum/tracks/product-economics/6-13' },
            { id: '6-14', name: '5.14 Product-Finance Partnership', topics: 'PM Scorecards, Revenue Attribution, Unit Economics Reporting', href: '/vault/curriculum/tracks/product-economics/6-14' },
            { id: '6-15', name: '5.15 Product Economics Synthesis', topics: 'Complete Product Economic Model, Portfolio View, Board Report', href: '/vault/curriculum/tracks/product-economics/6-15' },
        ],
        color: 'pink',
        icon: '📱',
        glossaryTerms: ['feature-bloat-calculus', 'cost-of-delay', 'cac', 'arr', 'product-led-growth', 'net-revenue-retention', 'burn-multiple'],
        tools: [{ name: 'PDI Calculator', href: '/tools/pdi' }, { name: 'APER Calculator', href: '/tools/aper' }],
    },
    {
        title: 'AI Operations Economics & Cost Governance',
        subtitle: 'Track 6 — AI Ops',
        description: 'The economics of deploying, governing, and scaling AI systems: model selection, prompt engineering ROI, AI compliance costs, agentic automation, and vendor comparison. Connects to Exogram and EAAP.',
        modules: [
            { id: '11-1', name: '6.1 AI Model Selection Economics', topics: 'Foundation Model Costs, Inference Pricing, Quality-Cost Tradeoffs', href: '/vault/curriculum/tracks/ai-operations/11-1' },
            { id: '11-2', name: '6.2 Prompt Engineering ROI', topics: 'Prompt Library Economics, Testing Costs, Prompt Infrastructure', href: '/vault/curriculum/tracks/ai-operations/11-2' },
            { id: '11-3', name: '6.3 AI Testing & Evaluation', topics: 'Eval Suite Costs, Benchmark Design, Quality Gate Economics', href: '/vault/curriculum/tracks/ai-operations/11-3' },
            { id: '11-4', name: '6.4 Hallucination Cost Modeling', topics: 'Detection Costs, Business Impact, Guardrail Investment', href: '/vault/curriculum/tracks/ai-operations/11-4' },
            { id: '11-5', name: '6.5 RAG Architecture Economics', topics: 'Embedding Costs, Vector DB Pricing, Chunking Strategy', href: '/vault/curriculum/tracks/ai-operations/11-5' },
            { id: '11-6', name: '6.6 AI Agent Economics', topics: 'Agent Orchestration, Tool-Use Pricing, Multi-Agent Systems', href: '/vault/curriculum/tracks/ai-operations/11-6' },
            { id: '11-7', name: '6.7 AI Compliance & Audit', topics: 'EU AI Act, NIST AI RMF, Model Cards, Governance Committees', href: '/vault/curriculum/tracks/ai-operations/11-7' },
            { id: '11-8', name: '6.8 AI Vendor Comparison', topics: 'OpenAI vs Anthropic vs Google, TCO, Switching Costs', href: '/vault/curriculum/tracks/ai-operations/11-8' },
            { id: '11-9', name: '6.9 AI Team Building', topics: 'ML Engineer Compensation, Skill Gap, Training Investment', href: '/vault/curriculum/tracks/ai-operations/11-9' },
            { id: '11-10', name: '6.10 AI Operations Synthesis', topics: 'Complete AI Economic Model, GPU Forecasting, Strategy', href: '/vault/curriculum/tracks/ai-operations/11-10' },
            { id: '11-11', name: '6.11 Graph RAG Implementation', topics: 'Knowledge Graphs, Hallucination Elimination, Query Routing', href: '/vault/curriculum/tracks/ai-operations/11-11' },
            { id: '11-12', name: '6.12 Multimodal Processing Pipelines', topics: 'Audio/Video Reasoning, Document Ingestion Costs, Latency', href: '/vault/curriculum/tracks/ai-operations/11-12' },
            { id: '11-13', name: '6.13 AI Product Management', topics: 'Probabilistic PM, Non-Deterministic Testing, Feature KPIs', href: '/vault/curriculum/tracks/ai-operations/11-13' },
            { id: '11-14', name: '6.14 Shadow AI Discovery', topics: 'Employee App Usage, Data Leakage Prevention, Policy Enforcement', href: '/vault/curriculum/tracks/ai-operations/11-14' },
            { id: '11-15', name: '6.15 Prompt Injection Defense', topics: 'Jailbreak Prevention, Input Sanitization, Security Economics', href: '/vault/curriculum/tracks/ai-operations/11-15' },
            { id: '11-16', name: '6.16 Model Collapse Financial Modeling', topics: 'Model Depreciation, Organic Data Costs, Financial Decay', href: '/vault/curriculum/tracks/ai-operations/11-16' },
        ],
        color: 'teal',
        icon: '🧠',
        glossaryTerms: ['ai-inference', 'rag-architecture', 'graph-rag', 'multimodal-ai', 'ai-product-management', 'shadow-ai', 'prompt-injection', 'guardrails', 'token-ai', 'ai-cogs', 'agentic-workflow'],
        tools: [{ name: 'AUEB Calculator', href: '/tools/aueb' }, { name: 'AI Scoring', href: '/tools/scoring' }],
    },
    {
        title: 'Cloud FinOps & AI Cost Management',
        subtitle: 'Track 7 — FinOps',
        description: 'The economics of cloud cost management, optimization, and FinOps practice. 98% of FinOps teams now manage AI spend. AI cost management is the #1 capability teams plan to add in 2026.',
        modules: [
            { id: '7-1', name: '7.1 FinOps Fundamentals', topics: 'FinOps Maturity, Stakeholder Alignment, Team Sizing', href: '/vault/curriculum/tracks/cloud-finops/7-1' },
            { id: '7-2', name: '7.2 Cloud Cost Allocation', topics: 'Tagging Strategies, Showback Dashboards, Chargeback', href: '/vault/curriculum/tracks/cloud-finops/7-2' },
            { id: '7-3', name: '7.3 Reserved Instances & Savings Plans', topics: 'RI vs Savings Plans, Coverage Analysis, Break-Even', href: '/vault/curriculum/tracks/cloud-finops/7-3' },
            { id: '7-4', name: '7.4 Kubernetes Cost Management', topics: 'K8s Right-Sizing, Namespace Budgets, Cluster Allocation', href: '/vault/curriculum/tracks/cloud-finops/7-4' },
            { id: '7-5', name: '7.5 Serverless vs Container Economics', topics: 'Lambda vs ECS vs EKS, Cold Start, Workload Fit', href: '/vault/curriculum/tracks/cloud-finops/7-5' },
            { id: '7-6', name: '7.6 Multi-Cloud Arbitrage', topics: 'Cross-Cloud Pricing, Egress Management, Negotiation', href: '/vault/curriculum/tracks/cloud-finops/7-6' },
            { id: '7-7', name: '7.7 Cloud Migration ROI', topics: 'Lift-and-Shift vs Refactor, Timeline, Post-Migration', href: '/vault/curriculum/tracks/cloud-finops/7-7' },
            { id: '7-8', name: '7.8 Data Transfer & Egress', topics: 'CDN Economics, Edge Caching, Bandwidth, Data Locality', href: '/vault/curriculum/tracks/cloud-finops/7-8' },
            { id: '7-9', name: '7.9 FinOps Team & Governance', topics: 'FinOps Roles, KPI Frameworks, Executive Reporting', href: '/vault/curriculum/tracks/cloud-finops/7-9' },
            { id: '7-10', name: '7.10 Infrastructure Synthesis', topics: 'Cloud Economic Model, Optimization Dashboard, Strategy', href: '/vault/curriculum/tracks/cloud-finops/7-10' },
            { id: '7-11', name: '7.11 AI FinOps Specialization', topics: 'LLM Token Allocation, GPU Cluster Depreciation, Margin Triage', href: '/vault/curriculum/tracks/cloud-finops/7-11' },
            { id: '7-12', name: '7.12 Cloud Repatriation Calculus', topics: 'Basecamp Migration Strategy, Bare Metal Racks, Egress Elimination', href: '/vault/curriculum/tracks/cloud-finops/7-12' },
            { id: '7-13', name: '7.13 Serverless GPU Brokering', topics: 'Modal vs Runpod, Cold Start Tolerances, GPU Spot Markets', href: '/vault/curriculum/tracks/cloud-finops/7-13' },
            { id: '7-14', name: '7.14 Data Security Posture Management (DSPM)', topics: 'Cloud Discovery Scanning, Shadow Data Remediation, ROI Analysis', href: '/vault/curriculum/tracks/cloud-finops/7-14' },
            { id: '7-15', name: '7.15 Continuous Architecture Modernization', topics: 'Refactoring Rhythms, Retiring Legacy Instances, Savings Decay', href: '/vault/curriculum/tracks/cloud-finops/7-15' },
        ],
        color: 'blue',
        icon: '☁️',
        glossaryTerms: ['finops', 'ai-finops', 'cloud-repatriation', 'serverless-gpus', 'dspm', 'burn-multiple', 'infrastructure-as-code', 'cloud-cost-optimization'],
        tools: [{ name: 'PDI Calculator', href: '/tools/pdi' }, { name: 'AUEB Calculator', href: '/tools/aueb' }],
    },
    {
        title: 'AI Pricing Strategy & Monetization Economics',
        subtitle: 'Track 8 — NEW',
        description: '37% of AI companies plan to change their pricing model in the next 12 months. Outcome-based pricing jumped from 2% to 18% in six months. Teach the economics of pricing AI products.',
        modules: [
            { id: '8-1', name: '8.1 AI Pricing Model Taxonomy', topics: 'Usage-Based vs Outcome-Based vs Subscription, Hybrid Models', href: '/vault/curriculum/tracks/ai-pricing/8-1' },
            { id: '8-2', name: '8.2 Token-Based Pricing Architecture', topics: 'Credit Systems, Metering Infrastructure, Rate Limiting Economics', href: '/vault/curriculum/tracks/ai-pricing/8-2' },
            { id: '8-3', name: '8.3 The Flat-Rate AI Death Trap', topics: 'Unlimited AI at Flat Rate, Margin Collapse Scenarios, Usage Spikes', href: '/vault/curriculum/tracks/ai-pricing/8-3' },
            { id: '8-4', name: '8.4 Outcome-Based Pricing Models', topics: 'Value Capture, Success Metrics, Risk-Sharing Economics', href: '/vault/curriculum/tracks/ai-pricing/8-4' },
            { id: '8-5', name: '8.5 AI Freemium Economics', topics: 'Free Tier COGS, Conversion Funnels, Upsell Trigger Points', href: '/vault/curriculum/tracks/ai-pricing/8-5' },
            { id: '8-6', name: '8.6 Enterprise AI Contract Design', topics: 'Commit Structures, Overage Pricing, Annual vs Monthly', href: '/vault/curriculum/tracks/ai-pricing/8-6' },
            { id: '8-7', name: '8.7 Competitive Pricing Intelligence', topics: 'Market Positioning, Price Anchoring, Differentiation Premiums', href: '/vault/curriculum/tracks/ai-pricing/8-7' },
            { id: '8-8', name: '8.8 Revenue Attribution for AI Features', topics: 'Feature-Level Revenue, Willingness-to-Pay Research, Bundling', href: '/vault/curriculum/tracks/ai-pricing/8-8' },
            { id: '8-9', name: '8.9 AI Marketplace Monetization', topics: 'API-as-Product, Model Marketplace Take Rates, Developer Ecosystems', href: '/vault/curriculum/tracks/ai-pricing/8-9' },
            { id: '8-10', name: '8.10 Pricing Strategy Synthesis', topics: 'Complete AI Pricing Model, Board Presentation, Margin Optimization', href: '/vault/curriculum/tracks/ai-pricing/8-10' },
        ],
        color: 'fuchsia',
        icon: '💰',
        glossaryTerms: ['ai-cogs', 'unit-economics', 'net-revenue-retention', 'burn-multiple', 'cost-of-predictivity'],
        tools: [{ name: 'AUEB Calculator', href: '/tools/aueb' }],
    },
    {
        title: 'Technical Debt as Financial Liability',
        subtitle: 'Track 9 — NEW',
        description: 'You already publish on calculating technical debt\'s EBITDA impact for PE due diligence. Direct buyer intent from PE firms, CFOs, and VPEs preparing for acquisitions or audits.',
        modules: [
            { id: '9-1', name: '9.1 Technical Debt on the Balance Sheet', topics: 'GAAP Treatment, Liability Classification, Audit Disclosure', href: '/vault/curriculum/tracks/tech-debt-liability/9-1' },
            { id: '9-2', name: '9.2 Quantifying Debt in Dollar Terms', topics: 'PDI Methodology, Maintenance Load Costing, Interest Rate Models', href: '/vault/curriculum/tracks/tech-debt-liability/9-2' },
            { id: '9-3', name: '9.3 Technical Insolvency Date', topics: 'When Debt Exceeds Capacity, Death Spiral Indicators, Tipping Points', href: '/vault/curriculum/tracks/tech-debt-liability/9-3' },
            { id: '9-4', name: '9.4 Debt Impact on EBITDA', topics: 'Maintenance Drag on Margins, Developer Velocity Tax, CFO Translation', href: '/vault/curriculum/tracks/tech-debt-liability/9-4' },
            { id: '9-5', name: '9.5 PE Due Diligence: Tech Debt Assessment', topics: 'Pre-LOI Scans, Deal Breakers, Discount Models, Holdback Structures', href: '/vault/curriculum/tracks/tech-debt-liability/9-5' },
            { id: '9-6', name: '9.6 Debt Forgiveness Protocols', topics: 'Sunk Cost Fallacy, Code Bankruptcy, Rewrite Mathematics', href: '/vault/curriculum/tracks/tech-debt-liability/9-6' },
            { id: '9-7', name: '9.7 Architecture Debt Valuation', topics: 'Coupling Costs, Monolith Decomposition, Migration Economics', href: '/vault/curriculum/tracks/tech-debt-liability/9-7' },
            { id: '9-8', name: '9.8 Infrastructure Debt', topics: 'EOL Hardware, Unpatched Systems, Cloud Migration Forcing Functions', href: '/vault/curriculum/tracks/tech-debt-liability/9-8' },
            { id: '9-9', name: '9.9 Communicating Debt to the Board', topics: 'Visual Frameworks, Risk Heat Maps, Investment Proposals', href: '/vault/curriculum/tracks/tech-debt-liability/9-9' },
            { id: '9-10', name: '9.10 Tech Debt Remediation Economics', topics: 'Wave Planning, ROI-First Prioritization, Continuous Paydown Models', href: '/vault/curriculum/tracks/tech-debt-liability/9-10' },
        ],
        color: 'red',
        icon: '🏚️',
        glossaryTerms: ['technical-debt', 'product-debt-index', 'technical-insolvency-date', 'innovation-tax', 'maintenance-load'],
        tools: [{ name: 'PDI Calculator', href: '/tools/pdi' }, { name: 'EV-SE Calculator', href: '/tools/ev-se' }],
    },
    {
        title: 'AI Due Diligence for Investors & Acquirers',
        subtitle: 'Track 10 — NEW',
        description: 'PE firms, corporate development teams, and VCs evaluating AI companies need this. A natural extension of R&D Capital Management with a clear buyer profile.',
        modules: [
            { id: '10-1', name: '10.1 AI Company Valuation Frameworks', topics: 'ARR Multiples for AI, Revenue Quality, Gross Margin Analysis', href: '/vault/curriculum/tracks/ai-due-diligence/10-1' },
            { id: '10-2', name: '10.2 AI Model Asset Valuation', topics: 'Proprietary Data Moats, Fine-Tuned Model Worth, Training Cost Basis', href: '/vault/curriculum/tracks/ai-due-diligence/10-2' },
            { id: '10-3', name: '10.3 AI Infrastructure Audit', topics: 'GPU Contracts, Cloud Commitments, Inference Cost Trajectories', href: '/vault/curriculum/tracks/ai-due-diligence/10-3' },
            { id: '10-4', name: '10.4 Data Asset Due Diligence', topics: 'Data Quality Scoring, Licensing Compliance, Privacy Risk Assessment', href: '/vault/curriculum/tracks/ai-due-diligence/10-4' },
            { id: '10-5', name: '10.5 AI Team Assessment', topics: 'Key-Person Risk, ML Engineer Retention, Talent Market Benchmarks', href: '/vault/curriculum/tracks/ai-due-diligence/10-5' },
            { id: '10-6', name: '10.6 AI Technical Debt Evaluation', topics: 'Model Drift Risk, Pipeline Fragility, Retraining Cost Projections', href: '/vault/curriculum/tracks/ai-due-diligence/10-6' },
            { id: '10-7', name: '10.7 AI Regulatory & Compliance Risk', topics: 'EU AI Act Exposure, IP Litigation, Bias Liability Quantification', href: '/vault/curriculum/tracks/ai-due-diligence/10-7' },
            { id: '10-8', name: '10.8 Competitive Moat Analysis for AI', topics: 'Data Flywheel Strength, Model Defensibility, Switching Costs', href: '/vault/curriculum/tracks/ai-due-diligence/10-8' },
            { id: '10-9', name: '10.9 Post-Acquisition AI Integration', topics: 'Model Consolidation, Team Merging, Infrastructure Rationalization', href: '/vault/curriculum/tracks/ai-due-diligence/10-9' },
            { id: '10-10', name: '10.10 AI Due Diligence Synthesis', topics: 'Complete AI DD Report Template, Board Presentation, Deal Structuring', href: '/vault/curriculum/tracks/ai-due-diligence/10-10' },
        ],
        color: 'indigo',
        icon: '🔍',
        glossaryTerms: ['vc-due-diligence', 'ai-cogs', 'ev-se', 'burn-rate', 'arr', 'saas-valuation'],
        tools: [{ name: 'EV-SE Calculator', href: '/tools/ev-se' }, { name: 'Audit Interview', href: '/tools/audit-interview' }],
    },
    {
        title: 'Economics of Build vs. Buy for AI',
        subtitle: 'Track 11 — NEW',
        description: 'Every engineering leader faces this right now. Frame it through your economic lens: TCO modeling, vendor lock-in costs, inference arbitrage, and the hidden costs of "free" open-source models.',
        modules: [
            { id: '11-1', name: '11.1 The Build vs Buy Decision Framework', topics: 'Total Cost of Ownership, Core vs Context, Strategic Differentiation Test', href: '/vault/curriculum/tracks/ai-build-vs-buy/11-1' },
            { id: '11-2', name: '11.2 API Provider Economics', topics: 'OpenAI vs Anthropic vs Google Pricing, Volume Discounts, Rate Limits', href: '/vault/curriculum/tracks/ai-build-vs-buy/11-2' },
            { id: '11-3', name: '11.3 Self-Hosting Economics', topics: 'GPU Infrastructure TCO, Llama/Mistral Hosting, DevOps Overhead', href: '/vault/curriculum/tracks/ai-build-vs-buy/11-3' },
            { id: '11-4', name: '11.4 Open Source Model Hidden Costs', topics: 'Fine-Tuning Compute, Evaluation Infrastructure, Maintenance Burden', href: '/vault/curriculum/tracks/ai-build-vs-buy/11-4' },
            { id: '11-5', name: '11.5 Vendor Lock-In Quantification', topics: 'Switching Costs, Embedding Migration, Prompt Rewriting, Data Gravity', href: '/vault/curriculum/tracks/ai-build-vs-buy/11-5' },
            { id: '11-6', name: '11.6 Inference Cost Arbitrage', topics: 'Model Routing, Tiered Quality, Cost-Performance Optimization', href: '/vault/curriculum/tracks/ai-build-vs-buy/11-6' },
            { id: '11-7', name: '11.7 RAG Build vs Buy', topics: 'Pinecone vs pgvector vs Custom, Managed vs Self-Hosted Embeddings', href: '/vault/curriculum/tracks/ai-build-vs-buy/11-7' },
            { id: '11-8', name: '11.8 AI Platform vs Point Solution', topics: 'Horizontal Platforms, Vertical AI SaaS, Integration Complexity', href: '/vault/curriculum/tracks/ai-build-vs-buy/11-8' },
            { id: '11-9', name: '11.9 Multi-Model Strategy Economics', topics: 'Portfolio Approach, Fallback Architecture, Best-of-Breed Routing', href: '/vault/curriculum/tracks/ai-build-vs-buy/11-9' },
            { id: '11-10', name: '11.10 Build vs Buy Synthesis', topics: 'Decision Matrix Template, Board Presentation, 3-Year TCO Model', href: '/vault/curriculum/tracks/ai-build-vs-buy/11-10' },
        ],
        color: 'orange',
        icon: '⚖️',
        glossaryTerms: ['total-cost-of-ownership', 'vendor-lock-in', 'ai-cogs', 'ai-inference', 'open-weights', 'cloud-repatriation'],
        tools: [{ name: 'AUEB Calculator', href: '/tools/aueb' }, { name: 'PDI Calculator', href: '/tools/pdi' }],
    },
    {
        title: 'Career Capital Economics',
        subtitle: 'Track 12 — NEW',
        description: 'Stop being a cost center. Learn to quantify your business impact, negotiate compensation using economic frameworks, and prove your dollar value at every level — from junior IC to Staff Engineer.',
        modules: [
            { id: '12-1', name: '12.1 Your Revenue-Per-Engineer Contribution', topics: 'Calculating APER Impact, Attributing Business Value, Beyond Story Points', href: '/vault/curriculum/tracks/career-capital/12-1' },
            { id: '12-2', name: '12.2 Compensation Economics', topics: 'Pay Band Analysis, Equity Valuation, Total Comp Modeling, RSU vs Options', href: '/vault/curriculum/tracks/career-capital/12-2' },
            { id: '12-3', name: '12.3 The Business Case for Promotion', topics: 'Quantified Impact Dossiers, P&L Outcomes, Translating Code to Revenue', href: '/vault/curriculum/tracks/career-capital/12-3' },
            { id: '12-4', name: '12.4 Navigating Layoff Economics', topics: 'Severance Math, Risk Indicators, Cost Center vs Profit Center Positioning', href: '/vault/curriculum/tracks/career-capital/12-4' },
            { id: '12-5', name: '12.5 The Senior Engineer P&L', topics: 'Measuring Leverage, Technical Debt Prevention ROI, Architecture Impact', href: '/vault/curriculum/tracks/career-capital/12-5' },
            { id: '12-6', name: '12.6 Staff Engineer as Capital Allocator', topics: 'Cross-Team Influence Economics, RFC ROI, Platform Strategy Ownership', href: '/vault/curriculum/tracks/career-capital/12-6' },
            { id: '12-7', name: '12.7 The Cost of Career Stagnation', topics: 'Opportunity Cost Modeling, Market Rate Drift, Skill Depreciation Curves', href: '/vault/curriculum/tracks/career-capital/12-7' },
            { id: '12-8', name: '12.8 Negotiation Using Economic Frameworks', topics: 'Anchoring with Data, Competing Offers, Equity vs Cash Tradeoffs', href: '/vault/curriculum/tracks/career-capital/12-8' },
            { id: '12-9', name: '12.9 Building a Revenue-Centric Resume', topics: 'Impact Metrics, Business Outcome Framing, P&L Language for Engineers', href: '/vault/curriculum/tracks/career-capital/12-9' },
            { id: '12-10', name: '12.10 Career Capital Synthesis', topics: 'Your Personal Economic Model, 5-Year Capital Plan, Board-of-You Strategy', href: '/vault/curriculum/tracks/career-capital/12-10' },
        ],
        color: 'rose',
        icon: '📈',
        glossaryTerms: ['cost-per-hire', 'attrition-rate', 'developer-experience', 'unit-economics'],
        tools: [{ name: 'APER Calculator', href: '/tools/aper' }, { name: 'Career Pathing', href: '/tools/career-pathing' }],
    },
    {
        title: 'Engineering-to-Executive Economics',
        subtitle: 'Track 13 — NEW',
        description: 'The economics translation layer for Directors, VPs, and aspiring CTOs. Learn to think in P&L, present to boards, own budgets, and position yourself as a revenue-driving executive — not a technical manager.',
        modules: [
            { id: '13-1', name: '13.1 The Language of the Boardroom', topics: 'EBITDA Translation, Margin Frameworks, Executive Vocabulary', href: '/vault/curriculum/tracks/exec-economics/13-1' },
            { id: '13-2', name: '13.2 Budget Ownership & R&D Stewardship', topics: 'CapEx vs OpEx, Headcount Modeling, Zero-Based Budgeting', href: '/vault/curriculum/tracks/exec-economics/13-2' },
            { id: '13-3', name: '13.3 Board Reporting for Technical Leaders', topics: '4-Quadrant Slides, KPI Dashboards, Investment Proposals', href: '/vault/curriculum/tracks/exec-economics/13-3' },
            { id: '13-4', name: '13.4 Reorg Economics & Org Design', topics: 'Restructuring Costs, Productivity Dip, Conway\'s Law at Scale', href: '/vault/curriculum/tracks/exec-economics/13-4' },
            { id: '13-5', name: '13.5 M&A Technical Leadership', topics: 'Due Diligence Leadership, Integration Playbook, Talent Retention', href: '/vault/curriculum/tracks/exec-economics/13-5' },
            { id: '13-6', name: '13.6 CTO vs VP Engineering Economics', topics: 'Role Separation, Cost Structures, Board Relationship Dynamics', href: '/vault/curriculum/tracks/exec-economics/13-6' },
            { id: '13-7', name: '13.7 Managing Technical Debt at the Board Level', topics: 'Risk Heat Maps, Investment Proposals, Remediation Roadmaps', href: '/vault/curriculum/tracks/exec-economics/13-7' },
            { id: '13-8', name: '13.8 AI Strategy for Executives', topics: 'AI Investment Framework, Build vs Buy at the C-Suite, Vendor Selection', href: '/vault/curriculum/tracks/exec-economics/13-8' },
            { id: '13-9', name: '13.9 The 90-Day CTO Turnaround', topics: 'Trust Bridge, 360 Audit, Quick Wins, Board Confidence Building', href: '/vault/curriculum/tracks/exec-economics/13-9' },
            { id: '13-10', name: '13.10 Executive Economics Synthesis', topics: 'Your CTO Dashboard, Quarterly Cadence, Long-Term Capital Planning', href: '/vault/curriculum/tracks/exec-economics/13-10' },
        ],
        color: 'indigo',
        icon: '👑',
        glossaryTerms: ['capex-vs-opex', 'ev-se', 'product-debt-index', 'vc-due-diligence', 'conways-law', 'span-of-control'],
        tools: [{ name: 'EV-SE Calculator', href: '/tools/ev-se' }, { name: 'Audit Interview', href: '/tools/audit-interview' }],
    },
    {
        title: 'The Economics of Leadership (Not Management)',
        subtitle: 'Track 14 — NEW',
        description: 'Leadership is a skill, not a rank. Companies train you for the technical job, then promote you to a job they never teach. That\'s why we get managers, not leaders. This track teaches the economics of becoming one.',
        modules: [
            { id: '14-1', name: '14.1 Leadership vs Management: The Economic Distinction', topics: 'The Promotion Gap, Manager Cost vs Leader ROI, Skill vs Rank', href: '/vault/curriculum/tracks/leadership-economics/14-1' },
            { id: '14-2', name: '14.2 The Peter Principle: The Cost of Promoting to Incompetence', topics: 'Good Engineer ≠ Good Leader, Transition Tax, The Training Void', href: '/vault/curriculum/tracks/leadership-economics/14-2' },
            { id: '14-3', name: '14.3 The Economics of Psychological Safety', topics: 'Innovation Premium, Fear Tax, Google\'s Project Aristotle Applied', href: '/vault/curriculum/tracks/leadership-economics/14-3' },
            { id: '14-4', name: '14.4 Attrition Economics: The Cost of Losing Your Best People', topics: 'Replacement Costs, Knowledge Drain, Productivity Ripple Effects', href: '/vault/curriculum/tracks/leadership-economics/14-4' },
            { id: '14-5', name: '14.5 Servant Leadership ROI', topics: 'Enabling vs Controlling, Unblocking as Value Creation, Trust Capital', href: '/vault/curriculum/tracks/leadership-economics/14-5' },
            { id: '14-6', name: '14.6 Mentoring as Capital Investment', topics: 'Knowledge Duplication ROI, Succession Planning, 10x Multiplier Effect', href: '/vault/curriculum/tracks/leadership-economics/14-6' },
            { id: '14-7', name: '14.7 Decision-Making Economics for Leaders', topics: 'Decision Latency Cost, Reversible vs Irreversible, Delegation ROI', href: '/vault/curriculum/tracks/leadership-economics/14-7' },
            { id: '14-8', name: '14.8 Communication as a Revenue Driver', topics: 'Clarity Premium, Meeting Cost Calculator, Feedback Loop ROI', href: '/vault/curriculum/tracks/leadership-economics/14-8' },
            { id: '14-9', name: '14.9 Building High-Performance Teams: The Economics', topics: 'Team Composition ROI, Cognitive Diversity Premium, Cross-Functional Value', href: '/vault/curriculum/tracks/leadership-economics/14-9' },
            { id: '14-10', name: '14.10 Leadership Development ROI Synthesis', topics: 'Your Leadership P&L, Development Budget, 360 Assessment Economics', href: '/vault/curriculum/tracks/leadership-economics/14-10' },
        ],
        color: 'amber',
        icon: '🔥',
        glossaryTerms: ['cost-per-hire', 'attrition-rate', 'developer-experience', 'conways-law', 'span-of-control'],
        tools: [{ name: 'APER Calculator', href: '/tools/aper' }, { name: 'Career Pathing', href: '/tools/career-pathing' }],
    },
    {
        title: 'The Economics of Remote & Distributed Teams',
        subtitle: 'Track 15 — NEW',
        description: 'Remote work isn\'t a perk — it\'s an economic model with measurable costs, arbitrage opportunities, and hidden taxes. This track gives you the financial framework to build, manage, and optimize distributed engineering organizations.',
        modules: [
            { id: '15-1', name: '15.1 Remote vs Office: Total Cost Analysis', topics: 'Office TCO, Remote Infrastructure Costs, Net Savings Calculation', href: '/vault/curriculum/tracks/remote-economics/15-1' },
            { id: '15-2', name: '15.2 Geographic Compensation Arbitrage', topics: 'Location-Based Pay Bands, Cost-of-Living Adjustments, Equity Implications', href: '/vault/curriculum/tracks/remote-economics/15-2' },
            { id: '15-3', name: '15.3 The Meeting Cost Calculator', topics: 'Per-Minute Meeting Costs, Async vs Sync ROI, Calendar Optimization', href: '/vault/curriculum/tracks/remote-economics/15-3' },
            { id: '15-4', name: '15.4 Async Communication ROI', topics: 'Written Communication Premium, Documentation-First Culture, Timezone Value', href: '/vault/curriculum/tracks/remote-economics/15-4' },
            { id: '15-5', name: '15.5 Remote Onboarding Economics', topics: 'Virtual Ramp Time, Buddy System ROI, 90-Day Productivity Curves', href: '/vault/curriculum/tracks/remote-economics/15-5' },
            { id: '15-6', name: '15.6 Distributed Team Productivity Measurement', topics: 'Output vs Hours, Outcome-Based Evaluation, Remote APER Calculation', href: '/vault/curriculum/tracks/remote-economics/15-6' },
            { id: '15-7', name: '15.7 Remote Attrition Premium', topics: 'Isolation Cost, Belonging Tax, Retention Strategy for Remote Workers', href: '/vault/curriculum/tracks/remote-economics/15-7' },
            { id: '15-8', name: '15.8 Cross-Timezone Coordination Costs', topics: 'Overlap Hour Economics, Follow-the-Sun Models, Handoff Efficiency', href: '/vault/curriculum/tracks/remote-economics/15-8' },
            { id: '15-9', name: '15.9 Remote Security & Compliance Economics', topics: 'WFH Endpoint Costs, Data Sovereignty, Remote Compliance Overhead', href: '/vault/curriculum/tracks/remote-economics/15-9' },
            { id: '15-10', name: '15.10 Hybrid Economics: The Worst of Both Worlds?', topics: 'Hybrid TCO, Occupancy Waste, Coordination Premium for Mixed Teams', href: '/vault/curriculum/tracks/remote-economics/15-10' },
        ],
        color: 'teal',
        icon: '🌍',
        glossaryTerms: ['cost-per-hire', 'attrition-rate', 'developer-experience', 'aper'],
        tools: [{ name: 'APER Calculator', href: '/tools/aper' }],
    },
    {
        title: 'M&A Technical Integration Economics',
        subtitle: 'Track 16 — NEW',
        description: 'Most acquisition value is destroyed during integration. This track teaches you to evaluate, plan, and execute technical integrations that preserve — not destroy — the value your company spent millions to acquire.',
        modules: [
            { id: '16-1', name: '16.1 Pre-Acquisition Technical Assessment', topics: 'Tech Stack Compatibility, Integration Cost Estimation, Deal-Breaker Discovery', href: '/vault/curriculum/tracks/ma-integration/16-1' },
            { id: '16-2', name: '16.2 Platform Merge Economics', topics: 'Dual-Stack Costs, Migration Timelines, Consolidation Savings Projections', href: '/vault/curriculum/tracks/ma-integration/16-2' },
            { id: '16-3', name: '16.3 Team Integration Without Attrition', topics: 'Culture Bridge Protocol, Retention Bonuses, Identity Preservation', href: '/vault/curriculum/tracks/ma-integration/16-3' },
            { id: '16-4', name: '16.4 Data & API Consolidation', topics: 'Schema Merge Costs, API Unification Strategy, Customer Migration Planning', href: '/vault/curriculum/tracks/ma-integration/16-4' },
            { id: '16-5', name: '16.5 Synergy Realization Tracking', topics: 'Synergy Timelines, Cost Savings Verification, Value Capture Dashboards', href: '/vault/curriculum/tracks/ma-integration/16-5' },
            { id: '16-6', name: '16.6 Post-Merger Architecture Decisions', topics: 'Best-of-Both Selection, Architecture Governance, Technical Debt Inheritance', href: '/vault/curriculum/tracks/ma-integration/16-6' },
            { id: '16-7', name: '16.7 Integration Governance & Reporting', topics: 'PMO Economics, Status Reporting, Board Integration Updates', href: '/vault/curriculum/tracks/ma-integration/16-7' },
            { id: '16-8', name: '16.8 Customer Impact Management', topics: 'Migration Communication, Feature Parity SLAs, Churn Prevention During Integration', href: '/vault/curriculum/tracks/ma-integration/16-8' },
            { id: '16-9', name: '16.9 Multi-Acquisition Portfolio Management', topics: 'Serial Acquisition Playbooks, Platform-First Strategy, Integration Velocity', href: '/vault/curriculum/tracks/ma-integration/16-9' },
            { id: '16-10', name: '16.10 Integration Post-Mortem & ROI Report', topics: 'Actual vs Projected Synergies, Lessons Learned, Board Accountability', href: '/vault/curriculum/tracks/ma-integration/16-10' },
        ],
        color: 'slate',
        icon: '🏗️',
        glossaryTerms: ['ev-se', 'product-debt-index', 'vc-due-diligence', 'capex-vs-opex'],
        tools: [{ name: 'EV-SE Calculator', href: '/tools/ev-se' }],
    },
    {
        title: 'The Economics of Developer Experience (DX)',
        subtitle: 'Track 17 — NEW',
        description: 'Developer experience is the hidden infrastructure tax or accelerator in every engineering organization. This track teaches you to measure, invest in, and monetize DX improvements with the same rigor as any capital investment.',
        modules: [
            { id: '17-1', name: '17.1 Developer Productivity as Economic Output', topics: 'DORA Metrics ROI, Flow State Economics, Interruption Cost Analysis', href: '/vault/curriculum/tracks/dx-economics/17-1' },
            { id: '17-2', name: '17.2 Tooling Investment ROI', topics: 'Build Time vs Revenue, IDE/CI ROI, Dev Environment Cost-Benefit', href: '/vault/curriculum/tracks/dx-economics/17-2' },
            { id: '17-3', name: '17.3 Onboarding Speed as Revenue Driver', topics: 'Time-to-First-Commit, New Hire Ramp Costs, Self-Service Environments', href: '/vault/curriculum/tracks/dx-economics/17-3' },
            { id: '17-4', name: '17.4 Platform Engineering Economics', topics: 'Internal Platform ROI, Self-Service Infrastructure, Golden Path Economics', href: '/vault/curriculum/tracks/dx-economics/17-4' },
            { id: '17-5', name: '17.5 CI/CD Pipeline Optimization', topics: 'Build Time Compound Costs, Pipeline Reliability ROI, Deployment Frequency Value', href: '/vault/curriculum/tracks/dx-economics/17-5' },
            { id: '17-6', name: '17.6 Documentation as Infrastructure', topics: 'Search vs Ask ROI, Knowledge Base Economics, Documentation Debt', href: '/vault/curriculum/tracks/dx-economics/17-6' },
            { id: '17-7', name: '17.7 Developer Satisfaction & Retention', topics: 'DX NPS, Friction-to-Attrition Pipeline, Joy as Retention Strategy', href: '/vault/curriculum/tracks/dx-economics/17-7' },
            { id: '17-8', name: '17.8 Inner Source & Code Reuse Economics', topics: 'Duplication Costs, Shared Library ROI, Inner Source Governance', href: '/vault/curriculum/tracks/dx-economics/17-8' },
            { id: '17-9', name: '17.9 AI-Augmented Development Economics', topics: 'Copilot ROI, AI Code Review, Automation vs Quality Trade-offs', href: '/vault/curriculum/tracks/dx-economics/17-9' },
            { id: '17-10', name: '17.10 DX Investment Prioritization Framework', topics: 'DX Scorecard, Budget Allocation, DX Roadmap Economics', href: '/vault/curriculum/tracks/dx-economics/17-10' },
        ],
        color: 'cyan',
        icon: '⚡',
        glossaryTerms: ['developer-experience', 'dora-metrics', 'aper', 'product-debt-index'],
        tools: [{ name: 'APER Calculator', href: '/tools/aper' }, { name: 'PDI Calculator', href: '/tools/pdi' }],
    },
    {
        title: 'Vendor & Contract Economics for Engineering Leaders',
        subtitle: 'Track 18 — NEW',
        description: 'Engineering leaders manage millions in vendor relationships but are never taught contract economics. This track teaches you to negotiate, optimize, and govern vendor spend with the same rigor you apply to your codebase.',
        modules: [
            { id: '18-1', name: '18.1 SaaS Sprawl Cost Analysis', topics: 'Shadow IT Quantification, License Waste, Overlapping Tool Audit', href: '/vault/curriculum/tracks/vendor-economics/18-1' },
            { id: '18-2', name: '18.2 Vendor Consolidation ROI', topics: 'Platform vs Best-of-Breed, Consolidation Savings, Migration Costs', href: '/vault/curriculum/tracks/vendor-economics/18-2' },
            { id: '18-3', name: '18.3 Contract Negotiation Economics', topics: 'Leverage Point Analysis, Quarter-End Timing, Competitive Positioning', href: '/vault/curriculum/tracks/vendor-economics/18-3' },
            { id: '18-4', name: '18.4 Cloud Commitment Strategy', topics: 'Reserved vs On-Demand, Savings Plan Economics, Commitment Risk Analysis', href: '/vault/curriculum/tracks/vendor-economics/18-4' },
            { id: '18-5', name: '18.5 Renewal vs Replacement Analysis', topics: 'Switching Cost Calculation, Feature Parity Assessment, Total Migration TCO', href: '/vault/curriculum/tracks/vendor-economics/18-5' },
            { id: '18-6', name: '18.6 Procurement Process Optimization', topics: 'Procurement Cycle Time, Legal Review Bottlenecks, Security Assessment Costs', href: '/vault/curriculum/tracks/vendor-economics/18-6' },
            { id: '18-7', name: '18.7 Enterprise License Agreement (ELA) Economics', topics: 'True-Up Risk, Shelfware Analysis, ELA vs À La Carte Comparison', href: '/vault/curriculum/tracks/vendor-economics/18-7' },
            { id: '18-8', name: '18.8 Vendor Risk & Dependency Management', topics: 'Single-Vendor Exposure, Vendor Viability Assessment, Exit Planning', href: '/vault/curriculum/tracks/vendor-economics/18-8' },
            { id: '18-9', name: '18.9 Open Source vs Commercial: The Complete TCO', topics: 'Free ≠ Free, Support Costs, Compliance Overhead, Community Risk', href: '/vault/curriculum/tracks/vendor-economics/18-9' },
            { id: '18-10', name: '18.10 Vendor Spend Dashboard & Governance', topics: 'Spend Visibility, ROI Tracking, Annual Review Cadence, Board Reporting', href: '/vault/curriculum/tracks/vendor-economics/18-10' },
        ],
        color: 'rose',
        icon: '📋',
        glossaryTerms: ['capex-vs-opex', 'vendor-lock-in', 'total-cost-of-ownership', 'saas-cogs'],
        tools: [{ name: 'Cloud FinOps Calculator', href: '/tools/cloud-finops-calculator' }],
    },
    {
        title: 'AI Agent Architecture & Economics',
        subtitle: 'Track 19 — AI Agents',
        description: 'AI agents are the next compute paradigm. This track teaches you to design, cost, and govern multi-agent systems — from single-tool agents to enterprise orchestration platforms. Inspired by real-world agent infrastructure like Exogram.',
        modules: [
            { id: '19-1', name: '19.1 What Is an AI Agent? Economic Primitives', topics: 'Agent vs Chatbot, Autonomy Spectrum, Cost-Per-Action, Agent ROI Framework', href: '/vault/curriculum/tracks/ai-agent-architecture/19-1' },
            { id: '19-2', name: '19.2 Agent Architecture Patterns & Costs', topics: 'ReAct, Plan-and-Execute, Tool-Use, Multi-Agent, Architecture Selection Economics', href: '/vault/curriculum/tracks/ai-agent-architecture/19-2' },
            { id: '19-3', name: '19.3 Tool-Use & Function Calling Economics', topics: 'API Call Costs, Tool Invocation Latency, MCP Protocol Economics, Error Recovery Costs', href: '/vault/curriculum/tracks/ai-agent-architecture/19-3' },
            { id: '19-4', name: '19.4 Memory & Context Management Costs', topics: 'Short-Term vs Long-Term Memory, Vector Store Costs, Context Window Economics, Exogram-Style Verification', href: '/vault/curriculum/tracks/ai-agent-architecture/19-4' },
            { id: '19-5', name: '19.5 Multi-Agent Orchestration Economics', topics: 'Agent-to-Agent Communication, Coordination Overhead, Consensus Costs, Swarm Architecture', href: '/vault/curriculum/tracks/ai-agent-architecture/19-5' },
            { id: '19-6', name: '19.6 Agent Inference Cost Optimization', topics: 'Model Routing for Agents, Tiered Reasoning, Cached Tool Responses, Batch vs Real-Time', href: '/vault/curriculum/tracks/ai-agent-architecture/19-6' },
            { id: '19-7', name: '19.7 Agent Reliability & Error Economics', topics: 'Hallucination Costs in Agents, Retry Economics, Guardrail Overhead, Human-in-the-Loop Costs', href: '/vault/curriculum/tracks/ai-agent-architecture/19-7' },
            { id: '19-8', name: '19.8 Agent Observability & Monitoring', topics: 'Trace Costs, Agent Analytics, Performance Dashboards, Anomaly Detection Economics', href: '/vault/curriculum/tracks/ai-agent-architecture/19-8' },
            { id: '19-9', name: '19.9 Agent Infrastructure at Scale', topics: 'Kubernetes for Agents, Serverless Agent Hosting, Queue Architecture, Scaling Patterns', href: '/vault/curriculum/tracks/ai-agent-architecture/19-9' },
            { id: '19-10', name: '19.10 Agent Security & Sandboxing Economics', topics: 'Code Execution Sandboxes, Permission Models, Prompt Injection Defense, Audit Logging', href: '/vault/curriculum/tracks/ai-agent-architecture/19-10' },
            { id: '19-11', name: '19.11 Agent Testing & Evaluation Frameworks', topics: 'Agent Benchmarking, Task Completion Rates, Regression Testing Costs, Eval Infrastructure', href: '/vault/curriculum/tracks/ai-agent-architecture/19-11' },
            { id: '19-12', name: '19.12 Agent Marketplace & Monetization', topics: 'Agent-as-a-Service Pricing, Usage-Based Models, Agent Marketplace Economics, Developer Ecosystems', href: '/vault/curriculum/tracks/ai-agent-architecture/19-12' },
            { id: '19-13', name: '19.13 Autonomous Agent Risk Management', topics: 'Autonomy Boundaries, Kill Switches, Escalation Protocols, Liability Frameworks', href: '/vault/curriculum/tracks/ai-agent-architecture/19-13' },
            { id: '19-14', name: '19.14 Agent Build vs Buy: The Complete TCO', topics: 'Custom vs Platform Agents, LangChain vs CrewAI vs Custom, Integration Complexity', href: '/vault/curriculum/tracks/ai-agent-architecture/19-14' },
            { id: '19-15', name: '19.15 Agent Architecture Synthesis & Board Presentation', topics: 'Complete Agent Economic Model, Investment Proposal, 3-Year Agent Strategy', href: '/vault/curriculum/tracks/ai-agent-architecture/19-15' },
        ],
        color: 'violet',
        icon: '🤖',
        glossaryTerms: ['agentic-workflow', 'ai-inference', 'ai-cogs', 'orchestration-debt', 'guardrails', 'rag', 'token-ai', 'mcp-protocol'],
        tools: [{ name: 'AUEB Calculator', href: '/tools/aueb' }, { name: 'AI Scoring', href: '/tools/scoring' }],
    },
    {
        title: 'Agentic Process Automation Economics',
        subtitle: 'Track 20 — AI Agents',
        description: 'Beyond RPA: agentic process automation replaces entire workflows, not just clicks. This track teaches you to identify, cost, and implement AI agent automation across enterprise operations — from customer support to DevOps to finance.',
        modules: [
            { id: '20-1', name: '20.1 From RPA to Agentic Automation', topics: 'RPA Limitations, Agentic Leap, Intelligence vs Scripting, Market Size & Opportunity', href: '/vault/curriculum/tracks/agentic-automation/20-1' },
            { id: '20-2', name: '20.2 Process Discovery for Agent Automation', topics: 'Workflow Mapping, Automation Candidate Scoring, Complexity vs Value Matrix', href: '/vault/curriculum/tracks/agentic-automation/20-2' },
            { id: '20-3', name: '20.3 FTE Displacement Economics', topics: 'Cost-Per-Task vs Cost-Per-FTE, Partial Automation ROI, Human+Agent Hybrid Models', href: '/vault/curriculum/tracks/agentic-automation/20-3' },
            { id: '20-4', name: '20.4 Customer Support Agent Economics', topics: 'Ticket Resolution Costs, First-Contact Resolution Rates, Escalation Economics, CSAT Impact', href: '/vault/curriculum/tracks/agentic-automation/20-4' },
            { id: '20-5', name: '20.5 DevOps & SRE Agent Automation', topics: 'Incident Response Agents, Auto-Remediation ROI, Alert Fatigue Reduction, MTTR Impact', href: '/vault/curriculum/tracks/agentic-automation/20-5' },
            { id: '20-6', name: '20.6 Sales & Revenue Agent Economics', topics: 'Lead Qualification Agents, Pipeline Automation, SDR Augmentation, Revenue Attribution', href: '/vault/curriculum/tracks/agentic-automation/20-6' },
            { id: '20-7', name: '20.7 Finance & Compliance Agent Automation', topics: 'Invoice Processing Agents, Audit Automation, Regulatory Reporting, Risk Scoring', href: '/vault/curriculum/tracks/agentic-automation/20-7' },
            { id: '20-8', name: '20.8 Code Generation & Review Agents', topics: 'Copilot Economics, Automated Code Review, PR Automation, Quality Gate Agents', href: '/vault/curriculum/tracks/agentic-automation/20-8' },
            { id: '20-9', name: '20.9 Agent Orchestration Platforms', topics: 'Enterprise Agent Platforms, Workflow Engines, Integration Patterns, Platform Selection', href: '/vault/curriculum/tracks/agentic-automation/20-9' },
            { id: '20-10', name: '20.10 Change Management for Agent Adoption', topics: 'Workforce Impact, Reskilling Economics, Union Considerations, Communication Strategy', href: '/vault/curriculum/tracks/agentic-automation/20-10' },
            { id: '20-11', name: '20.11 Agent Performance SLAs & Contracts', topics: 'Service Level Definitions, Performance Baseline, Penalty Structures, Vendor Benchmarks', href: '/vault/curriculum/tracks/agentic-automation/20-11' },
            { id: '20-12', name: '20.12 Agent Failure Modes & Recovery', topics: 'Cascading Failures, Graceful Degradation, Fallback to Human, Business Continuity', href: '/vault/curriculum/tracks/agentic-automation/20-12' },
            { id: '20-13', name: '20.13 Measuring Agent ROI at Scale', topics: 'Enterprise Agent KPIs, Portfolio View, Quarterly Business Reviews, Board Reporting', href: '/vault/curriculum/tracks/agentic-automation/20-13' },
            { id: '20-14', name: '20.14 Competitive Strategy with Agent Automation', topics: 'Agent-First Companies, Speed Advantage, Cost Structure Disruption, Market Positioning', href: '/vault/curriculum/tracks/agentic-automation/20-14' },
            { id: '20-15', name: '20.15 Agentic Automation Synthesis', topics: 'Complete Automation Business Case, Roadmap Design, Investment Proposal, Board Deck', href: '/vault/curriculum/tracks/agentic-automation/20-15' },
        ],
        color: 'cyan',
        icon: '⚙️',
        glossaryTerms: ['agentic-workflow', 'ai-cogs', 'ai-inference', 'cost-of-predictivity', 'fte-displacement', 'orchestration-debt'],
        tools: [{ name: 'FTE Displacement Calculator', href: '/tools/fte-displacement' }, { name: 'AUEB Calculator', href: '/tools/aueb' }],
    },
    {
        title: 'AI Agent Governance & Trust Infrastructure',
        subtitle: 'Track 21 — AI Agents',
        description: 'Autonomous agents acting on behalf of your organization create unprecedented governance challenges. This track teaches you to build the trust, verification, and compliance infrastructure that makes enterprise agent deployment possible. Inspired by Exogram\'s verification architecture.',
        modules: [
            { id: '21-1', name: '21.1 The Trust Problem in Autonomous AI', topics: 'Why AI Fails at Trust, Verification vs Validation, Exogram\'s Truth Layer Paradigm', href: '/vault/curriculum/tracks/agent-governance/21-1' },
            { id: '21-2', name: '21.2 Agent Permission & Access Control Economics', topics: 'Least-Privilege for Agents, Scope Creep Costs, Dynamic Permission Models, Audit Trails', href: '/vault/curriculum/tracks/agent-governance/21-2' },
            { id: '21-3', name: '21.3 Agent Audit & Compliance Frameworks', topics: 'SOC 2 for Agents, EU AI Act (Article 14), Agent Decision Logging, Regulatory Readiness', href: '/vault/curriculum/tracks/agent-governance/21-3' },
            { id: '21-4', name: '21.4 Hallucination Detection & Verification Economics', topics: 'Factual Grounding Costs, Citation Verification, Knowledge Graph Integration, Exogram Approach', href: '/vault/curriculum/tracks/agent-governance/21-4' },
            { id: '21-5', name: '21.5 Agent Output Verification Infrastructure', topics: 'Verification Pipelines, Confidence Scoring, Human Review Triggers, Quality Gates', href: '/vault/curriculum/tracks/agent-governance/21-5' },
            { id: '21-6', name: '21.6 Data Provenance & Lineage for Agents', topics: 'Source Attribution, Data Freshness Economics, Knowledge Cutoff Management, RAG Verification', href: '/vault/curriculum/tracks/agent-governance/21-6' },
            { id: '21-7', name: '21.7 Prompt Injection & Security Economics', topics: 'Attack Surface Analysis, Defense-in-Depth Costs, Red Teaming Budgets, Incident Response', href: '/vault/curriculum/tracks/agent-governance/21-7' },
            { id: '21-8', name: '21.8 Multi-Stakeholder Agent Governance', topics: 'Cross-Functional Governance Boards, RACI for Agents, Stakeholder Alignment Costs', href: '/vault/curriculum/tracks/agent-governance/21-8' },
            { id: '21-9', name: '21.9 Agent Ethics & Bias Economics', topics: 'Bias Detection Costs, Fairness Metrics, Ethical Review Boards, Reputational Risk', href: '/vault/curriculum/tracks/agent-governance/21-9' },
            { id: '21-10', name: '21.10 Insurance & Liability for AI Agents', topics: 'AI Insurance Products, Liability Allocation, Contractual Protections, Risk Quantification', href: '/vault/curriculum/tracks/agent-governance/21-10' },
            { id: '21-11', name: '21.11 Agent Versioning & Rollback Economics', topics: 'Model Version Control, A/B Testing Agents, Canary Deployments, Rollback Costs', href: '/vault/curriculum/tracks/agent-governance/21-11' },
            { id: '21-12', name: '21.12 Enterprise Agent Policy Engines', topics: 'Policy-as-Code, Guardrail Frameworks, Compliance Automation, Governance Platforms', href: '/vault/curriculum/tracks/agent-governance/21-12' },
            { id: '21-13', name: '21.13 Agent Incident Response & Forensics', topics: 'Agent Failure Investigation, Root Cause Analysis, Post-Mortem Templates, Regulatory Reporting', href: '/vault/curriculum/tracks/agent-governance/21-13' },
            { id: '21-14', name: '21.14 Building an Agent Center of Excellence', topics: 'CoE Structure, Staffing Economics, Capability Maturity Model, Knowledge Sharing', href: '/vault/curriculum/tracks/agent-governance/21-14' },
            { id: '21-15', name: '21.15 Agent Governance Synthesis & Board Strategy', topics: 'Complete Governance Framework, Risk Dashboard, Board Presentation, Maturity Roadmap', href: '/vault/curriculum/tracks/agent-governance/21-15' },
        ],
        color: 'emerald',
        icon: '🛡️',
        glossaryTerms: ['guardrails', 'agentic-workflow', 'ai-inference', 'orchestration-debt', 'rag', 'prompt-injection'],
        tools: [{ name: 'AI Scoring', href: '/tools/scoring' }, { name: 'Shadow AI Scanner', href: '/tools/shadow-ai' }],
    },
    {
        title: 'Strategic Leadership Economics',
        subtitle: 'Track 22 — Leadership',
        description: 'Leadership is the awesome responsibility to see those around us rise. Most of us achieved our rank because we were good at our old job — but that\'s not our job anymore. This track teaches the economics of becoming a leader who multiplies value, not just manages resources.',
        modules: [
            { id: '22-1', name: '22.1 The Leadership Multiplier Effect', topics: 'IC Output vs Leader Output, Leverage Economics, Value Multiplication Framework', href: '/vault/curriculum/tracks/strategic-leadership/22-1' },
            { id: '22-2', name: '22.2 From Technical Expert to Strategic Leader', topics: 'The Identity Shift, Letting Go of the Keyboard, Strategic Thinking Economics', href: '/vault/curriculum/tracks/strategic-leadership/22-2' },
            { id: '22-3', name: '22.3 Building & Leading High-Performance Teams', topics: 'Team Composition Economics, Cognitive Diversity Premium, Psychological Safety ROI', href: '/vault/curriculum/tracks/strategic-leadership/22-3' },
            { id: '22-4', name: '22.4 The Economics of Trust & Delegation', topics: 'Trust Building Costs, Delegation ROI, Micromanagement Tax, Autonomy Premium', href: '/vault/curriculum/tracks/strategic-leadership/22-4' },
            { id: '22-5', name: '22.5 Strategic Communication & Influence', topics: 'Stakeholder Mapping, Executive Presence ROI, Story-Based Decision Making, Narrative Economics', href: '/vault/curriculum/tracks/strategic-leadership/22-5' },
            { id: '22-6', name: '22.6 Coaching & Development Economics', topics: '1:1 ROI, Coaching Frameworks, Skill Development Investment, Succession Pipeline', href: '/vault/curriculum/tracks/strategic-leadership/22-6' },
            { id: '22-7', name: '22.7 Conflict Resolution & Alignment Economics', topics: 'Conflict Cost Calculator, Alignment Tax, Cross-Functional Friction, Resolution ROI', href: '/vault/curriculum/tracks/strategic-leadership/22-7' },
            { id: '22-8', name: '22.8 Change Leadership Economics', topics: 'Transformation Costs, Resistance Economics, Adoption Curves, Leading Through Ambiguity', href: '/vault/curriculum/tracks/strategic-leadership/22-8' },
            { id: '22-9', name: '22.9 Culture as Capital Asset', topics: 'Culture ROI, Values-Aligned Hiring Premium, Cultural Debt, Rebuilding After Layoffs', href: '/vault/curriculum/tracks/strategic-leadership/22-9' },
            { id: '22-10', name: '22.10 Decision Architecture for Leaders', topics: 'Decision Velocity, Reversible vs Irreversible, Consensus Costs, Disagree-and-Commit', href: '/vault/curriculum/tracks/strategic-leadership/22-10' },
            { id: '22-11', name: '22.11 Leading Remote & Distributed Organizations', topics: 'Remote Leadership Premium, Async Leadership, Distributed Decision Making', href: '/vault/curriculum/tracks/strategic-leadership/22-11' },
            { id: '22-12', name: '22.12 Innovation Leadership Economics', topics: 'Innovation Budget Allocation, Two-Pizza Teams, Hackathon ROI, Intrapreneurship', href: '/vault/curriculum/tracks/strategic-leadership/22-12' },
            { id: '22-13', name: '22.13 Crisis Leadership & Resilience', topics: 'Crisis Response Economics, Incident Command, Communication Under Pressure, Recovery Costs', href: '/vault/curriculum/tracks/strategic-leadership/22-13' },
            { id: '22-14', name: '22.14 Ethical Leadership & Governance', topics: 'Ethics ROI, Governance Structures, Board Responsibility, Long-Term Trust Building', href: '/vault/curriculum/tracks/strategic-leadership/22-14' },
            { id: '22-15', name: '22.15 Leadership Capital Synthesis', topics: 'Your Leadership P&L, Development Roadmap, 360 Assessment, Personal Board of Advisors', href: '/vault/curriculum/tracks/strategic-leadership/22-15' },
        ],
        color: 'amber',
        icon: '🏛️',
        glossaryTerms: ['span-of-control', 'conways-law', 'attrition-rate', 'cost-per-hire', 'developer-experience'],
        tools: [{ name: 'APER Calculator', href: '/tools/aper' }, { name: 'Career Pathing', href: '/tools/career-pathing' }],
    },
    {
        title: 'Executive Presence & Board Leadership',
        subtitle: 'Track 23 — Leadership',
        description: 'The final frontier: translating technical excellence into boardroom authority. This track teaches senior leaders and aspiring C-suite executives to command rooms, govern budgets, and drive organizational strategy with economic precision.',
        modules: [
            { id: '23-1', name: '23.1 Executive Presence as Economic Asset', topics: 'Presence Premium, Authority Economics, Credibility Capital, First Impressions ROI', href: '/vault/curriculum/tracks/executive-presence/23-1' },
            { id: '23-2', name: '23.2 Board Communication Mastery', topics: 'Board Slide Economics, Data Storytelling, 4-Quadrant Framework, Question Navigation', href: '/vault/curriculum/tracks/executive-presence/23-2' },
            { id: '23-3', name: '23.3 P&L Ownership for Technical Leaders', topics: 'Revenue Responsibility, Cost Center to Profit Center, Budget Defense, Margin Accountability', href: '/vault/curriculum/tracks/executive-presence/23-3' },
            { id: '23-4', name: '23.4 Investor Relations for CTOs', topics: 'Earnings Call Preparation, Technical Due Diligence, IR Strategy, Analyst Relations', href: '/vault/curriculum/tracks/executive-presence/23-4' },
            { id: '23-5', name: '23.5 Strategic Planning & OKR Economics', topics: 'Annual Planning Cycles, OKR Cascade Design, Strategy-to-Execution Translation', href: '/vault/curriculum/tracks/executive-presence/23-5' },
            { id: '23-6', name: '23.6 Cross-Functional Executive Alignment', topics: 'CTO-CFO Bridge, Engineering-Sales Alignment, Product-Engineering Governance', href: '/vault/curriculum/tracks/executive-presence/23-6' },
            { id: '23-7', name: '23.7 Executive Negotiation & Deal Economics', topics: 'High-Stakes Negotiation, M&A Leadership, Partnership Economics, Vendor C-Suite Engagement', href: '/vault/curriculum/tracks/executive-presence/23-7' },
            { id: '23-8', name: '23.8 Organizational Restructuring Economics', topics: 'Reorg ROI, Layoff Economics, Rebuilding Morale, Restructuring Communication', href: '/vault/curriculum/tracks/executive-presence/23-8' },
            { id: '23-9', name: '23.9 Executive Coaching & Peer Networks', topics: 'Executive Coach ROI, Peer Advisory Boards, Mastermind Economics, Network Capital', href: '/vault/curriculum/tracks/executive-presence/23-9' },
            { id: '23-10', name: '23.10 Public Speaking & Thought Leadership', topics: 'Conference ROI, Publishing Strategy, Media Training, Brand Value Economics', href: '/vault/curriculum/tracks/executive-presence/23-10' },
            { id: '23-11', name: '23.11 AI Strategy at the Board Level', topics: 'Board AI Literacy, AI Investment Governance, Risk Oversight, Innovation Committees', href: '/vault/curriculum/tracks/executive-presence/23-11' },
            { id: '23-12', name: '23.12 Succession Planning Economics', topics: 'Leadership Pipeline ROI, Key-Person Risk Mitigation, Talent Reviews, Development Budgets', href: '/vault/curriculum/tracks/executive-presence/23-12' },
            { id: '23-13', name: '23.13 Board Governance & Fiduciary Economics', topics: 'Board Composition, Committee Structures, Fiduciary Duty, Director Economics', href: '/vault/curriculum/tracks/executive-presence/23-13' },
            { id: '23-14', name: '23.14 Global Leadership & Scale', topics: 'International Expansion, Cross-Cultural Leadership, Global Team Economics, Regulatory Navigation', href: '/vault/curriculum/tracks/executive-presence/23-14' },
            { id: '23-15', name: '23.15 Executive Leadership Synthesis', topics: 'Your Executive Dashboard, Legacy Planning, Long-Term Capital Strategy, Board-Ready Portfolio', href: '/vault/curriculum/tracks/executive-presence/23-15' },
        ],
        color: 'indigo',
        icon: '👔',
        glossaryTerms: ['capex-vs-opex', 'ev-se', 'product-debt-index', 'vc-due-diligence', 'arr', 'saas-valuation'],
        tools: [{ name: 'EV-SE Calculator', href: '/tools/ev-se' }, { name: 'Board Room', href: '/tools/board-room' }],
    },
];