export const tracks = [
    {
        title: 'Engineering Economics Foundations',
        subtitle: 'Track 1 — Foundations',
        description: 'The core curriculum for understanding engineering as an economic activity. From basic metrics to advanced budgeting and organizational design.',
        modules: [
            { id: '1-1', name: '1.1 Engineering Productivity Metrics', topics: 'DORA Metrics, APER, Feature Velocity, Board-Ready Reporting', href: '/vault/curriculum/tracks/engineering-economics/1-1' },
            { id: '1-2', name: '1.2 Technical Debt Classification', topics: 'Code Debt, Architecture Debt, Infrastructure Debt, PDI Framework', href: '/vault/curriculum/tracks/engineering-economics/1-2' },
            { id: '1-3', name: '1.3 Cost of Delay & Prioritization', topics: 'Cost of Delay, WSJF, Debt Interest Rates, Executive Framing', href: '/vault/curriculum/tracks/engineering-economics/1-3' },
            { id: '1-4', name: '1.4 Team Topology & Conway\'s Law', topics: 'Conway\'s Law, Four Team Topologies, Cognitive Load, Coordination Tax', href: '/vault/curriculum/tracks/engineering-economics/1-4' },
            { id: '1-5', name: '1.5 Build vs Buy Economics', topics: 'TCO Analysis, Integration Debt, Vendor Lock-In, Differentiation Test', href: '/vault/curriculum/tracks/engineering-economics/1-5' },
            { id: '1-6', name: '1.6 Engineering Budget & Capex/Opex', topics: 'Budget Anatomy, Software Capitalization, R&D Tax Credits', href: '/vault/curriculum/tracks/engineering-economics/1-6' },
            { id: '1-7', name: '1.7 Platform Engineering Economics', topics: 'IDP ROI, Golden Path Economics, Developer Experience Metrics', href: '/vault/curriculum/tracks/engineering-economics/1-7' },
            { id: '1-8', name: '1.8 Engineering Hiring Economics', topics: 'Cost-per-Hire, Mis-Hire Impact, Retention ROI', href: '/vault/curriculum/tracks/engineering-economics/1-8' },
            { id: '1-9', name: '1.9 Outsourcing & Contractor Economics', topics: 'Blended Rates, Knowledge Retention, Offshore Cost Analysis', href: '/vault/curriculum/tracks/engineering-economics/1-9' },
            { id: '1-10', name: '1.10 Engineering Organization Design', topics: 'Team Sizing, Span of Control, IC vs Management Tracks', href: '/vault/curriculum/tracks/engineering-economics/1-10' },
            { id: '1-11', name: '1.11 Technical Debt Quantification', topics: 'PDI Methodology, Dollar Conversion, CFO Communication', href: '/vault/curriculum/tracks/engineering-economics/1-11' },
            { id: '1-12', name: '1.12 Engineering Benchmarking', topics: 'R&D Spend Benchmarks, Stage-Based APER, Performance Metrics', href: '/vault/curriculum/tracks/engineering-economics/1-12' },
            { id: '1-13', name: '1.13 Engineering Budget Planning', topics: 'Zero-Based Budgeting, Headcount Modeling, Contingency Planning', href: '/vault/curriculum/tracks/engineering-economics/1-13' },
            { id: '1-14', name: '1.14 M&A Engineering Integration', topics: 'Day 1-100 Playbook, Talent Retention, Tech Stack Consolidation', href: '/vault/curriculum/tracks/engineering-economics/1-14' },
            { id: '1-15', name: '1.15 Engineering Economics Synthesis', topics: 'Complete Economic Model, Dashboard Design, Quarterly Reporting', href: '/vault/curriculum/tracks/engineering-economics/1-15' },
            { id: '1-16', name: '1.16 Governing Vibe Coding & AI-Assisted Output', topics: 'Vibe Coding Debt, Copilot ROI, Validation', href: '/vault/curriculum/tracks/engineering-economics/1-16' },
        ],
        color: 'cyan',
        icon: '📊',
        glossaryTerms: ['technical-debt', 'dora-metrics', 'innovation-tax', 'technical-insolvency-date', 'maintenance-load', 'conways-law', 'cost-of-delay', 'developer-experience', 'architecture-review-board'],
        tools: [{ name: 'PDI Calculator', href: '/tools/pdi' }, { name: 'APER Calculator', href: '/tools/aper' }],
    },
    {
        title: 'AI Product Economics',
        subtitle: 'Track 2 — AI-First (Flagship)',
        description: 'Your most differentiated track. AI unit economics, inference costs, margin collapse — maps directly to CIO.com and Built In articles. AI cost management is the #1 FinOps priority in 2026.',
        modules: [
            { id: '2-1', name: '2.1 AI COGS Analysis', topics: 'AI COGS Equation, Token Economics, API Pricing Architecture', href: '/vault/curriculum/tracks/ai-product-economics/2-1' },
            { id: '2-2', name: '2.2 Model Selection & Optimization', topics: 'Model Tiers, Routing Architecture, Fine-Tuning ROI, Distillation', href: '/vault/curriculum/tracks/ai-product-economics/2-2' },
            { id: '2-3', name: '2.3 AI Feature Profitability', topics: 'Feature-Level P&L, Per-User Economics, The 10x Rule', href: '/vault/curriculum/tracks/ai-product-economics/2-3' },
            { id: '2-4', name: '2.4 RAG Architecture Economics', topics: 'Embedding Costs, Vector DB Pricing, Chunking, Caching & Reranking', href: '/vault/curriculum/tracks/ai-product-economics/2-4' },
            { id: '2-5', name: '2.5 AI Governance & Safety Costs', topics: 'Guardrail Tax, Red Teaming, Bias Testing, EU AI Act Compliance', href: '/vault/curriculum/tracks/ai-product-economics/2-5' },
            { id: '2-6', name: '2.6 AI Product Pricing Strategy', topics: 'Value-Based Pricing, AI Credits, Pricing Experiments', href: '/vault/curriculum/tracks/ai-product-economics/2-6' },
            { id: '2-7', name: '2.7 AI Build vs Buy Decisions', topics: 'API vs Custom Model, Open Source vs Proprietary, Self-Host TCO', href: '/vault/curriculum/tracks/ai-product-economics/2-7' },
            { id: '2-8', name: '2.8 RAG System Economics', topics: 'Embedding Costs, Retrieval Costs, Context Window Optimization', href: '/vault/curriculum/tracks/ai-product-economics/2-8' },
            { id: '2-9', name: '2.9 AI Feature Profitability Analysis', topics: 'Feature-Level P&L, Revenue Attribution, Sunset Decisions', href: '/vault/curriculum/tracks/ai-product-economics/2-9' },
            { id: '2-10', name: '2.10 GPU Infrastructure Economics', topics: 'GPU Pricing, Spot vs Reserved, Inference Batch Optimization', href: '/vault/curriculum/tracks/ai-product-economics/2-10' },
            { id: '2-11', name: '2.11 AI Compliance & Risk Costs', topics: 'EU AI Act, Model Auditing, Bias Testing Budgets', href: '/vault/curriculum/tracks/ai-product-economics/2-11' },
            { id: '2-12', name: '2.12 AI Team Composition', topics: 'ML Engineer Costs, Data Scientists, Prompt Engineers, AI PMs', href: '/vault/curriculum/tracks/ai-product-economics/2-12' },
            { id: '2-13', name: '2.13 AI Product Lifecycle', topics: 'Prototype to Production 10x Cost, Scaling Patterns', href: '/vault/curriculum/tracks/ai-product-economics/2-13' },
            { id: '2-14', name: '2.14 AI Marketplace Strategy', topics: 'API Monetization, Model-as-a-Service, Developer Ecosystems', href: '/vault/curriculum/tracks/ai-product-economics/2-14' },
            { id: '2-15', name: '2.15 AI Economics Synthesis', topics: 'Complete AI Economic Model, Portfolio Analysis, Board Reporting', href: '/vault/curriculum/tracks/ai-product-economics/2-15' },
            { id: '2-16', name: '2.16 ROAI and AI Unit Economics', topics: 'Cost of Predictivity, ROAI Calculation, AUEB Ratio', href: '/vault/curriculum/tracks/ai-product-economics/2-16' },
        ],
        color: 'violet',
        icon: '🤖',
        glossaryTerms: ['ai-cogs', 'cost-of-predictivity', 'orchestration-debt', 'ai-inference', 'rag', 'token-ai', 'guardrails', 'large-language-model', 'small-language-models', 'open-weights', 'agentic-workflow', 'ai-assisted-development'],
        tools: [{ name: 'AUEB Calculator', href: '/tools/aueb' }, { name: 'AI Scoring', href: '/tools/scoring' }],
    },
    {
        title: 'R&D Capital Management',
        subtitle: 'Track 3 — Executive',
        description: 'The executive track: managing engineering investment as a financial asset. For CTOs, PE partners, and board members. Includes engineering leadership, executive alignment, and board governance.',
        modules: [
            { id: '3-1', name: '3.1 R&D Capital Audit Methodology', topics: 'Discovery Phase, Technical Assessment, Economic Modeling', href: '/vault/curriculum/tracks/rd-capital-management/3-1' },
            { id: '3-2', name: '3.2 PE Due Diligence for Technology', topics: 'Technology Asset Valuation, Team Assessment, Debt as Deal Currency', href: '/vault/curriculum/tracks/rd-capital-management/3-2' },
            { id: '3-3', name: '3.3 Board Reporting & Executive Communication', topics: '4-Quadrant Board Slide, KPI Dashboards, Investment Proposals', href: '/vault/curriculum/tracks/rd-capital-management/3-3' },
            { id: '3-4', name: '3.4 M&A Technical Assessment', topics: 'Pre-Close Assessment, Integration Costs, Technology Synergies', href: '/vault/curriculum/tracks/rd-capital-management/3-4' },
            { id: '3-5', name: '3.5 Vendor & Platform Risk Assessment', topics: 'Criticality Scoring, Concentration Risk, Exit Strategy Planning', href: '/vault/curriculum/tracks/rd-capital-management/3-5' },
            { id: '3-6', name: '3.6 Remediation Roadmap & Execution', topics: 'ICE Prioritization, Wave Planning, Stakeholder Management', href: '/vault/curriculum/tracks/rd-capital-management/3-6' },
            { id: '3-7', name: '3.7 Architecture Assessment', topics: 'Coupling Analysis, Scalability Modeling, Architecture Debt', href: '/vault/curriculum/tracks/rd-capital-management/3-7' },
            { id: '3-8', name: '3.8 Testing & Quality Economics', topics: 'Bug Cost by Stage, Test Automation ROI, Quality Gates', href: '/vault/curriculum/tracks/rd-capital-management/3-8' },
            { id: '3-9', name: '3.9 Dependency & Vendor Risk', topics: 'Dependency Auditing, License Compliance, Vendor Concentration', href: '/vault/curriculum/tracks/rd-capital-management/3-9' },
            { id: '3-10', name: '3.10 Cloud Infrastructure Audit', topics: 'Cloud Cost Audit, Right-Sizing, Commitment Optimization', href: '/vault/curriculum/tracks/rd-capital-management/3-10' },
            { id: '3-11', name: '3.11 Security Debt Assessment', topics: 'Vulnerability Exposure, Compliance Gaps, Remediation Economics', href: '/vault/curriculum/tracks/rd-capital-management/3-11' },
            { id: '3-12', name: '3.12 Data Quality & Governance', topics: 'Data Quality Costs, Five Dimensions, Governance Frameworks', href: '/vault/curriculum/tracks/rd-capital-management/3-12' },
            { id: '3-13', name: '3.13 DevOps Maturity Assessment', topics: 'CI/CD Pipeline ROI, Observability Investment, Incident Costs', href: '/vault/curriculum/tracks/rd-capital-management/3-13' },
            { id: '3-14', name: '3.14 Technical Debt Communication', topics: 'CFO Translation, Board Presentations, Investor Due Diligence', href: '/vault/curriculum/tracks/rd-capital-management/3-14' },
            { id: '3-15', name: '3.15 R&D Capital Synthesis', topics: 'Complete Framework, Quarterly Cadence, Investment Culture', href: '/vault/curriculum/tracks/rd-capital-management/3-15' },
        ],
        color: 'emerald',
        icon: '💎',
        glossaryTerms: ['product-debt-index', 'ev-se', 'vc-due-diligence', 'architecture-review-board', 'vendor-lock-in', 'capex-vs-opex', 'technical-insolvency-date'],
        tools: [{ name: 'EV-SE Calculator', href: '/tools/ev-se' }, { name: 'Audit Interview', href: '/tools/audit-interview' }],
    },
    {
        title: 'Capstone & Applied Practice',
        subtitle: 'Track 4 — Capstone',
        description: 'Applied practice modules: startup economics scenarios, platform engineering, org scaling, cloud FinOps, SaaS metrics, and the full R&D Capital Audit capstone project.',
        modules: [
            { id: '4-1', name: '4.1 Startup Engineering Economics', topics: 'Runway-Aware Engineering, MVP Economics, Series A Positioning', href: '/vault/curriculum/tracks/capstone/4-1' },
            { id: '4-2', name: '4.2 Enterprise Platform Economics', topics: 'Platform Tax, Developer Experience ROI, Platform Team Economics', href: '/vault/curriculum/tracks/capstone/4-2' },
            { id: '4-3', name: '4.3 Engineering Org Scaling', topics: 'Scaling Laws, Hiring Economics, Span of Control, Conway\'s Law', href: '/vault/curriculum/tracks/capstone/4-3' },
            { id: '4-4', name: '4.4 Cloud FinOps & Infrastructure', topics: 'Cloud Cost Anatomy, Reservation Strategy, FinOps Culture', href: '/vault/curriculum/tracks/capstone/4-4' },
            { id: '4-5', name: '4.5 SaaS Metrics Deep Dive', topics: 'NRR, CAC:LTV, Unit Economics, Rule of 40, Engineering Efficiency', href: '/vault/curriculum/tracks/capstone/4-5' },
            { id: '4-6', name: '4.6 Capstone: Full R&D Capital Audit', topics: 'Complete Audit Project, Board-Ready Document, Investment Roadmap', href: '/vault/curriculum/tracks/capstone/4-6' },
            { id: '4-7', name: '4.7 Case Study: SaaS Scale-Up', topics: 'Series B Audit, Scaling Challenges, Technical Debt Hotspots', href: '/vault/curriculum/tracks/capstone/4-7' },
            { id: '4-8', name: '4.8 Case Study: PE Portfolio', topics: 'Post-Acquisition Audit, Platform Consolidation, Team Restructuring', href: '/vault/curriculum/tracks/capstone/4-8' },
            { id: '4-9', name: '4.9 Case Study: AI Startup', topics: 'Burn Rate Optimization, Model Economics, Commercialization', href: '/vault/curriculum/tracks/capstone/4-9' },
            { id: '4-10', name: '4.10 Case Study: Enterprise Modernization', topics: 'Legacy Migration, Dual-Speed IT, Strangler Fig Pattern', href: '/vault/curriculum/tracks/capstone/4-10' },
            { id: '4-11', name: '4.11 Building Your Practice', topics: 'Engagement Design, Pricing, Deliverables, Client Management', href: '/vault/curriculum/tracks/capstone/4-11' },
            { id: '4-12', name: '4.12 Tools Deep Dive', topics: 'Professional Tool Workflow, Cross-Referencing, Assessment Timing', href: '/vault/curriculum/tracks/capstone/4-12' },
            { id: '4-13', name: '4.13 Presentation & Storytelling', topics: 'SCR Framework, Data Visualization, Executive Communication', href: '/vault/curriculum/tracks/capstone/4-13' },
            { id: '4-14', name: '4.14 Continuous Improvement', topics: 'Engineering OKRs, Monthly Reviews, Automated Dashboards', href: '/vault/curriculum/tracks/capstone/4-14' },
            { id: '4-15', name: '4.15 Final Capstone Assessment', topics: 'End-to-End Audit, Peer Review, Professional Presentation', href: '/vault/curriculum/tracks/capstone/4-15' },
        ],
        color: 'amber',
        icon: '🏆',
        glossaryTerms: ['burn-rate', 'cac', 'arr', 'finops', 'developer-experience', 'cost-per-hire', 'dpi', 'down-round', 'saas-valuation'],
        tools: [{ name: 'PDI Calculator', href: '/tools/pdi' }, { name: 'APER Calculator', href: '/tools/aper' }, { name: 'AUEB Calculator', href: '/tools/aueb' }, { name: 'EV-SE Calculator', href: '/tools/ev-se' }],
    },
    {
        title: 'Product Management Economics',
        subtitle: 'Track 5 — Product',
        description: 'Product economics for PMs and CPOs: feature prioritization using economic models, pricing strategy, churn economics, and the bridge between product and finance. Nobody else teaches PM through the P&L lens.',
        modules: [
            { id: '6-1', name: '5.1 Feature Prioritization Economics', topics: 'RICE vs WSJF, Opportunity Cost, Stack Ranking by Dollar Value', href: '/vault/curriculum/tracks/product-economics/6-1' },
            { id: '6-2', name: '5.2 Pricing & Packaging Strategy', topics: 'Value-Based Pricing, Tiering, Usage Pricing, Price Elasticity', href: '/vault/curriculum/tracks/product-economics/6-2' },
            { id: '6-3', name: '5.3 Churn & Retention Economics', topics: 'Churn Waterfall, LTV Modeling, Retention ROI, Cohort Analysis', href: '/vault/curriculum/tracks/product-economics/6-3' },
            { id: '6-4', name: '5.4 Feature Bloat Calculus', topics: 'Feature Cost Decay, Maintenance Drag, Sunset Economics', href: '/vault/curriculum/tracks/product-economics/6-4' },
            { id: '6-5', name: '5.5 Product-Led Growth Economics', topics: 'PLG Funnel Costs, Free Tier Economics, Conversion Optimization', href: '/vault/curriculum/tracks/product-economics/6-5' },
            { id: '6-6', name: '5.6 Competitive Moat Analysis', topics: 'Switching Cost Quantification, Network Effects, Data Moats', href: '/vault/curriculum/tracks/product-economics/6-6' },
            { id: '6-7', name: '5.7 A/B Testing Economics', topics: 'Experimentation ROI, Test Duration Costs, Statistical Significance', href: '/vault/curriculum/tracks/product-economics/6-7' },
            { id: '6-8', name: '5.8 Product Operations', topics: 'ProductOps ROI, Tool Costs, Process Automation', href: '/vault/curriculum/tracks/product-economics/6-8' },
            { id: '6-9', name: '5.9 Customer Acquisition Economics', topics: 'CAC Payback, Channel Economics, Blended CAC', href: '/vault/curriculum/tracks/product-economics/6-9' },
            { id: '6-10', name: '5.10 Marketplace Economics', topics: 'Platform Take Rate, Network Economics, Liquidity Metrics', href: '/vault/curriculum/tracks/product-economics/6-10' },
            { id: '6-11', name: '5.11 Product Analytics ROI', topics: 'Analytics Stack Costs, Insight-to-Action, Data Warehouse ROI', href: '/vault/curriculum/tracks/product-economics/6-11' },
            { id: '6-12', name: '5.12 Technical Product Management', topics: 'TPM Economics, API Monetization, Dev Tool Pricing', href: '/vault/curriculum/tracks/product-economics/6-12' },
            { id: '6-13', name: '5.13 Product Roadmap Economics', topics: 'Opportunity Cost of Roadmaps, Pivot Costs, Feature Debt', href: '/vault/curriculum/tracks/product-economics/6-13' },
            { id: '6-14', name: '5.14 Product-Finance Partnership', topics: 'PM Scorecards, Revenue Attribution, Unit Economics Reporting', href: '/vault/curriculum/tracks/product-economics/6-14' },
            { id: '6-15', name: '5.15 Product Economics Synthesis', topics: 'Complete Product Economic Model, Portfolio View, Board Report', href: '/vault/curriculum/tracks/product-economics/6-15' },
        ],
        color: 'pink',
        icon: '📱',
        glossaryTerms: ['feature-bloat-calculus', 'cost-of-delay', 'cac', 'arr', 'product-led-growth', 'net-revenue-retention', 'burn-multiple'],
        tools: [{ name: 'PDI Calculator', href: '/tools/pdi' }, { name: 'APER Calculator', href: '/tools/aper' }],
    },
    {
        title: 'AI Operations Economics & Cost Governance',
        subtitle: 'Track 6 — AI Ops',
        description: 'The economics of deploying, governing, and scaling AI systems: model selection, prompt engineering ROI, AI compliance costs, agentic automation, and vendor comparison. Connects to Exogram and EAAP.',
        modules: [
            { id: '11-1', name: '6.1 AI Model Selection Economics', topics: 'Foundation Model Costs, Inference Pricing, Quality-Cost Tradeoffs', href: '/vault/curriculum/tracks/ai-operations/11-1' },
            { id: '11-2', name: '6.2 Prompt Engineering ROI', topics: 'Prompt Library Economics, Testing Costs, Prompt Infrastructure', href: '/vault/curriculum/tracks/ai-operations/11-2' },
            { id: '11-3', name: '6.3 AI Testing & Evaluation', topics: 'Eval Suite Costs, Benchmark Design, Quality Gate Economics', href: '/vault/curriculum/tracks/ai-operations/11-3' },
            { id: '11-4', name: '6.4 Hallucination Cost Modeling', topics: 'Detection Costs, Business Impact, Guardrail Investment', href: '/vault/curriculum/tracks/ai-operations/11-4' },
            { id: '11-5', name: '6.5 RAG Architecture Economics', topics: 'Embedding Costs, Vector DB Pricing, Chunking Strategy', href: '/vault/curriculum/tracks/ai-operations/11-5' },
            { id: '11-6', name: '6.6 AI Agent Economics', topics: 'Agent Orchestration, Tool-Use Pricing, Multi-Agent Systems', href: '/vault/curriculum/tracks/ai-operations/11-6' },
            { id: '11-7', name: '6.7 AI Compliance & Audit', topics: 'EU AI Act, NIST AI RMF, Model Cards, Governance Committees', href: '/vault/curriculum/tracks/ai-operations/11-7' },
            { id: '11-8', name: '6.8 AI Vendor Comparison', topics: 'OpenAI vs Anthropic vs Google, TCO, Switching Costs', href: '/vault/curriculum/tracks/ai-operations/11-8' },
            { id: '11-9', name: '6.9 AI Team Building', topics: 'ML Engineer Compensation, Skill Gap, Training Investment', href: '/vault/curriculum/tracks/ai-operations/11-9' },
            { id: '11-10', name: '6.10 AI Operations Synthesis', topics: 'Complete AI Economic Model, GPU Forecasting, Strategy', href: '/vault/curriculum/tracks/ai-operations/11-10' },
            { id: '11-11', name: '6.11 Graph RAG Implementation', topics: 'Knowledge Graphs, Hallucination Elimination, Query Routing', href: '/vault/curriculum/tracks/ai-operations/11-11' },
            { id: '11-12', name: '6.12 Multimodal Processing Pipelines', topics: 'Audio/Video Reasoning, Document Ingestion Costs, Latency', href: '/vault/curriculum/tracks/ai-operations/11-12' },
            { id: '11-13', name: '6.13 AI Product Management', topics: 'Probabilistic PM, Non-Deterministic Testing, Feature KPIs', href: '/vault/curriculum/tracks/ai-operations/11-13' },
            { id: '11-14', name: '6.14 Shadow AI Discovery', topics: 'Employee App Usage, Data Leakage Prevention, Policy Enforcement', href: '/vault/curriculum/tracks/ai-operations/11-14' },
            { id: '11-15', name: '6.15 Prompt Injection Defense', topics: 'Jailbreak Prevention, Input Sanitization, Security Economics', href: '/vault/curriculum/tracks/ai-operations/11-15' },
            { id: '11-16', name: '6.16 Model Collapse Financial Modeling', topics: 'Model Depreciation, Organic Data Costs, Financial Decay', href: '/vault/curriculum/tracks/ai-operations/11-16' },
        ],
        color: 'teal',
        icon: '🧠',
        glossaryTerms: ['ai-inference', 'rag-architecture', 'graph-rag', 'multimodal-ai', 'ai-product-management', 'shadow-ai', 'prompt-injection', 'guardrails', 'token-ai', 'ai-cogs', 'agentic-workflow'],
        tools: [{ name: 'AUEB Calculator', href: '/tools/aueb' }, { name: 'AI Scoring', href: '/tools/scoring' }],
    },
    {
        title: 'Cloud FinOps & AI Cost Management',
        subtitle: 'Track 7 — FinOps',
        description: 'The economics of cloud cost management, optimization, and FinOps practice. 98% of FinOps teams now manage AI spend. AI cost management is the #1 capability teams plan to add in 2026.',
        modules: [
            { id: '14-1', name: '7.1 FinOps Fundamentals', topics: 'FinOps Maturity, Stakeholder Alignment, Team Sizing', href: '/vault/curriculum/tracks/cloud-finops/14-1' },
            { id: '14-2', name: '7.2 Cloud Cost Allocation', topics: 'Tagging Strategies, Showback Dashboards, Chargeback', href: '/vault/curriculum/tracks/cloud-finops/14-2' },
            { id: '14-3', name: '7.3 Reserved Instances & Savings Plans', topics: 'RI vs Savings Plans, Coverage Analysis, Break-Even', href: '/vault/curriculum/tracks/cloud-finops/14-3' },
            { id: '14-4', name: '7.4 Kubernetes Cost Management', topics: 'K8s Right-Sizing, Namespace Budgets, Cluster Allocation', href: '/vault/curriculum/tracks/cloud-finops/14-4' },
            { id: '14-5', name: '7.5 Serverless vs Container Economics', topics: 'Lambda vs ECS vs EKS, Cold Start, Workload Fit', href: '/vault/curriculum/tracks/cloud-finops/14-5' },
            { id: '14-6', name: '7.6 Multi-Cloud Arbitrage', topics: 'Cross-Cloud Pricing, Egress Management, Negotiation', href: '/vault/curriculum/tracks/cloud-finops/14-6' },
            { id: '14-7', name: '7.7 Cloud Migration ROI', topics: 'Lift-and-Shift vs Refactor, Timeline, Post-Migration', href: '/vault/curriculum/tracks/cloud-finops/14-7' },
            { id: '14-8', name: '7.8 Data Transfer & Egress', topics: 'CDN Economics, Edge Caching, Bandwidth, Data Locality', href: '/vault/curriculum/tracks/cloud-finops/14-8' },
            { id: '14-9', name: '7.9 FinOps Team & Governance', topics: 'FinOps Roles, KPI Frameworks, Executive Reporting', href: '/vault/curriculum/tracks/cloud-finops/14-9' },
            { id: '14-10', name: '7.10 Infrastructure Synthesis', topics: 'Cloud Economic Model, Optimization Dashboard, Strategy', href: '/vault/curriculum/tracks/cloud-finops/14-10' },
            { id: '14-11', name: '7.11 AI FinOps Specialization', topics: 'LLM Token Allocation, GPU Cluster Depreciation, Margin Triage', href: '/vault/curriculum/tracks/cloud-finops/14-11' },
            { id: '14-12', name: '7.12 Cloud Repatriation Calculus', topics: 'Basecamp Migration Strategy, Bare Metal Racks, Egress Elimination', href: '/vault/curriculum/tracks/cloud-finops/14-12' },
            { id: '14-13', name: '7.13 Serverless GPU Brokering', topics: 'Modal vs Runpod, Cold Start Tolerances, GPU Spot Markets', href: '/vault/curriculum/tracks/cloud-finops/14-13' },
            { id: '14-14', name: '7.14 Data Security Posture Management (DSPM)', topics: 'Cloud Discovery Scanning, Shadow Data Remediation, ROI Analysis', href: '/vault/curriculum/tracks/cloud-finops/14-14' },
            { id: '14-15', name: '7.15 Continuous Architecture Modernization', topics: 'Refactoring Rhythms, Retiring Legacy Instances, Savings Decay', href: '/vault/curriculum/tracks/cloud-finops/14-15' },
        ],
        color: 'blue',
        icon: '☁️',
        glossaryTerms: ['finops', 'ai-finops', 'cloud-repatriation', 'serverless-gpus', 'dspm', 'burn-multiple', 'infrastructure-as-code', 'cloud-cost-optimization'],
        tools: [{ name: 'PDI Calculator', href: '/tools/pdi' }, { name: 'AUEB Calculator', href: '/tools/aueb' }],
    },
    {
        title: 'AI Pricing Strategy & Monetization Economics',
        subtitle: 'Track 8 — NEW',
        description: '37% of AI companies plan to change their pricing model in the next 12 months. Outcome-based pricing jumped from 2% to 18% in six months. Teach the economics of pricing AI products.',
        modules: [
            { id: 'N8-1', name: '8.1 AI Pricing Model Taxonomy', topics: 'Usage-Based vs Outcome-Based vs Subscription, Hybrid Models', href: '/vault/curriculum/tracks/ai-pricing/N8-1' },
            { id: 'N8-2', name: '8.2 Token-Based Pricing Architecture', topics: 'Credit Systems, Metering Infrastructure, Rate Limiting Economics', href: '/vault/curriculum/tracks/ai-pricing/N8-2' },
            { id: 'N8-3', name: '8.3 The Flat-Rate AI Death Trap', topics: 'Unlimited AI at Flat Rate, Margin Collapse Scenarios, Usage Spikes', href: '/vault/curriculum/tracks/ai-pricing/N8-3' },
            { id: 'N8-4', name: '8.4 Outcome-Based Pricing Models', topics: 'Value Capture, Success Metrics, Risk-Sharing Economics', href: '/vault/curriculum/tracks/ai-pricing/N8-4' },
            { id: 'N8-5', name: '8.5 AI Freemium Economics', topics: 'Free Tier COGS, Conversion Funnels, Upsell Trigger Points', href: '/vault/curriculum/tracks/ai-pricing/N8-5' },
            { id: 'N8-6', name: '8.6 Enterprise AI Contract Design', topics: 'Commit Structures, Overage Pricing, Annual vs Monthly', href: '/vault/curriculum/tracks/ai-pricing/N8-6' },
            { id: 'N8-7', name: '8.7 Competitive Pricing Intelligence', topics: 'Market Positioning, Price Anchoring, Differentiation Premiums', href: '/vault/curriculum/tracks/ai-pricing/N8-7' },
            { id: 'N8-8', name: '8.8 Revenue Attribution for AI Features', topics: 'Feature-Level Revenue, Willingness-to-Pay Research, Bundling', href: '/vault/curriculum/tracks/ai-pricing/N8-8' },
            { id: 'N8-9', name: '8.9 AI Marketplace Monetization', topics: 'API-as-Product, Model Marketplace Take Rates, Developer Ecosystems', href: '/vault/curriculum/tracks/ai-pricing/N8-9' },
            { id: 'N8-10', name: '8.10 Pricing Strategy Synthesis', topics: 'Complete AI Pricing Model, Board Presentation, Margin Optimization', href: '/vault/curriculum/tracks/ai-pricing/N8-10' },
        ],
        color: 'fuchsia',
        icon: '💰',
        glossaryTerms: ['ai-cogs', 'unit-economics', 'net-revenue-retention', 'burn-multiple', 'cost-of-predictivity'],
        tools: [{ name: 'AUEB Calculator', href: '/tools/aueb' }],
    },
    {
        title: 'Technical Debt as Financial Liability',
        subtitle: 'Track 9 — NEW',
        description: 'You already publish on calculating technical debt\'s EBITDA impact for PE due diligence. Direct buyer intent from PE firms, CFOs, and VPEs preparing for acquisitions or audits.',
        modules: [
            { id: 'N9-1', name: '9.1 Technical Debt on the Balance Sheet', topics: 'GAAP Treatment, Liability Classification, Audit Disclosure', href: '/vault/curriculum/tracks/tech-debt-liability/N9-1' },
            { id: 'N9-2', name: '9.2 Quantifying Debt in Dollar Terms', topics: 'PDI Methodology, Maintenance Load Costing, Interest Rate Models', href: '/vault/curriculum/tracks/tech-debt-liability/N9-2' },
            { id: 'N9-3', name: '9.3 Technical Insolvency Date', topics: 'When Debt Exceeds Capacity, Death Spiral Indicators, Tipping Points', href: '/vault/curriculum/tracks/tech-debt-liability/N9-3' },
            { id: 'N9-4', name: '9.4 Debt Impact on EBITDA', topics: 'Maintenance Drag on Margins, Developer Velocity Tax, CFO Translation', href: '/vault/curriculum/tracks/tech-debt-liability/N9-4' },
            { id: 'N9-5', name: '9.5 PE Due Diligence: Tech Debt Assessment', topics: 'Pre-LOI Scans, Deal Breakers, Discount Models, Holdback Structures', href: '/vault/curriculum/tracks/tech-debt-liability/N9-5' },
            { id: 'N9-6', name: '9.6 Debt Forgiveness Protocols', topics: 'Sunk Cost Fallacy, Code Bankruptcy, Rewrite Mathematics', href: '/vault/curriculum/tracks/tech-debt-liability/N9-6' },
            { id: 'N9-7', name: '9.7 Architecture Debt Valuation', topics: 'Coupling Costs, Monolith Decomposition, Migration Economics', href: '/vault/curriculum/tracks/tech-debt-liability/N9-7' },
            { id: 'N9-8', name: '9.8 Infrastructure Debt', topics: 'EOL Hardware, Unpatched Systems, Cloud Migration Forcing Functions', href: '/vault/curriculum/tracks/tech-debt-liability/N9-8' },
            { id: 'N9-9', name: '9.9 Communicating Debt to the Board', topics: 'Visual Frameworks, Risk Heat Maps, Investment Proposals', href: '/vault/curriculum/tracks/tech-debt-liability/N9-9' },
            { id: 'N9-10', name: '9.10 Tech Debt Remediation Economics', topics: 'Wave Planning, ROI-First Prioritization, Continuous Paydown Models', href: '/vault/curriculum/tracks/tech-debt-liability/N9-10' },
        ],
        color: 'red',
        icon: '🏚️',
        glossaryTerms: ['technical-debt', 'product-debt-index', 'technical-insolvency-date', 'innovation-tax', 'maintenance-load'],
        tools: [{ name: 'PDI Calculator', href: '/tools/pdi' }, { name: 'EV-SE Calculator', href: '/tools/ev-se' }],
    },
    {
        title: 'AI Due Diligence for Investors & Acquirers',
        subtitle: 'Track 10 — NEW',
        description: 'PE firms, corporate development teams, and VCs evaluating AI companies need this. A natural extension of R&D Capital Management with a clear buyer profile.',
        modules: [
            { id: 'N10-1', name: '10.1 AI Company Valuation Frameworks', topics: 'ARR Multiples for AI, Revenue Quality, Gross Margin Analysis', href: '/vault/curriculum/tracks/ai-due-diligence/N10-1' },
            { id: 'N10-2', name: '10.2 AI Model Asset Valuation', topics: 'Proprietary Data Moats, Fine-Tuned Model Worth, Training Cost Basis', href: '/vault/curriculum/tracks/ai-due-diligence/N10-2' },
            { id: 'N10-3', name: '10.3 AI Infrastructure Audit', topics: 'GPU Contracts, Cloud Commitments, Inference Cost Trajectories', href: '/vault/curriculum/tracks/ai-due-diligence/N10-3' },
            { id: 'N10-4', name: '10.4 Data Asset Due Diligence', topics: 'Data Quality Scoring, Licensing Compliance, Privacy Risk Assessment', href: '/vault/curriculum/tracks/ai-due-diligence/N10-4' },
            { id: 'N10-5', name: '10.5 AI Team Assessment', topics: 'Key-Person Risk, ML Engineer Retention, Talent Market Benchmarks', href: '/vault/curriculum/tracks/ai-due-diligence/N10-5' },
            { id: 'N10-6', name: '10.6 AI Technical Debt Evaluation', topics: 'Model Drift Risk, Pipeline Fragility, Retraining Cost Projections', href: '/vault/curriculum/tracks/ai-due-diligence/N10-6' },
            { id: 'N10-7', name: '10.7 AI Regulatory & Compliance Risk', topics: 'EU AI Act Exposure, IP Litigation, Bias Liability Quantification', href: '/vault/curriculum/tracks/ai-due-diligence/N10-7' },
            { id: 'N10-8', name: '10.8 Competitive Moat Analysis for AI', topics: 'Data Flywheel Strength, Model Defensibility, Switching Costs', href: '/vault/curriculum/tracks/ai-due-diligence/N10-8' },
            { id: 'N10-9', name: '10.9 Post-Acquisition AI Integration', topics: 'Model Consolidation, Team Merging, Infrastructure Rationalization', href: '/vault/curriculum/tracks/ai-due-diligence/N10-9' },
            { id: 'N10-10', name: '10.10 AI Due Diligence Synthesis', topics: 'Complete AI DD Report Template, Board Presentation, Deal Structuring', href: '/vault/curriculum/tracks/ai-due-diligence/N10-10' },
        ],
        color: 'indigo',
        icon: '🔍',
        glossaryTerms: ['vc-due-diligence', 'ai-cogs', 'ev-se', 'burn-rate', 'arr', 'saas-valuation'],
        tools: [{ name: 'EV-SE Calculator', href: '/tools/ev-se' }, { name: 'Audit Interview', href: '/tools/audit-interview' }],
    },
    {
        title: 'Economics of Build vs. Buy for AI',
        subtitle: 'Track 11 — NEW',
        description: 'Every engineering leader faces this right now. Frame it through your economic lens: TCO modeling, vendor lock-in costs, inference arbitrage, and the hidden costs of "free" open-source models.',
        modules: [
            { id: 'N11-1', name: '11.1 The Build vs Buy Decision Framework', topics: 'Total Cost of Ownership, Core vs Context, Strategic Differentiation Test', href: '/vault/curriculum/tracks/ai-build-vs-buy/N11-1' },
            { id: 'N11-2', name: '11.2 API Provider Economics', topics: 'OpenAI vs Anthropic vs Google Pricing, Volume Discounts, Rate Limits', href: '/vault/curriculum/tracks/ai-build-vs-buy/N11-2' },
            { id: 'N11-3', name: '11.3 Self-Hosting Economics', topics: 'GPU Infrastructure TCO, Llama/Mistral Hosting, DevOps Overhead', href: '/vault/curriculum/tracks/ai-build-vs-buy/N11-3' },
            { id: 'N11-4', name: '11.4 Open Source Model Hidden Costs', topics: 'Fine-Tuning Compute, Evaluation Infrastructure, Maintenance Burden', href: '/vault/curriculum/tracks/ai-build-vs-buy/N11-4' },
            { id: 'N11-5', name: '11.5 Vendor Lock-In Quantification', topics: 'Switching Costs, Embedding Migration, Prompt Rewriting, Data Gravity', href: '/vault/curriculum/tracks/ai-build-vs-buy/N11-5' },
            { id: 'N11-6', name: '11.6 Inference Cost Arbitrage', topics: 'Model Routing, Tiered Quality, Cost-Performance Optimization', href: '/vault/curriculum/tracks/ai-build-vs-buy/N11-6' },
            { id: 'N11-7', name: '11.7 RAG Build vs Buy', topics: 'Pinecone vs pgvector vs Custom, Managed vs Self-Hosted Embeddings', href: '/vault/curriculum/tracks/ai-build-vs-buy/N11-7' },
            { id: 'N11-8', name: '11.8 AI Platform vs Point Solution', topics: 'Horizontal Platforms, Vertical AI SaaS, Integration Complexity', href: '/vault/curriculum/tracks/ai-build-vs-buy/N11-8' },
            { id: 'N11-9', name: '11.9 Multi-Model Strategy Economics', topics: 'Portfolio Approach, Fallback Architecture, Best-of-Breed Routing', href: '/vault/curriculum/tracks/ai-build-vs-buy/N11-9' },
            { id: 'N11-10', name: '11.10 Build vs Buy Synthesis', topics: 'Decision Matrix Template, Board Presentation, 3-Year TCO Model', href: '/vault/curriculum/tracks/ai-build-vs-buy/N11-10' },
        ],
        color: 'orange',
        icon: '⚖️',
        glossaryTerms: ['total-cost-of-ownership', 'vendor-lock-in', 'ai-cogs', 'ai-inference', 'open-weights', 'cloud-repatriation'],
        tools: [{ name: 'AUEB Calculator', href: '/tools/aueb' }, { name: 'PDI Calculator', href: '/tools/pdi' }],
    },
    {
        title: 'Career Capital Economics',
        subtitle: 'Track 12 — NEW',
        description: 'Stop being a cost center. Learn to quantify your business impact, negotiate compensation using economic frameworks, and prove your dollar value at every level — from junior IC to Staff Engineer.',
        modules: [
            { id: 'N12-1', name: '12.1 Your Revenue-Per-Engineer Contribution', topics: 'Calculating APER Impact, Attributing Business Value, Beyond Story Points', href: '/vault/curriculum/tracks/career-capital/N12-1' },
            { id: 'N12-2', name: '12.2 Compensation Economics', topics: 'Pay Band Analysis, Equity Valuation, Total Comp Modeling, RSU vs Options', href: '/vault/curriculum/tracks/career-capital/N12-2' },
            { id: 'N12-3', name: '12.3 The Business Case for Promotion', topics: 'Quantified Impact Dossiers, P&L Outcomes, Translating Code to Revenue', href: '/vault/curriculum/tracks/career-capital/N12-3' },
            { id: 'N12-4', name: '12.4 Navigating Layoff Economics', topics: 'Severance Math, Risk Indicators, Cost Center vs Profit Center Positioning', href: '/vault/curriculum/tracks/career-capital/N12-4' },
            { id: 'N12-5', name: '12.5 The Senior Engineer P&L', topics: 'Measuring Leverage, Technical Debt Prevention ROI, Architecture Impact', href: '/vault/curriculum/tracks/career-capital/N12-5' },
            { id: 'N12-6', name: '12.6 Staff Engineer as Capital Allocator', topics: 'Cross-Team Influence Economics, RFC ROI, Platform Strategy Ownership', href: '/vault/curriculum/tracks/career-capital/N12-6' },
            { id: 'N12-7', name: '12.7 The Cost of Career Stagnation', topics: 'Opportunity Cost Modeling, Market Rate Drift, Skill Depreciation Curves', href: '/vault/curriculum/tracks/career-capital/N12-7' },
            { id: 'N12-8', name: '12.8 Negotiation Using Economic Frameworks', topics: 'Anchoring with Data, Competing Offers, Equity vs Cash Tradeoffs', href: '/vault/curriculum/tracks/career-capital/N12-8' },
            { id: 'N12-9', name: '12.9 Building a Revenue-Centric Resume', topics: 'Impact Metrics, Business Outcome Framing, P&L Language for Engineers', href: '/vault/curriculum/tracks/career-capital/N12-9' },
            { id: 'N12-10', name: '12.10 Career Capital Synthesis', topics: 'Your Personal Economic Model, 5-Year Capital Plan, Board-of-You Strategy', href: '/vault/curriculum/tracks/career-capital/N12-10' },
        ],
        color: 'rose',
        icon: '📈',
        glossaryTerms: ['cost-per-hire', 'attrition-rate', 'developer-experience', 'unit-economics'],
        tools: [{ name: 'APER Calculator', href: '/tools/aper' }, { name: 'Career Pathing', href: '/tools/career-pathing' }],
    },
    {
        title: 'Engineering-to-Executive Economics',
        subtitle: 'Track 13 — NEW',
        description: 'The economics translation layer for Directors, VPs, and aspiring CTOs. Learn to think in P&L, present to boards, own budgets, and position yourself as a revenue-driving executive — not a technical manager.',
        modules: [
            { id: 'N13-1', name: '13.1 The Language of the Boardroom', topics: 'EBITDA Translation, Margin Frameworks, Executive Vocabulary', href: '/vault/curriculum/tracks/exec-economics/N13-1' },
            { id: 'N13-2', name: '13.2 Budget Ownership & R&D Stewardship', topics: 'CapEx vs OpEx, Headcount Modeling, Zero-Based Budgeting', href: '/vault/curriculum/tracks/exec-economics/N13-2' },
            { id: 'N13-3', name: '13.3 Board Reporting for Technical Leaders', topics: '4-Quadrant Slides, KPI Dashboards, Investment Proposals', href: '/vault/curriculum/tracks/exec-economics/N13-3' },
            { id: 'N13-4', name: '13.4 Reorg Economics & Org Design', topics: 'Restructuring Costs, Productivity Dip, Conway\'s Law at Scale', href: '/vault/curriculum/tracks/exec-economics/N13-4' },
            { id: 'N13-5', name: '13.5 M&A Technical Leadership', topics: 'Due Diligence Leadership, Integration Playbook, Talent Retention', href: '/vault/curriculum/tracks/exec-economics/N13-5' },
            { id: 'N13-6', name: '13.6 CTO vs VP Engineering Economics', topics: 'Role Separation, Cost Structures, Board Relationship Dynamics', href: '/vault/curriculum/tracks/exec-economics/N13-6' },
            { id: 'N13-7', name: '13.7 Managing Technical Debt at the Board Level', topics: 'Risk Heat Maps, Investment Proposals, Remediation Roadmaps', href: '/vault/curriculum/tracks/exec-economics/N13-7' },
            { id: 'N13-8', name: '13.8 AI Strategy for Executives', topics: 'AI Investment Framework, Build vs Buy at the C-Suite, Vendor Selection', href: '/vault/curriculum/tracks/exec-economics/N13-8' },
            { id: 'N13-9', name: '13.9 The 90-Day CTO Turnaround', topics: 'Trust Bridge, 360 Audit, Quick Wins, Board Confidence Building', href: '/vault/curriculum/tracks/exec-economics/N13-9' },
            { id: 'N13-10', name: '13.10 Executive Economics Synthesis', topics: 'Your CTO Dashboard, Quarterly Cadence, Long-Term Capital Planning', href: '/vault/curriculum/tracks/exec-economics/N13-10' },
        ],
        color: 'indigo',
        icon: '👑',
        glossaryTerms: ['capex-vs-opex', 'ev-se', 'product-debt-index', 'vc-due-diligence', 'conways-law', 'span-of-control'],
        tools: [{ name: 'EV-SE Calculator', href: '/tools/ev-se' }, { name: 'Audit Interview', href: '/tools/audit-interview' }],
    },
];