import { CurriculumModule, l, d, m } from './curriculum-data';

export const tracks27Modules: Record<string, CurriculumModule> = {};
const t27 = 'Track 27  -  Synthetic Data & Model Collapse';

tracks27Modules['synthetic-data/27-1'] = m('27-1', 'The Exhaustion of Human Data', 'Hitting the data wall, generation pipelines, simulation curves.', t27, 
    ['Execute Synthetic Data pipelines', 'Measure data fidelity'], [
        l('Scaling Beyond the Text Deficit', 
            [
                'The massive surge of foundational models (GPT-4) was powered by vacuuming up the totality of human text on the public internet. However, humanity only produces so much text. By 2026, the industry collided violently with the "Data Wall" - the realization that there is literally not enough high-quality organic data left on Earth to train the next generation of Trillion-parameter models.', 
                'To bypass this boundary, enterprises must construct massive Synthetic Data Simulation pipelines. Using highly specialized "Teacher" models (like Llama 3 400B) to programmatically generate billions of permutations of high-fidelity logic problems, which are then used to effectively train significantly smaller, cheaper "Student" models.',
                'Synthetic Data allows organizations to perfectly map edge-cases that almost never occur natively in production. You can generate one million unique examples of a catastrophic fraud transaction to train your anomaly detection agent, without waiting 10 years to organically collect one million real frauds.'
            ],
            [
                d('Synthetic Yield Rate', 'The absolute volume of high-quality training pairs generated by logic scripts per hour.', 'Unlimited Scaling potential'),
                d('Edge Case Density', 'The concentration of statistically rare data patterns injected into the training pool.', 'Perfectly Controllable')
            ], 
            'Architect a programmatic generation pipeline for specialized task data.', 
            ['Deploy a dedicated Teacher model (e.g., Anthropic Claude Opus) via API.', 'Command it to instantly generate 10,000 highly nuanced technical JSON support tickets.', 'Utilize that output dataset strictly to fine-tune a tiny, hyper-efficient local proxy model for ticket routing.'], 
            {
                question: 'What is the primary architectural advantage of Synthetic Data generation for enterprise fine-tuning?',
                options: ['It uses less electricity', 'It allows you to programmatically spawn infinite, perfect examples of wildly rare statistical edge-cases, completely removing the reliance on slow, organic data collection', 'It prevents users from complaining', 'It makes the neural network hallucinate less natively'],
                correctIndex: 1,
                explanation: 'Real-world data is extremely messy, heavily biased, and often lacks crucial edge cases. Synthetic data is generated algorithmically to ensure absolute perfection and balance across the entire training spectrum.'
            }
        )
    ], '/vault/curriculum/tracks/synthetic-data/27-2', undefined, 'live'
);

tracks27Modules['synthetic-data/27-2'] = m('27-2', 'Model Collapse Dynamics', 'The feedback loop trap, data contamination, validation networks.', t27, 
    ['Establish pristine data isolation', 'Detect semantic degradation'], [
        l('The Danger of the Recursive AI ouroboros', 
            [
                'While Synthetic Data is mandatory for scaling, it introduces a catastrophic structural vulnerability known as "Model Collapse." If an AI model trains explicitly on the outputs of another AI model without rigorous mathematical filtering, the underlying statistical variance violently implodes.', 
                'In Model Collapse, the model forgets the rare tails of human distribution. It begins perfectly echoing the boring, repetitive center of the bell curve. After 3 or 4 generations of training on AI-generated data, the model completely loses its ability to comprehend complex reality, outputting absolute meaningless gibberish.',
                'Enterprise AI architectures must establish "Pristine Data Isolation" loops. The foundation of any synthetic pipeline must rely heavily on human-verified ground-truth anchors. Every iteration of synthetic data must be explicitly vetted by an adversarial discriminator model ensuring data density is not degrading.'
            ],
            [
                d('Collapse Implosion Horizon', 'The exact training iteration where generative semantic variance drops below absolute zero.', 'Monitor recursively'),
                d('Ground Truth Ratio', 'The unshakeable percentage of real-world human data structurally anchoring the fine-tuning layers.', 'Must be rigidly protected')
            ], 
            'Execute a strict variance test across massive synthetic ingestion pipelines.', 
            ['Identify the pipeline actively pouring generated tickets back into the central data lake.', 'Isolate the vectors and process a heavy dispersion algorithmic test.', 'If the generated text vectors start heavily grouping in a tight, homogeneous cluster, instantly shut down the synthetic generation node.'], 
            {
                question: 'What is "Model Collapse" in the context of Synthetic Data generation?',
                options: ['When the AI model becomes too smart for humans to understand', 'A catastrophic statistical implosion where training AI exclusively on previous AI outputs causes the model to entirely forget the nuances of human reality, degenerating into meaningless repetitive noise', 'When the cloud provider runs out of hard drive space', 'When the database crashes'],
                correctIndex: 1,
                explanation: 'An AI trained on human data learns the full spectrum of human variance. An AI trained on AI data learns to compress and average. Over multiple generations, it compresses the variance completely down to zero.'
            }
        )
    ], '/vault/curriculum/tracks/synthetic-data/27-10', undefined, 'live'
);

for (let i = 3; i <= 10; i++) {
    tracks27Modules[`synthetic-data/27-${i}`] = m(`27-${i}`, `Advanced Generation Pipelines ${i}`, `Expansion module tracking deep synthetic bounding networks.`, t27, 
        ['Optimize data filtering algorithms', 'Calculate model variance collapse', 'Establish discriminator bounds'], [
            l(`Deep Data Filtering Constraints ${i}`, 
                [
                    `Continuing the expansion into data pipeline protection. The failure to filter out low-quality AI outputs before merging them into a production training run is economically fatal.`, 
                    `The executive strategy demands deploying Adversarial Discriminators - models designed specifically to reject boring, incorrect, or heavily hallucinated synthetic data outputs.`,
                    `The architecture absolutely mandates establishing massive quality checkpoints prior to initiating a $10,000 GPU-intensive parameter update.`
                ],
                [
                    d(`Adversarial Rejection Rate ${i}`, `The percentage of synthetic data scrapped due to failing the complexity test.`, `Must act as a heavy filter`),
                    d(`Cost-Per-Verified-Example ${i}`, `The real cost of generating one piece of perfect synthetic truth.`, `Highly monitored`)
                ], 
                `Architect stringent filtering logic across the data lake.`, 
                [`Integrate mathematical perplexity scanners upon inbound generated text.`, `Monitor the distribution tails of vector density.`, `Force manual override tests ensuring edge cases are aggressively preserved.`], 
                {
                    question: `Why is an "Adversarial Discriminator" heavily required when executing Synthetic Data pipelines?`,
                    options: [`To make the system sound intimidating`, `To mathematically ruthlessly reject boring, wrong, or compressed AI-generated data before it poisons the expensive downstream fine-tuning processes`, `To secure the data from hackers`, `To prevent the database from overloading`],
                    correctIndex: 1,
                    explanation: `Generation creates millions of records. Quality checking those records requires an automated bouncer. The discriminator model brutally filters the noise to ensure only perfect data remains.`
                }
            )
        ], i < 10 ? `/vault/curriculum/tracks/synthetic-data/27-${i+1}` : undefined, undefined, 'live'
    );
}
