import { type CurriculumModule, m, l, d } from './curriculum-data';

export function populateTracks1To4(modules: Record<string, CurriculumModule>) {
    
    // Helper to generate the next href automatically
    const getNext = (trackStr: string, index: number, total: number) => {
        return index < total - 1 ? `/vault/curriculum/tracks/${trackStr}/${trackStr === 'engineering-economics' ? 1 : trackStr === 'ai-product-economics' ? 2 : trackStr === 'rd-capital-management' ? 3 : 4}-${index + 2}` : undefined;
    };

    // ═══════════════════ TRACK 1: CTO / Engineering Leader ═══════════════════
    const t1 = 'Track 1 — CTO / Engineering Leader';
    const ctoMods: [string, string, string, string[], ReturnType<typeof l>[]][] = [
        ['1-1', 'The Product Debt Index (PDI)', 'Learn the exact framework used in $7,500 advisory engagements to value legacy codebases.', 
            ['Define the Innovation Tax', 'Calculate Technical Insolvency', 'Build a PDI equation', 'Defend refactoring budgets to the board'],
            [
                l('Lesson 1: The Innovation Tax', 'Code doesn\'t rot, but your architecture’s fitness function decays. The Innovation Tax is the percentage of total engineering capacity spent solely on fighting legacy constraints instead of shipping new value. If your tax exceeds 40%, you are technically insolvent.', [
                    d('Innovation Tax Formula', 'Maintenance hours / Total engineering hours × 100', 'Target: < 20%'),
                    d('Technical Insolvency', 'The point where maintenance costs exceed the revenue generated by new features.', 'Action: Immediate Feature Freeze'),
                    d('Board Communication', 'Never say "tech debt" to a CFO. Call it an "unfunded capital liability."', 'Frame in lost EBITDA')
                ], 'Calculate your team\'s current Innovation Tax over the last three sprints using Jira/Linear telemetry.'),
                l('Lesson 2: Calculating the PDI', 'The Product Debt Index is a deterministic equation. PDI = (Cost of Delay × Dependency Graph Depth) / Automated Coverage %. A PDI > 100 means you have a systemic collapse risk.', [
                    d('Dependency Graph Depth', 'Number of internal systems that must update for a single feature release.', 'Target: < 3 hops'),
                    d('Automated Coverage', 'Not just unit tests, but integration tests covering critical user flows.', 'Target: > 80% coverage on path-to-purchase'),
                    d('Cost of Delay (CoD)', 'Lost monthly revenue for a feature blocked by tech debt.', 'Calculate in $ARR')
                ], 'Select your most brittle service. Run the PDI equation against it and document the exact score.'),
                l('Lesson 3: The Refactoring Strategy', 'You cannot halt the roadmap to rewrite the monolith. You must implement the Strangler Fig pattern, siphoning traffic bit by bit. This lesson covers the exact API gateway architecture needed to route legacy traffic to rewritten microservices.', [
                    d('Strangler Fig Proxy', 'A perimeter gateway routing traffic by bounded context.', 'AWS API Gateway / NGINX'),
                    d('Shadow Traffic', 'Mirroring reads to the new service before cutting over writes.', 'Zero-downtime regression testing'),
                    d('Cutover Metric', 'The defect parity threshold required to decommission the legacy route.', '0 P1 defects for 7 days')
                ], 'Draw an architecture diagram showing the Strangler Fig proxy for your largest legacy domain.')
            ]
        ],
        ['1-2', 'Engineering Velocity & APER', 'Move beyond story points to metrics that CFOs and Boards actually care about.', 
            ['Implement true DORA metrics', 'Calculate APER (Revenue/Eng)', 'Map systemic bottlenecks', 'Correlate deployment to ARR'],
            [
                l('Lesson 1: APER (Average Profit Per Engineer)', 'Story points are an internal operational metric. APER connects engineering to the P&L. APER = Total ARR / Number of Engineers. If APER is dropping while headcount grows, your marginal cost of engineering is failing.', [
                    d('APER Baseline', 'The industry average for SaaS companies.', 'Target: $250k - $500k per engineer'),
                    d('The Bloat Ceiling', 'The headcount point where communication overhead destroys marginal output.', 'Usually around 50 engineers'),
                    d('Tooling ROI', 'The APER lift generated by adopting better internal developer platforms (IDP).', 'Target: 15% APER lift')
                ], 'Calculate your APER for the trailing twelve months and map it against headcount growth.'),
                l('Lesson 2: DORA Metrics in Practice', 'Lead Time completely dictates market responsiveness. But measuring it wrong hides the real bottlenecks. True Lead Time = Commit to Production. If PR reviews take 3 days, your DORA metrics are failing.', [
                    d('Deployment Frequency', 'How often code reaches production.', 'Target: On-demand (multiple times / day)'),
                    d('Lead Time for Changes', 'Time from PR merge to live production.', 'Target: < 1 hour'),
                    d('Change Failure Rate', 'Percentage of deployments forcing a rollback or hotfix.', 'Target: < 5%')
                ], 'Audit your CI/CD pipeline. Identify the single largest temporal bottleneck between Merge and Deploy.'),
                l('Lesson 3: The Engineering Scorecard', 'How to present engineering health to the executive team. The 5 metrics you actually show the CEO, removing all technical jargon and focusing entirely on capital efficiency and risk.', [
                    d('Uptime SLA', 'Standard availability metric.', 'Target: 99.9% / 43m downtime per mo'),
                    d('Time-to-Resolve', 'How quickly P1 incidents are closed.', 'Target: < 2 hours'),
                    d('Security Posture', 'Mean time to patch critical vulnerabilites.', 'Target: < 48 hours for CVSS > 9')
                ], 'Draft a quarterly engineering scorecard ready for the Board of Directors.')
            ]
        ],
        ['1-3', 'Cloud FinOps & Infrastructure Economics', 'Stop bleeding infrastructure capital. Master the economics of the cloud.', 
            ['Execute Cloud Cost Allocation', 'Optimize Kubernetes spend', 'Audit vendor lock-in', 'Design FinOps architecture'],
            [
                l('Lesson 1: The Cloud Margin Tax', 'Cloud providers are incentivized to make consumption frictionless. Without strict tagging policies, your cloud bill is an untraceable black box. Every infrastructure component must map back to a specific feature P&L.', [
                    d('Tagging Compliance', 'Percentage of infrastructure assets mapped to cost centers.', 'Target: > 95% compliance'),
                    d('Idle Resource Waste', 'Percentage of cloud bill spent on unattached EBS volumes or idle instances.', 'Target: < 3%'),
                    d('COGS Attribution', 'Cost of Goods Sold accurately mapped per tenant.', 'Required for gross margin analysis')
                ], 'Run an AWS/GCP cost explorer audit and identify top 3 untagged resource clusters.'),
                l('Lesson 2: Compute Arbitrage', 'Paying on-demand prices for baseline workloads is architectural malpractice. Mastering Reserved Instances (RIs), Savings Plans, and Spot Instance architectures can yield 60% gross margin improvements.', [
                    d('Spot Instance Orchestration', 'Running stateless workloads on preemptible compute.', 'Cost reduction: 70-90%'),
                    d('Commitment Coverage', 'Percentage of baseline compute covered by 1-or-3 year reservations.', 'Target: 60-80% of baseline'),
                    d('Rightsizing Down', 'Downgrading over-provisioned instance memory/CPU.', 'Review cadence: Monthly')
                ], 'Model the financial savings of migrating your stateless web cluster to purely Spot Instances.'),
                l('Lesson 3: Avoiding Vendor Lock-In', 'Using proprietary managed services (like DynamoDB or Spanner) accelerates shipping but creates massive exit costs. The Build vs. Buy framework for deciding when to use primitives (EC2/S3) versus managed services.', [
                    d('Exit Cost Calculation', 'The engineering months required to migrate off a proprietary DB.', 'Include data egress fees'),
                    d('Multi-Cloud Value', 'The leverage gained in enterprise contract negotiations.', 'Often yields 15-20% discounts'),
                    d('Open Source Primitives', 'Relying on Postgres/Redis instead of vendor-locked equivalents.', 'Maximizes architectural portability')
                ], 'Perform a lock-in audit. Rank your top 5 vendor dependencies by migration difficulty.')
            ]
        ],
    ];

    ctoMods.forEach(([id, title, desc, takeaways, lessons], i) => {
        modules[`engineering-economics/${id}`] = m(id, title, desc, t1, takeaways, lessons, getNext('engineering-economics', i, ctoMods.length));
    });

    // ═══════════════════ TRACK 2: PM / CPO ═══════════════════
    const t2 = 'Track 2 — Product Manager / CPO';
    const pmMods: [string, string, string, string[], ReturnType<typeof l>[]][] = [
        ['2-1', 'Product Unit Economics', 'Transition from backlog manager to AI Economist.', 
            ['Calculate Feature ROI', 'Perform the Feature Bloat Calculus', 'Stop building zombie features', 'Map adoption metrics'],
            [
                l('Lesson 1: The Feature P&L', 'Every feature has its own Profit & Loss statement. If a feature costs $50,000 to build and $2,000/mo to maintain, but only 3% of users adopt it, you have negative ROI. Stop building 0-value features.', [
                    d('Feature Build Cost', 'Engineering hours × Average hourly rate.', 'Include QA and design time'),
                    d('Feature Maintenance Cost', 'Annual support, bug fix, and cloud hosting cost.', 'Typically 20% of build cost per year'),
                    d('Adoption Threshold', 'The minimum % of users required to justify maintenance.', 'Target: > 15% Daily Active Usage')
                ], 'Select a feature launched 6 months ago. Calculate its exact P&L, including maintenance drag.'),
                l('Lesson 2: The Kill Switch Protocol', 'Most product managers only know how to launch. Elite product leaders know how to kill. Removing unused features reduces technical debt, simplifies the UI, and returns engineering velocity.', [
                    d('Zombie Identification', 'Features with < 3% adoption and high maintenance.', 'Prime targets for sunsetting'),
                    d('Deprecation Timeline', 'The communication runway needed to remove a feature without churn.', 'Usually 60-90 days'),
                    d('Velocity Return', 'The engineering hours regained by killing a complex feature.', 'Immediate boost to new roadmap items')
                ], 'Identify the lowest-performing feature in your product and draft the Kill Switch deprecation email.'),
                l('Lesson 3: Customer Acquisition Cost (CAC) Payback', 'A feature isn\'t just about engagement; it’s an acquisition or retention mechanic. If a feature lowers CAC payback time by improving onboarding, it is a massive financial win for the business.', [
                    d('CAC Payback Period', 'Months required for a customer to pay back their acquisition cost.', 'SaaS Target: < 12 months'),
                    d('Expansion Revenue (NRR)', 'Features that drive upsells to higher tiers.', 'Target Net Revenue Retention: > 110%'),
                    d('Onboarding Friction', 'Drop-off rate between sign-up and "Aha!" moment.', 'Target: < 20% drop-off')
                ], 'Map your product’s critical path to value. Where is the highest drop-off rate, and what feature removes it?')
            ]
        ],
        ['2-2', 'Cost of Delay & Prioritization', 'Stop relying on gut-feel. Use mathematical prioritization.', 
            ['Master WSJF pricing', 'Calculate Cost of Delay', 'Handle technical debt vs features', 'Defend roadmaps to leadership'],
            [
                l('Lesson 1: The Cost of Delay (CoD)', 'If you ship a feature 3 months late that generates $50,000/mo, your Cost of Delay is $150,000. Prioritization isn\'t just about ROI, it\'s about minimizing the financial penalty of waiting.', [
                    d('User-Business Value', 'The immediate revenue or retention saved.', 'Calculate in $ARR'),
                    d('Time Criticality', 'How the value decays over time (e.g., missing a holiday launch).', 'High / Medium / Low'),
                    d('Risk Reduction', 'Value gained by unblocking future work.', 'Crucial for platform teams')
                ], 'Calculate the Cost of Delay in pure dollars for your top 3 roadmap items.'),
                l('Lesson 2: WSJF (Weighted Shortest Job First)', 'WSJF = Cost of Delay / Job Size. A massive feature with high value might lose to a tiny feature with medium value because the tiny feature ships immediately and starts compounding returns.', [
                    d('Job Duration (Size)', 'Estimated engineering effort.', 'Use T-shirt sizing translated to weeks'),
                    d('WSJF Score', 'The definitive ranking metric.', 'Sort highest to lowest'),
                    d('Batch Size Reduction', 'Breaking large epics down into smaller ships to improve WSJF.', 'Deliver value iteratively')
                ], 'Take your current sprint backlog and recalculate the priority order strictly using WSJF.'),
                l('Lesson 3: The 70/20/10 Allocation Matrix', 'Balancing feature development against technical debt and innovation. If you give engineering 0% for technical debt, velocity will inevitably grind to a halt.', [
                    d('Core Features', '70% allocation to roadmap items driving ARR.', 'The primary engine'),
                    d('Technical Debt', '20% allocation to refactoring and infrastructure.', 'Prevents velocity decay'),
                    d('Innovation Bets', '10% allocation to high-risk, 10x potential experiments.', 'Protects against disruption')
                ], 'Audit your team\'s time allocation over the last quarter. Map it against the 70/20/10 matrix.')
            ]
        ],
        ['2-3', 'AI Feature Economics', 'Designing, managing, and launching AI-native product features.', 
            ['Structure Generative UI', 'Calculate LLM token margins', 'Design probabilistic UX', 'Mitigate hallucination liabilities'],
            [
                l('Lesson 1: Margin Collapse Warning', 'If you charge $10/mo for an AI feature, but a power user consumes $15/mo in OpenAI API calls, your margins are inverted. AI PMs must master token economics and rate limiting.', [
                    d('Token Margin Tax', 'The API cost subtracted from the subscription tier.', 'Target Gross Margin: > 70%'),
                    d('Hard Caps vs Throttling', 'Degrading the model (falling back to cheaper models) for heavy users.', 'Preserves unit economics'),
                    d('AUEB Ratio', 'Average Unit Economic Boundary. The max API calls before unprofitability.', 'Must be modeled before launch')
                ], 'Model the profitability of your AI feature assuming 5%, 50%, and 99th percentile usage patterns.'),
                l('Lesson 2: Probabilistic UX Design', 'Standard software is deterministic. AI is probabilistic. PMs must design UI that handles failure gracefully, embraces latency, and sets clear user expectations for hallucinations.', [
                    d('Time-to-First-Token (TTFT)', 'The speed at which generated content begins streaming.', 'Target: < 1.5 seconds'),
                    d('Feedback Loops', 'Thumbs up/down buttons immediately feeding back to fine-tunes.', 'Crucial for RLHF'),
                    d('Graceful Degradation', 'How the UI reacts when the LLM returns an error or timeout.', 'Always provide a manual fallback')
                ], 'Redesign an AI feature interface to include streaming, explicit feedback buttons, and a fallback state.'),
                l('Lesson 3: RAG vs. Fine-Tuning Strategy', 'Deciding whether your feature requires Retrieval-Augmented Generation (giving the LLM search results) or Fine-Tuning (teaching the model your tone/format). They solve entirely different problems.', [
                    d('RAG Dominance', 'Best for fetching facts, real-time data, and proprietary docs.', 'High latency but highly accurate'),
                    d('Fine-Tuning Role', 'Best for specific formatting (JSON routing) or brand tone.', 'Expensive to train, cheap to run'),
                    d('The Hybrid Approach', 'Using RAG for facts and a cheap fine-tuned router model.', 'The modern architecture standard')
                ], 'Determine whether your next AI feature requires RAG, Fine-tuning, or both. Provide the architectural justification.')
            ]
        ],
        ['2-17', 'Shadow AI & Data Extrusion', 'Preventing uncontrolled employee access to unauthorized LLMs and stopping IP leakage.', 
            ['Define Shadow AI', 'Establish Corporate GenAI Walls', 'Audit network endpoints', 'Create defensible AI policies'],
            [
                l('Lesson 1: The Shadow AI Threat', 'Shadow AI is the unauthorized use of generative AI tools by employees to perform company work. It is Shadow IT on steroids. When engineers paste proprietary code into public models, or analysts upload financial spreadsheets to unsecured chat interfaces, you suffer immediate, irreversible Intellectual Property extrusion.', [
                    d('IP Extrusion', 'The permanent loss of proprietary data to public model training sets.', 'Action: Immediate blocklist of unauthorized endpoints'),
                    d('Copyright Contamination', 'Pasting AI-generated code from public tools into your repos.', 'Creates massive legal liabilities in M&A'),
                    d('Compliance Breach', 'Violating GDPR or HIPAA through unsecured AI prompts.', 'Fines can reach millions')
                ], 'Perform an audit of employee AI tool usage. How many unauthorized generative AI interfaces are being accessed daily?'),
                l('Lesson 2: The Corporate GenAI Wall', 'You cannot stop employees from wanting to use AI to work faster. You must provide a secure, governed alternative. Establishing a "Corporate GenAI Wall" means deploying internal, enterprise-secured LLM interfaces that guarantee zero-retention policies.', [
                    d('Zero-Retention Contracts', 'Enterprise agreements that explicitly forbid model training on your data.', 'Mandatory for all AI vendors'),
                    d('Internal AI Portals', 'Providing secure chat interfaces that route to governed APIs.', 'Neutralizes the urge to use public tools'),
                    d('Endpoint DLP Integration', 'Updating Data Loss Prevention (DLP) tools to flag LLM traffic.', 'Action: Block pasting of sensitive data types')
                ], 'Design the architecture for an internal AI portal. What models will it use, and how will it ensure zero retention?'),
                l('Lesson 3: Governing the Adoption Curve', 'Transitioning from Shadow AI to Governed AI requires cultural engineering. You must prove to employees that the secure internal tools are just as capable as the public tools they were using illicitly.', [
                    d('Adoption Metrics', 'Tracking the usage of internal governed AI tools vs. blocked attempts to external tools.', 'Target: > 90% internal adoption'),
                    d('Amnesty Programs', 'Allowing employees to report their Shadow AI usage without penalty.', 'Crucial for discovering hidden workflows'),
                    d('Continuous Monitoring', 'Regularly scanning the network for new, unauthorized AI endpoints.', 'The AI market shifts weekly')
                ], 'Draft a company-wide communication announcing an Amnesty Program for Shadow AI usage and introducing the new Governed AI portal.')
            ]
        ],
    ];

    pmMods.forEach(([id, title, desc, takeaways, lessons], i) => {
        modules[`ai-product-economics/${id}`] = m(id, title, desc, t2, takeaways, lessons, getNext('ai-product-economics', i, pmMods.length));
    });

    // ═══════════════════ TRACK 3: Investor / PE / VC ═══════════════════
    const t3 = 'Track 3 — PE / VC / Investor';
    const invMods: [string, string, string, string[], ReturnType<typeof l>[]][] = [
        ['3-1', 'Technical Due Diligence Red Flags', 'Exposing hidden technical risks that destroy M&A enterprise value.', 
            ['Spot legacy code rot', 'Audit key person dependencies', 'Evaluate architecture scaling ceilings', 'Assess AI lock-in risks'],
            [
                l('Lesson 1: Valuing Technical Debt in Deals', 'A target company with $10M ARR looks great until you realize their codebase is 15 years old and moving to the cloud will cost $2M in R&D. That $2M must be subtracted from the enterprise valuation.', [
                    d('Platform Re-Platforming Cost', 'The capital required post-close to modernize.', 'Subtract directly from EBITDA multiples'),
                    d('Version Lock-in', 'Dependencies on deprecated frameworks (e.g. Angular 1).', 'Severe risk of systemic failure'),
                    d('The QoT Report', 'Quality of Technology assessment delivered to the deal team.', 'Mandatory before LOI signing')
                ], 'Run a simulated QoT evaluation on a target architecture diagram, identifying three severe PDI flags.'),
                l('Lesson 2: Key Person Dependency', 'If the company relies on one Senior Architect who holds all system knowledge in their head, the asset is immensely fragile. If they quit post-acquisition, the value drops to zero.', [
                    d('Bus Factor', 'The number of people who can securely operate the system.', 'Target > 3 for core systems'),
                    d('Documentation Coverage', 'Is the system architecture codified or tribal knowledge?', 'Warning sign: Zero diagrams'),
                    d('Equity Lock-ups', 'Ensuring the core technical team is tied to the earn-out.', 'Vital for transition continuity')
                ], 'Assess the key person risk in a due diligence data room based on their git commit history distribution.'),
                l('Lesson 3: Architecture Scaling Ceilings', 'The code works at 1,000 users. Will it work at 100,000? Investors pay for future scale. Identify monolithic bottlenecks and database deadlocks that will require ground-up rewrites.', [
                    d('Database Sharding Limits', 'Can the data tier scale horizontally?', 'Single-instance bottlenecks = Severe Risk'),
                    d('Stateless Compute', 'Can the application tier auto-scale?', 'Stateful monoliths require massive ops work'),
                    d('CDN Distribution', 'Is the edge network protecting the origin servers?', 'Standard for global scalability')
                ], 'Examine an infrastructure topology bill (AWS report) to determine if the target company is scaling efficiently.')
            ]
        ],
        ['3-2', 'SaaS Unit Economics', 'Connect software telemetry directly to LTV, CAC, and NRR.', 
            ['Audit Annual Recurring Revenue', 'Calculate Net Revenue Retention', 'Evaluate Rule of 40 compliance', 'Optimize Gross Margins'],
            [
                l('Lesson 1: The Rule of 40', 'Growth Rate % + Profit Margin % must equal 40. A company growing at 20% must have a 20% profit margin. If engineering R&D is burning too much cash without generating feature adoption, the Rule of 40 collapses.', [
                    d('R&D to Revenue Ratio', 'How efficiently engineering spend turns into ARR.', 'Target: ~20% of revenue for mature SaaS'),
                    d('Profitability Levers', 'Cutting cloud waste to boost the profit side of the 40.', 'FinOps immediately boosts metrics'),
                    d('Growth Anchors', 'Technical debt slowing the growth side of the 40.', 'Refactoring unblocks features')
                ], 'Calculate the Rule of 40 for a target SaaS showing 18% growth and heavy AWS infrastructure spend.'),
                l('Lesson 2: Net Revenue Retention (NRR)', 'It\'s cheaper to retain a user than buy a new one. NRR > 100% means your current customers buy more upgrades than the revenue lost to churn. High codebase instability wrecks NRR.', [
                    d('Defect-to-Churn Correlation', 'How bug frequency drives customer cancellation.', 'Identify P1 defect rates'),
                    d('Expansion Revenue', 'Upgrading users via new premium API or AI features.', 'Drives NRR to 120%+'),
                    d('SLA Penalties', 'Money lost through SLA breach credits due to downtime.', 'A direct hit to MRR')
                ], 'Model the enterprise value difference between a target with 95% NRR vs 110% NRR over a 5-year hold.'),
                l('Lesson 3: Cloud Gross Margins', 'SaaS should command 80%+ gross margins. If a target is hitting 40% margins, their cloud architecture is fundamentally broken (usually massive database over-provisioning or inefficient AI execution).', [
                    d('COGS Definition', 'Cost of Goods Sold (AWS bill + support team).', 'Must be meticulously audited'),
                    d('Margin Compression', 'Generative AI API costs destroying traditional SaaS margins.', 'Requires immediate SLM strategy'),
                    d('Optimization Targets', 'Expected margin recovery post-acquisition via FinOps.', 'Typical recovery: 15-20%')
                ], 'Audit an AWS invoice to identify margin compression. Provide a 3-step turnaround plan to push margins back to 80%.')
            ]
        ],
        ['3-3', 'AI Investment Thesis', 'Auditing AI wrappers, deep tech, and the margin collapse risk.', 
            ['Separate Wrappers from Foundations', 'Spot AI vendor lock-in', 'Evaluate proprietary data moats', 'Calculate AI Gross Margins'],
            [
                l('Lesson 1: The AI Wrapper Trap', 'If a startup is just a thin UI over the OpenAI API, their economic moat is zero. You are investing in a prompt, which OpenAI will eventually bundle into their core offering.', [
                    d('Proprietary Data Moat', 'Does the startup own data that the base LLM lacks?', 'The only true defense'),
                    d('Fine-Tuned Weights', 'Have they trained a proprietary SLM (Small Language Model)?', 'Defines durable enterprise value'),
                    d('API Cost Vulnerability', 'If OpenAI raises prices, does the startup die?', 'Assess margin resilience')
                ], 'Evaluate three AI startups. Categorize them as Thin Wrappers, Semantic Data Moats, or Foundational Tech.'),
                l('Lesson 2: Data Quality & Governance', 'An AI is only as valuable as its ingestion pipeline. If a target company is training models on toxic, un-scrubbed PII, they carry massive compliance liabilities (GDPR fines, IP infringement).', [
                    d('Data Provenance', 'Can they prove where the training data originated?', 'Prevents copyright lawsuits'),
                    d('PII Scrubbing Pipelines', 'Are they leaking user data into the LLM context?', 'Check for basic DLP architecture'),
                    d('RAG Architecture Integrity', 'Is their vector search returning hallucinated contexts?', 'Audit the embedding pipeline')
                ], 'Draft the 5 critical AI Governance questions you must ask the CTO during diligence.'),
                l('Lesson 3: Post-Acquisition AI Strategy', 'How to multiply the value of a traditional SaaS acquisition by injecting AI agents into their monolithic workflows. The Agentic Value Creation Playbook.', [
                    d('Workflow Automation', 'Replacing manual SaaS clicks with conversational agents.', 'Drives massive UX improvements'),
                    d('Predictive Analytics', 'Up-selling enterprise tiers based on proprietary forecasting.', 'Drives NRR expansion'),
                    d('Operating Cost Reduction', 'Using AI to replace massive L1 support and operations teams.', 'Drives EBITDA expansion')
                ], 'Create a 100-day post-close plan to inject Agentic AI into a legacy B2B SaaS platform.')
            ]
        ],
        ['3-16', 'The Innovation Tax Audit', 'Are your software assets still generating value, or are they just burning resources? A guide to auditing your portfolio and killing zombie features.', 
            ['Identify Zombie Assets', 'Apply the Rule of Two', 'Execute the Scream Test', 'Establish Sunset Committees'],
            [
                l('Lesson 1: Diagnosing Zombie Assets', 'Every codebase harbors Zombie Assets—features that are technically alive but functionally dead. They consume compute resources, inflate test suites, and distract engineering attention, yet they deliver zero marginal value to the customer.', [
                    d('The Rule of Two', 'Look for features that have not been touched by a user in two months or updated by a developer in two years. If a feature hits both markers, it is a prime candidate for the morgue.', 'Audit your codebase with these metrics'),
                    d('Silent Drain', 'The hidden maintenance cost of code that never errors but never adds value.', 'Calculated in wasted infrastructure compute and engineering support'),
                    d('Risk Aversion', 'The psychological trap where removing features seems riskier than leaving them alone.', 'Combat through data-driven usage metrics')
                ], 'Identify three features in your primary application that likely meet the Rule of Two and propose them for a sunset review.'),
                l('Lesson 2: Executing the Scream Test', 'Once identified, how do you kill Zombie Assets safely? The cheapest way is the Scream Test: turn the feature off in staging, then production, and see if anyone complains. Most of the time, there will be silence.', [
                    d('Safe Shutoff', 'Disabling the code path without deleting the code repository—initially.', 'Use feature flags for easy reversal'),
                    d('Monitoring for Noise', 'Tracking customer support tickets and user behavior post-shutdown.', 'Establish a defined monitoring window (e.g., 2 weeks)'),
                    d('Final Deletion', 'If the Scream Test passes with silence, completely remove the code and its dependencies.', 'Claim the engineering velocity reward')
                ], 'Design a Scream Test for one low-usage feature. Draft the communication to support teams to handle potential (but unlikely) complaints.'),
                l('Lesson 3: Governing Asset Retirement', 'Real innovation doesn\'t just come from writing new code. It comes from having the courage to delete the code that no longer serves you. This requires structured governance.', [
                    d('Sunset Committees', 'An operational body with one explicit KPI: code retirement.', 'Meeting quarterly to review usage and mandate sunsets'),
                    d('Depersonalizing Deletion', 'Removing the emotional weight of deprecation from the original creators.', 'Treating retirement as routine maintenance, not a referendum on past work'),
                    d('Reclaiming Capital', 'Translating the deletion of a Zombie Asset back into the engineering P&L.', 'Quantifying the recovered velocity')
                ], 'Draft a charter for a new Sunset Committee, outlining its objective to reclaim 5% of engineering capacity through systematic code retirement.')
            ]
        ],
        ['3-17', 'Managing Shadow AI Risk', 'Defending enterprise IP against the existential threat of unauthorized generative AI usage.', 
            ['Quantify IP Extrusion Risk', 'Audit network perimeters', 'Enforce DLP policies', 'Deploy Sovereign Substrates'],
            [
                l('Lesson 1: The Executive View of Shadow AI', 'Shadow IT was about uncontrolled SaaS spend. Shadow AI is about uncontrolled IP loss. When your product team uses an unsecured public LLM to brainstorm next year’s roadmap, your intellectual property has left the building. Boards must understand this is an existential, not just operational, risk.', [
                    d('The Training Set Vulnerability', 'Your proprietary data becoming part of a public model\'s knowledge base.', 'Competitors can literally query your secrets'),
                    d('Regulatory Exposure', 'Unsanctioned AI usage violating data residency laws.', 'Immediate compliance failure'),
                    d('The Speed-Security Tradeoff', 'Balancing the need for AI velocity with the need for data protection.', 'Requires executive mandate')
                ], 'Brief the board on the specific IP risks posed by Shadow AI within your organization. Quantify the potential loss in valuation if core IP is leaked.'),
                l('Lesson 2: Defensible Network Architectures', 'Combating Shadow AI requires a hardened network perimeter. You must deploy advanced Data Loss Prevention (DLP) to monitor and block sensitive data flowing to known AI endpoints, while simultaneously routing traffic to secured, internal API endpoints.', [
                    d('Endpoint Scanning', 'Identifying and categorizing all AI-related traffic leaving the corporate network.', 'Action: Deploy Shadow AI Scanners'),
                    d('Corporate GenAI Walls', 'Establishing explicit, governed pathways for AI usage.', 'Zero-retention enterprise agreements only'),
                    d('Sovereign Substrates', 'Running Small Language Models (SLMs) entirely within your VPC.', 'The ultimate defense against data extrusion')
                ], 'Develop a technical remediation plan to block the top 10 most commonly used unauthorized AI tools while standing up a Sovereign Substrate alternative.'),
                l('Lesson 3: Creating a Culture of Governed AI', 'Technology alone cannot stop Shadow AI. If the internal, governed tools are inferior to the public ones, employees will find workarounds. Executives must champion the adoption of secure AI tools and penalize the use of unauthorized ones.', [
                    d('Amnesty and Education', 'Discovering existing Shadow AI workflows through non-punitive reporting.', 'Convert shadow workflows to governed ones'),
                    d('The Golden Dataset', 'Providing employees with high-quality, sanitized internal data for AI use.', 'Increases the value of internal tools'),
                    d('Ongoing Audit Cadence', 'Regularly reviewing AI usage policies and network traffic.', 'Shadow AI is a moving target')
                ], 'Draft a comprehensive "Acceptable AI Use Policy" that clearly delineates governed tools from prohibited tools and outlines the consequences of IP extrusion.')
            ]
        ],
        ['3-18', 'Technical Debt vs Technical Insolvency', 'Understanding the critical threshold where maintenance costs terminalize your engineering capability.', 
            ['Differentiate Debt from Insolvency', 'Identify the Event Horizon', 'Calculate the PDI limit', 'Communicate collapse to the Board'],
            [
                l('Lesson 1: The Gradual Decay of Technical Debt', 'Technical debt is a normal, healthy part of software development. It represents the deliberate choice to optimize for speed over perfection. Like financial debt, it allows you to leverage future capacity to capture immediate market share. But it must be serviced.', [
                    d('Linear Cost Accumulation', 'The steady increase in maintenance time as codebases grow.', 'Expected and manageable'),
                    d('Interest Payments', 'The time spent refactoring and updating dependencies.', 'Required to prevent compounding'),
                    d('The Velocity Drag', 'The slight, noticeable slowing of feature delivery.', 'The primary symptom of unmanaged debt')
                ], 'Audit your backlog. What percentage of current tickets represent "interest payments" on past technical debt?'),
                l('Lesson 2: The Event Horizon: Technical Insolvency', 'Technical Insolvency is not just "a lot of debt." It is a terminal state. It occurs when the maintenance load consumes 100% of engineering capacity, reducing feature velocity to zero. The company can no longer innovate; it can only struggle to survive.', [
                    d('The Non-Linear Collapse', 'The point where adding new engineers actually slows development down further.', 'Brooks\' Law in action'),
                    d('The PDI Threshold', 'When the Product Debt Index indicates that any change carries an unacceptable risk of catastrophic failure.', 'PDI > 100'),
                    d('The Market Penalty', 'Competitors with clean architectures out-ship you 10 to 1.', 'Results in rapid loss of market share')
                ], 'Calculate your current distance from Technical Insolvency. At current rates of debt accumulation, when will maintenance consume 100% of capacity?'),
                l('Lesson 3: Board Communication and Remediation', 'You cannot explain Technical Insolvency to a board using engineering terms. You must explain it as a collapse of the R&D asset. Remediation requires drastic action: feature freezes, massive capital expenditure on refactoring, or complete platform replacement.', [
                    d('The Asset Write-Down', 'Explaining that the codebase is no longer an asset, but a liability.', 'Frame in terms of lost EBITDA'),
                    d('The Capital Injection Request', 'Securing budget specifically for remediation, not new features.', 'Requires a hard ROI calculation'),
                    d('The Turnaround Strategy', 'Deploying the Strangler Fig pattern to systematically replace insolvent systems.', 'The only viable path back to solvency')
                ], 'Draft a presentation to the Board of Directors explaining that a core system is nearing Technical Insolvency and requesting a 6-month feature freeze to remediate.')
            ]
        ],
    ];

    invMods.forEach(([id, title, desc, takeaways, lessons], i) => {
        modules[`rd-capital-management/${id}`] = m(id, title, desc, t3, takeaways, lessons, getNext('rd-capital-management', i, invMods.length));
    });

    // ═══════════════════ TRACK 4: AI Enterprise Architect ═══════════════════
    const t4 = 'Track 4 — AI & Enterprise Architect';
    const aiMods: [string, string, string, string[], ReturnType<typeof l>[]][] = [
        ['4-1', 'AI Infrastructure & RAG Architecture', 'Deploying enterprise AI securely, affordably, and accurately.', 
            ['Optimize Vector Databases', 'Structure RAG pipelines', 'Calculate embedding costs', 'Deploy hybrid search mechanisms'],
            [
                l('Lesson 1: Scaling Vector Databases', 'Managed vector DBs (Pinecone, Weaviate) are easy but expensive at massive scale. Transitioning to pgvector or localized Milvus can cut infrastructure costs by 80% once you hit 100M+ vectors.', [
                    d('Vector Dimension Cost', 'Higher dimensions (1536) mean higher RAM costs.', 'Optimize embedding models'),
                    d('HNSW Graph Tuning', 'Balancing recall accuracy versus query latency.', 'Target: ~50ms recall times'),
                    d('Self-Hosted vs Managed', 'The operational tipping point for moving off Pinecone.', 'Usually > 50M vectors')
                ], 'Design an architecture diagram for migrating a Managed Vector DB to a self-hosted pgvector cluster on Kubernetes.'),
                l('Lesson 2: Advanced RAG Optimization', 'Naive RAG (chunk document -> embed -> search) fails in production. You must master Semantic Routing, Parent-Child Document retrieval, and Reranking algorithms to break through the 60% accuracy ceiling.', [
                    d('Cross-Encoder Reranking', 'Re-scoring top 50 results for precision.', 'Massive accuracy lift, slight latency hit'),
                    d('Semantic Query Routing', 'Using SLMs to route user intent to specific vector indices.', 'Reduces context window pollution'),
                    d('Chunking Strategies', 'Semantic boundary chunking vs token overlap.', 'Prevents fragmented context')
                ], 'Upgrade a naive RAG pipeline design by inserting a Semantic Router and a Cohere Reranker node.'),
                l('Lesson 3: The Cost of Predictivity', 'Every token matters. If your RAG pipeline injects 10k tokens of context for every query, you are burning capital for minor accuracy gains. The curve of accuracy vs cost is logarithmic.', [
                    d('Token Efficiency', 'Information density of the retrieved chunks.', 'Summarize chunks before inference'),
                    d('Context Window Waste', 'Paying for tokens the LLM ignores (Lost in the Middle).', 'Inject crucial facts at start/end of prompt'),
                    d('Caching Layer Returns', 'Semantic caching for repetitive queries.', 'Identical queries hit Redis, bypassing OpenAI')
                ], 'Calculate the daily cost of a 10K prompt context at 100 queries/min. Redesign the flow to reduce costs by 50%.')
            ]
        ],
        ['4-2', 'SLMs & Local Edge Inference', 'Severing the API oligopoly dependencies with Small Language Models.', 
            ['Deploy Llama 3 8B locally', 'Master QLoRA quantization', 'Achieve zero-latency inference', 'Cut token costs by 90%'],
            [
                l('Lesson 1: The API Margin Tax', 'Relying exclusively on hyperscalers for LLM inference introduces a permanent Margin Tax. Every request costs compute. By deploying Small Language Models (SLMs) locally, you sever the transaction cost.', [
                    d('VRAM Economics', 'The capital cost of buying GPUs vs renting API tokens.', 'Calculate the break-even horizon (usually 6-9 months)'),
                    d('Data Sovereignty', 'Processing PII directly on local edge hardware.', 'Guarantees GDPR/HIPAA compliance'),
                    d('Inference Latency', 'Eliminating internet round-trips to OpenAI servers.', 'Reduces TTFT to <20ms')
                ], 'Identify the three highest-volume AI primitives in your system that can be downgraded to an 8B perimeter model.'),
                l('Lesson 2: Quantization Architectures', 'You cannot casually load an FP16 model into an edge server without extreme cloud waste. Converting models via GGUF down to 4-bit quantization reduces VRAM by over 70% while suffering <3% fidelity loss.', [
                    d('4-Bit Quantization', 'Compressing model weights for consumer and edge hardware.', '< 8GB VRAM reqs for Llama 3 8B'),
                    d('Throughput Optimization', 'Using vLLM or Ollama for high-concurrency batching.', 'Maximizes GPU utilization'),
                    d('Fidelity Degradation', 'Testing the accuracy drop of quantized models.', 'Must run automated MMLU benchmarks')
                ], 'Calculate the exact VRAM required to serve a 4-bit quantized 70B parameter model. Choose the appropriate AWS EC2 instance.'),
                l('Lesson 3: Fallback Routing & Agent Hand-offs', 'SLMs handle the easy, high-frequency requests. If the SLM lacks confidence, it dynamically routes the prompt to an expensive model (GPT-4o). You pay for high intelligence only when necessary.', [
                    d('Confidence Thresholds', 'Detecting when the SLM is hallucinating or confused.', 'Triggers the fallback API'),
                    d('Router Latency', 'The overhead of decision-making before execution.', 'Use ultra-fast classifier models (sub 10ms)'),
                    d('Cascading Cost Savings', 'The net architectural blend of API vs Local costs.', 'Target: 80% Local / 20% API')
                ], 'Draft an intent-classification logic matrix that determines which queries go to local Llama vs remote GPT-4o.')
            ]
        ],
        ['4-3', 'AI Security & Zero-Trust Execution', 'Securing the Generative Attack Surface from injection and data leakage.', 
            ['Implement Data Loss Prevention (DLP)', 'Harden prompt injection defenses', 'Execute sandboxed code safely', 'Perform LLM ethical audits'],
            [
                l('Lesson 1: Prompt Injection & The Attack Surface', 'Unbounded context windows mean an attacker can execute prompt injection to extract data. The LLM is essentially a database with a conversational SQL injection vulnerability.', [
                    d('Blast Radius Isolation', 'Limiting what the LLM can access via RAG APIs.', 'RBAC on vector queries'),
                    d('System Prompt Hardening', 'Delimiters, XML tags, and strict formatting rules.', 'Prevents basic jailbreaks'),
                    d('Adversarial Testing', 'Red-teaming the LLM with automated injection payloads.', 'Mandatory CI/CD security step')
                ], 'Write a hardened system prompt using XML delimiters that successfully passes a simulated prompt injection attack.'),
                l('Lesson 2: Outbound Data Loss Prevention (DLP)', 'Before any packet leaves the perimeter for third-party inference, it must pass through an outbound DLP gateway. Implement Named Entity Recognition (NER) models to anonymize data BEFORE transit.', [
                    d('PII Scrubbing Latency', 'The time cost of sanitizing a prompt using local NER.', 'Target: < 30ms via Microsoft Presidio'),
                    d('Re-hydration Architecture', 'Mapping scrubbed tokens back to real names on the response.', 'Ensures invisible UX continuity while protecting data'),
                    d('Compliance Auditing', 'Logging every scrubbed outbound payload.', 'Proves compliance to ISO auditors')
                ], 'Design a DLP pipeline that intercepts an outbound LLM request, sanitizes PII, hits the API, and rehydrates the response.'),
                l('Lesson 3: Agentic Sandboxing', 'When you give an AI Agent tools to execute code, run database queries, or send emails, you are opening a massive threat vector. Zero-Trust requires sandboxed execution environments.', [
                    d('Ephemeral Containers', 'Running generated code in isolated, short-lived Docker pods.', 'Ensures no systemic compromise'),
                    d('Scope Restrictions', 'Strict whitelisting of allowed API endpoints and commands.', 'Deny-by-default architecture'),
                    d('Read-Only Fallbacks', 'Enforcing Human-in-the-Loop (HITL) for destructive actions.', 'Agents can draft, humans must click "Send"')
                ], 'Architect a secure execution enclave for an AI agent tasked with analyzing a CSV file and outputting SQL commands.')
            ]
        ],
    ];

    aiMods.forEach(([id, title, desc, takeaways, lessons], i) => {
        modules[`capstone/${id}`] = m(id, title, desc, t4, takeaways, lessons, getNext('capstone', i, aiMods.length));
    });
}
