import { CurriculumModule, l, d, m } from './curriculum-data';

export const tracks26Modules: Record<string, CurriculumModule> = {};
const t26 = 'Track 26 — AI-Native Internal Developer Platforms (IDPs)';

tracks26Modules['idps/26-1'] = m('26-1', 'The Collapse of DevOps Tool Sprawl', 'Abstracting cognitive load, platform engineering, paved roads.', t26, 
    ['Eradicate infrastructure cognitive load', 'Deploy the Golden Path'], [
        l('Developer Friction and The Golden Path', 
            [
                'For the last decade, the philosophy of "You build it, you run it" forced standard frontend and backend developers to possess deep, painful mastery of esoteric infrastructure layers like Kubernetes, Terraform, AWS IAM roles, and dense CI/CD pipelines. This resulted in epic cognitive overload, utterly destroying raw coding velocity.', 
                'Platform Engineering directly opposes this via the Internal Developer Platform (IDP). The IDP is a heavily automated "Paved Road" or "Golden Path". An engineer requests a "Standard Web App", and the IDP autonomously provisions the exact GitHub repo, the strictly compliant Terraform state, the exact Kubernetes manifests, and the deployment pipelines instantly. No infrastructure knowledge required.',
                'By 2026, the velocity ceiling of a company is purely restricted by the quality of its IDP. Forcing senior software engineers to write YAML configuration scripts is an unacceptable waste of corporate capital.'
            ],
            [
                d('Time to First Commit (Onboarding)', 'The total duration spanning a new engineer’s first day to their first production deployment.', '< 1 Day Mandatory Target'),
                d('Infrastructure Cognitive Waste', 'The literal developer hours burned attempting to configure complex cloud networking instead of writing business logic.', 'Massively Eliminated')
            ], 
            'Audit the explicit manual infrastructure steps required to launch a "Hello World" microservice.', 
            ['Track the exact number of JIRA tickets required for a developer to request a new Database table from DevOps.', 'Analyze the time delay of routing cloud-permission approvals.', 'Draft an architectural schema for a fully self-service UI template interface.'], 
            {
                question: 'What is the primary philosophical shift driving the adoption of Internal Developer Platforms (IDPs)?',
                options: ['Developers need to learn advanced Unix networking', 'Software engineers should spend 99% of their time writing actual business logic; forcing them to manually configure massive, complicated Kubernetes deployment states is an atrocious waste of highly-paid cognitive bandwidth', 'It allows the company to use older servers', 'It prevents AI from replacing developers'],
                correctIndex: 1,
                explanation: 'An IDP abstracts away all the painful infrastructure plumbing. The developer inputs code, and the IDP handles everything else required to securely launch it onto the internet.'
            }
        )
    ], '/vault/curriculum/tracks/idps/26-2', undefined, 'live'
);

tracks26Modules['idps/26-2'] = m('26-2', 'Agentic Code Scaffolding', 'Autonomous repo creation, security linting, AI integration.', t26, 
    ['Integrate autonomous security scanners', 'Execute AI pre-flight code reviews'], [
        l('The AI-Native Platform Layer', 
            [
                'A traditional IDP provisions the infrastructure correctly. An "AI-Native IDP" provisions the infrastructure and simultaneously primes the contextual intelligence required to continuously maintain it. When the platform generates a microservice, it automatically generates the hyper-specific AI context bounds for the repository.', 
                'It instantly writes the `.cursorrules` file or the `copilot-instructions.md` file, strictly defining the precise architectural boundaries, linting styles, and API contract obligations natively into the repo prompt space.',
                'Furthermore, it injects an autonomous "Pre-Flight Security Review Agent" directly into the CI/CD pipeline, guaranteeing that every line of code deployed from the Platform is fiercely audited for hallucinated bugs or insecure logic prior to human review.'
            ],
            [
                d('Prompt Context Priming rate', 'The percentage of new repositories instantly pre-configured with organizational AI context files.', 'Must be 100% via Platform'),
                d('Agentic Pipeline Defect Catch', 'The total volume of critical code vulnerabilities intercepted by the IDP AI node before master-branch merge.', 'Highly Critical Security Layer')
            ], 
            'Execute an AI ruleset injection directly into the IDP boilerplate templates.', 
            ['Ensure every template generated by the platform team instantly contains a rigid markdown ruleset explicitly detailing how AI agents should interact with the stack.', 'Hook the repository creation event into an AI system prompting the exact constraints for future code generations.', 'Inject a mandatory AI review step into the scaffolding Github Action.'], 
            {
                question: 'What fundamentally differentiates an AI-Native IDP from a standard Developer Platform?',
                options: ['It uses darker colors in the UI', 'It actively injects localized structural system prompts (`.cursorrules`) into newly built repositories, ensuring any coding agents subsequently utilized by the developer fundamentally understand the strict architectural constraints of the architecture', 'It requires using Python', 'It shuts off the servers at night'],
                correctIndex: 1,
                explanation: 'A platform doesn\'t just configure servers; it configures context. By seeding repositories with explicit rules engines, the platform mathematically bounds future AI coding agents.'
            }
        )
    ], '/vault/curriculum/tracks/idps/26-10', undefined, 'live'
);

for (let i = 3; i <= 10; i++) {
    tracks26Modules[`idps/26-${i}`] = m(`26-${i}`, `Advanced Platform Ergonomics ${i}`, `Expansion module tracking deep platform engineering scaling systems.`, t26, 
        ['Optimize Developer Experience (DX)', 'Eliminate JIRA ticket pipelines', 'Enforce Global Compliance'], [
            l(`Deep IDP Abstractions ${i}`, 
                [
                    `Continuing the expansion into Platform Engineering and Developer Portals (like Backstage). The failure to treat internal engineering efficiency as a literal Tier-1 Product guarantees sluggish feature delivery.`, 
                    `The executive strategy demands viewing the IDP as a product, and the internal developers as the hyper-critical customer. If the platform is harder to use than AWS console, the developers will violently reject it.`,
                    `The architecture absolutely mandates establishing massive template catalogs to prevent the constant manual reinvention of standard microservice plumbing.`
                ],
                [
                    d(`Internal Net Promoter Score ${i}`, `The real-time metric tracking how effectively the IDP eliminates pain for the engineering staff.`, `Must track continuously`),
                    d(`Shadow IT Evasion Rate ${i}`, `The percentage of developers actively bypassing the IDP to deploy manually.`, `Must crush to zero`)
                ], 
                `Architect stringent Self-Service workflows via backstage.`, 
                [`Integrate massive software catalog tracking within the platform UI.`, `Monitor the deployment metrics of autonomous infrastructure pipelines.`, `Force rigorous abstraction over massive Terraform configs.`], 
                {
                    question: `Why is an IDP considered a "Product" rather than just an IT operations ticket system?`,
                    options: [`You sell it to other companies`, `Because its ultimate goal is maximizing the Developer Experience (DX) and velocity of the internal user—requiring product analytics, UX testing, and continuous feedback loops to ensure high adoption`, `Because it has an expensive logo`, `Because it requires a credit card to use`],
                    correctIndex: 1,
                    explanation: `Developers will completely abandon complicated, slow internal tools. Treating the IDP like a high-end consumer SaaS product is the only way to successfully scale its adoption.`
                }
            )
        ], i < 10 ? `/vault/curriculum/tracks/idps/26-${i+1}` : undefined, undefined, 'live'
    );
}
