export interface ExogramDoc {
    id: string;
    slug: string;
    title: string;
    category: string;
    description: string;
    content: {
        type: 'h2' | 'p' | 'code' | 'ul';
        text?: string;
        items?: string[];
        language?: string;
    }[];
}

export const exogramDocs: ExogramDoc[] = [
    // --- ARCHITECTURE ---
    {
        id: 'schema-integrity',
        slug: 'schema-integrity',
        title: 'Schema Integrity Engine',
        category: 'Architecture',
        description: 'Prevent AI parser collapse, payload mismatch, and bad JSON structure errors.',
        content: [
            { type: 'p', text: 'The Schema Integrity Engine ensures that every output generated by an LLM conforms exactly to your application\'s expected data structures. By enforcing strict JSON schemas, Protocol Buffers, or custom AST shapes, it eliminates parsing errors.' },
            { type: 'h2', text: 'How It Works' },
            { type: 'p', text: 'When an AI node generates a response, the output is passed through a deterministic validation layer in under 5ms. If the schema is violated (e.g., missing keys, hallucinated fields, incorrect types), the engine automatically triggers a fast-repair loop or returns a safe fallback.' },
            { type: 'code', language: 'typescript', text: 'import { verifySchema } from "@exogram/sdk";\n\nconst result = await verifySchema(llmOutput, userSchema);\nif (!result.valid) {\n  throw new Error(result.errorGraph);\n}' },
            { type: 'h2', text: 'Performance' },
            { type: 'ul', items: ['Validation Latency: <5ms (p99)', 'Supported Formats: JSON, Avro, Protobuf, Zod', 'Repair Success Rate: 98% on first pass'] },
        ]
    },
    {
        id: 'boundary-control',
        slug: 'boundary-control',
        title: 'Boundary Control Protocol',
        category: 'Architecture',
        description: 'Stop autonomous agents from going rogue and draining session budgets.',
        content: [
            { type: 'p', text: 'The Boundary Control Protocol (BCP) prevents autonomous AI agents from wandering outside their defined operational mandate. Whether an agent is reading a database or triggering a financial transaction, BCP evaluates admissibility before execution.' },
            { type: 'h2', text: 'The Admissibility Engine' },
            { type: 'p', text: 'Before any tool call is dispatched, the EAAP (Exogram Action Admissibility Protocol) checks the action against a deterministic state-machine. If the action violates budget limits, scope definitions, or sequential logic, it is hard-blocked.' },
            { type: 'code', language: 'json', text: '{\n  "action": "execute_transfer",\n  "amount": 5000,\n  "admissible": false,\n  "reason": "Exceeds session budget block"\n}' }
        ]
    },
    {
        id: 'threat-prevention',
        slug: 'threat-prevention',
        title: 'Threat Prevention Layer',
        category: 'Architecture',
        description: 'Block prompt injections, jailbreak overrides, and outbound PII/IP leakage.',
        content: [
            { type: 'p', text: 'The Threat Prevention Layer acts as a bidirectional firewall for LLM payloads. It sanitizes inputs to prevent prompt injection and scrubs outputs to prevent data exfiltration and PII leakage.' },
            { type: 'h2', text: 'Inbound Sanitization' },
            { type: 'p', text: 'User inputs are vector-matched against known adversarial fingerprints and zero-day topological structures indicating jailbreak attempts. Safe inputs are passed; malicious inputs trigger an anomaly flag.' },
            { type: 'h2', text: 'Outbound Scrubbing' },
            { type: 'ul', items: ['PII Masking (SSN, Credit Cards, Emails)', 'Proprietary IP stripping', 'Toxicity classification'] }
        ]
    },
    {
        id: 'memory-integrity',
        slug: 'memory-integrity',
        title: 'Memory Integrity System',
        category: 'Architecture',
        description: 'Stop memory hallucinations and prevent signed state drift in conversational context.',
        content: [
            { type: 'p', text: 'Memory hallucinations occur when an LLM falsely claims to remember a user interaction that never happened. The Memory Integrity System solves this by cryptographically signing valid state context.' },
            { type: 'h2', text: 'State Hashing' },
            { type: 'p', text: 'Every valid context window update is hashed and stored in an immutable ledger. When an agent attempts to retrieve memory, the hash is verified. If the memory was hallucinated, the engine prevents the context insertion, keeping the agent grounded.' }
        ]
    },
    {
        id: 'shadow-agent-mitigation',
        slug: 'shadow-agent-mitigation',
        title: 'Shadow Agent Mitigation',
        category: 'Architecture',
        description: 'Detect and quarantine undocumented AI bots operating inside your network boundaries.',
        content: [
            { type: 'p', text: 'As organizations adopt autonomous AI, employees are deploying undocumented "Shadow Agents" that interact with internal APIs at machine speed. Exogram\'s Threat Prevention Layer stops rogue non-human actors by validating execution provenance.' },
            { type: 'h2', text: 'Execution Provenance Tracking' },
            { type: 'p', text: 'Every agentic action must supply a valid cryptographic trace linking the action directly back to an authorized, human-approved session. Unverified programmatic requests are instantly quarantined.' }
        ]
    },
    {
        id: 'semantic-caching-edge-filtering',
        slug: 'semantic-caching-edge-filtering',
        title: 'Semantic Caching & Edge Filtering Engine',
        category: 'Architecture',
        description: 'Slash runtime API spend by 50%+ using sub-millisecond edge code filters and vector similarity caches.',
        content: [
            { type: 'p', text: 'When running automated execution loops inside Exogram, token spend can scale rapidly if frontier models process routine logic that does not require complex reasoning. The Semantic Caching & Edge Filtering Engine places deterministic code filters and vector similarity matching in front of LLM endpoints.' },
            { type: 'h2', text: 'Sub-Millisecond Edge Filtering' },
            { type: 'p', text: 'Sub-millisecond edge filters evaluate incoming requests for deduplication, static rules, and simple code-based routing. Routine interactions are answered directly with traditional code without calling generative model APIs.' },
            { type: 'h2', text: 'Vector Semantic Caching' },
            { type: 'p', text: 'Requests passing the edge filter are checked against a high-performance vector similarity cache. Prompts matching historical intent thresholds (e.g. 0.92+ cosine similarity) are served instantly from local storage at near-zero cost. Only true cache misses escalate to frontier LLM inference.' },
            { type: 'code', language: 'typescript', text: 'import { ExogramEdgeFilter } from "@exogram/sdk";\n\nconst response = await ExogramEdgeFilter.execute({\n  prompt,\n  cacheThreshold: 0.92,\n  fallbackModel: "gpt-4o"\n});\n// Cut runtime API spend by 50%+ with zero quality loss' },
            { type: 'h2', text: 'Economic Impact' },
            { type: 'ul', items: ['Runtime API Spend Cut: >50%', 'Cache Hit Latency: <15ms', 'Response Quality Loss: 0%'] }
        ]
    },

    // --- CORE CONCEPTS ---
    {
        id: 'state-hashing',
        slug: 'state-hashing',
        title: 'State Hashing',
        category: 'Core Concepts',
        description: 'Attest context windows cryptographically to eliminate LLM execution drift.',
        content: [
            { type: 'p', text: 'State Hashing creates a deterministic signature for non-deterministic AI outputs. By hashing the exact sequence of prompts, tool calls, and verified responses, you guarantee the LLM\'s execution path.' },
            { type: 'h2', text: 'Implementation' },
            { type: 'p', text: 'At the end of every reasoning loop, Exogram generates an SHA-256 hash of the execution directed acyclic graph (DAG). This hash is used as the foundational state ID for the next inference step.' },
            { type: 'code', language: 'python', text: 'def get_state_hash(session_id):\n    # Returns the cryptographic proof of the interaction\n    return exogram.get_last_verified_state(session_id)' }
        ]
    },
    {
        id: 'action-admissibility',
        slug: 'action-admissibility',
        title: 'Action Admissibility',
        category: 'Core Concepts',
        description: 'Evaluate tool calls against budgets and policies before executing dangerous updates.',
        content: [
            { type: 'p', text: 'Action Admissibility is the Boolean evaluation of whether an AI-requested tool call is structurally valid, contextually appropriate, and organizationally safe to execute.' },
            { type: 'h2', text: 'The Three Checks' },
            { type: 'ul', items: ['Structural Check: Does the JSON payload match the tool schema?', 'Contextual Check: Does this action make sense sequentially?', 'Safety Check: Does this action violate read/write boundaries or budgets?'] }
        ]
    },
    {
        id: 'blast-radius-containment',
        slug: 'blast-radius-containment',
        title: 'Blast Radius Containment',
        category: 'Core Concepts',
        description: 'Limit the maximum operational and financial damage of a hijacked agent.',
        content: [
            { type: 'p', text: 'When an agent goes off the rails - either through hallucination or adversarial attack - Blast Radius Containment ensures the maximum resulting damage is bounded.' },
            { type: 'h2', text: 'Sandboxing' },
            { type: 'p', text: 'Agents run in isolated execution enclaves using Read-Only (RO) scopes by default. Write (RW) scopes are granted ephemerally through human-in-the-loop (HITL) overrides or strict EAAP verification sequences.' }
        ]
    },
    {
        id: 'deterministic-fallback',
        slug: 'deterministic-fallback',
        title: 'Deterministic Fallback',
        category: 'Core Concepts',
        description: 'Recover cleanly and trigger safety fallbacks when AI validation checks fail.',
        content: [
            { type: 'p', text: 'When an AI model fails a verification check (e.g., outputs invalid JSON or attempts an inadmissible action), applications need a reliable way to recover without crashing.' },
            { type: 'h2', text: 'Fallback Scenarios' },
            { type: 'ul', items: ['Re-prompting: Automatically instruct the LLM to fix its own syntax error (up to N retries).', 'Safe Defaults: Return a pre-configured neutral object.', 'Human Escalation: Pause the session and alert an operator.'] }
        ]
    },
    {
        id: 'audit-ledgers',
        slug: 'audit-ledgers',
        title: 'Audit Ledgers',
        category: 'Core Concepts',
        description: 'Immutable logging to prove AI safety and audit compliance for SOC 2.',
        content: [
            { type: 'p', text: 'In enterprise deployments, AI decisions must be auditable. Audit Ledgers record the exact prompt, the raw output, the verification result, and the execution trace in a tamper-evident database.' },
            { type: 'h2', text: 'Compliance Benefits' },
            { type: 'p', text: 'Essential for SOC 2, HIPAA, and EU AI Act compliance, ledgers allow security teams to reconstruct exactly why an AI made a specific decision at a specific time.' }
        ]
    },
    {
        id: 'latency-budgets',
        slug: 'latency-budgets',
        title: 'Latency Budgets',
        category: 'Core Concepts',
        description: 'Run full AI firewall validation checks under 5ms without bottlenecking latency.',
        content: [
            { type: 'p', text: 'Adding verification layers cannot bottleneck the application. Exogram enforces strict latency budgets for every check.' },
            { type: 'ul', items: ['Schema Validation: ~2ms', 'Threat Detection: ~15ms', 'Admissibility Check: ~5ms', 'State Hashing: ~1ms'] },
            { type: 'p', text: 'To achieve this, Exogram is built in Rust using WebAssembly modules deployed directly to the edge, running physically adjacent to your application logic.' }
        ]
    },
    {
        id: 'agentic-identity-rbac',
        slug: 'agentic-identity-rbac',
        title: 'Agentic Identity & RBAC',
        category: 'Core Concepts',
        description: 'Separate human credentials from AI swarm machine keys to prevent RBAC privilege escalation.',
        content: [
            { type: 'p', text: 'Standard Role-Based Access Control (RBAC) fails for autonomous AI. A human might have "database read" access, but their AI Agent should only be allowed to read specific anonymized tables. Exogram introduces Agentic Identity to separate human intent from machine execution.' },
            { type: 'h2', text: 'Machine-Specific Policies' },
            { type: 'p', text: 'By provisioning explicit Agentic Identities, Exogram enforces least-privilege boundaries specifically tailored to the reasoning capabilities of the LLM in use. High-risk write operations are strictly sandboxed or gated via human-in-the-loop.' }
        ]
    },

    // --- INTEGRATION ---
    {
        id: 'api-reference',
        slug: 'api-reference',
        title: 'API Reference',
        category: 'Integration',
        description: 'HTTP API reference for real-time AI security checks and structure verification.',
        content: [
            { type: 'p', text: 'The Exogram API allows any application to verify AI payloads over HTTP. All endpoints require a valid Bearer token.' },
            { type: 'h2', text: 'POST /v1/verify/schema' },
            { type: 'code', language: 'bash', text: 'curl -X POST https://api.exogram.ai/v1/verify/schema \\\n  -H "Authorization: Bearer EXO_KEY" \\\n  -d \'{"payload": "{...}", "schema_id": "usr_abc123"}\'' },
            { type: 'p', text: 'Returns a 200 OK with `valid: true` or a 400 Bad Request detailing the structural drift.' }
        ]
    },
    {
        id: 'sdk-setup',
        slug: 'sdk-setup',
        title: 'SDK Integration (TS/Python)',
        category: 'Integration',
        description: 'Drop-in SDK setup for real-time validation and guardrail checks in TS/Python.',
        content: [
            { type: 'p', text: 'The fastest way to deploy Exogram is via our official SDKs. They handle request batching, retry logic, and fallback gracefully.' },
            { type: 'h2', text: 'TypeScript Installation' },
            { type: 'code', language: 'bash', text: 'npm install @exogram/sdk' },
            { type: 'h2', text: 'Python Installation' },
            { type: 'code', language: 'bash', text: 'pip install exogram-py' }
        ]
    },
    {
        id: 'local-deployment',
        slug: 'local-deployment',
        title: 'Local Deployment (Docker)',
        category: 'Integration',
        description: 'Run the verification engine locally in air-gapped VPCs for maximum data sovereignty.',
        content: [
            { type: 'p', text: 'For air-gapped environments or applications with strict data sovereignty requirements, the Exogram Verification Engine can be deployed locally via Docker.' },
            { type: 'h2', text: 'Starting the Engine' },
            { type: 'code', language: 'bash', text: 'docker run -p 8080:8080 -e EXO_LICENSE=your_key exogram/engine:latest' },
            { type: 'p', text: 'This guarantees zero latency overhead from network transit and ensures proprietary data never leaves your VPC.' }
        ]
    },
    {
        id: 'custom-rulesets',
        slug: 'custom-rulesets',
        title: 'Defining Custom Rulesets',
        category: 'Integration',
        description: 'Write Rego policies to restrict agent refund limits and unauthorized tool execution.',
        content: [
            { type: 'p', text: 'Beyond basic schema validation, Exogram supports complex, cross-field logical business rules defined using OPA (Open Policy Agent) Rego policies.' },
            { type: 'h2', text: 'Example Policy' },
            { type: 'code', language: 'rego', text: 'package exogram.admissibility\n\ndefault verify = false\n\nverify {\n  input.action == "refund"\n  input.amount <= 50.00\n}' },
            { type: 'p', text: 'This policy guarantees an autonomous customer service agent cannot issue a refund greater than $50.00.' }
        ]
    },

    // --- PROTOCOLS ---
    {
        id: 'eaap-specification',
        slug: 'eaap-specification',
        title: 'EAAP Specification',
        category: 'Protocols & Standards',
        description: 'The open EAAP standard for secure tool-use handshakes and privilege negotiation.',
        content: [
            { type: 'p', text: 'EAAP is an open protocol defining how AI agents should negotiate permission to execute actions against host systems.' },
            { type: 'h2', text: 'The Admissibility Handshake' },
            { type: 'ul', items: ['1. Agent proposes an Action Intent Graph.', '2. Host evaluates Intent against Boundary Policies.', '3. Host returns a cryptographic Admissibility Token.', '4. Agent executes tool, passing the Token as authorization.'] }
        ]
    },
    {
        id: 'compliance-mapping',
        slug: 'compliance-mapping',
        title: 'SOC 2 & ISO 27001 Mapping',
        category: 'Protocols & Standards',
        description: 'Generate audit artifacts automatically for SOC 2 logical access and system operations.',
        content: [
            { type: 'p', text: 'Deploying autonomous AI heavily complicates compliance audits. Exogram automatically maps its verification layers to major framework controls.' },
            { type: 'h2', text: 'SOC 2 Trust Services Criteria' },
            { type: 'ul', items: ['CC6.1 (Logical Access): Handled by Boundary Control Protocol', 'CC7.1 (System Operations): Handled by Audit Ledgers', 'CC3.2 (Risk mitigation): Handled by Threat Prevention Layer'] },
            { type: 'p', text: 'Using Exogram provides instant artifact generation for auditors proving that your AI systems are deterministically bounded.' }
        ]
    }
];

export function getExogramDoc(slug: string): ExogramDoc | undefined {
    return exogramDocs.find(d => d.slug === slug);
}
