export type Role = 'engineering' | 'pm';

export interface Question {
    id: string;
    prompt: string;
    expected_signal: string;
    constraint?: string;
    context?: string;
}

export const QUESTION_BANK: Record<Role, Record<string, Question[]>> = {
    engineering: {
        orientation: [
            {
                id: "ENG-O1",
                prompt: "What do you believe the primary constraint is, and what specific information would you request before touching the system?",
                expected_signal: "Constraint recognition before action",
                context: "CONTEXT: You are joining a B2B SaaS company that processes customer data nightly.\nDATA (last 30 days):\n - Cloud costs up 40 percent\n - Batch jobs missing SLAs\n - No major features shipped",
                constraint: "CONSTRAINT: You may not see code yet."
            }
        ],
        audit: [
            {
                id: "ENG-A1",
                prompt: "Identify the single most dangerous failure mode and explain why it is the highest business risk.",
                expected_signal: "Verification depth and systemic risk detection",
                context: "CONTEXT: Below is a Python service generated by an AI assistant.\n - It runs correctly\n - It passes tests\n - It is deployed\n\nPROBLEM: It will fail at scale.",
            },
            {
                id: "ENG-A2",
                prompt: "Show how you would interrogate the AI to improve this code without introducing new operational or cost risk.",
                expected_signal: "AI interrogation skill",
                constraint: "CONSTRAINT: You may use AI tools."
            }
        ],
        defense: [
            {
                id: "ENG-D1",
                prompt: "What do you fix now, what do you defer, and what explicit risk are you accepting?",
                expected_signal: "Trade-off articulation and risk ownership",
                constraint: "CONSTRAINT: You can fix only one issue this week."
            }
        ]
    },
    pm: {
        diagnosis: [
            {
                id: "PM-D1",
                prompt: "What is the binding constraint, and which metric do you protect even if others worsen?",
                expected_signal: "Constraint identification and metric sacrifice",
                context: "CONTEXT (last two quarters):\n - Engagement flat\n - Revenue growth slowing\n - Enterprise churn rising",
                constraint: "CONSTRAINT: No new headcount or budget."
            }
        ],
        funeral: [
            {
                id: "PM-F1",
                prompt: "Which do you kill, and who will be upset?",
                expected_signal: "Willingness to disappoint",
                context: "CONTEXT: Five roadmap initiatives are in flight.",
                constraint: "CONSTRAINT: You must kill or materially downgrade at least one."
            }
        ],
        defense: [
            {
                id: "PM-D2",
                prompt: "Defend your decision to the CFO. What downside are you explicitly accepting this quarter, and why is it financially rational?",
                expected_signal: "Second-order thinking and economic realism",
                context: "CONTEXT: Sales leadership is unhappy."
            }
        ]
    }
};

export const SCENARIOS = {
    engineering: {
        phases: ["orientation", "audit", "defense"],
        time_limits: { orientation: 300, audit: 1200, defense: 600 },
        rubric: [
            "verification_depth",
            "architectural_reasoning",
            "economic_awareness",
            "ai_interrogation"
        ]
    },
    pm: {
        phases: ["diagnosis", "funeral", "defense"],
        time_limits: { diagnosis: 600, funeral: 900, defense: 600 },
        rubric: [
            "willingness_to_disappoint",
            "constraint_management",
            "second_order_thinking",
            "economic_reality"
        ]
    }
};
