export interface SeoLink {
    slug: string;
    title: string;
    type: 'guide' | 'comparison';
}

export const allSeoLinks: SeoLink[] = [
    { slug: "rust-vs-go", title: "Rust vs. Go", type: "comparison" },
    { slug: "kafka-vs-rabbitmq", title: "Kafka vs. RabbitMQ", type: "comparison" },
    { slug: "redis-vs-memcached", title: "Redis vs. Memcached", type: "comparison" },
    { slug: "docker-swarm-vs-kubernetes", title: "Docker Swarm vs. Kubernetes", type: "comparison" },
    { slug: "grpc-vs-trpc", title: "gRPC vs. tRPC", type: "comparison" },
    { slug: "cypress-vs-playwright", title: "Cypress vs. Playwright", type: "comparison" },
    { slug: "cloudflare-vs-fastly", title: "Cloudflare vs. Fastly", type: "comparison" },
    { slug: "snowflake-vs-redshift", title: "Snowflake vs. Redshift", type: "comparison" },
    { slug: "auth0-vs-clerk", title: "Auth0 vs. Clerk", type: "comparison" },
    { slug: "tailwind-vs-css-in-js", title: "Tailwind CSS vs. CSS-in-JS", type: "comparison" },
    { slug: "pdi-vs-dora", title: "PDI vs. DORA Metrics", type: "comparison" },
    { slug: "build-vs-buy", title: "Build vs. Buy", type: "comparison" },
    { slug: "graphql-vs-rest", title: "GraphQL vs. REST", type: "comparison" },
    { slug: "terraform-vs-pulumi", title: "Terraform vs. Pulumi", type: "comparison" },
    { slug: "datadog-vs-grafana", title: "Datadog vs. Grafana Stack", type: "comparison" },
    { slug: "revenue-per-engineer", title: "Revenue Per Engineer Benchmarks", type: "comparison" },
    { slug: "technical-debt-types", title: "Technical Debt Classification", type: "comparison" },
    { slug: "agile-vs-kanban", title: "Scrum vs. Kanban", type: "comparison" },
    { slug: "monolith-vs-microservices", title: "Monolith vs. Microservices", type: "comparison" },
    { slug: "fine-tuning-vs-rag", title: "Fine-Tuning vs. RAG", type: "comparison" },
    { slug: "staff-augmentation-vs-delivery", title: "Staff Augmentation vs. Managed Delivery", type: "comparison" },
    { slug: "platform-team-vs-sres", title: "Platform Team vs. SRE", type: "comparison" },
    { slug: "capex-vs-opex", title: "CapEx vs. OpEx", type: "comparison" },
    { slug: "dora-vs-space", title: "DORA vs. SPACE", type: "comparison" },
    { slug: "aws-vs-gcp-vs-azure", title: "AWS vs. GCP vs. Azure", type: "comparison" },
    { slug: "copilot-vs-cursor", title: "GitHub Copilot vs. Cursor", type: "comparison" },
    { slug: "react-spa-vs-nextjs", title: "React SPA vs. Next.js", type: "comparison" },
    { slug: "postgresql-vs-mongodb", title: "PostgreSQL vs. MongoDB", type: "comparison" },
    { slug: "build-ai-vs-buy-ai", title: "Build AI vs. Buy AI", type: "comparison" },
    { slug: "soc2-vs-iso27001", title: "SOC 2 vs. ISO 27001", type: "comparison" },
    { slug: "scrum-vs-safe", title: "Scrum vs. SAFe", type: "comparison" },
    { slug: "okrs-vs-kpis", title: "OKRs vs. KPIs", type: "comparison" },
    { slug: "feature-flags-vs-branching", title: "Feature Flags vs. Long-Lived Branches", type: "comparison" },
    { slug: "self-hosted-ai-vs-ai-saas", title: "Self-Hosted AI vs. AI SaaS", type: "comparison" },
    { slug: "tech-debt-vs-design-debt", title: "Tech Debt vs. Design Debt", type: "comparison" },
    { slug: "offshore-vs-nearshore", title: "Offshore vs. Nearshore", type: "comparison" },
    { slug: "unit-tests-vs-integration-tests", title: "Unit Tests vs. Integration Tests", type: "comparison" },
    { slug: "clickhouse-vs-bigquery", title: "ClickHouse vs. BigQuery", type: "comparison" },
    { slug: "vertical-ai-vs-horizontal-ai", title: "Vertical AI vs. Horizontal AI", type: "comparison" },
    { slug: "aper-vs-rpe", title: "APER vs. Revenue Per Engineer", type: "comparison" },
    { slug: "langchain-vs-llamaindex", title: "LangChain vs. LlamaIndex", type: "comparison" },
    { slug: "openai-vs-anthropic", title: "OpenAI vs. Anthropic", type: "comparison" },
    { slug: "vercel-vs-netlify", title: "Vercel vs. Netlify", type: "comparison" },
    { slug: "datadog-vs-newrelic", title: "Datadog vs. New Relic", type: "comparison" },
    { slug: "github-actions-vs-gitlab-ci", title: "GitHub Actions vs. GitLab CI", type: "comparison" },
    { slug: "snowflake-vs-databricks", title: "Snowflake vs. Databricks", type: "comparison" },
    { slug: "kubernetes-vs-serverless", title: "Kubernetes vs. Serverless", type: "comparison" },
    { slug: "linear-vs-jira", title: "Linear vs. Jira", type: "comparison" },
    { slug: "supabase-vs-firebase", title: "Supabase vs. Firebase", type: "comparison" },
    { slug: "dbt-vs-airflow", title: "dbt vs. Airflow", type: "comparison" },
    { slug: "agentic-ai-cost-guide", title: "Agentic AI Cost Guide \u2014 What AI Agents Actually Cost to Build, Deploy, and Operate", type: "guide" },
    { slug: "ai-agent-compliance-framework", title: "AI Agent Governance & Compliance Framework", type: "guide" },
    { slug: "ai-build-vs-buy", title: "AI Build vs. Buy Decision Framework \u2014 When to Build AI In-House", type: "guide" },
    { slug: "ai-coding-tools-roi", title: "AI Coding Tools ROI Calculator \u2014 Copilot, Cursor, and the Real Productivity Impact", type: "guide" },
    { slug: "ai-economics", title: "AI Economics — The Cost of Intelligence", type: "guide" },
    { slug: "ai-governance-audit-framework", title: "AI Governance & Audit Framework \u2014 EU AI Act Compliance, Risk Assessment, and Audit Playbook", type: "guide" },
    { slug: "ai-governance-compliance", title: "AI Governance & Compliance \u2014 NIST AI RMF to Board Reporting", type: "guide" },
    { slug: "ai-native-development-teams", title: "Building AI-Native Engineering Teams", type: "guide" },
    { slug: "ai-security-posture-2026", title: "AI Security Posture & Preemptive Defense", type: "guide" },
    { slug: "ai-talent-strategy", title: "AI Talent Strategy & Compensation Guide \u2014 Hire, Retain, and Develop ML Engineers at Scale", type: "guide" },
    { slug: "api-monetization", title: "The API Monetization Playbook \u2014 From Internal API to Revenue", type: "guide" },
    { slug: "board-tech-reporting", title: "Board Technology Reporting \u2014 What Boards Want to Hear", type: "guide" },
    { slug: "cloud-finops", title: "Cloud FinOps & Infrastructure Economics — Stop Wasting 35% of Your Cloud Spend", type: "guide" },
    { slug: "cloud-finops-playbook", title: "Cloud FinOps Playbook \u2014 Cut Cloud Costs by 30-50% \u2014 The Complete Framework", type: "guide" },
    { slug: "confidential-computing-playbook", title: "Confidential Computing for Enterprise AI", type: "guide" },
    { slug: "consumption-based-pricing", title: "Consumption-Based Pricing Playbook \u2014 Usage-Based, Value-Based, and Hybrid Pricing for SaaS", type: "guide" },
    { slug: "cto-first-90-days", title: "The CTO's First 90 Days", type: "guide" },
    { slug: "cto-to-ctro", title: "From CTO to Chief Tech Transformation Officer", type: "guide" },
    { slug: "cybersecurity-economics-playbook", title: "Cybersecurity Economics Playbook \u2014 Quantify Risk, Justify Budget, and Prioritize Investments", type: "guide" },
    { slug: "data-infrastructure-optimization", title: "Data Infrastructure Cost Optimization \u2014 Cut Data Stack Costs 40%", type: "guide" },
    { slug: "devops-roi", title: "DevOps ROI Playbook \u2014 Quantifying DevOps Investment", type: "guide" },
    { slug: "engineering-budget-planning", title: "Engineering Budget Planning \u2014 Board-Ready Engineering Budgets", type: "guide" },
    { slug: "engineering-due-diligence-ma-2026", title: "Engineering Due Diligence for M&A (2026 Edition) \u2014 The Updated Technology Assessment for Acquisitions", type: "guide" },
    { slug: "engineering-efficiency", title: "Engineering Efficiency Blueprint — From Measurement to Optimization", type: "guide" },
    { slug: "engineering-leadership-handbook", title: "The Engineering Leadership Handbook", type: "guide" },
    { slug: "engineering-org-design", title: "Engineering Org Design \u2014 From 10 to 500 Engineers", type: "guide" },
    { slug: "engineering-productivity-metrics-2026", title: "Engineering Productivity Metrics 2026 \u2014 DORA, SPACE, DX, and What Actually Matters", type: "guide" },
    { slug: "engineering-scaling-30-100", title: "Engineering Team Scaling (30 to 100) \u2014 Growth-Stage Operating Manual", type: "guide" },
    { slug: "executive-technology-guide", title: "The Executive's Technology Guide", type: "guide" },
    { slug: "fintech-engineering", title: "FinTech Engineering Economics \u2014 SOX, PCI & Financial Software", type: "guide" },
    { slug: "gpu-finops-supercomputing", title: "GPU FinOps & AI Supercomputing", type: "guide" },
    { slug: "green-software-economics", title: "Green Software Engineering Economics \u2014 Sustainability as a Business Advantage", type: "guide" },
    { slug: "healthtech-engineering", title: "HealthTech Engineering Economics \u2014 HIPAA, FDA & Healthcare Tech", type: "guide" },
    { slug: "hybrid-ai-infrastructure", title: "Hybrid AI Architectures & Cloud 3.0", type: "guide" },
    { slug: "ma-tech-diligence", title: "M&A Technology Due Diligence \u2014 The 47-Point Technical Assessment", type: "guide" },
    { slug: "microservices-migration", title: "Microservices Migration Playbook \u2014 Monolith to Microservices", type: "guide" },
    { slug: "multi-agent-orchestration", title: "The Guide to Multi-Agent Orchestration", type: "guide" },
    { slug: "pe-due-diligence", title: "PE Technology Due Diligence Guide", type: "guide" },
    { slug: "pe-portfolio-optimization", title: "PE Portfolio Tech Optimization \u2014 Value Creation for Operating Partners", type: "guide" },
    { slug: "platform-engineering-economics", title: "Platform Engineering Economics \u2014 Internal Developer Platforms", type: "guide" },
    { slug: "post-quantum-migration", title: "Post-Quantum Cryptography (PQC) Migration", type: "guide" },
    { slug: "product-economics", title: "Product Economics Playbook — Unit Economics, Feature P&L & Kill Switch Protocol", type: "guide" },
    { slug: "remote-engineering-economics", title: "Remote Engineering Team Economics \u2014 Distributed Teams Done Right", type: "guide" },
    { slug: "saas-metrics", title: "SaaS Metrics Masterclass — From ARR to Engineering ROI", type: "guide" },
    { slug: "spatial-computing-economics", title: "Spatial Computing Economics", type: "guide" },
    { slug: "startup-cto-handbook", title: "The Startup CTO Handbook \u2014 First Commit to Series B", type: "guide" },
    { slug: "technical-debt", title: "The Complete Guide to Technical Debt — Economic Framework", type: "guide" },
    { slug: "technical-interview-redesign", title: "Technical Interview Redesign \u2014 Test Judgment Not Syntax", type: "guide" },
    { slug: "vc-technology-assessment", title: "VC Technology Assessment Framework", type: "guide" },
    { slug: "vendor-management", title: "Vendor Management & Contract Negotiation \u2014 Save 20-40% on Software Spend", type: "guide" }
];
