export interface SeoLink {
    slug: string;
    title: string;
    type: 'guide' | 'comparison' | 'blog' | 'glossary';
}

export const allSeoLinks: SeoLink[] = [
    // === ACTIVE STATIC COMPARISONS ===
    { slug: "claude-code-vs-cursor-governance", title: "Claude Code vs. Cursor Governance", type: "comparison" },
    { slug: "claude-code-retry-loop-prevention", title: "Claude Code Retry Loop Prevention", type: "comparison" },
    { slug: "claude-context-rot-mitigation", title: "Claude Context Rot Mitigation", type: "comparison" },
    { slug: "cursor-repository-drift-prevention", title: "Cursor Repository Drift Prevention", type: "comparison" },
    { slug: "ai-coding-agents", title: "AI Coding Agents", type: "comparison" },
    { slug: "ai-guardrails-platforms", title: "AI Guardrails Platforms", type: "comparison" },
    { slug: "github-copilot-problems", title: "GitHub Copilot Problems", type: "comparison" },
    { slug: "cursor-problems", title: "Cursor Problems", type: "comparison" },
    { slug: "windsurf-problems", title: "Windsurf Problems", type: "comparison" },
    { slug: "why-claude-loses-context", title: "Why Claude Loses Context", type: "comparison" },
    { slug: "why-retry-loops-happen", title: "Why Retry Loops Happen", type: "comparison" },
    { slug: "why-cursor-rewrites-files", title: "Why Cursor Rewrites Files", type: "comparison" },
    { slug: "why-ai-coding-burns-money", title: "Why AI Coding Burns Money", type: "comparison" },
    { slug: "why-mcp-is-dangerous", title: "Why MCP Is Dangerous", type: "comparison" },
    { slug: "claude-md-is-not-governance", title: "CLAUDE.md Is Not Governance", type: "comparison" },
    { slug: "pdi-vs-sonarqube", title: "PDI vs. SonarQube", type: "comparison" },
    { slug: "pdi-vs-codeclimate", title: "PDI vs. CodeClimate", type: "comparison" },
    { slug: "pdi-vs-waydev", title: "PDI vs. Waydev", type: "comparison" },
    { slug: "audit-interview-vs-leetcode", title: "Audit Interview vs. LeetCode", type: "comparison" },
    { slug: "audit-interview-vs-hackerrank", title: "Audit Interview vs. HackerRank", type: "comparison" },
    { slug: "audit-interview-vs-traditional", title: "Audit Interview vs. Traditional", type: "comparison" },
    { slug: "aueb-vs-aws-cost-explorer", title: "AUEB vs. AWS Cost Explorer", type: "comparison" },
    { slug: "ev-se-vs-jellyfish", title: "EV-SE vs. Jellyfish", type: "comparison" },
    { slug: "aper-vs-jellyfish", title: "APER vs. Jellyfish", type: "comparison" },
    { slug: "aper-vs-linearb", title: "APER vs. LinearB", type: "comparison" },
    { slug: "copilot-roi-vs-gitclear", title: "Copilot ROI vs. GitClear", type: "comparison" },
    { slug: "dora-metrics-vs-aper", title: "DORA Metrics vs. APER", type: "comparison" },
    { slug: "shadow-ai-vs-shadow-it", title: "Shadow AI vs. Shadow IT", type: "comparison" },
    { slug: "technical-debt-vs-technical-insolvency", title: "Technical Debt vs. Technical Insolvency", type: "comparison" },
    { slug: "vibe-coding-vs-agile", title: "Vibe Coding vs. Agile", type: "comparison" },

    // === ACTIVE PROGRAMMATIC COMPARISONS ===
    { slug: "pdi-vs-sonar", title: "PDI vs. SonarQube (Programmatic)", type: "comparison" },
    { slug: "vercel-vs-netlify", title: "Vercel vs. Netlify", type: "comparison" },
    { slug: "openai-vs-anthropic", title: "OpenAI vs. Anthropic", type: "comparison" },
    { slug: "linear-vs-jira", title: "Linear vs. Jira", type: "comparison" },
    { slug: "github-actions-vs-gitlab-ci", title: "GitHub Actions vs. GitLab CI", type: "comparison" },
    { slug: "milvus-vs-qdrant", title: "Milvus vs. Qdrant", type: "comparison" },
    { slug: "stripe-vs-lemon-squeezy", title: "Stripe vs. Lemon Squeezy", type: "comparison" },
    { slug: "weaviate-vs-qdrant", title: "Weaviate vs. Qdrant", type: "comparison" },
    { slug: "langchain-vs-llamaindex", title: "LangChain vs. LlamaIndex", type: "comparison" },
    { slug: "new-relic-vs-dynatrace", title: "New Relic vs. Dynatrace", type: "comparison" },
    { slug: "docker-vs-kubernetes", title: "Docker vs. Kubernetes", type: "comparison" },
    { slug: "podman-vs-nomad", title: "Podman vs. Nomad", type: "comparison" },
    { slug: "remix-vs-nuxt", title: "Remix vs. Nuxt", type: "comparison" },
    { slug: "circleci-vs-jenkins", title: "CircleCI vs. Jenkins", type: "comparison" },
    { slug: "paddle-vs-lemon-squeezy", title: "Paddle vs. Lemon Squeezy", type: "comparison" },
    { slug: "anthropic-claude-vs-mistral", title: "Anthropic Claude vs. Mistral", type: "comparison" },
    { slug: "new-relic-vs-grafana", title: "New Relic vs. Grafana", type: "comparison" },
    { slug: "svelte-vs-nuxt", title: "Svelte vs. Nuxt", type: "comparison" },
    { slug: "postgresql-vs-mysql", title: "PostgreSQL vs. MySQL", type: "comparison" },
    { slug: "postgresql-vs-supabase", title: "PostgreSQL vs. Supabase", type: "comparison" },
    { slug: "vercel-vs-astro", title: "Vercel vs. Astro", type: "comparison" },
    { slug: "netlify-vs-remix", title: "Netlify vs. Remix", type: "comparison" },
    { slug: "svelte-vs-next-js", title: "Svelte vs. Next.js", type: "comparison" },
    { slug: "angular-vs-svelte", title: "Angular vs. Svelte", type: "comparison" },
    { slug: "nomad-vs-pulumi", title: "Nomad vs. Pulumi", type: "comparison" },
    { slug: "agentic-ai-cost-guide", title: "Agentic AI Cost Guide \u2014 What AI Agents Actually Cost to Build, Deploy, and Operate", type: "guide" },
    { slug: "ai-agent-compliance-framework", title: "AI Agent Governance & Compliance Framework", type: "guide" },
    { slug: "ai-build-vs-buy", title: "AI Build vs. Buy Decision Framework \u2014 When to Build AI In-House", type: "guide" },
    { slug: "ai-coding-tools-roi", title: "AI Coding Tools ROI Calculator \u2014 Copilot, Cursor, and the Real Productivity Impact", type: "guide" },
    { slug: "ai-economics", title: "AI Economics  -  The Cost of Intelligence", type: "guide" },
    { slug: "ai-governance-audit-framework", title: "AI Governance & Audit Framework \u2014 EU AI Act Compliance, Risk Assessment, and Audit Playbook", type: "guide" },
    { slug: "ai-governance-compliance", title: "AI Governance & Compliance \u2014 NIST AI RMF to Board Reporting", type: "guide" },
    { slug: "ai-native-development-teams", title: "Building AI-Native Engineering Teams", type: "guide" },
    { slug: "ai-security-posture-2026", title: "AI Security Posture & Preemptive Defense", type: "guide" },
    { slug: "ai-talent-strategy", title: "AI Talent Strategy & Compensation Guide \u2014 Hire, Retain, and Develop ML Engineers at Scale", type: "guide" },
    { slug: "api-monetization", title: "The API Monetization Playbook \u2014 From Internal API to Revenue", type: "guide" },
    { slug: "board-tech-reporting", title: "Board Technology Reporting \u2014 What Boards Want to Hear", type: "guide" },
    { slug: "cloud-finops", title: "Cloud FinOps & Infrastructure Economics  -  Stop Wasting 35% of Your Cloud Spend", type: "guide" },
    { slug: "cloud-finops-playbook", title: "Cloud FinOps Playbook \u2014 Cut Cloud Costs by 30-50% \u2014 The Complete Framework", type: "guide" },
    { slug: "confidential-computing-playbook", title: "Confidential Computing for Enterprise AI", type: "guide" },
    { slug: "consumption-based-pricing", title: "Consumption-Based Pricing Playbook \u2014 Usage-Based, Value-Based, and Hybrid Pricing for SaaS", type: "guide" },
    { slug: "cto-first-90-days", title: "The CTO's First 90 Days", type: "guide" },
    { slug: "cto-to-ctro", title: "From CTO to Chief Tech Transformation Officer", type: "guide" },
    { slug: "cybersecurity-economics-playbook", title: "Cybersecurity Economics Playbook \u2014 Quantify Risk, Justify Budget, and Prioritize Investments", type: "guide" },
    { slug: "data-infrastructure-optimization", title: "Data Infrastructure Cost Optimization \u2014 Cut Data Stack Costs 40%", type: "guide" },
    { slug: "devops-roi", title: "DevOps ROI Playbook \u2014 Quantifying DevOps Investment", type: "guide" },
    { slug: "engineering-budget-planning", title: "Engineering Budget Planning \u2014 Board-Ready Engineering Budgets", type: "guide" },
    { slug: "engineering-due-diligence-ma-2026", title: "Engineering Due Diligence for M&A (2026 Edition) \u2014 The Updated Technology Assessment for Acquisitions", type: "guide" },
    { slug: "engineering-efficiency", title: "Engineering Efficiency Blueprint  -  From Measurement to Optimization", type: "guide" },
    { slug: "engineering-leadership-handbook", title: "The Engineering Leadership Handbook", type: "guide" },
    { slug: "engineering-org-design", title: "Engineering Org Design \u2014 From 10 to 500 Engineers", type: "guide" },
    { slug: "engineering-productivity-metrics-2026", title: "Engineering Productivity Metrics 2026 \u2014 DORA, SPACE, DX, and What Actually Matters", type: "guide" },
    { slug: "engineering-scaling-30-100", title: "Engineering Team Scaling (30 to 100) \u2014 Growth-Stage Operating Manual", type: "guide" },
    { slug: "executive-technology-guide", title: "The Executive's Technology Guide", type: "guide" },
    { slug: "fintech-engineering", title: "FinTech Engineering Economics \u2014 SOX, PCI & Financial Software", type: "guide" },
    { slug: "gpu-finops-supercomputing", title: "GPU FinOps & AI Supercomputing", type: "guide" },
    { slug: "green-software-economics", title: "Green Software Engineering Economics \u2014 Sustainability as a Business Advantage", type: "guide" },
    { slug: "healthtech-engineering", title: "HealthTech Engineering Economics \u2014 HIPAA, FDA & Healthcare Tech", type: "guide" },
    { slug: "hybrid-ai-infrastructure", title: "Hybrid AI Architectures & Cloud 3.0", type: "guide" },
    { slug: "ma-tech-diligence", title: "M&A Technology Due Diligence \u2014 The 47-Point Technical Assessment", type: "guide" },
    { slug: "microservices-migration", title: "Microservices Migration Playbook \u2014 Monolith to Microservices", type: "guide" },
    { slug: "multi-agent-orchestration", title: "The Guide to Multi-Agent Orchestration", type: "guide" },
    { slug: "pe-due-diligence", title: "PE Technology Due Diligence Guide", type: "guide" },
    { slug: "pe-portfolio-optimization", title: "PE Portfolio Tech Optimization \u2014 Value Creation for Operating Partners", type: "guide" },
    { slug: "platform-engineering-economics", title: "Platform Engineering Economics \u2014 Internal Developer Platforms", type: "guide" },
    { slug: "post-quantum-migration", title: "Post-Quantum Cryptography (PQC) Migration", type: "guide" },
    { slug: "product-economics", title: "AI Economics Playbook  -  Unit Economics, Feature P&L & Kill Switch Protocol", type: "guide" },
    { slug: "remote-engineering-economics", title: "Remote Engineering Team Economics \u2014 Distributed Teams Done Right", type: "guide" },
    { slug: "saas-metrics", title: "SaaS Metrics Masterclass  -  From ARR to Engineering ROI", type: "guide" },
    { slug: "spatial-computing-economics", title: "Spatial Computing Economics", type: "guide" },
    { slug: "startup-cto-handbook", title: "The Startup CTO Handbook \u2014 First Commit to Series B", type: "guide" },
    { slug: "technical-debt", title: "The Complete Guide to Technical Debt  -  Economic Framework", type: "guide" },
    { slug: "technical-interview-redesign", title: "Technical Interview Redesign \u2014 Test Judgment Not Syntax", type: "guide" },
    { slug: "vc-technology-assessment", title: "VC Technology Assessment Framework", type: "guide" },
    { slug: "vendor-management", title: "Vendor Management & Contract Negotiation \u2014 Save 20-40% on Software Spend", type: "guide" },

    // === REMEDIATED ORPHANED BLOG POSTS ===
    { slug: "microservices-cost-truth", title: "Microservices Cost Truth", type: "blog" },
    { slug: "real-time-vs-batch-economics", title: "Real Time Vs Batch Economics", type: "blog" },
    { slug: "compliance-automation-roi", title: "Compliance Automation Roi", type: "blog" },
    { slug: "gpu-infrastructure-economics", title: "Gpu Infrastructure Economics", type: "blog" },
    { slug: "api-design-economics", title: "Api Design Economics", type: "blog" },
    { slug: "feature-factory-escape", title: "Feature Factory Escape", type: "blog" },
    { slug: "infrastructure-as-code-roi", title: "Infrastructure As Code Roi", type: "blog" },
    { slug: "pe-due-diligence-red-flags", title: "Pe Due Diligence Red Flags", type: "blog" },
    { slug: "geo-why-traditional-seo-is-dead-for-b2b-saas", title: "Geo Why Traditional Seo Is Dead For B2b Saas", type: "blog" },
    { slug: "the-rise-of-shadow-agents-why-your-next-data-breach-will-be-automated", title: "The Rise Of Shadow Agents Why Your Next Data Breach Will Be Automated", type: "blog" },
    { slug: "technical-insolvency-date", title: "Technical Insolvency Date", type: "blog" },
    { slug: "engineering-culture-economics", title: "Engineering Culture Economics", type: "blog" },
    { slug: "fine-tuning-roi-analysis", title: "Fine Tuning Roi Analysis", type: "blog" },
    { slug: "engineering-management-span", title: "Engineering Management Span", type: "blog" },
    { slug: "outsourcing-contractor-economics", title: "Outsourcing Contractor Economics", type: "blog" },
    { slug: "technical-migration-economics", title: "Technical Migration Economics", type: "blog" },
    { slug: "sre-team-economics", title: "Sre Team Economics", type: "blog" },
    { slug: "equity-compensation-engineering", title: "Equity Compensation Engineering", type: "blog" },
    { slug: "ai-governance-board-primer", title: "Ai Governance Board Primer", type: "blog" },
    { slug: "vibe-coding-debt-the-silent-killer-of-ai-native-startups", title: "Vibe Coding Debt The Silent Killer Of Ai Native Startups", type: "blog" },
    { slug: "technology-carveout-economics", title: "Technology Carveout Economics", type: "blog" },
    { slug: "soc2-compliance-cost", title: "Soc2 Compliance Cost", type: "blog" },
    { slug: "ai-feature-profitability", title: "Ai Feature Profitability", type: "blog" },
    { slug: "event-driven-architecture-roi", title: "Event Driven Architecture Roi", type: "blog" },
    { slug: "technical-debt-cfo-guide", title: "Technical Debt Cfo Guide", type: "blog" },
    { slug: "data-pipeline-cost-optimization", title: "Data Pipeline Cost Optimization", type: "blog" },
    { slug: "rd-tax-credit-engineering", title: "Rd Tax Credit Engineering", type: "blog" },
    { slug: "board-technology-oversight", title: "Board Technology Oversight", type: "blog" },
    { slug: "conways-law-economic-impact", title: "Conways Law Economic Impact", type: "blog" },
];
