const fs = require('fs');

const path = './app/lib/career-paths.ts';
let code = fs.readFileSync(path, 'utf8');

// The new CAIO object
const caio = `
    {
        slug: 'chief-ai-officer',
        title: 'Chief AI Officer (CAIO)',
        manifestoTitle: 'The Boardroom Fiduciary',
        label: 'CAIO',
        iconName: 'LineChart',
        color: 'emerald',
        domain: 'Product & Economics',
        description: 'The highest echelon of enterprise AI accountability. The CAIO abstracts technical implementations into definitive board-level ROI, regulatory guarantees, and margin expansion.',
        manifesto: [
            "The enterprise does not care about your parameter counts or context windows. The board only measures AI through dual optics: Net-Margin Expansion and Total Enterprise Risk Abatement.",
            "If an AI deployment cannibalizes headcount without mathematically dropping operational drag, it is a failed experiment. The CAIO operates as the fiduciary bridge between abstract mathematics and hard capital."
        ],
        glossaryTerms: ['agentic-process-automation', 'annualized-productivity-per-engineer', 'human-in-the-loop-hitl', 'ai-trust-risk-and-security-management-ai-trism', 'moat-erosion'],
        curriculumKeywords: ['Product', 'Strategy', 'Economics', 'Metrics', 'Governance'],
        seoMeta: 'Transition to Chief AI Officer (CAIO). Learn the executive framework, board metrics, and fiduciary mandates required to govern enterprise AI correctly.',
        seoKeywords: ['Chief AI Officer', 'CAIO', 'VP of AI', 'AI Executive Governance', 'Enterprise AI ROI', 'AI Fiduciary'],
        primaryMetrics: [
            { name: 'Enterprise Margin Velocity', description: 'The absolute speed at which implemented AI models drop execution costs against total headcount.' },
            { name: 'Systemic Compliance SLA', description: 'Deterministic proof that agentic workflows execute strictly within authorized geographic and data sovereignty boundaries.' },
            { name: 'Compute Capital Efficiency', description: 'Ratio of Inference Cloud Spend relative to top-line revenue generated by that exact compute.' }
        ],
        first90Days: {
            day30: "Audit all isolated Shadow AI deployments. Centralize compliance and establish the hard deterministic boundary layer for the organization.",
            day60: "Execute rigorous Cost-of-Compute audits. Destroy high-parameter vanity architectures and shift infrastructure to quantized SLMs where appropriate.",
            day90: "Present the first Fiduciary AI Ledger to the board: absolute proof of positive margin delta resulting from targeted Agentic Process Automation."
        },
        interviewAntiPatterns: [
            "Discussing favorite LLMs instead of defining API infrastructure constraints and regulatory bounds.",
            "Failing to articulate how to calculate Annualized Productivity per Engineer (APER).",
            "Pitching 'AI features' instead of 'Human-Replacement Capital Arbitrage'."
        ],
        marketEconomics: {
            salary: '$350,000 - $600,000+',
            growth: '+450% YoY',
            gap: "Technical visionaries are easily localized, but Board-ready fiduciaries who can prove mathematical risk abatement command unparalleled structural equity."
        },
        faqs: [
            { question: "What is the primary role of a Chief AI Officer?", answer: "A CAIO is not a lead engineer; they are a capital risk fiduciary. Their job is to ensure AI deployments mathematically expand enterprise margins without triggering regulatory, data, or hallucination-based liabilities." },
            { question: "How does a CAIO differ from a CTO?", answer: "While the CTO manages standard SaaS infrastructure and uptime, the CAIO manages non-deterministic risk. The CAIO focuses purely on the statistical outputs, compute economics, and sovereign alignment of autonomous models." },
            { question: "What are the core metrics for a Chief AI Officer?", answer: "CAIOs are measured by Compute Efficiency Ratios, APER (Annualized Productivity per Engineer), and the quantifiable reduction of human-execution latency in core workflows." }
        ]
    },`;

const rag = `
    {
        slug: 'rag-systems-architect',
        title: 'RAG Systems Architect',
        manifestoTitle: 'The Context Engineer',
        label: 'RAG Architect',
        iconName: 'Database',
        color: 'sky',
        domain: 'Data & AI Foundations',
        description: 'Prompt engineering is dead. The RAG Systems Architect defines high-dimensional semantic search, deterministic retrieval pipelines, and context-injection routing.',
        manifesto: [
            "Models do not hallucinate; they simply execute outside of your supplied contextual truth. The RAG Architect enforces truth.",
            "Vector mathematics is the new relational algebra. A model is only as intelligent as the data retrieval pipeline feeding its immediate context window."
        ],
        glossaryTerms: ['retrieval-augmented-generation-rag', 'semantic-chunking', 'vector-database-vdb', 'hallucination-entropy'],
        curriculumKeywords: ['RAG', 'Vector', 'Prompt', 'Search', 'Embedding', 'Data'],
        seoMeta: 'Become a Retrieval-Augmented Generation (RAG) Systems Architect. Master vector databases, semantic chunking, and deterministic knowledge injection.',
        seoKeywords: ['RAG Engineer', 'Retrieval-Augmented Architect', 'Vector Database Engineer', 'LLM Search Engineer', 'AI Data Pipeline'],
        primaryMetrics: [
            { name: 'Recall Precision Tolerance', description: 'Percentage of retrieved chunks that carry absolute deterministic relevancy to the specific query intent.' },
            { name: 'Chunk Density Ratio', description: 'Balancing token count per semantic vector to maximize hitting the context limit while minimizing latency.' },
            { name: 'Retrieval Latency (ms)', description: 'Hard algorithmic measurement of the database roundtrip before the LLM inference step begins.' }
        ],
        first90Days: {
            day30: "Audit existing token limits and pipeline latency. Migrate legacy keyword search functions into foundational dense-vector retrieval.",
            day60: "Introduce advanced Re-ranking and semantic chunking. Force the pipeline to algorithmically isolate specific enterprise truths.",
            day90: "Finalize a zero-trust grounding boundary. Ensure the LLM fundamentally refuses execution if the vector pipeline returns a null semantic threshold."
        },
        interviewAntiPatterns: [
            "Believing 'changing the prompt' is the solution to systemic model inaccuracies.",
            "Applying naive fixed-length chunking to dense financial or technical enterprise documents.",
            "Inability to explain the difference between Cosine Similarity and Dot Product in embedding evaluation."
        ],
        marketEconomics: {
            salary: '$185,000 - $285,000',
            growth: '+320% YoY',
            gap: "Anyone can call the OpenAI API. Very few can architect a deterministic sub-50ms retrieval pipeline that strictly bounds a model to corporate IP."
        },
        faqs: [
            { question: "What does a RAG Engineer actually do?", answer: "They build the pipeline that intercepts a user query, instantly searches massive internal corporate databases for the correct answer, and heavily feeds that correct data into the AI so the AI doesn't guess." },
            { question: "Why is RAG replacing prompt engineering?", answer: "Prompt engineering relies on the model's internal, static training data (which gets outdated and hallucinates). RAG overrides the model with live, dynamically injected facts." },
            { question: "Is RAG a long-term career?", answer: "Yes. As context windows expand, the problem shifts from 'fitting data' to 'retrieving exactly the right data efficiently' without incurring insane compute costs." }
        ]
    }`;

if (!code.includes("slug: 'chief-ai-officer'")) {
    let newCode = code.replace(/\];\s*$/, caio + rag + '\\n];\\n');
    fs.writeFileSync(path, newCode);
    console.log('Successfully injected CAIO and RAG career models.');
} else {
    console.log('Already exists.');
}
