export type AssetCategory = 'AI' | 'Software' | 'Product' | 'Capital' | 'Governance' | 'Organizational';

export type AISubType = 'Model' | 'Prompt' | 'Agent' | 'Workflow' | 'RAGPipeline';
export type SoftwareSubType = 'Repository' | 'Service' | 'API' | 'Application';
export type ProductSubType = 'Feature' | 'Initiative' | 'Product';
export type CapitalSubType = 'Budget' | 'Vendor' | 'Contract';
export type GovernanceSubType = 'Policy' | 'Control' | 'Permission' | 'Regulation';
export type OrganizationalSubType = 'Team' | 'Owner' | 'Decision';

export type AssetSubType = AISubType | SoftwareSubType | ProductSubType | CapitalSubType | GovernanceSubType | OrganizationalSubType;

export type AttributionConfidence = 'Direct' | 'Strongly Attributed' | 'Estimated' | 'Correlated' | 'Unknown';
export type ComplianceStatus = 'Compliant' | 'At Risk' | 'Non-Compliant' | 'Unaudited';
export type HealthStatus = 'Optimal' | 'Degraded' | 'Critical' | 'Insolvent';

/**
 * Atomic Primitive: Asset
 * Represents any hardware, software, AI agent, financial budget, or organizational unit in the enterprise.
 */
export interface Asset {
    id: string;
    name: string;
    category: AssetCategory;
    subType: AssetSubType;
    owner: string;
    department: 'Finance' | 'Engineering' | 'Product' | 'Security' | 'Executive';
    
    // Financial & Capital Properties
    monthlyCostUSD: number;
    capitalAllocatedUSD: number;
    aiVolatilityTaxAnnualUSD: number;
    
    // Technical & Engineering Debt
    verificationTaxHoursPerWeek: number;
    productDebtIndexScore: number; // 0-100 (100 = debt-free)
    estimatedMonthsToInsolvencyHorizon: number;
    
    // Governance & Security
    permissionLevel: 'Restricted' | 'Standard' | 'Elevated' | 'Unrestricted';
    hasKillSwitch: boolean;
    shadowExposureRisk: 'Low' | 'Moderate' | 'High' | 'Critical';
    complianceStatus: ComplianceStatus;
    
    // Runtime Telemetry
    tokenVolumeMonthly: number;
    cacheHitRatePct: number;
    healthStatus: HealthStatus;
    lastObservedAt: string;
    
    // Graph Connections
    dependsOnAssetIds: string[];
    consumedByAssetIds: string[];
}

/**
 * Outcome Primitive: Models the business results generated by an Asset or Workflow.
 * Capital -> Asset -> Activity -> Output -> Outcome -> Economic Value
 */
export interface Outcome {
    id: string;
    assetId: string;
    title: string;
    outcomeType: 
        | 'RevenueGenerated' 
        | 'CostAvoided' 
        | 'LaborHoursAvoided' 
        | 'TicketsDeflected' 
        | 'CycleTimeReduced' 
        | 'DefectsReduced' 
        | 'RiskMitigated';
        
    rawOutputUnits: number; // e.g. 318,000 automated ticket resolutions
    economicValueUSD: number; // e.g. $1,310,000 estimated economic value
    attributionConfidence: AttributionConfidence;
    observedPeriodStart: string;
    observedPeriodEnd: string;
}

/**
 * Universal Asset Graph State
 */
export interface AssetGraph {
    assets: Asset[];
    outcomes: Outcome[];
    totalMonthlyCostUSD: number;
    totalEconomicValueUSD: number;
    totalAnnualVolatilityTaxUSD: number;
    aiCapitalEfficiencyRatio: number; // (Economic Value) / (Cost + Verification + Risk)
    lastRecalculatedAt: string;
}

/**
 * Calculates the core AI Capital Efficiency Ratio:
 * Efficiency = (Verified Economic Value Created) / (Total AI Cost + Verification Cost + Risk Cost)
 */
export function calculateAICapitalEfficiencyRatio(
    economicValueUSD: number, 
    monthlyCostUSD: number, 
    verificationCostUSD: number, 
    riskCostUSD: number
): number {
    const totalInputCost = (monthlyCostUSD * 12) + verificationCostUSD + riskCostUSD;
    if (totalInputCost <= 0) return 0;
    return parseFloat((economicValueUSD / totalInputCost).toFixed(2));
}

/**
 * Factory helper to instantiate a typed Asset node.
 */
export function createAsset(data: Partial<Asset> & { id: string; name: string; category: AssetCategory; subType: AssetSubType }): Asset {
    return {
        id: data.id,
        name: data.name,
        category: data.category,
        subType: data.subType,
        owner: data.owner || 'Unassigned',
        department: data.department || 'Engineering',
        
        monthlyCostUSD: data.monthlyCostUSD || 0,
        capitalAllocatedUSD: data.capitalAllocatedUSD || 0,
        aiVolatilityTaxAnnualUSD: data.aiVolatilityTaxAnnualUSD || 0,
        
        verificationTaxHoursPerWeek: data.verificationTaxHoursPerWeek || 0,
        productDebtIndexScore: data.productDebtIndexScore || 100,
        estimatedMonthsToInsolvencyHorizon: data.estimatedMonthsToInsolvencyHorizon || 36,
        
        permissionLevel: data.permissionLevel || 'Standard',
        hasKillSwitch: data.hasKillSwitch ?? true,
        shadowExposureRisk: data.shadowExposureRisk || 'Low',
        complianceStatus: data.complianceStatus || 'Compliant',
        
        tokenVolumeMonthly: data.tokenVolumeMonthly || 0,
        cacheHitRatePct: data.cacheHitRatePct || 0,
        healthStatus: data.healthStatus || 'Optimal',
        lastObservedAt: data.lastObservedAt || new Date().toISOString(),
        
        dependsOnAssetIds: data.dependsOnAssetIds || [],
        consumedByAssetIds: data.consumedByAssetIds || []
    };
}
