import { GlossaryTerm } from '../types';

export const aiMlTerms: GlossaryTerm[] = [
    {
        slug: 'transformer-architecture',
        title: 'Transformer Architecture',
        tier: 'pillar',
        category: 'AI & Machine Learning',
        definition: `The Transformer architecture is the foundational neural network design behind all modern large language models including GPT-4, Claude, Gemini, and Llama. Introduced in the landmark 2017 paper "Attention Is All You Need" by Vaswani et al. at Google, transformers use self-attention mechanisms to process input sequences in parallel rather than sequentially.\n\nBefore transformers, recurrent neural networks (RNNs) processed text one word at a time. Transformers process entire sequences simultaneously, making them dramatically faster to train and better at capturing long-range dependencies in text.\n\nKey components include: multi-head self-attention (allowing the model to focus on different parts of the input simultaneously), positional encoding (preserving word order information), and feed-forward neural networks (processing each position independently).\n\nUnderstanding transformer architecture is essential for any leader making AI investment decisions because architecture determines cost structure. Transformer inference scales quadratically with input length  -  doubling your prompt length quadruples the compute cost.`,
        whyItMatters: `Transformer architecture determines the cost structure of all modern AI applications. Understanding how transformers work helps executives make better decisions about prompt design, context window management, and AI cost governance.`,
        faqs: [
            { question: 'What is a transformer in AI?', answer: 'A transformer is a neural network architecture that processes text in parallel using self-attention mechanisms. It powers all modern LLMs including GPT-4, Claude, and Gemini.' },
            { question: 'Why are transformers important?', answer: 'Transformers enabled the AI revolution by making it possible to train models on massive datasets efficiently. Every major AI breakthrough since 2017 is built on transformer architecture.' },
        ],
        relatedTerms: ['large-language-model', 'artificial-intelligence', 'prompt-engineering'],
        relatedTools: [{ name: 'AI Unit Economics Benchmark (AUEB)', url: '/tools/aueb' }],
    },
    {
        slug: 'fine-tuning',
        title: 'Fine-Tuning',
        tier: 'pillar',
        category: 'AI & Machine Learning',
        definition: `Fine-tuning is the process of taking a pre-trained AI model and training it further on a smaller, domain-specific dataset to customize its behavior for a particular use case. It's the middle ground between using a general-purpose model as-is and training a custom model from scratch.\n\nFine-tuning modifies the model's weights to improve performance on specific tasks. For example, fine-tuning GPT-4 on legal documents produces a model that generates better legal text than the base model.\n\nThe economics of fine-tuning involve a significant upfront cost ($1K-$100K+ depending on dataset size and model) but can reduce ongoing inference costs by producing shorter, more accurate outputs that require fewer tokens and less post-processing.\n\nFine-tuning vs. RAG: Fine-tuning changes the model itself. RAG provides context without changing the model. Fine-tuning is better for style and format. RAG is better for factual accuracy. Many production systems use both.`,
        whyItMatters: `Fine-tuning decisions have major cost implications. A well-fine-tuned model can reduce per-query costs by 50-80% compared to prompting a general model. But the upfront cost and maintenance burden of fine-tuned models must be weighed against the flexibility of RAG-based approaches.`,
        faqs: [
            { question: 'What is fine-tuning in AI?', answer: 'Fine-tuning takes a pre-trained AI model and trains it further on domain-specific data to improve its performance for a particular use case.' },
            { question: 'How much does fine-tuning cost?', answer: 'Fine-tuning costs range from $1K for small datasets to $100K+ for large-scale enterprise fine-tuning. The ROI depends on reducing per-query costs and improving output quality.' },
            { question: 'When should you fine-tune vs. use RAG?', answer: 'Fine-tune when you need to change the model style, format, or reasoning patterns. Use RAG when you need to ground the model in specific facts and documents. Many systems use both.' },
        ],
        relatedTerms: ['large-language-model', 'rag', 'prompt-engineering', 'cost-of-predictivity'],
        relatedTools: [{ name: 'AI Unit Economics Benchmark (AUEB)', url: '/tools/aueb' }],
    },
    {
        slug: 'ai-inference',
        title: 'AI Inference',
        tier: 'pillar',
        category: 'AI & Machine Learning',
        definition: `AI inference is the process of running a trained model to generate predictions or outputs from new input data. Unlike training (which is done once), inference happens every time a user interacts with an AI feature  -  every chatbot response, every code suggestion, every image generation.\n\nInference cost is the dominant variable cost in AI features. Training GPT-4 cost an estimated $100M, but inference costs across all users dwarf that number. Each inference call consumes GPU compute proportional to model size and input/output length.\n\nInference optimization is a critical engineering discipline: model quantization (reducing precision from 32-bit to 8-bit or 4-bit), batching (processing multiple requests simultaneously), caching (storing common responses), and distillation (creating smaller student models from larger teacher models).\n\nFor product leaders, inference cost is the unit cost that determines whether your AI feature has positive or negative unit economics. Richard Ewing's AUEB tool calculates Cost of Predictivity  -  the true per-query cost including inference, retrieval, verification, and error handling.`,
        whyItMatters: `Inference cost is what determines whether AI features are profitable or margin-destroying. Every AI query costs real money. Understanding and optimizing inference economics is essential for any AI product strategy.`,
        howToMeasure: `1. **Cost Per Query**: Total inference spend ÷ total queries.\n2. **Cost Per Useful Output**: Inference spend ÷ outputs that met quality threshold.\n3. **Token Efficiency**: Average tokens consumed per successful interaction.\n4. **Latency**: Time from request to response (affects user experience and throughput).\n5. **Batch Utilization**: % of GPU capacity utilized during inference.`,
        faqs: [
            { question: 'What is AI inference?', answer: 'AI inference is running a trained model to generate outputs from new inputs. It happens every time a user interacts with an AI feature, and each call costs compute resources.' },
            { question: 'How much does AI inference cost?', answer: 'Costs range from $0.0001/query for small models to $0.10+/query for frontier models. The total cost depends on model size, input/output length, and query volume.' },
        ],
        relatedTerms: ['large-language-model', 'cost-of-predictivity', 'artificial-intelligence'],
        relatedTools: [{ name: 'AI Unit Economics Benchmark (AUEB)', url: '/tools/aueb' }],
    },
    {
        slug: 'model-hallucination-rate',
        title: 'Model Hallucination Rate',
        category: 'AI & Machine Learning',
        definition: `Model hallucination rate is the percentage of AI outputs that contain factual errors, fabricated information, or ungrounded claims. It is the primary quality metric for any AI system that generates text, code, or structured data.\n\nHallucination rates vary significantly by model, task, and domain. Frontier models (GPT-4, Claude) hallucinate on 3-10% of factual queries. Smaller models can hallucinate on 15-30% of queries. Domain-specific queries without RAG can see hallucination rates of 20-40%.\n\nMeasuring hallucination rate requires ground truth data  -  verified correct answers against which model outputs can be evaluated. This is expensive to create but essential for production AI systems.\n\nRichard Ewing frames hallucination as an economic risk rather than an accuracy problem. Each hallucination has a cost: the cost of the incorrect output itself, the cost of detecting the error, the cost of correcting downstream decisions based on the error, and the potential liability cost if the error causes harm.`,
        whyItMatters: `Hallucination rate determines the total cost of ownership for AI features. A system with 10% hallucination rate requires human review of all outputs, which often costs more than the AI saves. Use the AUEB at richardewing.io/tools/aueb to model the economics.`,
        howToMeasure: `1. **Create Ground Truth**: Build a test set of questions with verified correct answers.\n2. **Run Evaluations**: Generate model responses and compare against ground truth.\n3. **Categorize Errors**: Factual errors, fabricated citations, logical contradictions, incomplete answers.\n4. **Calculate Rate**: Hallucinated responses ÷ total responses × 100.\n5. **Track Over Time**: Monitor hallucination rate as you update prompts, models, or retrieval systems.`,
        faqs: [
            { question: 'What is a normal hallucination rate for AI?', answer: 'Frontier models (GPT-4, Claude) hallucinate on 3-10% of factual queries. With RAG, rates can drop to 1-3%. Without RAG on domain-specific questions, rates can reach 20-40%.' },
            { question: 'How do you reduce AI hallucination rate?', answer: 'Use RAG to ground responses in documents, add verification layers, implement confidence scoring, fine-tune on domain data, and use structured outputs to constrain the response space.' },
        ],
        relatedTerms: ['ai-hallucination', 'rag', 'cost-of-predictivity', 'ai-governance'],
        relatedTools: [{ name: 'AI Unit Economics Benchmark (AUEB)', url: '/tools/aueb' }],
    },
    {
        slug: 'embedding',
        title: 'Embedding (Vector Embedding)',
        category: 'AI & Machine Learning',
        definition: `An embedding is a dense numerical representation of data (text, images, audio) as a vector of floating-point numbers. Embeddings capture semantic meaning  -  similar concepts have similar embeddings, enabling machines to understand relationships between data points.\n\nFor text, embedding models (like OpenAI's text-embedding-3, Cohere's embed, or open-source models like BAAI/bge) convert words, sentences, or documents into vectors of 256 to 3072 dimensions. "Dog" and "puppy" would have similar embeddings. "Dog" and "quantum physics" would have very different embeddings.\n\nEmbeddings power: semantic search (find documents by meaning not keywords), recommendation systems (find similar content), RAG pipelines (retrieve relevant context for AI), clustering (group similar items), and anomaly detection (find outliers).\n\nThe embedding model you choose directly affects your RAG pipeline's quality and cost. Higher-dimensional embeddings are more accurate but require more storage and compute. Most production systems use 768 or 1536 dimensions.`,
        whyItMatters: `Embeddings are the foundation of modern AI search and retrieval. Choosing the wrong embedding model can undermine your entire RAG pipeline. Understanding embedding economics (storage, compute, quality tradeoffs) is essential for AI product decisions.`,
        faqs: [
            { question: 'What is an embedding in AI?', answer: 'An embedding is a numerical representation of data (text, images) as a vector of numbers. Similar items have similar embeddings, enabling AI systems to understand semantic relationships.' },
            { question: 'How are embeddings used?', answer: 'Embeddings power semantic search, RAG pipelines, recommendation systems, content clustering, and anomaly detection. They convert human-readable data into machine-processable numbers.' },
        ],
        relatedTerms: ['rag', 'large-language-model', 'artificial-intelligence'],
    },
    {
        slug: 'vector-database', tier: 'pillar',
        title: 'Vector Database',
        category: 'AI & Machine Learning',
        definition: `A vector database is a specialized database designed to store, index, and query high-dimensional vector embeddings efficiently. Unlike traditional databases that search by exact matches or keywords, vector databases perform similarity search  -  finding the vectors closest to a query vector in high-dimensional space.\n\nPopular vector databases include: Pinecone (managed cloud-native), Weaviate (open-source), Qdrant (open-source, Rust), Chroma (lightweight, developer-friendly), Milvus (enterprise-scale), and pgvector (PostgreSQL extension).\n\nVector databases are the backbone of RAG pipelines. When a user asks a question, the question is embedded into a vector, the vector database finds the most similar document vectors, and those documents are provided as context to the LLM.\n\nKey performance metrics: query latency (milliseconds to return results), recall (% of truly relevant results returned), and throughput (queries per second at scale).`,
        whyItMatters: `Vector databases determine the speed, accuracy, and cost of your RAG pipeline. Choosing the right vector database and optimizing its configuration directly affects AI feature quality and unit economics.`,
        faqs: [
            { question: 'What is a vector database?', answer: 'A vector database stores and queries high-dimensional vector embeddings, enabling similarity search  -  finding items most similar to a query based on meaning rather than exact keywords.' },
            { question: 'Which vector database should I use?', answer: 'Pinecone for managed simplicity, pgvector for PostgreSQL users, Weaviate or Qdrant for open-source, and Milvus for enterprise scale. Choice depends on scale, budget, and operational complexity tolerance.' },
        ],
        relatedTerms: ['embedding', 'rag', 'artificial-intelligence', 'large-language-model'],
    },
    {
        slug: 'ai-alignment',
        title: 'AI Alignment',
        category: 'AI & Machine Learning',
        definition: `AI alignment is the challenge of ensuring that artificial intelligence systems behave in ways that are consistent with human values and intentions. It encompasses both narrow alignment (making an AI follow specific instructions correctly) and broad alignment (ensuring AI systems don't cause unintended harm at scale).\n\nTechniques for alignment include: Reinforcement Learning from Human Feedback (RLHF), Constitutional AI (training AI to follow explicit ethical principles), red-teaming (adversarial testing to find unsafe behaviors), and guardrails (runtime constraints that prevent harmful outputs).\n\nFor enterprise applications, alignment is a governance concern. An AI system that is technically capable but misaligned with business objectives, ethical guidelines, or regulatory requirements is a liability. Misaligned AI can generate inappropriate content, make biased decisions, or take harmful autonomous actions.\n\nIn 2026, alignment is a board-level concern. The EU AI Act requires organizations to demonstrate that high-risk AI systems are aligned with safety requirements. SEC guidance requires disclosure of material AI risks, including alignment failures.`,
        whyItMatters: `Misaligned AI creates legal, regulatory, and reputational risk. Organizations deploying AI without alignment testing and monitoring face liability exposure that scales with the autonomy and impact of their AI systems.`,
        faqs: [
            { question: 'What is AI alignment?', answer: 'AI alignment is ensuring AI systems behave consistently with human values and intentions  -  following instructions correctly, avoiding harm, and respecting ethical guidelines.' },
            { question: 'Why is AI alignment important for businesses?', answer: 'Misaligned AI can generate inappropriate content, make biased decisions, or violate regulations. The EU AI Act and SEC guidance require organizations to demonstrate AI alignment and safety.' },
        ],
        relatedTerms: ['ai-governance', 'ai-hallucination', 'agentic-ai', 'artificial-intelligence'],
    },
    {
        slug: 'machine-learning-ops',
        title: 'MLOps (Machine Learning Operations)',
        category: 'AI & Machine Learning',
        definition: `MLOps is the set of practices, tools, and cultural changes needed to deploy, monitor, and maintain machine learning models in production reliably. It applies DevOps principles to the ML lifecycle: data management, model training, deployment, monitoring, and retraining.\n\nMLOps addresses the unique challenges of ML in production: model drift (accuracy degrades as real-world data changes), data pipeline failures, reproducibility requirements, A/B testing for model versions, and cost management for GPU-intensive workloads.\n\nKey MLOps tools include: MLflow and Weights & Biases (experiment tracking), Kubeflow and SageMaker (training orchestration), Seldon and BentoML (model serving), Great Expectations (data quality), and Evidently AI (model monitoring).\n\nIn 2026, MLOps has expanded to include LLMOps  -  the specific practices for managing large language model applications, including prompt versioning, RAG pipeline management, hallucination monitoring, and inference cost optimization.`,
        whyItMatters: `Most ML projects fail in production, not in development. MLOps practices determine whether your AI investment generates returns or becomes an expensive prototype that never scales beyond a demo environment.`,
        faqs: [
            { question: 'What is MLOps?', answer: 'MLOps applies DevOps practices to machine learning: automated training pipelines, model deployment, monitoring, and retraining. It ensures ML models work reliably in production.' },
            { question: 'What is the difference between MLOps and LLMOps?', answer: 'MLOps covers traditional ML models (classification, regression). LLMOps covers LLM-specific concerns: prompt management, RAG pipelines, hallucination monitoring, and inference cost optimization.' },
        ],
        relatedTerms: ['devops', 'large-language-model', 'artificial-intelligence', 'ai-governance'],
    },
    {
        slug: 'ai-model-distillation',
        title: 'Model Distillation',
        category: 'AI & Machine Learning',
        definition: `Model distillation (also called knowledge distillation) is a technique for creating smaller, faster AI models by training them to mimic the behavior of larger, more capable models. The large model is called the "teacher" and the small model is called the "student."\n\nThe student model learns to replicate the teacher's output distribution rather than learning from raw data. This is more efficient because the teacher's outputs contain "dark knowledge"  -  information about the relationships between classes and the confidence levels of predictions.\n\nDistillation is one of the most impactful cost optimization strategies for AI applications. A distilled model can achieve 90-95% of the teacher model's quality at 10-50x lower inference cost. For high-volume applications, this can mean the difference between positive and negative unit economics.\n\nExample: instead of calling GPT-4 ($0.03/query) for every customer support question, you can distill GPT-4's responses into a fine-tuned GPT-3.5 ($0.001/query)  -  a 30x cost reduction with minimal quality loss.`,
        whyItMatters: `Model distillation is the key to making AI features economically viable at scale. It directly addresses the Cost of Predictivity problem by reducing inference costs while preserving quality.`,
        faqs: [
            { question: 'What is model distillation?', answer: 'Model distillation creates smaller, cheaper AI models by training them to mimic larger models. The small "student" model learns from the large "teacher" model outputs.' },
            { question: 'How much does distillation save?', answer: 'Distilled models typically achieve 90-95% of the original quality at 10-50x lower inference cost. This can turn negative unit economics positive.' },
        ],
        relatedTerms: ['ai-inference', 'cost-of-predictivity', 'large-language-model', 'fine-tuning'],
        relatedTools: [{ name: 'AI Unit Economics Benchmark (AUEB)', url: '/tools/aueb' }],
    },
    {
        slug: 'ai-safety',
        title: 'AI Safety',
        category: 'AI & Machine Learning',
        definition: `AI safety is the field focused on ensuring artificial intelligence systems operate safely, reliably, and beneficially. It encompasses technical research (alignment, robustness, interpretability), policy frameworks (regulation, standards, certification), and organizational practices (audits, red-teaming, incident response).\n\nIn 2026, AI safety has moved from an academic concern to a regulatory requirement. The EU AI Act classifies AI systems by risk level and mandates safety assessments for high-risk applications. Company boards are expected to understand and govern AI safety at a strategic level.\n\nKey AI safety concerns for enterprise applications: bias and fairness (AI systems reproducing or amplifying societal biases), robustness (AI behaving unpredictably with novel inputs), transparency (inability to explain AI decisions), and security (adversarial attacks that manipulate AI behavior).\n\nPractical AI safety measures include: bias testing across demographic groups, adversarial testing (red-teaming), output monitoring and filtering, human-in-the-loop oversight, and incident response plans for AI failures.`,
        whyItMatters: `AI safety is a fiduciary responsibility. Board members who don't understand AI safety risks face personal liability. Organizations without AI safety practices face regulatory penalties, lawsuits, and reputational damage.`,
        faqs: [
            { question: 'What is AI safety?', answer: 'AI safety ensures AI systems operate safely, reliably, and beneficially. It covers alignment, bias prevention, robustness, transparency, and security.' },
            { question: 'Is AI safety required by law?', answer: 'Increasingly yes. The EU AI Act mandates safety assessments for high-risk AI. SEC guidance requires disclosure of material AI risks. Boards have fiduciary duty to govern AI safety.' },
        ],
        relatedTerms: ['ai-alignment', 'ai-governance', 'ai-hallucination', 'artificial-intelligence'],
    },
    {
        slug: 'natural-language-processing',
        title: 'Natural Language Processing (NLP)',
        category: 'AI & Machine Learning',
        definition: `Natural Language Processing is the branch of artificial intelligence focused on giving computers the ability to understand, interpret, and generate human language. NLP powers chatbots, search engines, translation services, sentiment analysis, content moderation, and text summarization.\n\nModern NLP is dominated by transformer-based language models. Before transformers (pre-2017), NLP relied on statistical methods, word embeddings (Word2Vec, GloVe), and recurrent neural networks. Post-transformers, pre-trained models like BERT (understanding) and GPT (generation) transformed the field.\n\nKey NLP tasks include: text classification (spam detection, sentiment analysis), named entity recognition (extracting people, companies, dates from text), machine translation, question answering, summarization, and text generation.\n\nFor business applications, NLP enables: automated customer support, document analysis, contract review, compliance monitoring, market intelligence, and content generation. The economics of NLP applications depend heavily on model choice  -  smaller task-specific models are dramatically cheaper than general-purpose LLMs.`,
        whyItMatters: `NLP is the technology that makes AI accessible to non-technical users through natural language interfaces. Understanding NLP capabilities and limitations is essential for any executive evaluating AI investments.`,
        faqs: [
            { question: 'What is NLP?', answer: 'Natural Language Processing is AI that understands and generates human language. It powers chatbots, search engines, translation, sentiment analysis, and content generation.' },
            { question: 'What is the difference between NLP and LLMs?', answer: 'NLP is the broad field of language AI. LLMs are a specific type of NLP model (large transformer models). Not all NLP uses LLMs  -  many tasks use smaller, cheaper, task-specific models.' },
        ],
        relatedTerms: ['large-language-model', 'artificial-intelligence', 'transformer-architecture'],
    },
    {
        slug: 'computer-vision',
        title: 'Computer Vision',
        category: 'AI & Machine Learning',
        definition: `Computer vision is the field of artificial intelligence that enables computers to interpret and understand visual information from the real world  -  images, videos, and 3D models. It powers facial recognition, autonomous vehicles, medical imaging, manufacturing quality control, and visual search.\n\nKey computer vision tasks include: image classification (what is in this image?), object detection (where are the objects in this image?), semantic segmentation (pixel-level classification), pose estimation (where are the body parts?), and optical character recognition (extracting text from images).\n\nModern computer vision uses convolutional neural networks (CNNs) and increasingly transformer-based architectures (Vision Transformers, or ViTs). Multimodal models like GPT-4V combined language and vision capabilities in a single model.\n\nComputer vision applications in business include: quality inspection in manufacturing (detecting defects), retail analytics (customer behavior tracking), healthcare diagnostics (radiology, pathology), security and surveillance, and document processing (invoice extraction, ID verification).`,
        whyItMatters: `Computer vision creates measurable business value in industries where visual inspection is expensive or error-prone. Manufacturing quality control, medical diagnostics, and document processing are high-ROI applications with clear unit economics.`,
        faqs: [
            { question: 'What is computer vision?', answer: 'Computer vision is AI that interprets visual information  -  images and videos. It powers facial recognition, object detection, quality inspection, and medical imaging.' },
            { question: 'How accurate is computer vision?', answer: 'State-of-the-art computer vision exceeds human accuracy on many tasks. Medical imaging AI achieves 95%+ accuracy on specific diagnostic tasks. Manufacturing defect detection reaches 99%+ accuracy.' },
        ],
        relatedTerms: ['artificial-intelligence', 'transformer-architecture'],
    },
    {
        slug: 'generative-ai',
        title: 'Generative AI',
        tier: 'pillar',
        category: 'AI & Machine Learning',
        definition: `Generative AI refers to artificial intelligence systems that create new content  -  text, images, audio, video, code, and 3D models  -  rather than simply analyzing or classifying existing content. It represents a fundamental shift in computing from analysis to creation.\n\nKey generative AI modalities: text generation (GPT-4, Claude, Gemini), image generation (DALL-E, Midjourney, Stable Diffusion), code generation (GitHub Copilot, Cursor), audio generation (ElevenLabs, Suno), video generation (Sora, Runway), and 3D model generation.\n\nThe economics of generative AI are fundamentally different from traditional software. Traditional software has near-zero marginal cost per user. Generative AI has significant marginal cost per query  -  every generated output costs compute. This is what Richard Ewing calls the Cost of Predictivity.\n\nIn 2026, generative AI has moved from novelty to production infrastructure. Companies are using it for customer support, content creation, code generation, design, data analysis, and decision support. The winners are organizations that understand the unit economics  -  cost per useful output  -  not just the technology.`,
        whyItMatters: `Generative AI is the most major technology of the decade, but its variable cost structure breaks traditional software economics. Understanding generative AI unit economics is essential for building sustainable AI features.`,
        faqs: [
            { question: 'What is generative AI?', answer: 'Generative AI creates new content (text, images, code, audio, video) rather than just analyzing existing content. It powers chatbots, code assistants, image generators, and creative tools.' },
            { question: 'How much does generative AI cost?', answer: 'Costs vary by modality: text generation $0.001-0.10/query, image generation $0.02-0.20/image, code generation $0.01-0.05/completion. Use the AUEB at richardewing.io/tools/aueb to model your specific costs.' },
        ],
        relatedTerms: ['large-language-model', 'artificial-intelligence', 'cost-of-predictivity', 'vibe-coding'],
        relatedTools: [{ name: 'AI Unit Economics Benchmark (AUEB)', url: '/tools/aueb' }],
    },
    {
        slug: 'ai-bias',
        title: 'AI Bias',
        category: 'AI & Machine Learning',
        definition: `AI bias occurs when artificial intelligence systems produce systematically unfair outcomes that favor or disadvantage certain groups. Bias can enter AI systems through training data (historical bias), algorithm design (measurement bias), and deployment context (evaluation bias).\n\nCommon types of AI bias: historical bias (training data reflects past discrimination), representation bias (certain groups are underrepresented in training data), measurement bias (the wrong thing is being measured), aggregation bias (a one-size-fits-all model ignores subgroup differences), and evaluation bias (testing doesn't include diverse populations).\n\nAI bias in enterprise applications creates legal and financial risk. Biased hiring algorithms face EEOC scrutiny. Biased lending models violate fair lending laws. Biased content moderation systems face regulatory action.\n\nDetecting and mitigating AI bias requires: diverse training data, fairness metrics (demographic parity, equalized odds), regular bias audits, diverse development teams, and continuous monitoring of production outputs across demographic groups.`,
        whyItMatters: `AI bias creates legal liability, regulatory risk, and reputational damage. Organizations deploying AI without bias testing face EEOC complaints, fair lending violations, and public backlash. Bias prevention is both an ethical imperative and a risk management requirement.`,
        faqs: [
            { question: 'What is AI bias?', answer: 'AI bias is when AI systems produce systematically unfair outcomes. It enters through biased training data, flawed algorithm design, or biased evaluation methods.' },
            { question: 'How do you detect AI bias?', answer: 'Test model outputs across demographic groups, measure fairness metrics (demographic parity, equalized odds), and conduct regular bias audits with diverse evaluators.' },
        ],
        relatedTerms: ['ai-safety', 'ai-governance', 'ai-alignment', 'artificial-intelligence'],
    },
    {
        slug: 'multimodal-ai',
        title: 'Multimodal AI',
        category: 'AI & Machine Learning',
        definition: `Multimodal AI refers to artificial intelligence systems that can process, understand, and generate multiple types of data  -  text, images, audio, video, and structured data  -  within a single model. Unlike unimodal AI that handles only one data type, multimodal AI can reason across modalities.\n\nExamples include: GPT-4V (text + images), Gemini (text + images + audio + video), and Claude (text + images + documents). These models can describe images, answer questions about visual content, generate text from visual inputs, and combine reasoning across modalities.\n\nMultimodal AI enables new application categories: visual question answering, document understanding (extracting data from forms and receipts), video analysis, and cross-modal search (finding images by describing them in text).\n\nThe cost structure of multimodal AI is more complex than text-only AI. Image inputs cost 2-10x more than text inputs. Video analysis costs can be 100x+ more. Understanding these costs is critical for product planning.`,
        whyItMatters: `Multimodal AI accesses applications impossible with text-only models: document processing, visual inspection, video understanding, and rich content generation. But the cost premium for multimodal processing must be factored into unit economics.`,
        faqs: [
            { question: 'What is multimodal AI?', answer: 'Multimodal AI processes multiple data types (text, images, audio, video) within a single model, enabling cross-modal reasoning like describing images or answering questions about visual content.' },
            { question: 'How much more does multimodal AI cost?', answer: 'Image inputs typically cost 2-10x more than text. Video analysis can cost 100x+ more. These premiums must be factored into AI feature unit economics.' },
        ],
        relatedTerms: ['large-language-model', 'computer-vision', 'generative-ai', 'artificial-intelligence'],
    },
    {
        slug: 'ai-agent-framework',
        title: 'AI Agent Framework',
        category: 'AI & Machine Learning',
        definition: `An AI agent framework is a software library or platform that provides the infrastructure for building autonomous AI agents  -  systems that can plan, reason, use tools, and take actions independently. Popular frameworks include LangChain, LangGraph, CrewAI, AutoGen, and the Vercel AI SDK.\n\nAgent frameworks provide: tool calling (allowing AI to use APIs, databases, and code execution), memory management (maintaining context across interactions), planning and reasoning (multi-step task decomposition), error handling (recovering from failed tool calls), and orchestration (coordinating multiple agents).\n\nThe economics of AI agents are complex. Each agent step involves an LLM call (cost), a tool call (latency + cost), and state management (complexity). A multi-step agent workflow can cost 5-20x more than a single prompt-response interaction.\n\nFor enterprises, agent frameworks represent both opportunity (automating complex workflows) and risk (autonomous systems making decisions without human oversight). Richard Ewing's AI governance framework recommends tiered autonomy: fully automated for low-risk tasks, human-in-the-loop for medium-risk, and human-approval-required for high-risk.`,
        whyItMatters: `Agent frameworks are the foundation of the next wave of AI automation. But each autonomous agent step adds cost, latency, and risk. Understanding the economics and governance requirements of AI agents is essential for responsible deployment.`,
        faqs: [
            { question: 'What is an AI agent framework?', answer: 'Software infrastructure for building autonomous AI agents that can plan, reason, use tools, and take actions independently. Popular frameworks include LangChain, CrewAI, and AutoGen.' },
            { question: 'How much do AI agents cost to run?', answer: 'AI agent workflows cost 5-20x more than single prompt-response interactions because each step involves LLM calls, tool calls, and state management.' },
        ],
        relatedTerms: ['agentic-ai', 'large-language-model', 'artificial-intelligence', 'ai-governance'],
    },
    {
        slug: 'synthetic-data',
        title: 'Synthetic Data',
        category: 'AI & Machine Learning',
        definition: `Synthetic data is artificially generated data that mimics the statistical properties of real-world data without containing any actual real-world records. It's created using AI models, simulation engines, or mathematical algorithms to produce datasets for training, testing, and validation.\n\nUse cases include: training ML models when real data is scarce or expensive, privacy-preserving data sharing (no real PII), testing edge cases that rarely occur in production, augmenting imbalanced datasets, and compliance with data protection regulations (GDPR, CCPA).\n\nGartner predicts that by 2030, synthetic data will completely overshadow real data in AI model training. The economics are compelling: generating synthetic data can cost 10-100x less than collecting and labeling real data.\n\nRisks include: synthetic data that doesn't accurately represent real-world distributions, mode collapse (synthetic data lacking the diversity of real data), and overfit to synthetic patterns that don't exist in production.`,
        whyItMatters: `Synthetic data solves the data scarcity and privacy problems that block many AI projects. Understanding when synthetic data is appropriate  -  and when it's risky  -  is critical for AI project planning and compliance.`,
        faqs: [
            { question: 'What is synthetic data?', answer: 'Synthetic data is artificially generated data that mimics real-world data properties without containing actual records. It is used for model training, testing, and privacy-preserving data sharing.' },
            { question: 'Is synthetic data as good as real data?', answer: 'For many tasks, yes. Well-generated synthetic data can match real data performance within 5-10%. But it must be validated against real-world distributions to avoid training on unrealistic patterns.' },
        ],
        relatedTerms: ['artificial-intelligence', 'ai-bias', 'machine-learning-ops', 'fine-tuning'],
    },
    {
        slug: 'context-window',
        title: 'Context Window',
        category: 'AI & Machine Learning',
        definition: `A context window is the maximum amount of text (measured in tokens) that a language model can process in a single interaction. It determines how much information you can provide to the model and how long a response it can generate.\n\nContext window sizes have grown dramatically: GPT-3 had 4K tokens, GPT-4 offered 128K tokens, and Gemini 1.5 reached 1M tokens. Larger context windows enable processing entire documents, codebases, or conversation histories.\n\nHowever, larger context windows come with costs: inference cost scales with context length (quadratically for standard attention), model accuracy degrades in the "middle" of long contexts (the "lost in the middle" phenomenon), and latency increases with context size.\n\nToken is the unit of measurement: roughly 1 token ≈ 0.75 words in English. A 128K context window can hold approximately 96,000 words  -  roughly the length of a novel. But filling the full context window every query is expensive (tokens × price-per-token).`,
        whyItMatters: `Context window size determines what's possible with your AI application. Too small and you can't provide enough context for accurate responses. Too large and you're paying for unused capacity. Optimizing context usage is a key lever for AI cost management.`,
        faqs: [
            { question: 'What is a context window in AI?', answer: 'The context window is the maximum amount of text a language model can process at once, measured in tokens. It determines how much information you can include in a prompt.' },
            { question: 'Does a larger context window cost more?', answer: 'Yes. Inference cost scales with context length. A query using 100K tokens costs roughly 25x more than one using 4K tokens. Optimize context usage to manage costs.' },
        ],
        relatedTerms: ['large-language-model', 'prompt-engineering', 'ai-inference', 'cost-of-predictivity'],
        relatedTools: [{ name: 'AI Unit Economics Benchmark (AUEB)', url: '/tools/aueb' }],
    },
    {
        slug: 'guardrails-ai',
        title: 'AI Guardrails',
        category: 'AI & Machine Learning',
        definition: `AI guardrails are runtime constraints, filters, and validation systems that prevent AI models from producing harmful, inappropriate, or incorrect outputs. They act as safety nets between the model's raw output and what the user sees.\n\nTypes of guardrails include: input validation (blocking malicious prompts), output filtering (removing harmful content), format validation (ensuring structured outputs match expected schemas), fact-checking (verifying claims against knowledge bases), PII detection (redacting personal information), and toxicity filtering.\n\nPopular guardrail frameworks include: Guardrails AI (open-source), NeMo Guardrails (NVIDIA), Llama Guard (Meta), and custom implementations using regex, classifiers, and secondary LLM calls.\n\nGuardrails add latency and cost to every AI interaction. Each validation check requires compute time and potentially additional API calls. The art is balancing safety with performance  -  applying strict guardrails to high-risk outputs and lighter guardrails to low-risk outputs.`,
        whyItMatters: `Guardrails are the difference between a demo-ready AI feature and a production-ready AI feature. Without guardrails, AI systems will eventually produce outputs that damage your brand, violate regulations, or harm users.`,
        faqs: [
            { question: 'What are AI guardrails?', answer: 'AI guardrails are runtime systems that prevent AI models from producing harmful, inappropriate, or incorrect outputs. They include input validation, output filtering, fact-checking, and PII detection.' },
            { question: 'Do guardrails add cost?', answer: 'Yes. Each guardrail check adds latency (10-100ms) and cost (additional compute or API calls). Design guardrails proportional to risk  -  strict for high-risk outputs, light for low-risk.' },
        ],
        relatedTerms: ['ai-safety', 'ai-alignment', 'ai-governance', 'ai-hallucination'],
    },
    {
        slug: 'ai-benchmarking',
        title: 'AI Benchmarking',
        category: 'AI & Machine Learning',
        definition: `AI benchmarking is the practice of evaluating AI model performance against standardized test sets and metrics. Benchmarks provide objective comparisons between models, versions, and approaches.\n\nPopular benchmarks include: MMLU (massive multitask language understanding), HellaSwag (commonsense reasoning), HumanEval (code generation), MT-Bench (multi-turn conversation quality), and domain-specific benchmarks for medical, legal, and financial applications.\n\nBenchmark limitations: models can be specifically optimized for benchmarks without improving real-world performance ("teaching to the test"), benchmarks may not reflect your specific use case, and benchmark datasets can leak into training data, inflating scores.\n\nFor enterprise AI evaluation, Richard Ewing recommends going beyond public benchmarks to create internal benchmarks that reflect your specific use cases, data distributions, and quality requirements. The AI Unit Economics Benchmark (AUEB) provides a framework for evaluating AI features on their economic impact, not just accuracy.`,
        whyItMatters: `Benchmarks prevent the "vibes-based" evaluation of AI systems. Without objective metrics, teams pick models based on marketing claims and demos rather than rigorous evaluation on their actual use cases.`,
        faqs: [
            { question: 'What are AI benchmarks?', answer: 'AI benchmarks are standardized tests that measure model performance on specific tasks. They enable objective comparison between models, versions, and approaches.' },
            { question: 'Are AI benchmarks reliable?', answer: 'Public benchmarks have limitations: models can be optimized for specific benchmarks, and test data can leak into training sets. Always supplement public benchmarks with internal evaluations on your specific use cases.' },
        ],
        relatedTerms: ['large-language-model', 'ai-inference', 'artificial-intelligence'],
        relatedTools: [{ name: 'AI Unit Economics Benchmark (AUEB)', url: '/tools/aueb' }],
    },
];
