import { GlossaryTerm } from '../types';

// =============================================================================
// TWELFTH PASS: AI Agent Tools, Frameworks, and Infrastructure
// OpenClaw, NemoClaw, LangChain, RAG, Vector DBs, Embeddings, etc.
// =============================================================================

export const aiToolsTerms: GlossaryTerm[] = [
    {
        title: 'OpenClaw',
        slug: 'openclaw',
        definition: `OpenClaw is an open-source AI agent framework that functions as an "operating system for personal AI." Created by Peter Steinberger (later hired by OpenAI), OpenClaw went viral in early 2026 and was showcased at NVIDIA's GTC Developer Conference.\n\n**What OpenClaw does:**\n- Runs multiple AI agents locally on your machine\n- Intercepts and orchestrates messages across LLMs\n- Executes commands across shell, filesystem, and web browsers\n- Integrates with Telegram, Discord, Slack, and WhatsApp\n- Provides a tool-execution environment for AI agents\n\n**Why it matters for AI economics:** OpenClaw-style frameworks shift AI compute costs from cloud API calls to local inference. This fundamentally changes AI COGS calculations  -  local models have higher upfront cost but near-zero marginal cost per query.`,
        whyItMatters: 'OpenClaw represents the shift toward local AI execution. For product leaders evaluating AI architecture, the choice between cloud APIs (variable cost) and local models (fixed cost) determines your entire cost structure.',
        category: 'AI Tools & Frameworks',
        relatedTerms: ['nemoclaw', 'ai-agent', 'agentic-workflow', 'large-language-model'],
        faqs: [{ question: 'Is OpenClaw free?', answer: 'Yes  -  OpenClaw is fully open-source. However, running AI models locally requires capable hardware (GPU with sufficient VRAM). The real cost is in the computing infrastructure, not the software.' }],
    },
    {
        title: 'NemoClaw',
        slug: 'nemoclaw',
        definition: `NemoClaw is NVIDIA's enterprise-grade AI agent framework, built on the OpenClaw foundation. Announced at GTC 2026, NemoClaw adds enterprise security, governance, and compliance features to OpenClaw's open-source agent architecture.\n\n**Enterprise additions over OpenClaw:**\n- **Role-based access control (RBAC):** Fine-grained permissions for agent actions\n- **Authentication integration:** Enterprise SSO and identity management\n- **Audit logging:** Comprehensive logging of all agent actions for compliance\n- **Privacy routing:** Intelligently routes sensitive workloads to local models\n- **Local Nemotron deployment:** Ensures sensitive data never leaves premises\n- **Policy-based guardrails:** Enforced boundaries on agent behavior\n\nNemoClaw addresses the core enterprise concern with AI agents: "How do I give agents autonomy while maintaining control?"  -  which is exactly the problem Exogram's EAAP protocol solves.`,
        whyItMatters: 'NemoClaw validates the enterprise need for AI agent governance  -  the same problem Exogram solves at the protocol level. As AI agents become enterprise infrastructure, governance frameworks like NemoClaw and Exogram become essential.',
        category: 'AI Tools & Frameworks',
        relatedTerms: ['openclaw', 'ai-agent', 'agentic-governance', 'zero-trust'],
        faqs: [{ question: 'How does NemoClaw compare to Exogram?', answer: 'NemoClaw provides NVIDIA-specific agent execution governance. Exogram provides a universal protocol (EAAP) for AI agent admissibility that works across any agent framework. Think of NemoClaw as the implementation and Exogram as the standard.' }],
    },
    {
        title: 'LangChain',
        slug: 'langchain',
        definition: `LangChain is the most widely-used framework for building applications powered by Large Language Models. It provides modular components for chaining together LLM calls, tool use, memory management, and retrieval systems.\n\n**Core components:**\n- **Chains:** Sequences of LLM calls and operations\n- **Agents:** LLM-powered decision-makers that choose which tools to use\n- **Memory:** Persistent context across conversation turns\n- **Retrievers:** Interfaces to vector stores and knowledge bases for RAG\n- **Tools:** Integrations with APIs, databases, search engines, and more\n\n**LangGraph:** A companion framework for building stateful, multi-agent workflows with explicit state management and loop handling.\n\nLangChain has become the de facto standard for LLM application development, with thousands of integrations and a massive community.`,
        whyItMatters: 'LangChain is the most common framework teams use when building AI features. Understanding its architecture helps product leaders evaluate build complexity, maintenance burden, and the technical debt implications of LLM application development.',
        category: 'AI Tools & Frameworks',
        relatedTerms: ['large-language-model', 'rag-architecture', 'ai-agent', 'prompt-engineering'],
        faqs: [{ question: 'Is LangChain production-ready?', answer: 'Yes, LangChain is used in production by thousands of companies. However, it moves fast  -  breaking changes between versions create maintenance debt. Teams should pin versions and test thoroughly before upgrading.' }],
    },
    {
        title: 'Retrieval-Augmented Generation (RAG)',
        slug: 'rag-architecture',
        definition: `Retrieval-Augmented Generation (RAG) is an AI architecture pattern that enhances LLM responses by first retrieving relevant information from external knowledge bases before generating an answer.\n\n**How RAG works:**\n1. **Index:** Documents are split into chunks and converted to embeddings (vectors)\n2. **Store:** Embeddings are stored in a vector database (Pinecone, Chroma, Weaviate)\n3. **Retrieve:** User query is converted to an embedding and similar chunks are retrieved\n4. **Generate:** Retrieved chunks + user query are sent to the LLM for response generation\n\n**RAG vs Fine-Tuning:**\n- RAG: Lower upfront cost, higher per-query cost, dynamic knowledge\n- Fine-tuning: Higher upfront cost, lower per-query cost, static knowledge\n\n**Advanced RAG patterns:**\n- **Agentic RAG:** AI agents that iteratively retrieve, reason, and retrieve again\n- **Multimodal RAG:** Retrieving across text, images, audio, and video\n- **Hybrid search:** Combining vector similarity with keyword matching\n\nThe RAG market is experiencing explosive growth driven by enterprise AI adoption.`,
        whyItMatters: 'RAG is the most cost-effective way to give LLMs access to private, up-to-date knowledge without expensive fine-tuning. But RAG systems create their own technical debt  -  embedding drift, chunking strategies, and retrieval quality all require ongoing maintenance.',
        category: 'AI & Machine Learning',
        relatedTerms: ['vector-database', 'embeddings', 'large-language-model', 'fine-tuning'],
        faqs: [{ question: 'What is the cost of a RAG system?', answer: 'RAG costs include: vector database hosting ($50-500/mo), embedding generation ($0.10-0.50 per 1M tokens), and LLM generation costs. Total: $200-5,000/mo for a small deployment. Use the AUEB calculator to model your specific economics.' }],
    },
    {
        title: 'Vector Database',
        slug: 'vector-database', tier: 'pillar',
        definition: `A Vector Database is a specialized database designed to store, index, and query high-dimensional vector embeddings efficiently. It is the infrastructure backbone of RAG systems and semantic search.\n\n**How it works:** Text, images, or other data are converted into numerical vectors (embeddings) that capture semantic meaning. Similar items have similar vectors. The database enables fast similarity search across millions or billions of vectors.\n\n**Leading solutions (2025-2026):**\n- **Pinecone:** Managed, serverless, enterprise-grade\n- **Chroma:** Open-source, developer-friendly\n- **Weaviate:** Open-source with hybrid search\n- **Milvus/Zilliz:** High-performance, scalable\n- **pgvector:** PostgreSQL extension for vector search\n\n**Market size:** The vector database market reached $2.55B in 2025, projected to reach $3.7B+ in 2026. Growth is driven by enterprise AI adoption and the explosion of unstructured data.`,
        whyItMatters: 'Vector databases are the "memory" infrastructure for AI applications. Choosing the right vector database and indexing strategy directly impacts AI feature performance, cost, and scalability.',
        category: 'AI & Machine Learning',
        relatedTerms: ['rag-architecture', 'embeddings', 'large-language-model', 'ai-cogs'],
        faqs: [{ question: 'Do I need a vector database for AI features?', answer: 'If your AI feature needs to reference private data, documents, or knowledge  -  yes. Vector databases enable semantic search and RAG, which are the most practical ways to give LLMs access to your specific information.' }],
    },
    {
        title: 'Embeddings',
        slug: 'embeddings',
        definition: `Embeddings are numerical vector representations of data (text, images, audio) that capture semantic meaning in a high-dimensional space. Similar concepts have similar embeddings, enabling semantic search and similarity matching.\n\n**How embeddings work:**\n- Text → Embedding model → [0.023, -0.184, 0.442, ...] (768-3072 dimensions)\n- "CEO" and "Chief Executive" produce similar vectors\n- "CEO" and "hamburger" produce very different vectors\n\n**Key embedding models (2025-2026):**\n- **OpenAI text-embedding-3-large:** Most popular commercial model\n- **Cohere Embed v3:** Multilingual, high-performance\n- **BGE-M3:** Open-source, multilingual\n- **Sentence-BERT:** Foundation open-source model\n\n**Emerging trends:**\n- **Multimodal embeddings:** Unifying text, image, and audio in one vector space\n- **Self-hosted models:** Privacy-first, rivaling commercial quality\n- **Dynamic embeddings:** Context-aware, adapting to user behavior`,
        whyItMatters: 'Embeddings are the foundation of AI search, recommendation systems, and RAG. Every embedding generation costs money (API calls), and embedding quality directly determines retrieval accuracy. Poor embeddings = poor AI responses = wasted compute.',
        category: 'AI & Machine Learning',
        relatedTerms: ['vector-database', 'rag-architecture', 'large-language-model', 'ai-cogs'],
        faqs: [{ question: 'How much do embeddings cost?', answer: 'OpenAI text-embedding-3-large costs $0.13 per 1M tokens. For a knowledge base of 100K documents, initial embedding costs ~$1-5. But re-embedding for updates and query-time embedding adds ongoing cost.' }],
    },
    {
        title: 'CrewAI',
        slug: 'crewai',
        definition: `CrewAI is an open-source framework for building role-based multi-agent AI systems that collaborate like real-world teams.\n\n**Core concept:** Assign each AI agent a specific role (researcher, analyst, writer, reviewer) and let them collaborate on complex tasks with defined workflows.\n\n**Components:**\n- **Agents:** Role-defined AI entities with specific goals and backstories\n- **Tasks:** Specific assignments given to agents\n- **Crews:** Teams of agents working together on a shared objective\n- **Tools:** External capabilities agents can use (search, APIs, databases)\n\n**Use cases:** Research automation, content creation pipelines, data analysis workflows, code review teams, and customer support escalation.\n\nCrewAI is one of the fastest-growing multi-agent frameworks, competing with LangGraph and Microsoft AutoGen.`,
        whyItMatters: 'Multi-agent systems create unique engineering economics: each agent has its own LLM costs, but the combined output can be greater than the sum of parts. Understanding multi-agent cost structures is essential for product leaders building AI features.',
        category: 'AI Tools & Frameworks',
        relatedTerms: ['ai-agent', 'agentic-workflow', 'langchain', 'large-language-model'],
        faqs: [{ question: 'How does CrewAI pricing work?', answer: 'CrewAI itself is free and open-source. The cost comes from the underlying LLM API calls. A crew of 4 agents each making 5 LLM calls costs 20 API calls per task  -  costs multiply with the number of agents and interaction rounds.' }],
    },
    {
        title: 'Model Context Protocol (MCP)',
        slug: 'model-context-protocol',
        definition: `The Model Context Protocol (MCP) is an open standard developed by Anthropic that enables AI models and agents to connect with external tools, data sources, and services through a standardized interface.\n\n**What MCP enables:**\n- AI models can access databases, APIs, and file systems through unified connectors\n- Standardized tool calling across different AI models and frameworks\n- Pluggable architecture  -  add new capabilities without changing the AI model\n- Secure, permission-controlled access to enterprise systems\n\n**Why MCP matters:** Before MCP, every AI integration was custom-built. MCP provides a standard "USB port" for AI  -  any MCP-compatible tool works with any MCP-compatible AI model. This reduces the integration debt that AI features accumulate.`,
        whyItMatters: 'MCP reduces AI integration debt by standardizing how AI connects to tools. Without a standard like MCP, every AI-to-tool connection is custom engineering  -  creating massive maintenance burden as the number of integrations grows.',
        category: 'AI Tools & Frameworks',
        relatedTerms: ['ai-agent', 'agentic-workflow', 'langchain', 'openclaw'],
        faqs: [{ question: 'Is MCP only for Claude/Anthropic?', answer: 'No  -  MCP is an open standard. While Anthropic created it, MCP is designed to be model-agnostic. Any AI model or framework can implement MCP to connect with MCP-compatible tools.' }],
    },
    {
        title: 'Ollama',
        slug: 'ollama',
        definition: `Ollama is a lightweight, open-source framework for running Large Language Models (LLMs) locally on your own hardware. It simplifies the process of downloading, configuring, and running models like Llama, Mistral, and Gemma without cloud dependencies.\n\n**Why Ollama is popular:**\n- **Privacy:** Data never leaves your machine\n- **Cost:** No API fees after hardware investment\n- **Speed:** No network latency for inference\n- **Flexibility:** Run any open-source model\n\n**Economic implications:** Ollama enables a "fixed cost" AI model where hardware is the upfront investment and marginal query cost is essentially electricity. This contrasts with cloud APIs where every query has a variable cost.\n\nFor organizations with high query volume, local inference via Ollama can be 10-100x cheaper than API-based models.`,
        whyItMatters: 'Ollama represents the "buy vs rent" decision in AI infrastructure. For high-volume AI features, running models locally can dramatically reduce AI COGS  -  but requires upfront hardware investment and operational expertise.',
        category: 'AI Tools & Frameworks',
        relatedTerms: ['large-language-model', 'ai-cogs', 'openclaw', 'fine-tuning'],
        faqs: [{ question: 'Can Ollama replace OpenAI API?', answer: 'For many use cases, yes  -  if you have adequate hardware (GPU with 8GB+ VRAM). Open-source models like Llama 3 and Mistral perform at 80-90% of GPT-4 quality for most tasks. The tradeoff is hardware cost vs API cost.' }],
    },
    {
        title: 'Hugging Face',
        slug: 'hugging-face',
        definition: `Hugging Face is the largest open-source platform for AI models, datasets, and machine learning tools. Often called the "GitHub of machine learning," Hugging Face hosts over 500,000 pre-trained models and 100,000 datasets.\n\n**Key offerings:**\n- **Transformers library:** The standard Python library for using pre-trained AI models\n- **Model Hub:** Repository of 500K+ models (text, image, audio, multimodal)\n- **Datasets Hub:** 100K+ datasets for training and evaluation\n- **Spaces:** Hosted demo applications for AI models\n- **Inference API:** Serverless model deployment\n\n**For product leaders:** Hugging Face is where open-source AI innovation happens. Understanding what models are available helps evaluate build-vs-buy decisions for AI features.`,
        whyItMatters: 'Hugging Face democratizes access to AI models. For product leaders, it provides the alternative to expensive proprietary APIs  -  but using open-source models introduces different cost structures (hosting, maintenance, fine-tuning) that require careful economic analysis.',
        category: 'AI Tools & Frameworks',
        relatedTerms: ['large-language-model', 'fine-tuning', 'embeddings', 'ollama'],
        faqs: [{ question: 'Is Hugging Face free?', answer: 'The platform and open-source libraries are free. Model hosting, Inference API (at scale), and enterprise features (security, SSO, private repos) are paid. Most individual developers and small teams can use it entirely for free.' }],
    },
    {
        title: 'Prompt Injection',
        slug: 'prompt-injection', tier: 'pillar',
        definition: `Prompt Injection is a security vulnerability where malicious input causes an AI model to ignore its system instructions, reveal internal prompts, or perform unintended actions.\n\n**Types:**\n- **Direct injection:** User input that overrides system instructions (e.g., "Ignore all previous instructions and...")\n- **Indirect injection:** Malicious content embedded in external data the AI processes (e.g., hidden instructions in a webpage the AI summarizes)\n\n**Why it's dangerous:**\n- AI agents with tool access can be tricked into executing harmful actions\n- Customer-facing AI can be made to reveal proprietary system prompts\n- RAG systems can be poisoned by injecting malicious content into knowledge bases\n\n**Mitigation strategies:** Input sanitization, output filtering, instruction hierarchy separation, and validation layers between agent decisions and action execution.`,
        whyItMatters: 'Prompt injection is the SQL injection of the AI era. Every AI-facing product needs prompt injection defenses. The cost of a successful injection  -  data leakage, unauthorized actions, reputational damage  -  makes this a critical AI economics concern.',
        category: 'AI Governance & Verification',
        relatedTerms: ['ai-red-teaming', 'ai-guardrails', 'ai-hallucination', 'zero-trust'],
        faqs: [{ question: 'Can prompt injection be fully prevented?', answer: 'Not yet  -  there is no complete solution. Best practices include defense-in-depth: input validation, output filtering, sandboxed execution, and human-in-the-loop for sensitive actions. This is why AI agent governance (like Exogram) is essential.' }],
    },
    {
        title: 'Transformer Architecture',
        slug: 'transformer-architecture',
        definition: `The Transformer is the neural network architecture that powers virtually all modern AI  -  GPT, Claude, Gemini, Llama, and every other LLM. Introduced in the 2017 paper "Attention Is All You Need," the transformer uses a self-attention mechanism that allows the model to weigh the importance of different parts of the input simultaneously.\n\n**Key innovations:**\n- **Self-attention:** Each element can attend to every other element in the sequence\n- **Parallelization:** Unlike RNNs, transformers process all inputs simultaneously (faster training)\n- **Scaling:** Performance improves predictably with more parameters, data, and compute\n\n**Why it matters for AI economics:** Transformer compute costs scale quadratically with input length (context window). A 128K context window costs 4x more than a 64K context window. This directly impacts AI COGS.`,
        whyItMatters: 'Understanding transformer architecture helps product leaders make informed decisions about context window sizes, input optimization, and cost management. Every extra token costs money  -  transformers make this cost relationship predictable.',
        category: 'AI & Machine Learning',
        relatedTerms: ['large-language-model', 'generative-ai', 'ai-cogs', 'fine-tuning'],
        faqs: [{ question: 'Why do longer prompts cost more?', answer: 'Transformer self-attention computation scales quadratically with input length. Doubling the context window roughly quadruples the compute. This is why AI COGS increase with longer conversations and why efficient prompt engineering saves money.' }],
    },
];
