import { GlossaryTerm } from '../types';

// =============================================================================
// ELEVENTH PASS: HIGH-VOLUME SEARCH TERMS — SaaS metrics + foundational AI
// These are the terms people ACTUALLY search for in massive volume.
// =============================================================================

export const highVolumeTerms: GlossaryTerm[] = [
    {
        title: 'Annual Recurring Revenue (ARR)',
        slug: 'arr',
        tier: 'pillar',
        definition: `Annual Recurring Revenue (ARR) is the annualized value of recurring subscription revenue. It is the single most important metric for SaaS company valuation.\n\n**Formula:** ARR = MRR × 12\n\n**Or more precisely:**\nARR = (New ARR) + (Expansion ARR) - (Contraction ARR) - (Churned ARR)\n\n**Why ARR matters for valuation:**\n- Public SaaS companies trade at 5-15x ARR multiples\n- High-quality SaaS (Rule of 40+) commands premium multiples\n- ARR growth rate is the #1 predictor of valuation multiple\n\nARR only counts recurring revenue — one-time fees, professional services, and usage-based revenue are excluded from ARR calculations.`,
        whyItMatters: 'ARR is the foundation of SaaS valuation. It measures the predictable, recurring revenue engine. Technical debt that slows feature velocity directly suppresses ARR growth by delaying new revenue-generating capabilities.',
        howToMeasure: 'Sum all active subscription contracts, annualized. Exclude one-time fees and services revenue.',
        category: 'SaaS Metrics & Finance',
        relatedTerms: ['mrr', 'net-revenue-retention', 'rule-of-40', 'burn-multiple'],
        faqs: [{ question: 'What ARR growth rate is considered good?', answer: 'For Series A: 200%+ YoY. Series B: 100-200%. Series C+: 50-100%. Public companies: 20-40% is strong. The T2D3 benchmark (triple, triple, double, double, double) describes ideal ARR trajectory.' }],
    },
    {
        title: 'Monthly Recurring Revenue (MRR)',
        slug: 'mrr',
        definition: `Monthly Recurring Revenue (MRR) is the predictable monthly revenue generated from active subscriptions. It is ARR divided by 12, and the most granular measure of SaaS business health.\n\n**MRR components:**\n- **New MRR:** Revenue from new customers acquired this month\n- **Expansion MRR:** Additional revenue from existing customers (upgrades, add-ons)\n- **Contraction MRR:** Revenue lost from downgrades\n- **Churned MRR:** Revenue lost from cancelled subscriptions\n\n**Net New MRR = New + Expansion - Contraction - Churn**\n\nTracking MRR by component reveals whether growth is coming from acquisition (expensive) or expansion (efficient).`,
        whyItMatters: 'MRR is the operational heartbeat of a SaaS business. Net new MRR trending negative is an early warning sign. Segmenting MRR by cohort, geography, and plan tier reveals where growth is healthy and where it is fragile.',
        howToMeasure: 'Sum all active monthly subscription values. For annual contracts, divide by 12. Track new, expansion, contraction, and churn components separately.',
        category: 'SaaS Metrics & Finance',
        relatedTerms: ['arr', 'churn-rate', 'net-revenue-retention', 'customer-lifetime-value'],
        faqs: [{ question: 'Should I track MRR or ARR?', answer: 'Track both. MRR for operational decisions (monthly trends, churn detection). ARR for strategic decisions (fundraising, valuation, board reporting). They measure the same thing at different time horizons.' }],
    },
    {
        title: 'Customer Acquisition Cost (CAC)',
        slug: 'customer-acquisition-cost',
        tier: 'pillar',
        definition: `Customer Acquisition Cost (CAC) is the total cost of acquiring a new customer, including all sales and marketing expenses.\n\n**Formula:** CAC = Total Sales & Marketing Spend / Number of New Customers Acquired\n\n**2025 benchmarks:**\n- B2B SaaS average: ~$1,200 per customer\n- Enterprise SaaS: $5,000-$50,000+ per customer\n- SMB SaaS: $200-$2,000 per customer\n- PLG SaaS: $50-$500 per customer\n\n**Critical ratios:**\n- **LTV:CAC ratio:** Should be ≥ 3:1 for healthy economics\n- **CAC Payback Period:** Months to recover CAC from subscription revenue (ideal: < 18 months)`,
        whyItMatters: 'CAC determines the efficiency of your growth engine. Rising CAC without proportional LTV increase signals market saturation or competitive pressure. For investors, CAC payback period is a key indicator of capital efficiency.',
        howToMeasure: 'Divide total sales and marketing spend (including salaries, tools, advertising, events) by the number of new customers acquired in the same period.',
        category: 'SaaS Metrics & Finance',
        relatedTerms: ['customer-lifetime-value', 'burn-multiple', 'product-led-growth', 'arr'],
        faqs: [{ question: 'What is a good LTV:CAC ratio?', answer: '3:1 is the standard benchmark. Below 3:1 means you are spending too much to acquire customers. Above 5:1 might mean you are underinvesting in growth and leaving revenue on the table.' }],
    },
    {
        title: 'Customer Lifetime Value (LTV / CLTV)',
        slug: 'customer-lifetime-value',
        tier: 'pillar',
        definition: `Customer Lifetime Value (LTV or CLTV) is the total revenue expected from a customer account over the entire duration of their relationship with your company.\n\n**Simple formula:** LTV = ARPA × Customer Lifetime\n\n**More precise:** LTV = ARPA / Monthly Churn Rate\n\nWhere ARPA = Average Revenue Per Account\n\n**Example:**\n- ARPA: $500/month\n- Monthly churn rate: 2%\n- LTV = $500 / 0.02 = $25,000\n\nLTV is the most important metric to pair with Customer Acquisition Cost (CAC). The LTV:CAC ratio determines whether your unit economics are sustainable.`,
        whyItMatters: 'LTV tells you the ceiling on what you can spend to acquire a customer and still make money. If your LTV is $25,000, you can afford to spend up to ~$8,000 on acquisition (3:1 ratio). Technical debt that causes churn directly reduces LTV.',
        howToMeasure: 'Divide average revenue per account by your monthly churn rate. For more precision, model by cohort and segment.',
        category: 'SaaS Metrics & Finance',
        relatedTerms: ['customer-acquisition-cost', 'churn-rate', 'net-revenue-retention', 'arr'],
        faqs: [{ question: 'How does technical debt affect LTV?', answer: 'Technical debt degrades product quality, which increases churn rate, which directly reduces LTV. A 1% increase in monthly churn can cut LTV by 33%. This is why technical debt is a financial metric, not just an engineering one.' }],
    },
    {
        title: 'Churn Rate',
        slug: 'churn-rate',
        definition: `Churn Rate measures the percentage of customers or revenue lost over a given period. It is the inverse of retention and the most critical indicator of product-market fit.\n\n**Types:**\n- **Customer churn (logo churn):** % of customers who cancel\n- **Revenue churn (MRR churn):** % of MRR lost to cancellations and downgrades\n- **Gross churn:** Total lost revenue before expansion\n- **Net churn:** Lost revenue minus expansion (can be negative = net expansion)\n\n**2025 benchmarks:**\n- Monthly churn average: 4.1% (3.0% voluntary + 1.1% involuntary)\n- B2B monthly churn: ~3.5%\n- B2C monthly churn: ~4.0%\n- Best-in-class annual churn: < 5%`,
        whyItMatters: 'Churn is the most honest metric in SaaS. High churn means customers are not getting enough value. It directly reduces LTV, increases required CAC, and signals product-market fit problems. Even small reductions in churn rate have massive compounding effects on revenue.',
        howToMeasure: 'Divide customers lost in a period by customers at the start of the period. Track both customer churn and revenue churn separately.',
        category: 'SaaS Metrics & Finance',
        relatedTerms: ['net-revenue-retention', 'customer-lifetime-value', 'arr', 'product-market-fit'],
        faqs: [{ question: 'How does technical debt increase churn?', answer: 'Technical debt causes slower feature delivery, more bugs, degraded performance, and increased downtime — all of which reduce the value customers receive. Customers churn when the product stops meeting their needs, and debt-driven stagnation is the #1 cause.' }],
    },
    {
        title: 'Large Language Model (LLM)',
        slug: 'large-language-model',
        tier: 'pillar',
        definition: `A Large Language Model (LLM) is an AI system trained on massive text datasets to understand and generate human language. LLMs are the foundation of modern AI assistants, chatbots, coding tools, and content generation.\n\n**Key LLMs (2025-2026):**\n- **GPT-4o / GPT-5** (OpenAI)\n- **Claude 4 / Opus** (Anthropic)\n- **Gemini 2.5 / 3.1** (Google)\n- **Llama 3.x / 4** (Meta, open-source)\n- **Mistral Large** (Mistral AI)\n\n**How LLMs work:** LLMs are neural networks with billions of parameters trained on text from the internet, books, and other sources. They predict the next likely token (word/subword) given the preceding context. This probabilistic generation is what enables both their power and their tendency to hallucinate.\n\n**Economic impact:** Every LLM query costs money (compute + API fees). This variable cost fundamentally changes the economics of software — from near-zero marginal cost to measurable per-interaction cost.`,
        whyItMatters: 'LLMs are the most transformative technology since the internet. But they introduce variable costs to software economics for the first time. Understanding LLM economics — cost per token, accuracy vs cost tradeoffs, and margin impact — is essential for any product leader building AI features.',
        category: 'AI & Machine Learning',
        relatedTerms: ['ai-cogs', 'cost-of-predictivity', 'ai-hallucination', 'rag-architecture'],
        faqs: [{ question: 'How much does it cost to run an LLM query?', answer: 'API costs range from $0.001 to $0.10+ per query depending on model, context length, and provider. At 1M queries/month, this can be $1,000-$100,000/month in AI COGS alone. The AUEB calculator helps model these economics.' }],
    },
    {
        title: 'AI Agent',
        slug: 'ai-agent',
        tier: 'pillar',
        definition: `An AI Agent is an autonomous software system that can perceive its environment, reason about goals, make plans, use tools, and take actions with minimal human intervention.\n\n**How AI agents differ from chatbots:**\n- **Chatbot:** Responds to prompts, stateless, single-turn\n- **AI Agent:** Plans multi-step actions, uses tools, maintains state, operates autonomously\n\n**Agent capabilities:**\n- Break complex goals into subtasks\n- Call APIs, databases, and other tools\n- Evaluate results and adjust approach\n- Maintain context across multiple interactions\n- Collaborate with other agents\n\n**Examples:** Coding agents (Devin, SWE-Agent), research agents, customer service agents, DevOps agents, and data analysis agents.\n\nSearch interest for "AI agents" surged 900% in 2025, making it one of the most searched AI terms globally.`,
        whyItMatters: 'AI agents represent the shift from AI as a tool (you ask, it answers) to AI as a worker (you assign, it executes). This creates massive value but also introduces governance challenges — which is exactly what Exogram solves.',
        category: 'AI & Machine Learning',
        relatedTerms: ['agentic-workflow', 'agentic-governance', 'ai-agent-iam', 'orchestration-debt'],
        faqs: [{ question: 'What is the difference between an AI agent and an AI assistant?', answer: 'An AI assistant responds to direct prompts. An AI agent takes autonomous action toward goals. An assistant helps you write an email. An agent researches, drafts, and sends the email on your behalf — and follows up if there is no reply.' }],
    },
    {
        title: 'Prompt Engineering',
        slug: 'prompt-engineering',
        tier: 'pillar',
        definition: `Prompt Engineering is the practice of designing, structuring, and optimizing inputs (prompts) to AI models to produce desired outputs reliably and efficiently.\n\n**Key techniques:**\n- **Zero-shot prompting:** Direct instruction without examples\n- **Few-shot prompting:** Providing examples of desired input/output pairs\n- **Chain-of-thought (CoT):** Instructing the model to reason step-by-step\n- **System prompts:** Setting context, role, and constraints for the model\n- **ReAct (Reasoning + Acting):** Combining reasoning with tool use\n- **Tree of thoughts:** Exploring multiple reasoning paths in parallel\n\n**Economic impact:** Better prompts reduce token usage (lower cost) and improve accuracy (higher value). Prompt engineering directly impacts AI COGS and the Cost of Predictivity.`,
        whyItMatters: 'Prompt engineering is the most cost-effective way to improve AI output quality without fine-tuning. A well-crafted prompt can reduce token usage by 50% and improve accuracy by 20%+ — directly impacting AI unit economics.',
        category: 'AI & Machine Learning',
        relatedTerms: ['large-language-model', 'ai-cogs', 'cost-of-predictivity', 'rag-architecture'],
        faqs: [{ question: 'Is prompt engineering a real job?', answer: 'Yes — and it pays well. But the term is evolving. In 2025-2026, "prompt engineering" is becoming part of every product manager and engineer role, not a standalone position. Understanding how to communicate with AI systems is a core competency.' }],
    },
    {
        title: 'Fine-Tuning',
        slug: 'fine-tuning',
        definition: `Fine-tuning is the process of taking a pre-trained AI model and further training it on a smaller, specialized dataset to adapt it for specific tasks or domains.\n\n**When to fine-tune vs use RAG:**\n- **Fine-tune when:** You need consistent behavior, specific formatting, domain-specific language, or model personality changes\n- **Use RAG when:** You need up-to-date information, source attribution, or dynamic knowledge that changes frequently\n\n**Cost considerations:**\n- Fine-tuning has high upfront cost (training compute) but lower per-query cost\n- RAG has lower upfront cost but higher per-query cost (retrieval + generation)\n- The breakeven depends on query volume and accuracy requirements\n\n**Process:** Prepare labeled data → Upload to provider → Train on your data → Evaluate → Deploy → Monitor for drift`,
        whyItMatters: 'Fine-tuning is a strategic decision with significant economic implications. The choice between fine-tuning, RAG, and prompt engineering determines your AI COGS structure. Getting this decision wrong can make the difference between a profitable AI feature and a money pit.',
        category: 'AI & Machine Learning',
        relatedTerms: ['large-language-model', 'rag-architecture', 'ai-cogs', 'cost-of-predictivity'],
        faqs: [{ question: 'How much does fine-tuning cost?', answer: 'Fine-tuning GPT-4 costs $25-50 per million training tokens. A typical fine-tuning job with 10K examples costs $50-500. But the real cost is in data preparation, evaluation, and ongoing maintenance as the model drifts.' }],
    },
    {
        title: 'Generative AI',
        slug: 'generative-ai',
        definition: `Generative AI refers to AI systems that can create new content — text, images, code, audio, video, and 3D models — based on patterns learned from training data.\n\n**Key modalities:**\n- **Text:** GPT-4, Claude, Gemini, Llama\n- **Images:** DALL-E, Midjourney, Stable Diffusion\n- **Code:** GitHub Copilot, Cursor, Claude Code\n- **Audio:** ElevenLabs, Suno, Udio\n- **Video:** Sora, Runway, Pika\n\n**Economic impact:** Generative AI introduces variable cost to content creation for the first time. Every generated image, text passage, or code snippet costs compute. This fundamentally changes the economics of content-driven products.\n\nBy 2025, generative AI had become the fastest-adopted technology in history, reaching 200M weekly active users faster than any previous technology.`,
        whyItMatters: 'Generative AI is the most disruptive technology shift since cloud computing. It changes who can create what, how fast, and at what cost. But it also introduces new forms of technical debt — AI Hallucination Debt, Model Drift, and Orchestration Debt.',
        category: 'AI & Machine Learning',
        relatedTerms: ['large-language-model', 'ai-hallucination', 'vibe-coding', 'ai-cogs'],
        faqs: [{ question: 'Is generative AI just a buzzword?', answer: 'No — generative AI represents a genuine paradigm shift. It changes the cost structure of content creation from high fixed cost (hire humans) to variable cost (pay per generation). This has massive implications for product economics.' }],
    },
    {
        title: 'Microservices Architecture',
        slug: 'microservices', tier: 'pillar',
        definition: `Microservices is an architectural style where an application is composed of small, independently deployable services that communicate over well-defined APIs.\n\n**Benefits:**\n- Independent deployment and scaling\n- Technology flexibility per service\n- Team autonomy and ownership\n- Fault isolation\n\n**Hidden costs (Microservices Debt):**\n- **Distributed system complexity:** Network latency, partial failures, eventual consistency\n- **Operational overhead:** Each service needs monitoring, logging, deployment pipelines\n- **Integration testing difficulty:** Testing interactions between 50+ services is exponentially harder\n- **Data consistency challenges:** Transactions across services require saga patterns or event sourcing\n\nThe initial move to microservices often creates more technical debt than it eliminates — especially when teams don't have the operational maturity to manage distributed systems.`,
        whyItMatters: 'Microservices are not inherently better than monoliths. They trade one type of complexity (monolith) for another (distributed systems). The economic case for microservices only works when team size and deployment frequency justify the operational overhead.',
        category: 'Architecture & Design',
        relatedTerms: ['technical-debt', 'platform-engineering', 'infrastructure-as-code', 'continuous-deployment'],
        faqs: [{ question: 'When should you NOT use microservices?', answer: 'Small teams (< 20 engineers), early-stage products, simple domains, and organizations without DevOps maturity. Amazon built their first version as a monolith. Start monolithic, extract microservices when you hit specific scaling bottlenecks.' }],
    },
    {
        title: 'Cloud-Native',
        slug: 'cloud-native',
        definition: `Cloud-native is an approach to building and running applications that fully exploits the advantages of the cloud computing model — elasticity, scalability, and managed services.\n\n**Core pillars:**\n- **Containerization:** Packaging applications in Docker/OCI containers\n- **Orchestration:** Kubernetes for container management\n- **Microservices:** Decomposed, independently deployable services\n- **Service mesh:** Infrastructure layer for service-to-service communication\n- **Immutable infrastructure:** Replace rather than update infrastructure\n- **Declarative APIs:** Define desired state, let the system reconcile\n\n**Cloud-native does NOT mean:** "We use AWS/Azure/GCP." Many cloud-hosted applications are not cloud-native. Running a monolith on EC2 is cloud-hosted, not cloud-native.`,
        whyItMatters: 'Cloud-native architecture enables rapid scaling and deployment but creates significant operational complexity. The engineering cost of managing Kubernetes, service meshes, and container orchestration is a form of infrastructure technical debt.',
        category: 'Architecture & Design',
        relatedTerms: ['microservices', 'infrastructure-as-code', 'platform-engineering', 'finops'],
        faqs: [{ question: 'Is cloud-native always better?', answer: 'No. Cloud-native architecture makes sense for large-scale, distributed systems with multiple teams. For small teams and simple applications, a well-built monolith deployed on managed services (Vercel, Railway, Heroku) is often more cost-effective.' }],
    },
    {
        title: 'Technical Debt',
        slug: 'technical-debt-definition',
        tier: 'pillar',
        definition: `Technical Debt is the accumulated cost of expedient engineering decisions that create future maintenance burden. Coined by Ward Cunningham in 1992, the debt metaphor describes how choosing quick solutions over optimal ones generates "interest payments" in the form of increased maintenance work.\n\n**Types of technical debt:**\n- **Deliberate debt:** Conscious shortcuts taken under deadline pressure\n- **Accidental debt:** Debt accumulated through lack of knowledge or changing requirements\n- **Bit rot:** Debt that accumulates simply from aging code and evolving ecosystems\n- **Design debt:** Architectural decisions that made sense originally but no longer scale\n- **AI-generated debt:** Code produced by LLMs without full understanding of system context\n\n**The economic model:**\n- Technical debt accrues "interest" — ongoing maintenance cost\n- Interest compounds as the codebase grows\n- The "principal" is the cost to refactor/replace\n- The Technical Insolvency Date is when interest consumes 100% of engineering capacity\n\nRichard Ewing's contribution: treating technical debt as an economic phenomenon measurable in dollars and quarters, not just a code quality concern.`,
        whyItMatters: 'Technical debt is the central concept in product economics. It is the mechanism by which engineering decisions become financial consequences. Understanding debt economics — not just debt existence — is what separates good engineering leaders from great ones.',
        howToMeasure: 'Use the Product Debt Index (PDI) calculator at richardewing.io/tools/pdi to quantify your debt in dollars and calculate your Technical Insolvency Date.',
        category: 'Technical Debt & Code Quality',
        relatedTerms: ['technical-insolvency-date', 'innovation-tax', 'product-debt-index', 'technical-debt-ratio'],
        relatedTools: [{ name: 'Product Debt Index (PDI) Calculator', url: '/tools/pdi' }],
        faqs: [{ question: 'Is all technical debt bad?', answer: 'No. Strategic debt — deliberate shortcuts taken with full knowledge of the consequences and a plan to repay — can be a valid business decision. The problem is unmanaged debt that accumulates without tracking or repayment plans.' }],
    },
];
