import { GlossaryTerm } from '../types';

// =============================================================================
// THIRTEENTH PASS: More high-demand terms — DevOps, Architecture, Business
// =============================================================================

export const moreTerms: GlossaryTerm[] = [
    {
        title: 'API Gateway',
        slug: 'api-gateway',
        definition: `An API Gateway is a server that acts as a single entry point for all client requests to your backend services. It handles request routing, API composition, rate limiting, authentication, monitoring, and protocol translation.\n\n**Key functions:**\n- **Routing:** Directs requests to appropriate microservices\n- **Rate limiting:** Prevents abuse and protects backend services\n- **Authentication/Authorization:** Validates API keys, JWT tokens, OAuth\n- **Load balancing:** Distributes traffic across service instances\n- **Caching:** Reduces backend load for frequently requested data\n- **Monitoring:** Collects metrics on API usage and performance\n\n**Popular solutions:** AWS API Gateway, Kong, Nginx, Traefik, Cloudflare Gateway.\n\nAPI gateways become a critical chokepoint — and a form of infrastructure debt — when they're misconfigured, under-monitored, or not scaled properly.`,
        whyItMatters: 'API gateways are the front door to your services. A poorly managed gateway creates latency debt, security debt, and operational risk. Understanding gateway economics helps right-size API infrastructure investment.',
        category: 'Architecture & Design',
        relatedTerms: ['microservices', 'cloud-native', 'infrastructure-as-code', 'platform-engineering'],
        faqs: [{ question: 'Do I need an API gateway?', answer: 'If you have more than 2-3 backend services, yes. An API gateway centralizes cross-cutting concerns like auth, rate limiting, and monitoring. Without one, each service implements these independently — creating duplicated effort and inconsistent behavior.' }],
    },
    {
        title: 'CI/CD Pipeline',
        slug: 'ci-cd-pipeline',
        definition: `A CI/CD Pipeline is an automated workflow that builds, tests, and deploys code changes from development to production. CI (Continuous Integration) automatically builds and tests code on every commit. CD (Continuous Delivery/Deployment) automatically deploys verified code to staging or production.\n\n**Typical pipeline stages:**\n1. **Source:** Code pushed to repository (GitHub, GitLab)\n2. **Build:** Compile code, install dependencies\n3. **Test:** Run unit tests, integration tests, security scans\n4. **Deploy to staging:** Automatic deployment for QA\n5. **Deploy to production:** Automatic or manual promotion\n\n**Pipeline as code:** Modern CI/CD pipelines are defined in code (YAML files) alongside the application, making them version-controlled and reviewable.\n\n**Pipeline debt:** Over time, CI/CD pipelines accumulate their own technical debt — slow tests, flaky builds, manual steps, and security gaps.`,
        whyItMatters: 'CI/CD pipeline quality directly determines DORA metrics. A broken or slow pipeline is invisible infrastructure debt that compounds — every engineer waits for it on every code change.',
        category: 'DevOps & Infrastructure',
        relatedTerms: ['dora-metrics', 'platform-engineering', 'shift-left-testing', 'infrastructure-as-code'],
        faqs: [{ question: 'How long should a CI/CD pipeline take?', answer: 'Best practice: under 10 minutes for the full pipeline. Under 5 minutes is excellent. If your pipeline takes 30+ minutes, engineers context-switch while waiting — destroying productivity.' }],
    },
    {
        title: 'Kubernetes',
        slug: 'kubernetes',
        definition: `Kubernetes (K8s) is an open-source container orchestration platform originally developed by Google. It automates deploying, scaling, and managing containerized applications across clusters of machines.\n\n**Core concepts:**\n- **Pods:** Smallest deployable units (one or more containers)\n- **Services:** Stable network endpoints for sets of pods\n- **Deployments:** Declarative updates for pods and replica sets\n- **Namespaces:** Virtual clusters for resource isolation\n- **Ingress:** External access routing to services\n\n**The Kubernetes Tax:** Running Kubernetes requires 1-3 full-time platform engineers just for cluster management. For small teams (< 20 engineers), this overhead often exceeds the benefits. Many companies adopt Kubernetes prematurely, creating significant infrastructure debt.\n\n**Alternatives:** Managed platforms (Vercel, Railway, Render) abstract away Kubernetes complexity for teams that don't need fine-grained infrastructure control.`,
        whyItMatters: 'Kubernetes is powerful but expensive to operate. The "Kubernetes Tax" — dedicated platform engineers, training, tooling — is often underestimated. Product leaders need to evaluate whether Kubernetes complexity is justified for their scale.',
        category: 'DevOps & Infrastructure',
        relatedTerms: ['cloud-native', 'microservices', 'platform-engineering', 'infrastructure-as-code'],
        faqs: [{ question: 'When should you NOT use Kubernetes?', answer: 'Teams under 20 engineers, simple applications, early-stage startups, and organizations without dedicated platform engineers. Managed platforms like Vercel or Railway are often more cost-effective until you hit specific scaling bottlenecks.' }],
    },
    {
        title: 'Observability',
        slug: 'observability',
        definition: `Observability is the ability to understand a system's internal state by examining its external outputs. Unlike traditional monitoring (which checks known failure modes), observability enables debugging unknown failure modes through three pillars:\n\n**The Three Pillars:**\n1. **Logs:** Timestamped records of discrete events\n2. **Metrics:** Numerical measurements aggregated over time (CPU, latency, error rates)\n3. **Traces:** End-to-end request paths through distributed systems\n\n**Beyond the three pillars (2025-2026):**\n- **Profiling:** Continuous profiling for performance optimization\n- **Real User Monitoring (RUM):** Client-side performance and experience data\n- **AI-Powered Analysis:** LLM-based log analysis and anomaly detection\n\n**Popular tools:** Datadog, Grafana/Prometheus, New Relic, Honeycomb, OpenTelemetry.\n\nObservability debt accumulates when systems grow faster than monitoring coverage — creating blind spots that lead to longer incident resolution times.`,
        whyItMatters: 'You cannot improve what you cannot see. Observability debt — systems without adequate monitoring — directly increases MTTR and change failure rate. Every blind spot is a risk.',
        category: 'DevOps & Infrastructure',
        relatedTerms: ['dora-metrics', 'service-level-objectives', 'platform-engineering', 'kubernetes'],
        faqs: [{ question: 'What is the difference between monitoring and observability?', answer: 'Monitoring answers "Is the system working?" Observability answers "Why is the system broken?" Monitoring checks known failure modes. Observability enables investigating unknown failures through logs, metrics, and traces.' }],
    },
    {
        title: 'Product-Led Growth (PLG)',
        slug: 'product-led-growth',
        definition: `Product-Led Growth (PLG) is a go-to-market strategy where the product itself is the primary driver of customer acquisition, conversion, and expansion. Users can try the product (free trial or freemium) before talking to sales.\n\n**PLG mechanics:**\n- **Self-serve onboarding:** Users sign up and get value without sales involvement\n- **Freemium or free trial:** Low barrier to entry\n- **In-product upsells:** Conversion happens inside the product\n- **Viral loops:** Users invite other users naturally\n\n**PLG companies:** Slack, Figma, Notion, Calendly, Datadog, Vercel\n\n**PLG economics:** Lower CAC ($50-500 vs $5K-50K for sales-led), faster time-to-value, but requires excellent product and UX — which means technical debt directly impacts growth.\n\n**The PLG-to-Enterprise motion:** Most successful PLG companies eventually add sales for enterprise deals while keeping PLG for SMB.`,
        whyItMatters: 'PLG has the best unit economics of any go-to-market strategy — but it only works if the product is excellent. Technical debt that degrades product quality directly kills PLG growth. This makes engineering quality a revenue metric, not just a cost metric.',
        category: 'Growth & Marketing',
        relatedTerms: ['customer-acquisition-cost', 'customer-lifetime-value', 'churn-rate', 'product-market-fit'],
        faqs: [{ question: 'Is PLG right for every product?', answer: 'No. PLG works best for products with: low complexity, clear self-serve value, network effects, and broad appeal. Complex enterprise products with long sales cycles usually need sales-led growth.' }],
    },
    {
        title: 'Net Revenue Retention (NRR)',
        slug: 'net-revenue-retention-nrr',
        definition: `Net Revenue Retention (NRR) — also called Net Dollar Retention (NDR) — measures the percentage of recurring revenue retained from existing customers over a period, including expansion (upgrades), contraction (downgrades), and churn (cancellations).\n\n**Formula:** NRR = (Starting MRR + Expansion - Contraction - Churn) / Starting MRR × 100\n\n**Benchmarks:**\n- **Below 90%:** Concerning — customer base is shrinking\n- **90-100%:** Average — some growth from existing customers\n- **100-120%:** Good — existing customers growing\n- **120-140%:** Excellent — strong expansion revenue\n- **140%+:** Elite — (Snowflake at 158%, Datadog at 130%)\n\nNRR above 100% means your existing customer base grows without any new customer acquisition. This is the "holy grail" of SaaS because it means you grow even if you stop acquiring new customers.\n\nNRR is the #1 predictor of SaaS valuation multiples. Companies with 130%+ NRR trade at 2-3x higher multiples.`,
        whyItMatters: 'NRR is the single best metric for measuring product stickiness and expansion potential. Technical debt that causes churn or prevents feature delivery directly suppresses NRR.',
        howToMeasure: 'Track starting MRR for a cohort, then measure expansion (upgrades), contraction (downgrades), and churn after 12 months. NRR = ending cohort MRR / starting cohort MRR.',
        category: 'SaaS Metrics & Finance',
        relatedTerms: ['arr', 'mrr', 'churn-rate', 'customer-lifetime-value'],
        faqs: [{ question: 'Why is NRR so important for investors?', answer: 'NRR measures three things at once: product quality (low churn), expansion potential (upsells work), and pricing power (customers pay more over time). A high NRR means the product compounds its own revenue.' }],
    },
    {
        title: 'Burn Multiple',
        slug: 'burn-multiple-metric',
        definition: `Burn Multiple is a capital efficiency metric that measures how much a company burns to generate each incremental dollar of ARR. It was popularized by David Sacks of Craft Ventures.\n\n**Formula:** Burn Multiple = Net Burn / Net New ARR\n\n**Benchmarks:**\n- **< 1x:** Amazing — generating more ARR than you burn\n- **1-1.5x:** Great — efficient growth\n- **1.5-2x:** Good — acceptable efficiency\n- **2-3x:** Concerning — burning too much per ARR dollar\n- **> 3x:** Bad — very inefficient growth\n\n**Why it matters for fundraising:** In 2025-2026, investors use burn multiple as a primary efficiency screen. Companies with burn multiples above 2x face significantly harder fundraising environments.\n\nBurn multiple directly connects to technical debt: if engineering inefficiency means it takes 3x as many engineers to deliver the same features, your burn multiple suffers proportionally.`,
        whyItMatters: 'Burn multiple is the efficiency metric that investors scrutinize most in 2025-2026. It directly connects engineering efficiency to capital efficiency. Technical debt that inflates headcount needs inflates burn multiple.',
        howToMeasure: 'Burn Multiple = Net Cash Burn (total spend minus revenue) / Net New ARR added in the same period.',
        category: 'SaaS Metrics & Finance',
        relatedTerms: ['arr', 'rule-of-40', 'customer-acquisition-cost', 'burn-rate'],
        faqs: [{ question: 'What is a good burn multiple?', answer: 'Under 1.5x is great. Under 2x is acceptable. Above 3x is a red flag. In the 2025-2026 capital environment, investors strongly prefer efficient growth with low burn multiples.' }],
    },
    {
        title: 'Model Drift',
        slug: 'model-drift',
        definition: `Model drift occurs when an AI/ML model's performance degrades over time because the real-world data it encounters differs from the data it was trained on. There are two types:\n\n**Data drift (covariate shift):** The input data distribution changes. Example: a fraud detection model trained on pre-COVID purchase patterns performs poorly post-COVID because consumer behavior changed.\n\n**Concept drift:** The relationship between input features and the target variable changes. Example: a house price prediction model becomes inaccurate as economic conditions shift.\n\n**Economic impact:**\n- Undetected drift causes silent accuracy degradation\n- Wrong predictions lead to wrong business decisions\n- Retraining costs (compute, data, engineering time) are ongoing\n- Each model is a maintenance commitment, not a one-time deployment\n\nModel drift is a form of AI technical debt — it requires continuous investment just to maintain current performance.`,
        whyItMatters: 'Every deployed ML model is a maintenance commitment that accrues drift. Organizations that deploy models without monitoring and retraining plans accumulate AI technical debt that compounds silently.',
        category: 'AI & Machine Learning',
        relatedTerms: ['ai-technical-debt', 'ai-cogs', 'fine-tuning', 'large-language-model'],
        faqs: [{ question: 'How do you detect model drift?', answer: 'Monitor input data distributions, prediction confidence scores, and business outcomes over time. Tools like Evidently AI, Arize, and WhyLabs specialize in drift detection. Set up alerts when distributions shift beyond thresholds.' }],
    },
    {
        title: 'Token',
        slug: 'token-ai',
        definition: `In AI/LLM context, a token is a chunk of text that a language model processes as a single unit. Tokens are the fundamental unit of both input and output for LLMs, and they determine cost.\n\n**Tokenization rules of thumb:**\n- 1 token ≈ 4 characters in English\n- 1 token ≈ ¾ of a word\n- 100 tokens ≈ 75 words\n- 1,000 tokens ≈ 750 words ≈ 1.5 pages of text\n\n**Pricing is per-token:**\n- GPT-4o: ~$2.50/1M input tokens, ~$10/1M output tokens\n- Claude Sonnet: ~$3/1M input, ~$15/1M output\n- Llama 3 (self-hosted): Cost of GPU compute only\n\n**Context window:** The maximum number of tokens a model can process in a single request. GPT-4o supports 128K tokens. Larger context = more tokens = higher cost.\n\nEvery AI feature's unit economics ultimately reduce to: cost per token × tokens per interaction × interactions per user × users.`,
        whyItMatters: 'Tokens are the atomic unit of AI cost. Understanding token economics is essential for modeling AI COGS and unit economics. Poor prompt engineering wastes tokens. Good prompt engineering optimizes them.',
        category: 'AI & Machine Learning',
        relatedTerms: ['large-language-model', 'ai-cogs', 'prompt-engineering', 'cost-of-predictivity'],
        faqs: [{ question: 'How do I reduce token costs?', answer: 'Shorter prompts, more efficient system instructions, caching frequent responses, using smaller models for simple tasks, and prompt compression techniques. The AUEB calculator helps model token economics.' }],
    },
    {
        title: 'Agentic Workflow',
        slug: 'agentic-workflow',
        definition: `An agentic workflow is a multi-step process where AI agents autonomously plan, execute, evaluate, and iterate on tasks to achieve a defined goal. Unlike simple prompt-response interactions, agentic workflows involve loops, tool use, and decision-making.\n\n**Agentic workflow patterns:**\n- **Reflection:** Agent evaluates its own output and iterates\n- **Tool use:** Agent calls APIs, databases, or external services\n- **Planning:** Agent decomposes complex goals into subtasks\n- **Multi-agent delegation:** Multiple specialized agents collaborate\n- **Human-in-the-loop:** Agent pauses for human approval on critical decisions\n\n**Economic implications:** Agentic workflows consume 5-50x more tokens than single-turn interactions. A workflow that makes 10 LLM calls with tool use costs 10x a single query. This multiplier must be factored into AI unit economics.\n\nResearch agents, coding agents (like Devin), and customer service agents all use agentic workflow patterns.`,
        whyItMatters: 'Agentic workflows are the architecture of autonomous AI. But their cost structure is fundamentally different from chatbots — 5-50x more expensive per interaction. Understanding this cost multiplier is critical for AI AI economics.',
        category: 'AI & Machine Learning',
        relatedTerms: ['ai-agent', 'agentic-governance', 'large-language-model', 'ai-cogs'],
        faqs: [{ question: 'How much do agentic workflows cost?', answer: 'A typical agentic workflow with 10 LLM calls, 3 tool uses, and 2 reflection loops costs $0.10-$1.00 per execution, compared to $0.01-$0.05 for a single chatbot response. Volume multiplies this quickly.' }],
    },
];
