import { GlossaryTerm } from '../types';

// =============================================================================
// NINETEENTH PASS: More niche + industry-specific + searched-for terms
// =============================================================================

export const nineteenthPassTerms: GlossaryTerm[] = [
    {
        title: 'API Gateway',
        slug: 'api-gateway',
        definition: `An API gateway is a server that acts as the single entry point for all API requests in a microservices architecture. It handles routing, authentication, rate limiting, load balancing, and request/response transformation.\n\n**Core functions:**\n- **Routing:** Direct requests to the correct microservice\n- **Authentication:** Validate API keys, JWTs, OAuth tokens\n- **Rate limiting:** Prevent abuse and ensure fair usage\n- **Load balancing:** Distribute traffic across service instances\n- **Caching:** Cache common responses to reduce backend load\n- **Monitoring:** Log requests, track latency, generate alerts\n\n**Popular API gateways:** Kong, AWS API Gateway, Azure API Management, Nginx, Traefik, Envoy.\n\nThe API gateway pattern is essential for microservices but creates a single point of failure. Gateway resilience, caching strategy, and rate limiting configuration all create potential technical debt.`,
        whyItMatters: 'API gateways are the front door of your application. A misconfigured gateway creates performance bottlenecks, security vulnerabilities, and availability risks. Gateway technical debt is invisible until it causes an outage.',
        category: 'API & Integration',
        relatedTerms: ['microservices-communication', 'graphql', 'api-versioning'],
        faqs: [{ question: 'Do I need an API gateway?', answer: 'If you have more than 3-4 microservices: yes. The gateway provides centralized authentication, rate limiting, and monitoring. For monolithic applications: usually not needed — your web framework handles these concerns.' }],
    },
    {
        title: 'Service Level Objectives (SLOs)',
        slug: 'service-level-objectives',
        definition: `Service Level Objectives (SLOs) are specific, measurable targets for service reliability — the percentage of time a service should work correctly. SLOs are the foundation of Site Reliability Engineering (SRE).\n\n**SLO components:**\n- **SLI (Service Level Indicator):** The metric (e.g., request latency, error rate, availability)\n- **SLO (Service Level Objective):** The target (e.g., 99.9% of requests under 200ms)\n- **SLA (Service Level Agreement):** The business contract built on SLOs (with penalties for violations)\n- **Error budget:** The allowed amount of unreliability (100% - SLO = error budget)\n\n**The error budget concept:**\nIf your SLO is 99.9% availability: you have 0.1% error budget = ~43 minutes of downtime per month. This budget is "spent" on deployments, experiments, and incidents. When your budget is exhausted, you shift to reliability work.\n\nGoogle pioneered SLOs in their SRE practice. The concept transforms reliability from "we need 100% uptime" (impossible) to "we accept X% unreliability and manage it intentionally."`,
        whyItMatters: 'SLOs make reliability an engineering decision with clear trade-offs. Without SLOs, teams either over-invest in reliability (slow feature delivery) or under-invest (too many outages). SLOs balance innovation speed with stability.',
        category: 'Cloud & Infrastructure',
        relatedTerms: ['observability', 'incident-response', 'chaos-engineering'],
        faqs: [{ question: 'What SLO should I target?', answer: '99.9% (three nines) is standard for most services. 99.99% for payment processing. 99.95% for internal tooling. Remember: going from 99.9% to 99.99% is 10x harder and more expensive.' }],
    },
    {
        title: 'Data Lake',
        slug: 'data-lake',
        definition: `A data lake is a centralized repository that stores raw data at any scale — structured (databases), semi-structured (JSON, XML), and unstructured (images, logs, documents) — in its native format until needed for analysis.\n\n**Data lake vs. data warehouse:**\n- **Data warehouse:** Structured, cleaned, schema-on-write, optimized for business reporting (Snowflake, BigQuery)\n- **Data lake:** Raw, uncleaned, schema-on-read, optimized for flexibility (S3, ADLS, GCS)\n- **Data lakehouse:** Hybrid combining lake flexibility with warehouse performance (Delta Lake, Apache Iceberg)\n\n**Data lake anti-patterns:**\n- **Data swamp:** Lake without governance, cataloging, or documentation\n- **Dump and pray:** Putting everything in the lake without use cases\n- **Copy everything:** Replicating full databases instead of selecting what's needed\n\nThe lakehouse architecture (Delta Lake, Apache Iceberg) is replacing pure data lakes by adding ACID transactions and schema enforcement.`,
        whyItMatters: 'Data lakes that become "data swamps" are a major form of data infrastructure debt. Without governance, they cost money to store data nobody uses or can find.',
        category: 'Data & Analytics',
        relatedTerms: ['data-mesh', 'data-lakehouse', 'feature-store'],
        faqs: [{ question: 'Should I build a data lake or a data warehouse?', answer: 'For most teams in 2025: a lakehouse (Delta Lake or Apache Iceberg). It gives you the flexibility of a lake with the reliability of a warehouse. Pure data lakes often become unmanageable swamps.' }],
    },
    {
        title: 'Zero Trust Security',
        slug: 'zero-trust-security',
        definition: `Zero Trust is a security architecture that requires all users, devices, and applications to be continuously authenticated and authorized — regardless of whether they are inside or outside the network perimeter. The core principle: "never trust, always verify."\n\n**Zero Trust principles:**\n1. **Verify explicitly:** Authenticate every request based on all available data\n2. **Least privilege access:** Grant minimum permissions needed for the task\n3. **Assume breach:** Design systems assuming the attacker is already inside\n\n**Zero Trust implementation:**\n- Identity-aware proxies (BeyondCorp, Cloudflare Access)\n- Micro-segmentation (network isolation between services)\n- Continuous authentication (not just at login)\n- Device posture checking\n- Encrypted communications everywhere (mTLS)\n\nThe traditional perimeter-based security model ("castle and moat") is obsolete. Remote work, cloud computing, and API-first architectures have dissolved the network perimeter.`,
        whyItMatters: 'Zero Trust is the security architecture standard for modern engineering. Implementing it creates significant infrastructure debt — but NOT implementing it creates security vulnerability debt that can be catastrophic.',
        category: 'Security & Compliance',
        relatedTerms: ['soc-2-compliance', 'supply-chain-security', 'incident-response'],
        faqs: [{ question: 'How long does Zero Trust implementation take?', answer: '12-24 months for a full implementation. Start with identity (SSO, MFA), then add network micro-segmentation, then continuous verification. It\'s a journey, not a single project.' }],
    },
    {
        title: 'Cost per Hire',
        slug: 'cost-per-hire',
        definition: `Cost per Hire (CPH) is the total cost to recruit and onboard a new employee, including advertising, recruiter fees, interview time, background checks, and onboarding costs.\n\n**CPH components:**\n- **External costs:** Job board fees, recruiter commissions (typically 15-25% of salary), advertising\n- **Internal costs:** HR time, interviewer time, hiring manager time, background checks\n- **Onboarding costs:** Equipment, training, ramp-up productivity loss\n\n**Engineering-specific benchmarks:**\n- Junior engineer: $10K-$20K CPH\n- Senior engineer: $25K-$40K CPH\n- Staff/Principal: $40K-$75K CPH\n- Using external recruiters: add 20-25% of first-year salary\n\n**Cost of a bad hire:** 3-5x annual salary when you factor in ramp-up time, team disruption, severance, and re-hiring. For a $200K engineer, a bad hire costs $600K-$1M.\n\nRichard Ewing's Audit Interview reduces CPH by standardizing assessment (15 minutes vs. 6-hour loops) and reducing mis-hire rates.`,
        whyItMatters: 'Engineering hiring is the largest single investment in R&D. Understanding CPH — and especially the cost of mis-hires — transforms hiring from an HR process to a financial engineering decision.',
        category: 'People & Culture',
        relatedTerms: ['technical-interview', 'engineering-manager', 'engineering-productivity'],
        relatedTools: [{ name: 'Audit Interview', url: '/tools/audit-interview' }],
        faqs: [{ question: 'How do I reduce cost per hire?', answer: 'Three levers: 1) Build employer brand (reduces advertising costs), 2) Standardize interviews (reduces interviewer time), 3) Reduce mis-hires (the biggest hidden cost). The Audit Interview addresses #2 and #3.' }],
    },
    {
        title: 'Customer Acquisition Cost (CAC)',
        slug: 'customer-acquisition-cost',
        definition: `Customer Acquisition Cost (CAC) is the total cost to acquire a new paying customer, including marketing spend, sales team costs, and any free-tier infrastructure costs.\n\n**Formula:** CAC = (Total Sales + Marketing Spend) / Number of New Customers Acquired\n\n**Benchmarks by stage:**\n- **Seed/Series A:** CAC < 3x monthly subscription price\n- **Series B+:** CAC payback period < 18 months\n- **Enterprise SaaS:** $5K-$50K CAC (longer sales cycles, higher ACV)\n- **PLG Self-Serve:** $100-$1,000 CAC (lower touch, higher volume)\n\n**CAC to LTV ratio:** Healthy = 1:3 or better (every $1 in acquisition returns $3+ in lifetime value). Below 1:3 signals unsustainable growth.\n\n**AI impact on CAC:** AI features can reduce CAC through better targeting, personalized onboarding, and product-led growth — but AI inference costs increase the COGS side of the equation.`,
        whyItMatters: 'CAC determines whether growth is economically sustainable. High CAC with low NRR creates a "leaky bucket" — you spend more to acquire customers than they generate in lifetime value.',
        category: 'SaaS & Metrics',
        relatedTerms: ['net-revenue-retention', 'unit-economics', 'product-led-growth', 'freemium-model'],
        faqs: [{ question: 'What is a good CAC payback period?', answer: 'Under 18 months for VC-backed SaaS. Under 12 months is excellent. Over 24 months is a red flag. For enterprise sales with annual contracts, measure payback against annual contract value.' }],
    },
    {
        title: 'OpenClaw',
        slug: 'openclaw',
        definition: `OpenClaw refers to open-source AI frameworks and libraries for building controllable, structured AI agent systems — focusing on giving developers "claws" (action capabilities) for AI agents while maintaining safety boundaries.\n\n**The open-source AI agent ecosystem:**\n- **AutoGPT:** One of the earliest autonomous AI agent frameworks\n- **CrewAI:** Multi-agent collaboration framework\n- **LangGraph:** Stateful, multi-actor applications with LLMs\n- **OpenHands (formerly OpenDevin):** Open-source AI software developer\n- **AgentGPT:** Browser-based autonomous AI agent\n\n**Key challenge:** Giving AI agents the ability to take real-world actions (writing code, sending emails, querying databases) while preventing harmful or unauthorized actions.\n\nRichard Ewing's EAAP (Exogram Action Admissibility Protocol) addresses this by defining an admissibility governance framework — what actions an AI agent is allowed to take and under what conditions.`,
        whyItMatters: 'The open-source AI agent ecosystem is evolving rapidly. Understanding which frameworks are production-ready vs. experimental prevents both premature adoption (wasted investment) and delayed adoption (competitive disadvantage).',
        category: 'AI Tools & Frameworks',
        relatedTerms: ['agentic-workflow', 'agentic-governance', 'eaap-protocol', 'crewai', 'langchain'],
        faqs: [{ question: 'Which open-source AI agent framework should I use?', answer: 'For multi-agent coordination: CrewAI. For stateful agent workflows: LangGraph. For general-purpose LLM applications: LangChain. For production AI coding: start with API-first, add frameworks when complexity justifies it.' }],
    },
    {
        title: 'Token (AI)',
        slug: 'token-ai',
        definition: `In AI and natural language processing, a token is a unit of text that a language model processes. Tokens are how LLMs "read" — they break text into smaller pieces before processing.\n\n**Token economics:**\n- 1 token ≈ 4 characters in English (≈ 0.75 words)\n- "ChatGPT is great" = 4 tokens\n- Average email: ~300 tokens\n- Average article: ~2,000 tokens\n\n**Cost per token (as of 2025):**\n- GPT-4o: $2.50 / 1M input tokens, $10 / 1M output tokens\n- GPT-4o mini: $0.15 / 1M input, $0.60 / 1M output\n- Claude 3.5 Sonnet: $3 / 1M input, $15 / 1M output\n- Open-source (self-hosted): $0.01-0.10 / 1M tokens\n\n**Context window:** The maximum number of tokens a model can process at once. GPT-4o: 128K tokens. Claude 3: 200K tokens. Larger context = more expensive per request.\n\nToken economics are the foundation of AI product pricing. Richard Ewing's AI COGS framework starts with per-token cost analysis.`,
        whyItMatters: 'Tokens are the unit of measure for AI costs. Every AI feature is denominated in tokens consumed. Understanding token economics prevents margin collapse when AI features scale.',
        category: 'AI & Machine Learning',
        relatedTerms: ['ai-inference', 'ai-cogs', 'large-language-model', 'transformer-architecture'],
        faqs: [{ question: 'How do I estimate AI feature costs?', answer: 'Estimate tokens per request (input + output), multiply by cost per token, then multiply by expected request volume. Include retries and error handling. The AUEB calculator automates this.' }],
    },
    {
        title: 'Observability',
        slug: 'observability',
        definition: `Observability is the ability to understand the internal state of a system by examining its external outputs — logs, metrics, and traces. Unlike monitoring (which tells you WHEN something is wrong), observability helps you understand WHY.\n\n**Three pillars of observability:**\n1. **Logs:** Textual records of events ("User X attempted login, failed: invalid password")\n2. **Metrics:** Numerical measurements over time (request rate, error rate, latency percentiles)\n3. **Traces:** Request flow across distributed services (Service A → Service B → Database → Response)\n\n**Observability vs. monitoring:**\n- Monitoring = predefined dashboards for known problems\n- Observability = ability to ask arbitrary questions about system behavior\n\n**Observability stack:** Grafana + Prometheus + Loki (open-source), Datadog, New Relic, Splunk, Honeycomb.\n\nThe observability gap — when teams can see symptoms but can't diagnose causes — is a major contributor to high MTTR (Mean Time to Recovery).`,
        whyItMatters: 'Observability is the immune system of engineering organizations. Without it, every incident is a mystery. With it, MTTR drops from hours to minutes. The investment in observability infrastructure always pays for itself.',
        category: 'Cloud & Infrastructure',
        relatedTerms: ['opentelemetry', 'service-level-objectives', 'incident-response', 'chaos-engineering'],
        faqs: [{ question: 'How much should we spend on observability?', answer: '3-5% of cloud infrastructure spend is typical. If you\'re spending less, you probably have blind spots. If you\'re spending more, you might be over-instrumenting. Optimize by focusing on critical paths first.' }],
    },
    {
        title: 'Annual Recurring Revenue (ARR)',
        slug: 'annual-recurring-revenue',
        definition: `Annual Recurring Revenue (ARR) is the normalized annual value of recurring subscription revenue. It's the primary top-line metric for SaaS businesses and the basis for valuation multiples.\n\n**ARR calculation:** Monthly Recurring Revenue (MRR) × 12\n\n**ARR components:**\n- **New ARR:** Revenue from new customers\n- **Expansion ARR:** Revenue growth from existing customers (upsells, cross-sells)\n- **Contraction ARR:** Revenue decrease from existing customers (downgrades)\n- **Churned ARR:** Revenue lost from customers who cancel\n\n**Valuation multiples (2025):**\n- High-growth SaaS (>40% growth): 10-20x ARR\n- Moderate growth (20-40%): 5-10x ARR\n- Slow growth (<20%): 3-5x ARR\n- Rule of 40: Growth rate + profit margin > 40% = premium valuation\n\nRichard Ewing's EV-SE (Enterprise Value per Software Engineer) framework connects ARR to engineering headcount — answering "how efficiently does engineering investment convert to recurring revenue?"`,
        whyItMatters: 'ARR is the language of SaaS valuation. Every engineering investment ultimately impacts ARR — either directly (new revenue features) or indirectly (reducing churn through reliability). Understanding ARR connects engineering work to business outcomes.',
        category: 'SaaS & Metrics',
        relatedTerms: ['net-revenue-retention', 'unit-economics', 'ev-se', 'customer-acquisition-cost'],
        relatedTools: [{ name: 'EV-SE Calculator', url: '/tools/ev-se' }],
        faqs: [{ question: 'What is a good ARR growth rate?', answer: 'T2D3 trajectory (triple, triple, double, double, double) from $1M to $100M ARR. Year 1: $1M → $3M. By year 5: ~$72M. Most companies don\'t hit this — 30-50% annual growth is strong.' }],
    },
];
