import { GlossaryTerm } from '../types';

export const saasMetricsTerms: GlossaryTerm[] = [
    {
        slug: 'customer-acquisition-cost',
        title: 'Customer Acquisition Cost (CAC)',
        category: 'SaaS Metrics & Finance',
        definition: `Customer Acquisition Cost is the total cost of acquiring a new customer, including all marketing spend, sales team salaries, tools, and overhead divided by the number of new customers acquired in that period.\n\nCAC = (Total Sales & Marketing Spend) ÷ (New Customers Acquired)\n\nCAC varies dramatically by business model: B2C SaaS averages $50-200, B2B SMB averages $200-2,000, B2B enterprise averages $5,000-50,000+. The channel mix matters  -  organic/inbound CAC is typically 3-5x lower than paid/outbound CAC.\n\nCAC payback period  -  the number of months it takes for a customer's revenue to recoup their acquisition cost  -  is equally important. A $10,000 CAC with 12-month payback is healthy. A $10,000 CAC with 36-month payback is capital-intensive and risky.`,
        whyItMatters: `CAC determines how capital-efficient your growth is. If CAC exceeds LTV, every new customer loses money. If CAC payback exceeds 18 months, you need significant upfront capital to fund growth.`,
        howToMeasure: `1. **Blended CAC**: Total S&M spend ÷ total new customers.\n2. **Channel CAC**: Break down by acquisition channel (organic, paid, partnerships).\n3. **CAC Payback**: CAC ÷ (monthly revenue per customer × gross margin %).\n4. **LTV:CAC Ratio**: Customer lifetime value ÷ CAC. Target: 3:1 or higher.\n5. **CAC Trend**: Track quarterly to ensure efficiency is improving.`,
        faqs: [
            { question: 'What is a good CAC for SaaS?', answer: 'It depends on ACV. The benchmark is LTV:CAC ratio of 3:1 or higher. CAC payback should be under 18 months. For B2B enterprise, CAC of $5K-20K with 12-month payback is healthy.' },
            { question: 'How do you reduce CAC?', answer: 'Invest in organic channels (content, SEO, product-led growth), optimize conversion rates, improve sales efficiency, and expand through word-of-mouth.' },
        ],
        relatedTerms: ['unit-economics', 'arr', 'churn-rate', 'net-revenue-retention'],
        relatedTools: [{ name: 'Enterprise Value Scenario Engine (EV-SE)', url: '/tools/ev-se' }],
    },
    {
        slug: 'gross-margin',
        title: 'Gross Margin',
        category: 'SaaS Metrics & Finance',
        definition: `Gross margin is the percentage of revenue remaining after subtracting the cost of goods sold (COGS). For SaaS companies, COGS includes: hosting and infrastructure costs, third-party software licenses, customer support costs, and professional services costs directly tied to revenue delivery.\n\nGross Margin = (Revenue - COGS) ÷ Revenue × 100\n\nHealthy SaaS gross margins range from 70-85%. Below 70% is concerning and impacts valuation multiples. Above 80% is excellent and commands premium valuations.\n\nAI-powered SaaS products face margin pressure because AI inference costs are variable COGS. Each AI query costs compute  -  unlike traditional software where serving an additional user has near-zero marginal cost. This is what Richard Ewing calls the Cost of Predictivity problem.\n\nFor AI economists, gross margin is the most important financial metric after revenue growth. It determines how much money is available for R&D, sales, and profit  -  the engine of the business.`,
        whyItMatters: `Gross margin determines SaaS valuation multiples. Companies with 80%+ margins trade at 2-3x higher multiples than companies with 60% margins. For AI products, maintaining high margins while scaling inference costs is the central economic challenge.`,
        howToMeasure: `1. **Overall Gross Margin**: (Revenue - COGS) ÷ Revenue × 100.\n2. **Per-Customer Margin**: Track at customer level to identify unprofitable accounts.\n3. **AI Feature Margin**: Isolate AI inference costs as a percentage of AI feature revenue.\n4. **Trend**: Quarterly trending. Declining gross margins signal scaling problems.`,
        faqs: [
            { question: 'What is a good gross margin for SaaS?', answer: '70-85% is the target range. Below 70% is concerning. Above 80% is excellent. AI-heavy SaaS may see lower margins (50-70%) due to inference costs.' },
            { question: 'How do AI costs affect gross margin?', answer: 'AI inference is a variable cost that scales with usage, unlike traditional software. Each AI query costs compute, creating margin pressure as usage grows. This is the Cost of Predictivity.' },
        ],
        relatedTerms: ['arr', 'unit-economics', 'cost-of-predictivity', 'rule-of-40'],
        relatedTools: [{ name: 'AI Unit Economics Benchmark (AUEB)', url: '/tools/aueb' }],
    },
    {
        slug: 'ltv-lifetime-value',
        title: 'Lifetime Value (LTV)',
        category: 'SaaS Metrics & Finance',
        definition: `Lifetime Value is the total revenue a company expects to earn from a single customer over the entire duration of their relationship. It's the fundamental metric for understanding customer value and justifying acquisition spend.\n\nSimple LTV = Average Revenue Per Account (ARPA) × Average Customer Lifetime\n\nFor SaaS: LTV = ARPA ÷ Monthly Churn Rate (for monthly metrics) or ARPA × (1 ÷ Annual Churn Rate) for annual metrics.\n\nMore sophisticated LTV calculations account for expansion revenue, variable margins, and discount rates. A customer who starts at $500/month but expands to $2,000/month over 3 years has a very different LTV than one who stays at $500/month.\n\nThe LTV:CAC ratio is the most important unit economics metric in SaaS. A ratio of 3:1 means every dollar spent acquiring a customer generates $3 in lifetime revenue. Below 1:1 means you're losing money on every customer.`,
        whyItMatters: `LTV determines the maximum you can spend to acquire a customer (CAC ceiling), the segments worth targeting, and whether your business model works at scale. LTV:CAC ratio is the #1 unit economics metric investors evaluate.`,
        faqs: [
            { question: 'How do you calculate LTV?', answer: 'Simple: ARPA ÷ Monthly Churn Rate. More accurate: sum of discounted future revenue accounting for expansion, contraction, and churn over the expected customer lifetime.' },
            { question: 'What is a good LTV:CAC ratio?', answer: '3:1 or higher is the benchmark. Below 1:1 means you lose money on every customer. Between 1:1 and 3:1 is concerning. Above 5:1 may mean you are under-investing in growth.' },
        ],
        relatedTerms: ['customer-acquisition-cost', 'churn-rate', 'unit-economics', 'net-revenue-retention'],
    },
    {
        slug: 'runway-calculation',
        title: 'Runway Calculation',
        category: 'SaaS Metrics & Finance',
        definition: `Runway is the number of months a startup can continue operating at its current spending rate before running out of cash. It's the most critical operational metric for any pre-profitable company.\n\nRunway = Cash Balance ÷ Monthly Net Burn Rate\n\nNet burn rate = Monthly expenses - Monthly revenue. A company with $3M cash and $250K net monthly burn has 12 months of runway.\n\nRunway planning requires scenario modeling: what happens if revenue grows 20% slower than planned? What if a key customer churns? What if the fundraising cycle takes 6 months longer than expected?\n\nRichard Ewing's rule of thumb: always add 6 months to your estimated time to next milestone. If you think you need 12 months of runway, you actually need 18. This buffer accounts for the inevitable surprises that consume cash faster than planned.`,
        whyItMatters: `Running out of cash is the #1 cause of startup death. Runway determines when to fundraise, when to cut costs, and when to pivot. Companies that track runway rigorously make better strategic decisions under uncertainty.`,
        faqs: [
            { question: 'How much runway should a startup have?', answer: '18+ months is ideal. 12-18 months is acceptable. Below 12 months is urgent  -  start fundraising immediately. Below 6 months is an emergency.' },
            { question: 'How do you extend runway?', answer: 'Revenue growth, cost reduction, fundraising, or a combination. Cutting non-essential spending buys time. Revenue is the only sustainable solution.' },
        ],
        relatedTerms: ['burn-rate', 'arr', 'unit-economics'],
    },
    {
        slug: 'annual-contract-value',
        title: 'Annual Contract Value (ACV)',
        category: 'SaaS Metrics & Finance',
        definition: `Annual Contract Value is the average annualized revenue per customer contract. ACV = Total Contract Value ÷ Contract Length in Years. It normalizes contracts of different lengths for comparison.\n\nACV segments define go-to-market strategy: micro-SaaS ($0-1K ACV) uses product-led growth, SMB ($1K-25K ACV) uses inside sales, mid-market ($25K-100K ACV) uses field sales, and enterprise ($100K+ ACV) uses enterprise sales with longest cycles.\n\nACV distribution matters as much as average ACV. A company with $50K average ACV might have 80% of customers at $10K and 20% at $200K. The whale accounts drive revenue but create concentration risk.\n\nACV trends reveal pricing power. If ACV is increasing over time, your product commands higher prices  -  a sign of strong product-market fit. If ACV is decreasing, you may be competing on price (dangerous) or moving downmarket.`,
        whyItMatters: `ACV determines your entire go-to-market strategy: sales model, marketing channels, customer success requirements, and hiring plan. Misaligning GTM with ACV is one of the most expensive mistakes a SaaS company can make.`,
        faqs: [
            { question: 'What is ACV?', answer: 'Annual Contract Value is the average annualized revenue per contract. A 3-year contract worth $150K has an ACV of $50K.' },
            { question: 'What ACV range is best for SaaS?', answer: 'There is no best  -  each range requires a different GTM strategy. The mistake is pricing in the "dead zone" ($1K-5K ACV) where it is too expensive for self-serve but too cheap to justify a sales team.' },
        ],
        relatedTerms: ['arr', 'customer-acquisition-cost', 'saas-valuation', 'net-revenue-retention'],
    },
    {
        slug: 'revenue-recognition',
        title: 'Revenue Recognition (ASC 606)',
        category: 'SaaS Metrics & Finance',
        definition: `Revenue recognition is the accounting principle that determines when and how revenue is recorded on financial statements. For SaaS companies, ASC 606 (the US standard) requires that revenue be recognized when performance obligations are satisfied  -  typically ratably over the subscription period.\n\nKey implications for SaaS: a $120K annual contract signed in January is not $120K of January revenue. It's $10K/month recognized over 12 months. Billings (cash collected) and revenue (recognized) are different numbers.\n\nThis distinction matters for financial reporting, tax planning, and metrics. A company can have strong billings (lots of cash coming in from new annual contracts) but modest recognized revenue (because the revenue is spread over the contract term).\n\nFor AI economists, revenue recognition also affects R&D capitalization. Under ASC 350-40, certain software development costs can be capitalized rather than expensed  -  but only costs incurred during the application development stage, not planning or maintenance.`,
        whyItMatters: `Misunderstanding revenue recognition leads to poor financial planning, incorrect metrics, and potentially fraudulent reporting. For SaaS leaders, the distinction between billings, recognized revenue, and deferred revenue is fundamental.`,
        faqs: [
            { question: 'What is revenue recognition?', answer: 'Revenue recognition determines when revenue appears on financial statements. For SaaS, subscription revenue is recognized ratably over the contract term, not when cash is collected.' },
            { question: 'What is the difference between billings and revenue?', answer: 'Billings is cash collected. Revenue is what is recognized under accounting rules. A $120K annual contract results in $120K billings but only $10K/month in recognized revenue.' },
        ],
        relatedTerms: ['arr', 'gross-margin', 'saas-valuation'],
    },
    {
        slug: 'net-dollar-retention',
        title: 'Net Dollar Retention (NDR)',
        category: 'SaaS Metrics & Finance',
        definition: `Net Dollar Retention is the percentage change in recurring revenue from existing customers, including expansion, contraction, and churn. It measures whether your customer base is growing or shrinking independently of new customer acquisition.\n\nNDR = (Starting MRR + Expansion - Contraction - Churn) ÷ Starting MRR × 100\n\nNDR above 100% means your existing customers spend more over time  -  you grow even without new customers. NDR below 100% means your customer base is eroding.\n\nBenchmarks: below 90% is concerning, 90-100% is average, 100-120% is good, 120-140% is excellent, 140%+ is elite. The best SaaS companies (Snowflake 158%, Datadog 130%) prove that existing customers can be the primary growth engine.\n\nNDR is functionally identical to Net Revenue Retention (NRR). The terms are used interchangeably in the industry.`,
        whyItMatters: `NDR is the single best predictor of SaaS company valuation and the metric most scrutinized by investors. Companies with NDR >120% trade at dramatically higher multiples because they grow automatically through expansion.`,
        faqs: [
            { question: 'What is NDR?', answer: 'Net Dollar Retention measures whether existing customers spend more or less over time, including expansion, contraction, and churn. NDR above 100% means growth from existing customers.' },
            { question: 'Is NDR the same as NRR?', answer: 'Yes. Net Dollar Retention (NDR) and Net Revenue Retention (NRR) are interchangeable terms for the same metric.' },
        ],
        relatedTerms: ['net-revenue-retention', 'arr', 'churn-rate', 'saas-valuation'],
        relatedTools: [{ name: 'Enterprise Value Scenario Engine (EV-SE)', url: '/tools/ev-se' }],
    },
    {
        slug: 'magic-number-saas',
        title: 'SaaS Magic Number',
        category: 'SaaS Metrics & Finance',
        definition: `The SaaS Magic Number measures sales efficiency  -  how much new ARR is generated for every dollar spent on sales and marketing. It answers the question: "Is our sales investment paying off?"\n\nMagic Number = (Current Quarter ARR - Previous Quarter ARR) ÷ Previous Quarter S&M Spend\n\nInterpretation: below 0.5 means sales spend is inefficient (tighten spend). 0.5-0.75 is acceptable but room for improvement. 0.75-1.0 is good. Above 1.0 is excellent (invest more aggressively).\n\nThe Magic Number is a lagging indicator  -  it reflects the efficiency of sales spend from the previous period. It works best for B2B SaaS with sales-led motions and should be combined with CAC payback period for a complete picture.`,
        whyItMatters: `The Magic Number tells you whether to invest more in sales (>1.0) or pull back (<0.5). It's one of the clearest signals board members and investors use to evaluate go-to-market efficiency.`,
        faqs: [
            { question: 'What is the SaaS Magic Number?', answer: 'Net new ARR divided by previous quarter sales and marketing spend. It measures how efficiently sales spending converts to new revenue.' },
            { question: 'What is a good Magic Number?', answer: 'Below 0.5 = pull back on spend. 0.5-0.75 = optimize. 0.75-1.0 = good. Above 1.0 = invest more aggressively.' },
        ],
        relatedTerms: ['customer-acquisition-cost', 'arr', 'unit-economics', 'rule-of-40'],
    },
    {
        slug: 'gross-revenue-retention',
        title: 'Gross Revenue Retention (GRR)',
        category: 'SaaS Metrics & Finance',
        definition: `Gross Revenue Retention measures the percentage of recurring revenue retained from existing customers, excluding expansion revenue. Unlike NRR which includes upsells, GRR only measures the revenue you keep.\n\nGRR = (Starting MRR - Contraction - Churn) ÷ Starting MRR × 100\n\nGRR can never exceed 100%. It measures pure retention  -  how much of your existing revenue you keep without any upsells or cross-sells.\n\nBenchmarks: below 85% is poor, 85-90% is below average, 90-95% is good, 95-100% is excellent. Enterprise SaaS companies should target 95%+ GRR.\n\nGRR is a purer measure of product stickiness than NRR because it isn't masked by expansion revenue. A company can have 120% NRR but 80% GRR  -  meaning they grow through aggressive upselling despite significant churn. This pattern is unsustainable.`,
        whyItMatters: `GRR reveals the true stickiness of your product. High NRR with low GRR indicates a leaky bucket being filled by aggressive upselling  -  a pattern that breaks at scale when expansion opportunities dry up.`,
        faqs: [
            { question: 'What is the difference between GRR and NRR?', answer: 'GRR measures retained revenue excluding expansion (max 100%). NRR includes expansion revenue (can exceed 100%). GRR measures pure retention; NRR measures overall customer base value change.' },
            { question: 'What is a good GRR for SaaS?', answer: 'Below 85% is poor. 85-90% is below average. 90-95% is good. 95%+ is excellent. Enterprise SaaS should target 95%+.' },
        ],
        relatedTerms: ['net-revenue-retention', 'churn-rate', 'arr', 'saas-valuation'],
    },
    {
        slug: 'arpu-arpa',
        title: 'ARPU / ARPA',
        category: 'SaaS Metrics & Finance',
        definition: `ARPU (Average Revenue Per User) and ARPA (Average Revenue Per Account) measure the average revenue generated per unit. ARPU tracks individual users; ARPA tracks company accounts. For B2B SaaS, ARPA is typically more relevant because one account may have many users.\n\nARPA = MRR ÷ Number of Active Accounts\n\nARPA trends reveal pricing power and product value. Increasing ARPA means customers are buying more (expansion) or you're moving upmarket. Decreasing ARPA may indicate competitive price pressure or moving downmarket.\n\nARPA segmentation is critical: break ARPA by customer segment (SMB, mid-market, enterprise), cohort (customers acquired this year vs. last year), and industry. This reveals which segments drive the most value.`,
        whyItMatters: `ARPA determines the viability of your go-to-market strategy. A $50/month ARPA requires product-led growth. A $5,000/month ARPA justifies dedicated account management. Misaligning GTM with ARPA wastes resources.`,
        faqs: [
            { question: 'What is the difference between ARPU and ARPA?', answer: 'ARPU measures revenue per user. ARPA measures revenue per account. For B2B SaaS, ARPA is more relevant because one account (company) may have many users.' },
            { question: 'How do you increase ARPA?', answer: 'Introduce higher-priced tiers, usage-based pricing, add-on products, seat-based pricing that grows with the customer, and strategic upselling.' },
        ],
        relatedTerms: ['arr', 'mrr', 'unit-economics', 'annual-contract-value'],
    },
    {
        slug: 'payback-period',
        title: 'CAC Payback Period',
        category: 'SaaS Metrics & Finance',
        definition: `CAC Payback Period is the number of months it takes for a customer's contribution margin to recoup their acquisition cost. It measures how quickly your sales and marketing investment pays for itself.\n\nCAC Payback = CAC ÷ (Monthly ARPA × Gross Margin %)\n\nBenchmarks: under 12 months is excellent, 12-18 months is good, 18-24 months is acceptable for enterprise, above 24 months is concerning, above 36 months requires reevaluation of unit economics.\n\nShorter payback means faster cash recycling  -  you get your money back sooner and can reinvest in acquiring more customers. Longer payback means you need more upfront capital to fund growth.\n\nPayback period is closely related to capital efficiency. Companies with short payback periods (under 12 months) can fund their own growth from customer revenue. Companies with long payback periods (24+ months) are dependent on external funding to grow.`,
        whyItMatters: `Payback period determines how capital-intensive your growth strategy is. Short payback = self-funded growth. Long payback = dependent on fundraising. Investors increasingly favor efficient growth with payback under 18 months.`,
        faqs: [
            { question: 'What is a good CAC payback period?', answer: 'Under 12 months is excellent. 12-18 months is good. Above 18 months is concerning. Enterprise SaaS with 18-24 month payback can be acceptable if LTV:CAC ratio is high.' },
            { question: 'How do you shorten CAC payback?', answer: 'Reduce CAC (improve marketing efficiency), increase ARPA (raise prices, upsell), or improve gross margins (reduce COGS).' },
        ],
        relatedTerms: ['customer-acquisition-cost', 'ltv-lifetime-value', 'unit-economics', 'gross-margin'],
    },
    {
        slug: 'cohort-analysis',
        title: 'Cohort Analysis',
        category: 'SaaS Metrics & Finance',
        definition: `Cohort analysis groups customers by a shared characteristic (usually their signup month) and tracks their behavior over time. It reveals patterns that aggregate metrics hide.\n\nThe most important SaaS cohort analysis is the revenue retention curve: for each monthly cohort, what percentage of their original revenue remains after 3 months, 6 months, 12 months, and 24 months?\n\nHealthy cohort curves flatten (customers who stay beyond month 6 tend to stay indefinitely). Unhealthy curves continue declining (customers never stop churning). The best cohort curves increase over time as expansion revenue exceeds churn  -  this is what negative net churn looks like at the cohort level.\n\nCohort analysis also reveals whether your product and acquisition are improving. If newer cohorts retain better than older cohorts, your product is getting stickier. If newer cohorts retain worse, something is degrading.`,
        whyItMatters: `Cohort analysis is the most honest retention metric because it can't be gamed by fast growth. Aggregate retention looks good when you're growing fast (new customers mask churning old ones). Cohort analysis shows the true retention picture.`,
        faqs: [
            { question: 'What is cohort analysis?', answer: 'Cohort analysis groups customers by signup month and tracks their behavior over time. It reveals true retention patterns that aggregate metrics hide.' },
            { question: 'What does a good cohort curve look like?', answer: 'A good cohort curve flattens after 3-6 months (retained customers stay) and ideally increases over time (expansion exceeds churn). A bad curve continues declining indefinitely.' },
        ],
        relatedTerms: ['churn-rate', 'net-revenue-retention', 'ltv-lifetime-value'],
    },
];
