import { GlossaryTerm } from '../types';

export const technicalDebtTerms: GlossaryTerm[] = [
    {
        slug: 'dependency-hell',
        title: 'Dependency Hell',
        category: 'Technical Debt & Code Quality',
        definition: `Dependency hell describes the frustrating situation where software packages rely on other packages that conflict with each other, creating complex webs of incompatible version requirements. It is one of the most common and time-consuming forms of technical debt.\n\nIn modern software, a single application may have hundreds or thousands of transitive dependencies. When Package A requires version 2.x of Library Z, but Package B requires version 3.x of the same library, you're in dependency hell. The problem compounds exponentially as the dependency graph grows.\n\nDependency hell manifests in several ways: version conflicts that prevent updates, security vulnerabilities in pinned old versions, build failures after seemingly innocuous changes, and "works on my machine" problems caused by environment-specific dependency resolution.\n\nThe economic cost is substantial. Engineering teams can spend 10-20% of their time managing dependencies  -  updating packages, resolving conflicts, testing compatibility, and rolling back breaking changes. This is pure maintenance overhead that produces zero customer value.`,
        whyItMatters: `Dependency hell is a hidden multiplier of technical debt. Every unresolved dependency conflict makes future updates harder, increases security exposure, and slows down deployment velocity. Organizations that don't actively manage their dependency graph risk accumulating vulnerabilities that can lead to regulatory penalties or security breaches.`,
        howToMeasure: `1. **Dependency Age**: Track the average age of your dependencies. Anything >2 years old is a risk.\n2. **Known Vulnerabilities**: Use tools like Snyk, Dependabot, or npm audit to count known CVEs.\n3. **Update Frequency**: How often can you update dependencies without breaking changes?\n4. **Conflict Count**: Number of dependency version conflicts in your lock file.\n5. **Time Spent**: Track hours spent on dependency management per sprint.`,
        faqs: [
            { question: 'What is dependency hell?', answer: 'Dependency hell is when software packages have conflicting version requirements, creating complex webs of incompatible dependencies that are time-consuming and risky to resolve.' },
            { question: 'How do you escape dependency hell?', answer: 'Use lock files, automate updates with tools like Dependabot, adopt semantic versioning, minimize direct dependencies, and schedule regular dependency maintenance windows.' },
            { question: 'What causes dependency hell?', answer: 'Common causes include: not updating regularly, pinning exact versions instead of ranges, using packages with many transitive dependencies, and mixing incompatible ecosystems.' },
        ],
        relatedTerms: ['technical-debt', 'legacy-code', 'refactoring', 'cicd'],
    },
    {
        slug: 'code-coverage',
        title: 'Code Coverage',
        category: 'Technical Debt & Code Quality',
        definition: `Code coverage is a metric that measures the percentage of source code executed during automated testing. It indicates how thoroughly your test suite exercises the codebase, typically measured as line coverage, branch coverage, function coverage, or statement coverage.\n\nLine coverage measures the percentage of code lines executed by tests. Branch coverage measures whether both true and false paths of conditional statements are tested. Function coverage measures whether every function has been called. Branch coverage is generally considered the most meaningful metric.\n\nHigh code coverage (>80%) doesn't guarantee code quality  -  you can have 100% coverage with terrible tests that assert nothing. But low code coverage (<40%) almost always indicates high risk. Code without tests is code you're afraid to change, which is the definition of legacy code.\n\nThe relationship between code coverage and technical debt is inverse: as coverage decreases, the cost of making changes increases because every modification carries unverified risk. Teams with low coverage deploy less frequently, have higher change failure rates, and spend more time on manual QA.`,
        whyItMatters: `Code coverage directly impacts deployment confidence, change velocity, and bug rates. Teams with >80% branch coverage deploy 3-5x more frequently than teams with <40% coverage. For investors performing due diligence, code coverage is a proxy for engineering discipline and codebase health.`,
        howToMeasure: `1. **Line Coverage**: % of code lines executed during tests. Target: >80%.\n2. **Branch Coverage**: % of conditional branches tested. Target: >70%.\n3. **Critical Path Coverage**: Coverage specifically on revenue-generating or safety-critical code paths. Target: >90%.\n4. **Trend**: Is coverage increasing or decreasing over time? Decreasing coverage is a leading indicator of debt accumulation.`,
        faqs: [
            { question: 'What is good code coverage?', answer: '80%+ line coverage is considered good. 70%+ branch coverage is considered good. More important than the number is the trend  -  coverage should be stable or increasing, never decreasing.' },
            { question: 'Does 100% code coverage mean no bugs?', answer: 'No. Code coverage measures execution, not correctness. You can have 100% coverage with tests that never assert anything. Coverage is a necessary but not sufficient condition for quality.' },
            { question: 'How much does low code coverage cost?', answer: 'Teams with <40% coverage spend 2-3x more time on manual testing, deploy 3-5x less frequently, and have 2x higher change failure rates  -  all of which translate to higher engineering costs.' },
        ],
        relatedTerms: ['technical-debt', 'dora-metrics', 'cicd', 'refactoring'],
    },
    {
        slug: 'cyclomatic-complexity',
        title: 'Cyclomatic Complexity',
        category: 'Technical Debt & Code Quality',
        definition: `Cyclomatic complexity is a quantitative measure of the number of linearly independent paths through a program's source code. Invented by Thomas J. McCabe in 1976, it counts the number of decision points (if statements, loops, switch cases) plus one.\n\nA function with no branches has complexity 1. Each if/else adds 1. Each loop adds 1. A function with complexity 10 has 10 independent paths that need to be tested for full coverage.\n\nBenchmarks: 1-10 is simple and low risk. 11-20 is moderate complexity. 21-50 is high complexity and hard to test. Above 50 is untestable and should be refactored immediately.\n\nHigh cyclomatic complexity is one of the strongest predictors of bugs. Research shows that modules with complexity >20 are 5x more likely to contain defects than modules with complexity <10. It's also the primary driver of long testing cycles  -  each independent path needs its own test case.`,
        whyItMatters: `Cyclomatic complexity is one of the most reliable leading indicators of maintenance cost and bug risk. It's measurable, actionable, and directly correlates with testing effort. Teams that enforce complexity limits (e.g., max 15 per function) consistently produce more maintainable, less buggy code.`,
        howToMeasure: `1. **Per Function**: Use static analysis tools (SonarQube, ESLint, pylint) to measure complexity per function.\n2. **Module Average**: Average complexity across all functions in a module.\n3. **Hotspots**: Identify the top 10 most complex functions  -  these are your highest-risk code.\n4. **Threshold**: Set a maximum (e.g., 15) and fail CI builds that exceed it.`,
        faqs: [
            { question: 'What is cyclomatic complexity?', answer: 'Cyclomatic complexity counts the number of independent execution paths through a function. More paths = more complexity = harder to test and maintain.' },
            { question: 'What is a good cyclomatic complexity score?', answer: '1-10 is simple and low risk. 11-20 is moderate. Above 20 should be refactored. Above 50 is untestable.' },
        ],
        relatedTerms: ['code-smell', 'technical-debt', 'refactoring', 'code-coverage'],
    },
    {
        slug: 'tech-debt-quadrant',
        title: 'Technical Debt Quadrant',
        category: 'Technical Debt & Code Quality',
        definition: `The Technical Debt Quadrant is a classification framework by Martin Fowler that categorizes technical debt along two axes: deliberate vs. inadvertent, and reckless vs. prudent.\n\n**Reckless + Deliberate**: "We don't have time for design." The team knowingly takes shortcuts without planning to fix them.\n\n**Reckless + Inadvertent**: "What's layering?" The team doesn't know enough to realize they're creating problems.\n\n**Prudent + Deliberate**: "We must ship now and deal with consequences." The team understands the tradeoff and has a plan to address the debt.\n\n**Prudent + Inadvertent**: "Now we know how we should have done it." The team learns better approaches only after building the first version.\n\nThe quadrant helps teams and leaders communicate about debt more precisely. "We have tech debt" is vague. "We have prudent deliberate debt from the Q3 launch that's now costing us 20 hours/sprint" is actionable.`,
        whyItMatters: `The quadrant framework enables more nuanced conversations about technical debt with non-technical stakeholders. Not all debt is equal  -  prudent deliberate debt can be a smart business decision, while reckless inadvertent debt indicates a training and process problem.`,
        faqs: [
            { question: 'What is the technical debt quadrant?', answer: 'A framework by Martin Fowler that classifies technical debt as reckless/prudent and deliberate/inadvertent. It helps teams communicate about different types of debt more precisely.' },
            { question: 'Is all technical debt bad?', answer: 'No. Prudent deliberate debt  -  knowingly taking a shortcut to ship faster with a plan to fix it  -  can be a smart business decision. The key is that it must be measured, tracked, and repaid on schedule.' },
        ],
        relatedTerms: ['technical-debt', 'refactoring', 'innovation-tax', 'technical-insolvency-date'],
    },
    {
        slug: 'dead-code',
        title: 'Dead Code',
        category: 'Technical Debt & Code Quality',
        definition: `Dead code is source code that exists in the codebase but is never executed during normal operation. It includes unreachable code paths, unused functions, commented-out code blocks, deprecated features that were never removed, and variables that are assigned but never read.\n\nDead code is surprisingly common. Studies suggest that 10-30% of a typical codebase is dead code. It accumulates naturally as features evolve, requirements change, and refactoring efforts leave remnants behind.\n\nWhile dead code doesn't directly cause bugs, it has real costs: it increases cognitive load for developers reading the codebase, inflates build times, creates false positives in security scans, and makes refactoring harder because developers aren't sure if the code might be needed.\n\nRichard Ewing's Kill Switch Protocol addresses dead code systematically by identifying "Zombie Features"  -  code that costs money to maintain but produces zero value.`,
        whyItMatters: `Dead code is the silent tax on developer productivity. Every line of dead code must be read, understood (or misunderstood), and maintained during refactoring. Removing dead code is one of the highest-ROI refactoring activities because it reduces cognitive load with zero functional risk.`,
        faqs: [
            { question: 'What is dead code?', answer: 'Dead code is code that exists in your codebase but is never executed. It includes unused functions, unreachable code paths, and deprecated features that were never removed.' },
            { question: 'How much dead code is normal?', answer: '10-30% of a typical codebase is dead code. This is normal but costly  -  each line adds cognitive load and maintenance burden.' },
            { question: 'How do you find dead code?', answer: 'Use static analysis tools (tree-shaking bundlers, unused import detectors, code coverage tools). Also search for functions with zero callers and features with zero usage metrics.' },
        ],
        relatedTerms: ['code-smell', 'kill-switch-protocol', 'refactoring', 'technical-debt'],
    },
    {
        slug: 'spaghetti-code',
        title: 'Spaghetti Code',
        category: 'Technical Debt & Code Quality',
        definition: `Spaghetti code is a pejorative term for source code with a complex, tangled control flow that makes it extremely difficult to understand, maintain, or modify. The name comes from the resemblance to a plate of spaghetti  -  you can't follow any single strand without getting lost in the tangle.\n\nSpaghetti code typically features: deeply nested conditionals, excessive use of goto statements or their modern equivalents, functions that are hundreds or thousands of lines long, unclear variable naming, tightly coupled components, and global state mutations scattered throughout.\n\nSpaghetti code is both a cause and symptom of technical debt. It often starts as clean code that accumulates patches, hotfixes, and quick additions until the original structure is unrecognizable. Each modification makes the next modification harder, creating a vicious cycle.\n\nThe cost of spaghetti code is measurable: onboarding new developers takes 2-5x longer, bug fix times increase exponentially, and the risk of introducing regressions with every change approaches certainty.`,
        whyItMatters: `Spaghetti code is the primary driver of the "afraid to touch it" syndrome that leads to engineering paralysis. When teams are afraid to modify code, feature velocity drops, bugs persist, and the organization loses its ability to compete.`,
        faqs: [
            { question: 'What is spaghetti code?', answer: 'Spaghetti code is poorly structured source code with tangled control flow that is extremely difficult to understand, maintain, or modify safely.' },
            { question: 'How do you fix spaghetti code?', answer: 'Incremental refactoring: add tests around the messy code first, then extract functions, reduce nesting, and clarify variable names. Never attempt a full rewrite of spaghetti code without comprehensive test coverage.' },
        ],
        relatedTerms: ['technical-debt', 'code-smell', 'refactoring', 'legacy-code', 'cyclomatic-complexity'],
    },
    {
        slug: 'coupling-and-cohesion',
        title: 'Coupling & Cohesion',
        category: 'Technical Debt & Code Quality',
        definition: `Coupling and cohesion are complementary software design metrics. Coupling measures how dependent modules are on each other. Cohesion measures how related the elements within a single module are. Good software design aims for low coupling and high cohesion.\n\n**Low coupling** means modules can be modified, replaced, or tested independently. A change to Module A doesn't require changes to Modules B, C, and D.\n\n**High cohesion** means every element in a module serves a single, well-defined purpose. A "UserService" that handles user CRUD, email notifications, billing, and report generation has low cohesion.\n\nThe opposite  -  high coupling and low cohesion  -  is the defining characteristic of unmaintainable systems. When everything depends on everything else and each module does many unrelated things, every change is risky and expensive.\n\nMicroservices architecture aims to enforce low coupling by separating services at process boundaries. But poorly designed microservices can create "distributed monolith"  -  all the coupling of a monolith with the operational complexity of microservices.`,
        whyItMatters: `Coupling and cohesion determine how expensive it is to change software. High coupling means every change cascades across the codebase. Low cohesion means every change requires understanding unrelated code. Together, they set the maintenance cost floor for your engineering organization.`,
        faqs: [
            { question: 'What is coupling in software?', answer: 'Coupling measures how dependent software modules are on each other. Low (loose) coupling is desirable  -  modules can be changed independently without breaking other modules.' },
            { question: 'What is cohesion in software?', answer: 'Cohesion measures how related the elements within a module are. High cohesion means a module does one thing well. Low cohesion means a module does many unrelated things.' },
        ],
        relatedTerms: ['monolith-to-microservices', 'refactoring', 'code-smell', 'technical-debt'],
    },
    {
        slug: 'test-driven-development',
        title: 'Test-Driven Development (TDD)',
        category: 'Technical Debt & Code Quality',
        definition: `Test-Driven Development is a software development practice where tests are written before the code they test. The TDD cycle is: Red (write a failing test), Green (write minimal code to pass the test), Refactor (improve the code while keeping tests passing).\n\nTDD was popularized by Kent Beck and is a core practice of Extreme Programming (XP). It produces code with high test coverage by default, since every line of production code exists to make a test pass.\n\nProponents argue TDD produces better-designed code because writing tests first forces you to think about interfaces and behavior before implementation. Critics argue TDD slows initial development speed and that writing tests after (Test-After Development) achieves similar quality.\n\nThe data is mixed. Studies show TDD reduces defect rates by 40-80% compared to no testing, but the difference between TDD and Test-After is smaller (~20%). The real benefit may be behavioral: TDD practitioners write more tests, period.`,
        whyItMatters: `TDD is one of the most effective practices for preventing technical debt accumulation. By requiring tests before code, it ensures high coverage from the start. The cost of adding tests retroactively is 3-10x higher than writing them alongside the code.`,
        faqs: [
            { question: 'What is TDD?', answer: 'Test-Driven Development is writing tests before writing the production code. The cycle is: write a failing test, write code to pass it, then refactor. It ensures high test coverage by default.' },
            { question: 'Does TDD slow development?', answer: 'Initially yes  -  15-20% slower. But TDD reduces debugging time by 40-80%, so total time to working software is often shorter.' },
        ],
        relatedTerms: ['code-coverage', 'refactoring', 'cicd', 'technical-debt'],
    },
    {
        slug: 'code-review',
        title: 'Code Review',
        category: 'Technical Debt & Code Quality',
        definition: `Code review is the systematic examination of source code by peers before it is merged into the main codebase. It is one of the most effective quality assurance practices in software engineering, catching bugs, enforcing standards, and spreading knowledge across the team.\n\nModern code review happens through pull requests (PRs) or merge requests (MRs) on platforms like GitHub, GitLab, or Bitbucket. A developer submits their changes, one or more reviewers examine the diff, leave comments, request changes, and eventually approve the merge.\n\nEffective code reviews catch 60-90% of defects that automated testing misses. They also serve as knowledge transfer  -  junior developers learn patterns from senior reviewers, and senior developers stay aware of codebase changes they didn't write.\n\nGoogle's research shows that code review effectiveness drops sharply after 200 lines of code. Smaller, more frequent reviews are significantly more effective than large batch reviews.`,
        whyItMatters: `Code review is the frontline defense against technical debt. Every code change that introduces a shortcut, violates a pattern, or lacks tests is an opportunity for a reviewer to catch it before it compounds. Teams without code review accumulate debt 2-3x faster.`,
        howToMeasure: `1. **Review Turnaround Time**: Time from PR submission to first review. Target: <4 hours.\n2. **Review Coverage**: % of code changes that receive review. Target: 100%.\n3. **Comments Per Review**: Average feedback density. Too low (<1) suggests rubber-stamping.\n4. **Rejection Rate**: % of PRs that require changes. 20-40% is healthy.`,
        faqs: [
            { question: 'How long should a code review take?', answer: 'Reviewing 200 lines should take 30-60 minutes. Larger reviews should be broken into smaller PRs. Google research shows effectiveness drops sharply after 200 lines.' },
            { question: 'What should code reviewers look for?', answer: 'Logic errors, security vulnerabilities, test coverage, code style consistency, performance issues, documentation, and architectural alignment.' },
        ],
        relatedTerms: ['cicd', 'dora-metrics', 'engineering-productivity', 'code-coverage'],
    },
    {
        slug: 'technical-debt-ratio',
        title: 'Technical Debt Ratio (TDR)',
        category: 'Technical Debt & Code Quality',
        definition: `The Technical Debt Ratio is a quantitative metric that expresses the cost of fixing all known technical debt as a percentage of the cost of rewriting the entire application from scratch. It provides a single number that summarizes the overall health of a codebase.\n\nTDR = (Remediation Cost ÷ Development Cost) × 100\n\nA TDR of 5% means fixing all known issues would cost 5% of what a complete rewrite would cost  -  healthy. A TDR of 15% is concerning. Above 20% indicates the codebase is in serious trouble and approaching what Richard Ewing calls the Technical Insolvency Date.\n\nThe TDR is calculated by static analysis tools like SonarQube, which estimate remediation time for each issue and model development cost based on codebase size. While the absolute numbers are estimates, the trend over time is highly informative.`,
        whyItMatters: `The TDR provides a single, trackable metric for board-level reporting on codebase health. Saying "our TDR is 8% and trending down" is infinitely more useful than "we have some tech debt." It enables comparisons across projects and time periods.`,
        howToMeasure: `1. **Automated**: Use SonarQube or CodeClimate to calculate TDR automatically.\n2. **Manual**: Estimate hours to fix all known issues ÷ estimate hours for full rewrite.\n3. **Track Quarterly**: The trend matters more than the absolute number.\n4. **Benchmark**: <5% excellent, 5-10% good, 10-20% concerning, >20% critical.`,
        faqs: [
            { question: 'What is a good technical debt ratio?', answer: 'Below 5% is excellent. 5-10% is good. 10-20% is concerning and needs active management. Above 20% is critical and likely approaching the Technical Insolvency Date.' },
            { question: 'How do you calculate technical debt ratio?', answer: 'TDR = (Remediation Cost ÷ Development Cost) × 100. Tools like SonarQube calculate this automatically based on static analysis.' },
        ],
        relatedTerms: ['technical-debt', 'technical-insolvency-date', 'code-coverage', 'cyclomatic-complexity'],
    },
    {
        slug: 'boy-scout-rule',
        title: 'Boy Scout Rule',
        category: 'Technical Debt & Code Quality',
        definition: `The Boy Scout Rule in software engineering states: "Always leave the code better than you found it." Attributed to Robert C. Martin (Uncle Bob), the principle encourages developers to make small improvements to any code they touch, even if those improvements aren't part of the current task.\n\nExamples include: renaming a confusing variable, adding a missing test, extracting a duplicated block into a function, updating a deprecated API call, or improving documentation. Each individual improvement is small, but applied consistently by an entire team, the cumulative effect is powerful.\n\nThe Boy Scout Rule is the opposite of the "not my problem" mentality that allows technical debt to accumulate. It converts every code change from a potential debt-adding event into a potential debt-reducing event.\n\nThe key constraint: boy scout improvements must be small enough to not require separate review or testing. If the improvement needs its own PR, it's not a boy scout fix  -  it's a refactoring task.`,
        whyItMatters: `The Boy Scout Rule is the most sustainable approach to technical debt management. It requires no budget allocation, no sprint planning, and no management approval. It simply requires a team culture that values incremental improvement.`,
        faqs: [
            { question: 'What is the Boy Scout Rule in programming?', answer: 'Always leave the code better than you found it. Make small improvements (rename variables, add tests, remove duplication) whenever you touch code, even if it is not part of your current task.' },
            { question: 'How does the Boy Scout Rule reduce technical debt?', answer: 'It converts every code change into an improvement opportunity. Over time, the cumulative effect of hundreds of small improvements keeps the codebase healthy without requiring dedicated refactoring sprints.' },
        ],
        relatedTerms: ['refactoring', 'technical-debt', 'code-review', 'code-smell'],
    },
    {
        slug: 'strangler-fig-pattern',
        title: 'Strangler Fig Pattern',
        category: 'Technical Debt & Code Quality',
        definition: `The Strangler Fig Pattern is a migration strategy for incrementally replacing a legacy system with a new system. Named after the strangler fig tree that grows around an existing tree and eventually replaces it, this pattern avoids the risks of a "big bang" rewrite.\n\nThe approach: build new functionality alongside the old system, route traffic to the new system piece by piece, and gradually deprecate old components until the legacy system can be removed entirely.\n\nStep 1: Add a routing layer (facade) in front of the legacy system. Step 2: Build new components that implement specific functions. Step 3: Route specific requests to new components. Step 4: Repeat until all functionality is migrated. Step 5: Remove the legacy system.\n\nThe Strangler Fig Pattern is significantly safer than a full rewrite because: you can migrate incrementally and roll back individual changes, the legacy system continues to serve live traffic during migration, and you can validate new components against production data.`,
        whyItMatters: `The Strangler Fig Pattern is the recommended approach for modernizing legacy systems because it dramatically reduces risk compared to full rewrites. It allows organizations to modernize incrementally while maintaining business continuity.`,
        faqs: [
            { question: 'What is the strangler fig pattern?', answer: 'A migration strategy where you incrementally replace a legacy system by building new components alongside it and gradually routing traffic to the new system until the old one can be removed.' },
            { question: 'When should you use the strangler fig pattern?', answer: 'When migrating from a monolith to microservices, replacing a legacy system, or modernizing architecture. It is preferred over full rewrites because it is incremental and reversible.' },
        ],
        relatedTerms: ['monolith-to-microservices', 'legacy-code', 'refactoring', 'technical-debt'],
    },
    {
        slug: 'static-code-analysis',
        title: 'Static Code Analysis',
        category: 'Technical Debt & Code Quality',
        definition: `Static code analysis is the automated examination of source code without executing it. Static analysis tools scan code for potential bugs, security vulnerabilities, code smells, style violations, and complexity issues before the code is deployed.\n\nCommon static analysis tools include: SonarQube (multi-language, enterprise), ESLint (JavaScript/TypeScript), pylint/mypy (Python), RuboCop (Ruby), Checkstyle/SpotBugs (Java), and CodeClimate (multi-language SaaS).\n\nStatic analysis catches issues that are invisible during code review and common in human-written or AI-generated code: null pointer dereferences, SQL injection vulnerabilities, unused variables, unreachable code, type mismatches, and race conditions.\n\nIn the era of AI-generated code (vibe coding), static analysis is more important than ever. AI code generators produce code that often passes functional tests but contains subtle security, performance, or maintainability issues that only static analysis detects.`,
        whyItMatters: `Static analysis is the most cost-effective quality assurance practice in software engineering. Finding a bug in static analysis costs 10x less than finding it in testing and 100x less than finding it in production. It is essential for organizations using AI code generation.`,
        faqs: [
            { question: 'What is static code analysis?', answer: 'Static code analysis is automated examination of code without running it, checking for bugs, security vulnerabilities, style violations, and complexity issues.' },
            { question: 'What tools do static code analysis?', answer: 'SonarQube (enterprise, multi-language), ESLint (JS/TS), pylint (Python), CodeClimate (SaaS), and language-specific linters like RuboCop, Checkstyle, and SwiftLint.' },
        ],
        relatedTerms: ['code-coverage', 'code-smell', 'cyclomatic-complexity', 'cicd'],
    },
    {
        slug: 'code-documentation',
        title: 'Code Documentation',
        category: 'Technical Debt & Code Quality',
        definition: `Code documentation encompasses all written descriptions of what code does, why it exists, and how to use it. It includes inline comments, API documentation, README files, architecture decision records (ADRs), runbooks, and onboarding guides.\n\nGood documentation answers three questions: What does this code do? (API docs). Why does it do it this way? (Architecture Decision Records). How do I use it? (Tutorials and examples).\n\nDocumentation debt  -  the gap between how well-documented code should be and how well-documented it actually is  -  is one of the most common forms of technical debt. Unlike code debt, documentation debt is invisible to automated tools and only surfaces when new team members struggle to onboard or when institutional knowledge is lost due to turnover.\n\nThe cost of poor documentation: onboarding takes 2-4x longer, tribal knowledge creates bus factor risk, and teams make incorrect assumptions about code behavior because existing documentation is outdated or missing.`,
        whyItMatters: `Documentation debt is the most underestimated form of technical debt. When key engineers leave, undocumented knowledge leaves with them. This creates hidden risk that only materializes in team transitions, on-call incidents, and onboarding.`,
        faqs: [
            { question: 'What is documentation debt?', answer: 'Documentation debt is the gap between how well-documented code should be and how well it actually is. It includes missing API docs, outdated READMEs, and undocumented architecture decisions.' },
            { question: 'How much should you document?', answer: 'Focus on: API docs for all public interfaces, Architecture Decision Records for major choices, runbooks for operational procedures, and onboarding guides for new team members.' },
        ],
        relatedTerms: ['technical-debt', 'legacy-code', 'engineering-productivity'],
    },
    {
        slug: 'broken-windows-theory',
        title: 'Broken Windows Theory (Software)',
        category: 'Technical Debt & Code Quality',
        definition: `The Broken Windows Theory in software development, drawn from urban criminology, states that visible signs of disorder (like poor code quality, ignored warnings, or failing tests) encourage further negligence. One broken window  -  one ignored linting error, one skipped test, one hacky workaround  -  makes the next broken window more acceptable.\n\nIn codebases, broken windows compound: a few ignored compiler warnings become hundreds. One untested module becomes several. One hardcoded configuration becomes a pattern. Once the team accepts "that's just how it is," the standard permanently drops.\n\nThe practical implication: maintaining high standards requires constant vigilance. Allowing "just this once" exceptions creates a ratchet effect where quality only moves in one direction  -  down. This is why CI/CD pipelines should have zero-tolerance policies for critical issues: if warnings are allowed to accumulate, they will.`,
        whyItMatters: `The Broken Windows Theory explains why technical debt accelerates. The first broken window (ignored warning, skipped test) makes the second one easier to justify. Maintaining a strict zero-tolerance policy for critical issues is the most effective prevention strategy.`,
        faqs: [
            { question: 'What is the broken windows theory in programming?', answer: 'One visible quality problem (an ignored warning, a skipped test) normalizes future quality problems. Quality degrades as standards become more permissive over time.' },
            { question: 'How do you prevent broken windows in code?', answer: 'Enforce zero-tolerance CI/CD policies for critical issues. Fix broken tests immediately. Never ignore compiler warnings. The boy scout rule helps: always leave code better than you found it.' },
        ],
        relatedTerms: ['boy-scout-rule', 'technical-debt', 'code-smell', 'cicd'],
    },
    {
        slug: 'feature-flags',
        title: 'Feature Flags',
        category: 'Technical Debt & Code Quality',
        definition: `Feature flags (also called feature toggles, feature switches, or feature gates) are a software development technique that allows teams to enable or disable functionality without deploying new code. They decouple deployment from release, letting teams deploy code to production while keeping new features hidden until they're ready.\n\nFeature flags support several use cases: gradual rollout (enable for 5% of users, then 25%, then 100%), A/B testing (show different features to different user segments), kill switches (disable a broken feature without deploying), and trunk-based development (merge incomplete features that are flag-hidden).\n\nThe catch: feature flags are technical debt generators. Every flag adds conditional logic, increases testing complexity, and creates code paths that diverge. Old feature flags that are never cleaned up create "flag debt"  -  dead code wrapped in conditional logic that nobody is sure is safe to remove.\n\nBest practice: treat every feature flag as temporary debt. Set an expiration date when the flag is created and clean it up immediately after the flag decision is finalized.`,
        whyItMatters: `Feature flags enable faster, safer deployments but create hidden technical debt if not managed aggressively. The most common mistake is creating flags without cleanup deadlines, leading to flag debt that compounds over time.`,
        faqs: [
            { question: 'What are feature flags?', answer: 'Feature flags let you enable or disable functionality without deploying new code. They support gradual rollouts, A/B testing, and kill switches for broken features.' },
            { question: 'Are feature flags technical debt?', answer: 'Yes  -  every flag is temporary debt. Best practice: set an expiration date when creating the flag and clean it up immediately after the feature decision is finalized.' },
        ],
        relatedTerms: ['cicd', 'dora-metrics', 'dead-code', 'technical-debt'],
    },
    {
        slug: 'code-duplication',
        title: 'Code Duplication',
        category: 'Technical Debt & Code Quality',
        definition: `Code duplication occurs when identical or near-identical code blocks exist in multiple locations within a codebase. Also known as copy-paste programming or WET (Write Everything Twice) code, duplication is one of the most common code smells and a significant driver of maintenance costs.\n\nDuplicated code creates problems: when a bug is found in one copy, all copies need to be fixed separately. When behavior needs to change, every copy must be updated. When testing, each copy needs its own tests. The DRY principle (Don't Repeat Yourself) addresses this directly.\n\nTools like jscpd, PMD, and SonarQube can detect duplicated code blocks automatically. The ideal target is <5% duplication across the codebase. Above 10% duplication indicates systematic copy-paste patterns that need refactoring.\n\nNot all duplication is bad. Sometimes two pieces of code are similar by coincidence but serve different domains. Premature abstraction of such code creates worse problems than the original duplication.`,
        whyItMatters: `Code duplication is a direct multiplier of maintenance cost. Every duplicated block multiplies the cost of every future change by the number of copies. Reducing duplication from 15% to 5% can reduce maintenance hours by 20-30%.`,
        faqs: [
            { question: 'How much code duplication is acceptable?', answer: 'Below 5% is healthy. 5-10% is common but should be reduced. Above 10% indicates systematic copy-paste patterns that need refactoring.' },
            { question: 'How do you reduce code duplication?', answer: 'Extract duplicated blocks into shared functions or modules. Use static analysis tools to identify duplicates. Be cautious of premature abstraction  -  only combine code that changes for the same reasons.' },
        ],
        relatedTerms: ['code-smell', 'refactoring', 'technical-debt', 'dead-code'],
    },
];
