import { GlossaryTerm } from '../types';

// =============================================================================
// ELEVENTH PASS: Enterprise Economics & AI Architecture
// =============================================================================

export const trendingTermsBatch4: GlossaryTerm[] = [
    {
        title: 'Deterministic Control Plane',
        slug: 'deterministic-control-plane', tier: 'pillar',
        definition: `A Deterministic Control Plane is a rigid, hard-coded interception layer that sits between a probabilistic AI model (like an LLM) and enterprise infrastructure. It forces stochastic text predictors to operate within mathematically verifiable, predictable bounds.\n\nBecause standard LLMs have zero capacity for accountability and suffer from clinical amnesia, they cannot be trusted to execute autonomous actions against production databases or APIs. The control plane solves this by applying an immutable trust ledger and admissibility guardrails. If a proposed AI action is not explicitly permitted by the deterministic ruleset, it is blocked.`,
        whyItMatters: 'To safely deploy AI at scale, admissibility and accountability are existential requirements. A deterministic control plane separates probabilistic inference from deterministic execution, preventing catastrophic data loss and hallucinated database actions.',
        category: 'AI Architecture',
        relatedTerms: ['ai-agent-iam', 'zero-trust', 'ai-hallucination'],
        faqs: [{ question: 'Why can\'t we just use better prompts for autonomous agents?', answer: 'Prompts are probabilistic requests. You cannot build a reliable, autonomous enterprise system on a foundation that hallucinates and forgets. You must use deterministic code to verify the probabilistic intent.' }],
    },
    {
        title: 'Coordination Tax',
        slug: 'coordination-tax', tier: 'pillar',
        definition: `The Coordination Tax is the invisible financial penalty organizations pay when they add engineering headcount to a system drowning in technical debt. Because communication channels scale exponentially with headcount (calculated as n(n-1)/2), adding more developers to a brittle architecture actually decreases overall velocity.\n\nInstead of building new features, highly paid engineers spend a massive percentage of their week in alignment meetings, waiting on cross-team dependencies, and navigating legacy code to avoid breaking production systems.`,
        whyItMatters: 'The Coordination Tax masks technical debt as an agile velocity problem. When CTOs demand more headcount to ship a backlog, and velocity drops further, they are scaling a Ponzi scheme of technical debt rather than scaling an engineering organization.',
        howToMeasure: 'Run a forensic analysis on cross-functional dependencies. Calculate the exact dollar amount of engineering salaries spent on cross-team alignment and legacy maintenance versus shipping new net-revenue features.',
        category: 'Engineering Management',
        relatedTerms: ['technical-debt', 'product-debt-index', 'aper'],
        faqs: [{ question: 'How do you eliminate the Coordination Tax?', answer: 'You don\'t solve a Coordination Tax by hiring Scrum Masters. You solve it by executing an Innovation Tax Audit and deleting the legacy code that requires excessive coordination.' }],
    },
    {
        title: 'Synthetic COGS',
        slug: 'synthetic-cogs',
        definition: `Synthetic COGS (Cost of Goods Sold) refers to the variable, unmanaged compute costs generated by integrating LLMs and Generative AI into SaaS platforms. Unlike traditional software where compute costs per user are relatively fixed and predictable, AI features incur distinct API or compute charges for every single interaction.\n\nSynthetic COGS can rapidly compress gross margins, especially when flat-rate subscription models are used to subsidize power users who consume disproportionate amounts of AI compute.`,
        whyItMatters: 'If you do not manage Synthetic COGS, highly engaged power users become financial liabilities. An unmanaged AI feature can actively bankrupt a profitable SaaS product if usage scales without usage-based pricing or hardcoded caps.',
        category: 'SaaS Metrics & Finance',
        relatedTerms: ['finops', 'evergreen-ratio'],
        faqs: [{ question: 'How do we control Synthetic COGS?', answer: 'By deploying the Evergreen Ratio to cache responses, and implementing the Product P&L Test to ensure AI features have strict fair-use limits.' }],
    },
    {
        title: 'Evergreen Ratio',
        slug: 'evergreen-ratio',
        definition: `The Evergreen Ratio is a financial engineering metric used to protect gross margins in AI-enabled SaaS applications. It measures the percentage of AI queries that are served from pre-computed, static caches versus those requiring expensive real-time inference from a frontier model.\n\n**Formula:** (Cached Responses / Total AI Interactions) * 100\n\nThe sweet spot for a profitable AI feature sits between 60% and 80%. An Evergreen Ratio of 0% indicates maximum financial volatility, as the company pays full compute costs for every user interaction, even for repetitive queries.`,
        whyItMatters: 'As enterprise demand for AI processing skyrockets, organizations cannot rely on the hope that base compute costs will drop. They must architect interception layers to maximize cached efficiency and defend EBITDA.',
        category: 'SaaS Metrics & Finance',
        relatedTerms: ['synthetic-cogs', 'finops'],
        faqs: [{ question: 'What happens if my Evergreen Ratio is zero?', answer: 'You are exposed to severe margin compression. Your most engaged power users will destroy your gross margins because you are paying a frontier model to reason through the problem from scratch every time.' }],
    }
];
