import { redirect } from 'next/navigation';
import { currentUser } from '@clerk/nextjs/server';
import Link from 'next/link';
import { Download, ShieldCheck, Database, ChevronRight, Lock } from 'lucide-react';

export const metadata = {
    title: 'Governance Assets | Client Vault',
    description: 'Secure access to your purchased governance systems.',
};

// Hardcoded mapping of skill slugs to their display info to avoid circular dependencies
// These match the slugs generated by the Stripe checkout / webhook for skills.
const GOVERNANCE_ASSETS: Record<string, { title: string; category: string; description: string; version: string; }> = {
    'context-rot-prevention': {
        title: "Context Rot Prevention",
        category: "Cognitive Governance",
        description: "Prevents semantic contamination, recursive patching, retry inflation, and repository drift in long-horizon Claude sessions.",
        version: "v1.2.0"
    },
    'runtime-governance': {
        title: "Runtime Governance",
        category: "Execution Governance",
        description: "Enforce execution gating, admissibility pipelines, rollback containment, and runtime interception.",
        version: "v2.0.1"
    },
    'hallucination-debt-reduction': {
        title: "Hallucination Debt Reduction",
        category: "Output Governance",
        description: "Mitigate the verification burden and synthetic QA growth by structurally eliminating probabilistic assumptions.",
        version: "v1.1.4"
    },
    'ai-engineering-economics': {
        title: "AI Engineering Economics",
        category: "Economic Governance",
        description: "Map and optimize synthetic COGS, orchestration cost curves, and governance drag expansion.",
        version: "v1.0.0"
    },
    'mcp-governance': {
        title: "MCP Governance",
        category: "Integration Governance",
        description: "Establish enterprise-grade access and runtime limits for Model Context Protocol systems.",
        version: "v1.3.2"
    },
    'verification-burden-collapse': {
        title: "Verification Burden Collapse",
        category: "Output Governance",
        description: "Zero-trust validation pipelines for autonomous outputs.",
        version: "v1.0.0"
    },
    'orchestration-entropy': {
        title: "Orchestration Entropy Control",
        category: "Execution Governance",
        description: "Halt multi-agent recursive loops and prevent integration state collapse.",
        version: "v1.1.0"
    },
    'retry-inflation-control': {
        title: "Retry Inflation Control",
        category: "Economic Governance",
        description: "Cap LLM token burn via algorithmic circuit breakers on retry depth.",
        version: "v2.0.0"
    },
    'repository-drift-prevention': {
        title: "Repository Drift Prevention",
        category: "Cognitive Governance",
        description: "Continuous divergence detection and deterministic alignment protocols.",
        version: "v1.0.5"
    },
    'agentic-change-management': {
        title: "Agentic Change Management",
        category: "Integration Governance",
        description: "Cryptographic CAB approvals for autonomous infrastructure mutations.",
        version: "v1.0.0"
    },
    'context-window-compression': {
        title: "Context Window Compression",
        category: "Economic Governance",
        description: "Semantic prioritization and truncation for LLM token economy.",
        version: "v1.2.0"
    },
    'autonomous-execution-safety': {
        title: "Autonomous Execution Safety",
        category: "Execution Governance",
        description: "Shell command whitelisting and blast-radius containment.",
        version: "v2.1.0"
    },
    'tool-permission-governance': {
        title: "Tool Permission Governance",
        category: "Integration Governance",
        description: "Dynamic MCP tool provisioning based on rigorous task manifests.",
        version: "v1.1.0"
    },
    'ai-cost-containment': {
        title: "AI Cost Containment",
        category: "Economic Governance",
        description: "Real-time USD burn tracking with financial circuit breakers.",
        version: "v1.5.0"
    },
    'deterministic-agentic-engineering': {
        title: "Deterministic Agentic Engineering",
        category: "Execution Governance",
        description: "The unified flagship Orchestrator and Admissibility Engine.",
        version: "v3.0.0"
    }
};

export default async function AssetsPage() {
    const user = await currentUser();

    if (!user) {
        redirect('/sign-in?redirect_url=/vault/assets');
    }

    const hasAllAccess = user.publicMetadata?.has_yearly_subscription === true || user.publicMetadata?.is_team_admin === true;
    const unlockedAssets = (user.publicMetadata?.unlocked_assets as string[]) || [];

    // Filter available assets based on unlocks (or all if they have the subscription pass)
    const availableAssets = hasAllAccess 
        ? Object.keys(GOVERNANCE_ASSETS) 
        : unlockedAssets.filter(slug => GOVERNANCE_ASSETS[slug]);

    return (
        <main className="min-h-screen pt-32 pb-24 px-6 bg-[#F5F0EB]">
            <div className="max-w-5xl mx-auto">
                {/* HEADER */}
                <div className="mb-12">
                    <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/20 mb-6">
                        <ShieldCheck className="w-4 h-4 text-cyan-900 font-extrabold font-semibold" />
                        <span className="text-xs font-bold font-medium font-mono text-cyan-900 font-extrabold font-semibold uppercase tracking-widest">Asset Provisioning Layer</span>
                    </div>
                    
                    <h1 className="text-4xl md:text-5xl font-grotesk font-bold text-[#1A1A1A] mb-4">
                        Governance Infrastructure
                    </h1>
                    <p className="text-[#4A4A4A] max-w-2xl text-lg leading-relaxed">
                        Securely download your licensed operational middleware, YAML policies, and governance orchestration playbooks. Assets are dynamically generated from the `main` branch to ensure you always receive the latest deterministic architecture.
                    </p>
                </div>

                {/* ASSET GRID */}
                <div className="space-y-6">
                    {availableAssets.length > 0 ? (
                        availableAssets.map((slug) => {
                            const assetInfo = GOVERNANCE_ASSETS[slug];
                            if (!assetInfo) return null;
                            
                            return (
                                <div key={slug} className="p-8 rounded-2xl border border-[rgba(0,0,0,0.08)] bg-white hover:border-cyan-500/30 transition-all group flex flex-col md:flex-row md:items-center justify-between gap-6 shadow-sm">
                                    <div className="flex-1">
                                        <div className="flex items-center gap-3 mb-3">
                                            <span className="px-2 py-1 rounded text-[10px] font-bold font-mono uppercase tracking-widest bg-zinc-100 text-[#4A4A4A] border border-[rgba(0,0,0,0.05)]">
                                                {assetInfo.category}
                                            </span>
                                            <span className="px-2 py-1 rounded text-[10px] font-bold font-mono uppercase tracking-widest bg-cyan-50 text-cyan-900 font-extrabold font-semibold border border-cyan-100">
                                                {assetInfo.version}
                                            </span>
                                        </div>
                                        <h2 className="text-2xl font-bold text-[#1A1A1A] mb-2">{assetInfo.title}</h2>
                                        <p className="text-[#4A4A4A] text-sm leading-relaxed max-w-2xl">
                                            {assetInfo.description}
                                        </p>
                                    </div>
                                    
                                    <div className="flex-shrink-0">
                                        <a 
                                            href={`/api/assets/download?slug=${slug}`}
                                            className="inline-flex items-center justify-center px-6 py-3 bg-[#1A1A1A] text-white font-bold text-sm rounded shadow-md hover:bg-black transition-colors"
                                            download
                                        >
                                            <Download className="w-4 h-4 mr-2" />
                                            Download Package
                                        </a>
                                    </div>
                                </div>
                            );
                        })
                    ) : (
                        <div className="p-12 rounded-2xl border border-[rgba(0,0,0,0.08)] bg-white text-center flex flex-col items-center">
                            <div className="w-16 h-16 rounded-full bg-zinc-100 flex items-center justify-center mb-6">
                                <Lock className="w-6 h-6 text-zinc-400" />
                            </div>
                            <h2 className="text-2xl font-bold text-[#1A1A1A] mb-3">No Infrastructure Licensed</h2>
                            <p className="text-[#4A4A4A] max-w-md mx-auto mb-8">
                                You do not currently hold an active license for any deterministic governance assets. Browse the marketplace to deploy operational infrastructure.
                            </p>
                            <Link href="/skills" className="inline-flex items-center justify-center px-8 py-3 bg-[#1A1A1A] text-white font-bold rounded hover:bg-black transition-colors">
                                View Marketplace
                            </Link>
                        </div>
                    )}
                </div>
            </div>
        </main>
    );
}
