import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'R&D Audit Checklist — The Product Economist',
    description: 'The 15 questions Richard Ewing asks in every $7,500 engagement. Free R&D audit checklist for CTOs, VPs of Engineering, and Product Leaders.',
    keywords: ['R&D audit', 'engineering audit checklist', 'technical due diligence', 'CTO checklist', 'product economist'],
};

const checklistItems = [
    { number: '01', question: 'What percentage of engineering time is spent on maintenance vs. new features?', why: 'If maintenance exceeds 40%, you may be approaching Technical Insolvency.' },
    { number: '02', question: 'What is your Revenue Per Engineer (RPE), and how does it trend?', why: 'Declining RPE signals engineering capital misallocation — you\'re spending more but earning less per engineer.' },
    { number: '03', question: 'Can you identify which features generate revenue and which are zombie features?', why: 'Most organizations can\'t. This means they\'re maintaining features that destroy value.' },
    { number: '04', question: 'What is the fully-loaded cost per AI inference request?', why: 'AI features often have hidden variable costs that erode gross margins. The Cost of Predictivity compounds.' },
    { number: '05', question: 'What is your Technical Insolvency Date?', why: 'The exact quarter when maintenance costs consume 100% of engineering capacity. Most companies don\'t know theirs.' },
    { number: '06', question: 'What percentage of your "R&D spend" is actually maintenance OpEx?', why: 'The Innovation Tax — many companies report 50% R&D investment when 80% is actually maintenance.' },
    { number: '07', question: 'Do your PMs own a P&L, or just a backlog?', why: 'PMs who don\'t understand their P&L make uninformed capital allocation decisions every sprint.' },
    { number: '08', question: 'What is your DORA metrics profile (deployment frequency, lead time, failure rate, MTTR)?', why: 'DORA measures delivery speed. Pair with PDI to see if you\'re shipping fast toward insolvency.' },
    { number: '09', question: 'How much of your production code was generated by AI, and what\'s its defect rate?', why: 'Vibe-coded applications accumulate hallucination debt — technical debt no one on the team fully understands.' },
    { number: '10', question: 'Can you calculate the gross margin of each product line?', why: 'AI features introduce variable COGS. Without per-product margin visibility, you may be scaling losses.' },
    { number: '11', question: 'What would happen if you removed your 10 least-used features tomorrow?', why: 'The Kill Switch Protocol typically recovers 20-40% of engineering capacity from zombie features.' },
    { number: '12', question: 'Do you have a model right-sizing strategy for AI features?', why: 'Using a frontier model for every request is like using a Ferrari for the mailbox. Right-sizing cuts AI costs 60-80%.' },
    { number: '13', question: 'What is the accuracy-cost curve for your critical AI features?', why: 'Going from 80% to 95% accuracy often costs 10x more. The Cost of Predictivity must be modeled before commitments.' },
    { number: '14', question: 'Is your engineering organization structured around products or projects?', why: 'Project-based teams ship and move on. Product-based teams own the outcome. The P&L impact is dramatic.' },
    { number: '15', question: 'If a PE firm audited your engineering organization today, what would they find?', why: 'Technical Due Diligence reveals hidden liabilities. Better to find them yourself than have an acquirer negotiate them down.' },
];

export default function ChecklistPage() {
    return (
        <div className="max-w-4xl w-full relative z-10 mx-auto">
            <div className="mb-6 flex items-center gap-2 text-[10px] font-mono text-zinc-600 uppercase tracking-widest">
                <span>Resources</span><span>/</span><span className="text-emerald-400 font-bold">R&D Audit Checklist</span>
            </div>

            {/* Success Message */}
            <div className="mb-10 p-6 rounded-2xl bg-emerald-500/5 border border-emerald-500/20 text-center">
                <div className="text-4xl mb-3">✓</div>
                <h2 className="text-2xl font-bold text-emerald-400 mb-2">You&apos;re In — Checklist Below</h2>
                <p className="text-zinc-400">You&apos;ve been added to The Product Economist briefing. Here&apos;s the checklist as promised.</p>
            </div>

            <h1 className="text-4xl sm:text-5xl font-grotesk font-bold text-white mb-6">
                The R&D Audit <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-cobalt">Checklist</span>
            </h1>
            <p className="text-lg text-zinc-400 mb-12 leading-relaxed">
                The 15 questions I ask in every <span className="text-white font-bold">$7,500 diagnostic engagement</span>. 
                These questions surface hidden capital risks, zombie features, and structural margin collapse before they become catastrophic.
            </p>

            {/* The Checklist */}
            <div className="space-y-6 mb-16">
                {checklistItems.map((item) => (
                    <div key={item.number} className="card p-6 hover:border-cyan-500/30 transition-all group">
                        <div className="flex items-start gap-4">
                            <div className="shrink-0 w-10 h-10 rounded-xl bg-cyan-500/10 border border-cyan-500/20 flex items-center justify-center font-mono text-cyan-400 font-bold text-sm">
                                {item.number}
                            </div>
                            <div>
                                <h3 className="text-white font-bold text-lg mb-2 group-hover:text-cyan-400 transition-colors">{item.question}</h3>
                                <p className="text-zinc-500 text-sm leading-relaxed">
                                    <span className="text-zinc-400 font-semibold">Why this matters: </span>{item.why}
                                </p>
                            </div>
                        </div>
                    </div>
                ))}
            </div>

            {/* CTA: Go Deeper */}
            <div className="text-center py-12 border-t border-white/10">
                <h2 className="text-2xl font-bold text-white mb-4">Want These Questions Answered?</h2>
                <p className="text-zinc-400 mb-8">Book a diagnostic engagement and get a written executive summary with quantified findings.</p>
                <div className="flex flex-wrap justify-center gap-4">
                    <a href="/advisory" className="px-8 py-4 bg-white text-black font-bold uppercase tracking-widest text-xs rounded-xl hover:bg-cyan-400 transition-colors">
                        Book Diagnostic ($2,500) →
                    </a>
                    <a href="/tools/pdi" className="px-8 py-4 border border-white/20 text-white font-bold uppercase tracking-widest text-xs rounded-xl hover:border-cyan-500 hover:text-cyan-400 transition-all">
                        Try the Free PDI Tool →
                    </a>
                </div>
            </div>
        </div>
    );
}
