const domains = [
    {
        title: 'Engineering Velocity & Delivery',
        icon: '⚡',
        color: 'cyan',
        description: 'How fast and reliably does your engineering organization deliver value?',
        questions: [
            { q: 'What percentage of engineering time is spent on maintenance vs. new features?', why: 'If maintenance exceeds 40%, you may be approaching Technical Insolvency.', action: 'Calculate Innovation Tax: maintenance hours ÷ total hours. Track monthly.', scoring: { red: '>60%', yellow: '40-60%', green: '<40%' } },
            { q: 'What are your DORA metrics (deploy frequency, lead time, failure rate, MTTR)?', why: 'DORA measures delivery speed. Pair with PDI to see if you\'re shipping fast toward insolvency.', action: 'Instrument CI/CD pipeline. Track all 4 metrics weekly.', scoring: { red: 'Monthly deploys, >1wk lead time', yellow: 'Weekly deploys, 1-7d lead time', green: 'Multiple/day, <1hr lead time' } },
            { q: 'What is your cycle time from commit to production?', why: 'Long cycle times compound delays and reduce feedback speed.', action: 'Measure commit-to-production time. Target: <1 hour for elite teams.', scoring: { red: '>1 week', yellow: '1-7 days', green: '<1 day' } },
            { q: 'How often do deployments cause incidents?', why: 'Change failure rate directly measures deployment quality.', action: 'Calculate: failed deployments ÷ total deployments.', scoring: { red: '>30%', yellow: '15-30%', green: '<15%' } },
            { q: 'What is your average sprint completion rate?', why: 'Consistently missing sprint commitments signals estimation or capacity problems.', action: 'Track: stories completed ÷ stories committed per sprint.', scoring: { red: '<60%', yellow: '60-80%', green: '>80%' } },
            { q: 'Do you have feature flags for safe rollouts?', why: 'Feature flags enable incremental releases, A/B testing, and instant rollback.', action: 'Implement feature flag system. Target: all new features behind flags.', scoring: { red: 'No flags', yellow: 'Some features', green: 'All features flagged' } },
            { q: 'What is your code review turnaround time?', why: 'Slow reviews create bottlenecks and context-switching costs.', action: 'Measure: time from PR open to first review. Target: <4 hours.', scoring: { red: '>24 hours', yellow: '4-24 hours', green: '<4 hours' } },
        ],
    },
    {
        title: 'Technical Debt & Architecture',
        icon: '🏗️',
        color: 'red',
        description: 'What is the health of your technology capital, and where is value being destroyed?',
        questions: [
            { q: 'Can you identify your 3 largest sources of technical debt and their financial impact?', why: 'Most organizations cannot quantify debt in dollars. Without financial language, leadership ignores it.', action: 'Run PDI assessment. Assign dollar values to top debt categories.', scoring: { red: 'Cannot identify', yellow: 'Identified but not quantified', green: 'Quantified in dollars' } },
            { q: 'What is your Technical Insolvency Date?', why: 'The exact quarter when maintenance costs consume 100% of engineering capacity.', action: 'Plot Innovation Tax trend. Extrapolate to 100%. That\'s your insolvency date.', scoring: { red: '<6 months away', yellow: '6-18 months', green: '>18 months or improving' } },
            { q: 'What percentage of your codebase has test coverage?', why: 'Low coverage = high change failure rate = slow delivery = more rework costs.', action: 'Measure line/branch coverage. Target: >70% for critical paths.', scoring: { red: '<30%', yellow: '30-70%', green: '>70%' } },
            { q: 'When was your last architecture review?', why: 'Architecture debt is the most expensive form of debt — it requires rewrites, not refactors.', action: 'Establish quarterly Architecture Review Board. Document all decisions.', scoring: { red: 'Never / >12 months', yellow: '6-12 months ago', green: 'Within last quarter' } },
            { q: 'How many services or modules have a single maintainer?', why: 'Single points of failure. If that person leaves, the knowledge leaves with them.', action: 'Audit: map each service to its maintainers. Cross-train where count = 1.', scoring: { red: '>30% of services', yellow: '10-30%', green: '<10%' } },
            { q: 'What is the age distribution of your critical dependencies?', why: 'Outdated dependencies = security vulnerabilities + compatibility issues + upgrade debt.', action: 'Audit dependency ages. Flag anything >2 major versions behind.', scoring: { red: '>50% outdated', yellow: '20-50% outdated', green: '<20% outdated' } },
            { q: 'Do you have automated security scanning in your CI/CD pipeline?', why: 'Manual security reviews don\'t scale. Automated SAST/DAST catches vulnerabilities before production.', action: 'Integrate SAST tool. Block merges with critical vulnerabilities.', scoring: { red: 'No scanning', yellow: 'Manual only', green: 'Automated in CI/CD' } },
        ],
    },
    {
        title: 'AI & Emerging Technology Economics',
        icon: '🤖',
        color: 'violet',
        description: 'Are your AI investments creating or destroying value?',
        questions: [
            { q: 'What is the fully-loaded cost per AI inference request?', why: 'AI features often have hidden variable costs that erode gross margins.', action: 'Instrument per-request cost tracking: compute + tokens + storage + overhead.', scoring: { red: 'Unknown', yellow: 'Estimated', green: 'Tracked per-request' } },
            { q: 'Do you use model routing (different models for different query types)?', why: 'Using frontier models for every query costs 10-50x more than necessary.', action: 'Classify queries by complexity. Route 70% to smaller, cheaper models.', scoring: { red: 'One model for all', yellow: '2-3 models', green: 'Smart routing with 3+ tiers' } },
            { q: 'What percentage of your AI features have positive unit economics?', why: '40-60% of AI features launch unprofitable. Growth accelerates losses.', action: 'Calculate per-feature P&L. Kill or optimize negative-margin features.', scoring: { red: 'Unknown / <30%', yellow: '30-60%', green: '>60% profitable' } },
            { q: 'How much of your production code was generated by AI, and what\'s its defect rate?', why: 'Vibe-coded applications accumulate hallucination debt — debt no one on the team fully understands.', action: 'Track AI-generated code percentage. Measure defect rate vs. human-written code.', scoring: { red: '>30% AI code, no quality tracking', yellow: 'AI code tracked', green: 'AI code tracked + quality monitored' } },
            { q: 'Do you have a model right-sizing strategy?', why: 'Using a Ferrari for the mailbox. Right-sizing cuts AI costs 60-80%.', action: 'Benchmark: test smaller models against quality thresholds. Document findings.', scoring: { red: 'No strategy', yellow: 'Some right-sizing', green: 'Systematic optimization' } },
            { q: 'What guardrails exist for AI output quality?', why: 'Without guardrails: hallucinations, bias, and harmful outputs reach users.', action: 'Implement output validation, safety filters, and quality monitoring.', scoring: { red: 'No guardrails', yellow: 'Basic filters', green: 'Comprehensive guardrail pipeline' } },
        ],
    },
    {
        title: 'Product & Revenue Alignment',
        icon: '💰',
        color: 'emerald',
        description: 'Is engineering investment aligned with revenue generation?',
        questions: [
            { q: 'What is your Revenue Per Engineer (RPE), and how does it trend?', why: 'Declining RPE signals engineering capital misallocation.', action: 'Calculate: ARR ÷ engineering headcount. Track quarterly. Use APER calculator.', scoring: { red: '<$200K or declining', yellow: '$200K-500K, flat', green: '>$500K and growing' } },
            { q: 'Can you identify which features generate revenue and which are zombie features?', why: 'Most organizations maintain features that destroy value. 30-50% of features have <5% usage.', action: 'Instrument feature usage. Identify features with <5% MAU. Run Kill Switch Protocol.', scoring: { red: 'No feature-level tracking', yellow: 'Some tracking', green: 'Full feature-level P&L' } },
            { q: 'Do your PMs own a P&L, or just a backlog?', why: 'PMs who don\'t understand their P&L make uninformed capital allocation decisions every sprint.', action: 'Create per-product P&L. Train PMs on unit economics.', scoring: { red: 'Backlog only', yellow: 'Some financial awareness', green: 'Full P&L ownership' } },
            { q: 'Can you calculate the gross margin of each product line?', why: 'AI features introduce variable COGS. Without margin visibility, you may be scaling losses.', action: 'Allocate engineering + infrastructure costs per product. Calculate margins.', scoring: { red: 'No margin tracking', yellow: 'Aggregate only', green: 'Per-product margins' } },
            { q: 'What would happen if you removed your 10 least-used features tomorrow?', why: 'The Kill Switch Protocol typically recovers 20-40% of engineering capacity from zombie features.', action: 'List 10 lowest-usage features. Calculate maintenance cost of each. Draft removal plan.', scoring: { red: 'Don\'t know usage', yellow: 'Know usage, afraid to cut', green: 'Regular feature pruning' } },
            { q: 'What is your time-to-revenue for new features?', why: 'Long time-to-revenue means engineering investment isn\'t generating returns fast enough.', action: 'Track: feature release date → first revenue attribution. Target: <30 days.', scoring: { red: '>90 days or unknown', yellow: '30-90 days', green: '<30 days' } },
        ],
    },
    {
        title: 'Organization & People',
        icon: '👥',
        color: 'amber',
        description: 'Is your team structured for sustainable, scalable delivery?',
        questions: [
            { q: 'What is your engineering attrition rate over the last 12 months?', why: 'Each departure costs $150K-250K (recruiting + onboarding + lost productivity).', action: 'Calculate: departures ÷ average headcount × 100.', scoring: { red: '>20%', yellow: '10-20%', green: '<10%' } },
            { q: 'What is the average tenure on your engineering team?', why: 'Low tenure means constant knowledge loss and ramp-up costs.', action: 'Track average tenure. Flag teams with <18 month average.', scoring: { red: '<12 months avg', yellow: '12-24 months', green: '>24 months' } },
            { q: 'Is your engineering org structured around products or projects?', why: 'Project-based teams ship and move on. Product teams own outcomes.', action: 'Evaluate: do teams own products end-to-end, or get assigned projects?', scoring: { red: 'Project-based', yellow: 'Mixed', green: 'Product-based, end-to-end ownership' } },
            { q: 'What is your span of control (direct reports per manager)?', why: 'Below 5: manager overhead too high. Above 8: insufficient coaching.', action: 'Audit: count direct reports per manager. Restructure outliers.', scoring: { red: '<4 or >10', yellow: '4-5 or 9-10', green: '6-8' } },
            { q: 'How many key-person dependencies exist?', why: 'If one person\'s departure would halt a project, that\'s a critical risk.', action: 'Map: for each critical system, who are the only people who understand it?', scoring: { red: '>5 single-points-of-failure', yellow: '2-5', green: '0-1' } },
            { q: 'Do you have a documented career ladder with clear levels?', why: 'Without clear progression, top engineers leave for companies that offer it.', action: 'Publish engineering career ladder. Review annually.', scoring: { red: 'No ladder', yellow: 'Informal', green: 'Published with clear criteria' } },
        ],
    },
    {
        title: 'Strategic & Financial',
        icon: '📊',
        color: 'purple',
        description: 'Is your R&D investment being valued, reported, and optimized at the board level?',
        questions: [
            { q: 'What percentage of your "R&D spend" is actually maintenance OpEx?', why: 'The Innovation Tax — many companies report 50% R&D investment when 80% is actually maintenance.', action: 'Audit: categorize every engineering hour as innovation vs. maintenance.', scoring: { red: '>70% maintenance', yellow: '40-70%', green: '<40% maintenance' } },
            { q: 'If a PE firm audited your engineering organization today, what would they find?', why: 'Technical Due Diligence reveals hidden liabilities. Better to find them yourself.', action: 'Conduct an internal pre-diligence audit using this checklist + PDI tool.', scoring: { red: 'Major undisclosed liabilities', yellow: 'Known but unquantified issues', green: 'Clean, documented assessment' } },
            { q: 'What is the accuracy-cost curve for your critical AI features?', why: 'Going from 80% to 95% accuracy often costs 10x more. The Cost of Predictivity must be modeled.', action: 'For each AI feature: plot accuracy vs. cost. Find the diminishing returns inflection point.', scoring: { red: 'Not modeled', yellow: 'Partially modeled', green: 'Fully modeled with trade-off analysis' } },
            { q: 'Can your engineering investment survive a 30% budget cut?', why: 'Knowing your critical path vs. nice-to-have helps make tough decisions before they\'re forced.', action: 'Create a tiered investment plan: must-have (70%), should-have (20%), nice-to-have (10%).', scoring: { red: 'No prioritization framework', yellow: 'Some prioritization', green: 'Tiered investment plan documented' } },
            { q: 'Do you report engineering health metrics to the board?', why: 'Boards that see engineering metrics make better investment decisions.', action: 'Create quarterly technology capital report: PDI, APER, DORA, Innovation Tax.', scoring: { red: 'No engineering metrics to board', yellow: 'Ad-hoc reporting', green: 'Quarterly technology capital report' } },
            { q: 'What is the total cost of ownership for your technology stack?', why: 'Most companies underestimate TCO by 40-60%. Hidden costs: maintenance, integration, training, migration.', action: 'Map TCO for each major platform: license + integration + maintenance + opportunity cost.', scoring: { red: 'Unknown', yellow: 'Partially calculated', green: 'Fully mapped and reviewed annually' } },
        ],
    },
]; module.exports = domains;