/**
 * RUNTIME PERMISSION VALIDATOR
 * 
 * Middleware that intercepts all bash/shell commands generated by the LLM.
 * Compares the payload against a strict, deterministic whitelist/denylist 
 * before it is passed to the host OS.
 */

import { readFileSync } from 'fs';
import * as yaml from 'js-yaml';

export interface CommandAttempt {
    agentId: string;
    commandString: string;
    intendedCwd: string;
}

export interface ExecutionSafetyPolicy {
    spec: {
        enforcement_mode: 'STRICT' | 'AUDIT';
        denylist: {
            exact_matches: string[];
            regex_patterns: string[];
        };
        whitelist: {
            allowed_base_commands: string[];
        };
    };
}

export class RuntimePermissionValidator {
    private policy: ExecutionSafetyPolicy;

    constructor(policyPath: string = './execution-safety-policy.yaml') {
        const fileContents = readFileSync(policyPath, 'utf8');
        this.policy = yaml.load(fileContents) as ExecutionSafetyPolicy;
    }

    /**
     * Parses the bash command and determines if it is safe to execute.
     */
    public validateCommand(attempt: CommandAttempt): boolean {
        const { agentId, commandString } = attempt;
        
        // 1. Sanitize: Collapse spaces and convert to lowercase for basic checking
        const normalizedCmd = commandString.trim().toLowerCase().replace(/\s+/g, ' ');
        const baseCommand = normalizedCmd.split(' ')[0];

        // 2. Exact Denylist Check
        if (this.policy.spec.denylist.exact_matches.some(denied => normalizedCmd.includes(denied))) {
            this.handleViolation(agentId, commandString, `Command contains explicitly banned sequence.`);
        }

        // 3. Regex Denylist Check (e.g., catching chained commands like `cmd1 | cmd2` or `cmd1 && cmd2`)
        for (const pattern of this.policy.spec.denylist.regex_patterns) {
            const regex = new RegExp(pattern, 'i');
            if (regex.test(commandString)) {
                this.handleViolation(agentId, commandString, `Command matches banned regex pattern: ${pattern}`);
            }
        }

        // 4. Whitelist Check (Zero-Trust Approach)
        // If it's not explicitly allowed, it's blocked.
        if (!this.policy.spec.whitelist.allowed_base_commands.includes(baseCommand)) {
            this.handleViolation(agentId, commandString, `Base command '${baseCommand}' is not in the whitelist.`);
        }

        console.log(`[EXECUTION GATING] Command '${commandString}' passed safety validation.`);
        return true;
    }

    private handleViolation(agentId: string, command: string, reason: string): never {
        console.error(`[CRITICAL SECURITY EVENT] Agent ${agentId} attempted unsafe execution.`);
        console.error(`[PAYLOAD] ${command}`);
        console.error(`[REASON] ${reason}`);

        if (this.policy.spec.enforcement_mode === 'STRICT') {
            throw new Error(`[GOVERNANCE HALT] Unsafe Shell Execution Blocked: ${reason}`);
        } else {
            console.warn(`[AUDIT MODE] Would have blocked unsafe command: ${command}`);
            throw new Error(`[AUDIT WARNING] Unsafe Shell Execution Detected: ${reason}`);
        }
    }
}
